### ISSUE TITLE
Watch does not work at all in Windows 10

### ISSUE THREAD

**Issue by chuckhendo** [Shopify/themekit#106]
I haven't tested on other computers/versions of Windows, but on my copy of Windows 10, watch will not detect any changes. 

I pulled the source code, and I think I've got the problem isolated to the "extractAssetKey" function inside of file_watcher.go. My knowledge of Go is extremely limited, but just by doing some Printf's throughout the function, it seems that "split := strings.SplitAfterN(filename, dir, 2)" is not actually splitting anything, because assetLocations is using forward slashes for path separators, and filename is using backslashes. I was able to do a string replace to fix the slashes, and themekit will then detect changes, but of course that causes a whole new slew of issues.

If you need any more information or if you need me to test anything to resolve this issue, please let me know.

**Comment by csaunders** [comment]
That's weird that it's only specific to Windows 10. There's some code in there that should make it coerce the backslashes correctly. I'll look into this when I get a chance (I don't have a windows 10 VM with go setup at the moment)

**Comment by chuckhendo** [comment]
Well, not necessarily isolated to just Windows 10. But that's the OS I'm observing it on. I'll download an 8.1 VM tonight and see how it behaves there

**Comment by chuckhendo** [comment]
Issue seems to be occurring in 8.1 as well.

**Comment by csaunders** [comment]
Interesting. This must be a regression because one of the main reasons this
project exists is to make it easier to do theme development on Windows.

On Thu, Oct 29, 2015 at 8:45 PM, Carl Henderson <notifications@github.com>
wrote:

> Issue seems to be occurring in 8.1 as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shopify/themekit/issues/106#issuecomment-152369014>.
>



-- 
Chris Saunders // Developer @ Shopify

**Comment by chuckhendo** [comment]
Well, does seem to be a regression. Here's what I've found so far:

0.2.6: Works
0.2.7: Seems to work, but then you get a 404 like so 
```shell
Received Update event on assets\app.scss.liquid
[404]Could not complete operation because assets\app.scss.liquid does not exist
```
0.3.0: Doesn't do anything on file save

**Comment by chuckhendo** [comment]
Issue seems to have specifically started with 41d4db6

**Comment by csaunders** [comment]
Thanks for that! I have an update that I'm working on that will hopefully
come out soon. I'll try to get this patched up and in there too.

Cheers :)

On Sat, Oct 31, 2015 at 8:04 PM, Carl Henderson <notifications@github.com>
wrote:

> Issue seems to have specifically started with 41d4db6
> <https://github.com/Shopify/themekit/commit/41d4db65fb4e87bda26a4a8065aaca94055cd7ad>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shopify/themekit/issues/106#issuecomment-152782194>.
>



-- 
Chris Saunders // Developer @ Shopify
