### ISSUE TITLE
[Doc] Manual installation instructions PATH line

### ISSUE THREAD

**Issue by NathanPJF** [Shopify/themekit#107]
In the [manual instructions](http://themekit.cat/install/#installing-on-mac-os-amp-linux) for installing Theme Kit, it has instructions to modify your profile by adding `export PATH=$PATH:~/Applications/bin` to the bottom of the file.

The problem with this is if you have the **shopify_theme** gem already installed, the `theme` command will still be based on the gem and not theme kit.  

To avoid having to explain the theme gem or giving more details on editing your profile, this can be solved by just re-writing the `export` line to:

```
export PATH=~/Applications/bin:$PATH
```

Big ups to @jtgrenz for telling me what the gnomes in my computer were actually doing.

**Comment by tanema** [comment]
fixed in 92e031dc28ae5f34594ed224fb47eba520617620
