### ISSUE TITLE
Alternative installation in /usr/local/bin

### ISSUE THREAD

**Issue by altern8tif** [Shopify/themekit#111]
Is there any reason why it needs to be installed in `~/Applications/bin`?  I thought that binaries are typically installed in `/usr/local/bin` rather than directly in the user's Applications folder.

Even better, it should be made even easier to install using [Homebrew](https://github.com/Homebrew/homebrew).  This could eliminate any possible installation errors.

I can put up a PR to add it to the Homebrew registry if someone could shed some light on my initial query above.

**Comment by csaunders** [comment]
Homebrew is Mac specific, so it's another script to maintain for a slightly different unix-like system.

Installing in `/usr/local/bin` requires changing the entire directory permissions or running as root.

![](https://www.dropbox.com/s/898ltreorwpan4i/Screenshot%202015-11-06%2009.18.38.png?dl=0)
