### ISSUE TITLE
[Doc] using `env` example

### ISSUE THREAD

**Issue by NathanPJF** [Shopify/themekit#117]
Can an example on how to use `--env` be added to the documentation, please?

Just spent a good while trying to figure out why `theme replace [file] --env=staging` wasn't working.  It would be helpful to be shown an example of using different environments.

**Comment by NathanPJF** [comment]
For adventures who make it this far, the answer: `theme replace --env=staging [file]`

**Comment by adamwooding** [comment]
:+1: 
I just spent an hour trying to figure out how to upload to different environments & I just found this thread. Thank you SO much @NathanPJF for posting the correct way to do it.  I agree that this should be added to the documentation :)

**Comment by Jorybraun** [comment]
Thank you !!!!

**Comment by eddyparkinson** [comment]
Would be great to have docs for 'env' here as well:

https://shopify.github.io/themekit/
