### ISSUE TITLE
Feature request: Default Ignores

### ISSUE THREAD

**Issue by sdn90** [Shopify/themekit#118]
I can't really see any major use cases for watching files outside of the Shopify theme structure. Anything outside of the structure doesn't upload anyways.

Pretty much ignore everything **not** in:

```
/assets
/layout
/snippets
/templates
/config
/locales
```

**Comment by tanema** [comment]
This may not be the case in older versions but right now the code tried to normalize filepaths to those directories and if it can't then the file will be filtered out. So this probably doesn't apply anymore.
