### ISSUE TITLE
themekit.cat needs ownership transferred over to Shopify

### ISSUE THREAD

**Issue by csaunders** [Shopify/themekit#137]
@chrisbutcher @ilikeorangutans could one of you get in contact with someone on the operations team so I can get the domain transferred over to Shopify? It's going to renew on the 26th of February. I won't let the renewal lapse, but it would be good if I didn't have to worry about paying for it :)

**Comment by chrisbutcher** [comment]
Sure thing!

**Comment by mpiotrowicz** [comment]
FYI @fredryk @cshold @m-ux

**Comment by tanema** [comment]
@chrisbutcher was this ever taken care of?

**Comment by chrisbutcher** [comment]
@tanema Not sure. The last this was discussed is here: https://github.com/Shopify/traffic/issues/571

**Comment by chrisbutcher** [comment]
Looks like it still needs to be transferred

**Comment by csaunders** [comment]
Yeah this still needs to get taken care of. I've never really done domain transfers, so whoever from ops should reach out and let me know what needs to happen.

I think I bought this domain with Hover, so this should be fairly easy I think.

**Comment by csaunders** [comment]
Just a reminder that this domain expires on `2017-02-26T16:27:46.758Z` so hopefully this can be addressed soon.

**Comment by tanema** [comment]
Thanks @csaunders hopefully I can expedite this then.

**Comment by tanema** [comment]
Shopify now has management of this domain.
