### ISSUE TITLE
Watch fails when ignore_files contains parent directory name

### ISSUE THREAD

**Issue by ilikeorangutans** [Shopify/themekit#138]
Debugged this with @t-kelly and figured out that if ignore_files contains a directory name that can be found in the projects directory, it will ignore everything. For example, the project lives under ~/src/theme and config.yml contains:

``` yaml
development:
  ignored_files:
  - src
```

then the filewatcher ignores all files resulting in an empty watch list. 

Two tasks at hand:
- Have themekit report that you're watching an empty file list (would have been super useful here!)
- Fix the ignore mechanism

CC @chrisbutcher

**Comment by chrisbutcher** [comment]
It might be wise to adopt a bit of gitignore's syntax, which considers files prefixed with `/` to be folders, and otherwise files.

**Comment by ilikeorangutans** [comment]
I think it's probably not wrong, but confusing and unproductive. The expectation of @t-kelly (and mine) was that the filters apply only to what is _within_ the project directory. I don't think we'll need a filter that applies to the entire project directory itself; that seems... counterproductive. :)

So while it's not wrong, at least we should give the users a helpful hint, and at best make it work more like they would expect it to. 

As for the scenario of a folder and file called `src`, the git way would be to either specify the explicit path of the file to ignore `path/to/src` or you would have a separate gitignore file in the directory that contains the file. 

Building file filtering mechanisms boils down to `1. build a list of things to include (and that could literally be everything in a given path)` and `2. remove ignored stuff from this list (via glob/regex)`. Really powerful systems like [Ant's Fileset](https://ant.apache.org/manual/Types/fileset.html) via its [PatternSet](https://ant.apache.org/manual/Types/patternset.html) let you specify very explicitly a root for the fileset, includes via globs and excludes, in the same fashion. 

I think we can draw some inspiration from this! :)

**Comment by chrisbutcher** [comment]
Sounds good to me

**Comment by t-kelly** [comment]
Just saw this! :+1:
