### ISSUE TITLE
Improve themekit installation workflow on all platforms.

### ISSUE THREAD

**Issue by chrisbutcher** [Shopify/themekit#146]
Promising results so far,  seen in https://github.com/Shopify/canvas/pull/262

Other options available for all platforms:
- [x]  Improve curl / pipe installation script (should be installed in a more appropriate location.)
- [x] HomeBrew formulae https://github.com/Shopify/homebrew-shopify/pull/34
- [ ] Linux apt package
- [x] [NSIS](https://en.wikipedia.org/wiki/Nullsoft_Scriptable_Install_System)
- [x] Gulp/Node pacakge

**Comment by chrisbutcher** [comment]
Example package.json "scripts" pre-post/install script https://github.com/milani/appjs/blob/master/package.json#L36
https://github.com/milani/appjs/blob/master/cli/postinstall.js

**Comment by onedanshow** [comment]
+1 for Brew formulae

**Comment by brettchalupa** [comment]
I'd like to take on the Homebrew formulae if no one else is already. 👍

**Comment by swoodford** [comment]
Just chiming in here, installing this to `~/.themekit` on a Linux server is not a great idea, especially for use in CI/CD environments with Jenkins.  It should be installed to a more standard location such as `/usr/local/bin` and given the proper permissions for system wide usage.

**Comment by tanema** [comment]
@swoodford can't agree enough we will be taking that into consideration.

**Comment by tanema** [comment]
Open PR will make theme kit now install to `/usr/local/bin/` as well as adds a home brew formula. I may need help with the other two installation strategies because I have no experience doing them and the documentation is not great.
