### ISSUE TITLE
Package management

### ISSUE THREAD

**Issue by reggi** [Shopify/themekit#15]
Hey! Just stumbled upon this repo from [shopify_theme](https://github.com/Shopify/shopify_theme/issues/121). I know this project is very fresh, and is still being developed. I was surprised to see you have everything in downloadable releases. I'd love it if you guys used a package manager. I really don't care what package manager you guys choose, just so that I can download this dependency and embed it into my build process.

**Comment by csaunders** [comment]
Installation of themekit on [Linux and OSX is now basically jokes](http://themekit.cat/install/). And when #94 gets merged updating to newer versions will be a single command.

**Install for first time:**
`curl https://raw.githubusercontent.com/Shopify/themekit/installers/install | python`

**Update Application (once v0.3.0 goes out)**
`theme update`
