### ISSUE TITLE
-allenvs fails on watch, and -env fails on upload

### ISSUE THREAD

**Issue by tyler-king** [Shopify/themekit#156]
It seems using `development` is required? We have a few sites which are clones of eachother execpt theres liquid to to detect the Shopify domain and hide/show different features. We've named the environment `ca`, `us` and `int`.

```bash
theme watch -allenvs
'' is not a valid environment. The following environments are available within config.yml:
 - ca
 - us
 - int
```

```bash
grunt release && theme upload assets/style.css.liquid assets/scripts.js.liquid -env us
...
'development' is not a valid environment. The following environments are available within config.yml:
 - ca
 - us
 - int
```

Is this a bug or `development` required?

**Comment by patrick-evolabs** [comment]
I was having the same error with theme replace. After adding development it started working but theme watch -allenvs now returns : 
' ' is not a valid environment. The following environments are available within config.yml:
 - development
 - france
 - worldwide
 - taiwan

**Comment by ndrewcowley** [comment]
+1 to this. If anyone knows of a fix, please share.

**Comment by tyler-king** [comment]
Ive not done any Go coding but looking into the source and playing with it, it seems its just not built in right now.

It seems there needs to be a loop [here](https://github.com/Shopify/themekit/blob/master/cmd/theme/main.go#L212) to create an set of theme clients for [this function to use](https://github.com/Shopify/themekit/blob/master/commands/watch.go#L12) because [isSingleEnvironment](https://github.com/Shopify/themekit/blob/master/commands/watch.go#L32) is returning true where `args.ThemeClients` is not set, only `args.ThemeClient` (singular).

**Comment by macdonaldr93** [comment]
@tyler-king for the env option, it should work if you put the environment before the list of files:

`theme upload -env=us assets/style.css.liquid assets/scripts.js.liquid`

Still a bug, but at least you can workaround until the fix.

**Comment by tyler-king** [comment]
Ah ok, but what about watch? This seems to not work for watch.

Sent from my iPhone

On Aug 12, 2016, at 3:59 PM, Ryan Macdonald <notifications@github.com<mailto:notifications@github.com>> wrote:


@tyler-king<https://github.com/tyler-king> for the env option, it should work if you put the environment before the list of files:

theme upload -env=us assets/style.css.liquid assets/scripts.js.liquid

Still a bug, but at least you can workaround until the fix.

-

**Comment by macdonaldr93** [comment]
`theme watch -env=staging`, for example, seems to work fine for me. There's still a bug with `-allenvs`.

**Comment by tyler-king** [comment]
As stated in my [previous comment](https://github.com/Shopify/themekit/issues/156#issuecomment-236904442) that the support is simply not coded in, we've come to a work-around of simply run multiple `theme watch -env (env-here)` at once which seems to work for the meantime.

**Comment by tanema** [comment]
Hey @tyler-king I will look into this let me just get this list of items missing straight:

[ ] - `-allenvs` option in watch
[ ] - `-env` option in upload

Is there anything I am missing

**Comment by tanema** [comment]
Well, I have looked into if further and found there there is no problem with upload only that you are required to have the flags before the arguments. This is not a bug but possibly we should update our docs to make this clearer.

However I will have a fix for the `-allenvs` bug early tomorrow.
