### ISSUE TITLE
Theme watch does not delete files

### ISSUE THREAD

**Issue by Moondrop** [Shopify/themekit#159]
Hello, the `theme watch` command does not remove files from Shopify's server if they are deleted locally. For example, if I delete an image in `/assets` it does not process. No problems with adding/uploading files however.

I had this exact same problem on the shopify_theme gem as well: https://github.com/Shopify/shopify_theme/issues/200

**Comment by Cam** [comment]
Interesting. For me `theme watch` has the default behaviour of deleting any files that gets changed locally in any way at all :/
