### ISSUE TITLE
Fonts are being uploaded as ascii files and being corrupted when using watch and upload.

### ISSUE THREAD

**Issue by scottbaggett** [Shopify/themekit#160]
When I put any of my fonts inside the assets folder they are not uploaded as binary which causes them to not work inside Chrome & Firefox. Is there any way to configure binary file patterns? 

If I upload these directly to my own S3 bucket as binary files they work, but if I set them as ascii I get the exact same error and after some digging around it does appear that this is an ascii upload error. 

![Image of Chrome Console Errors](http://cl.ly/3g0T2K0Z253h/download/Screen%20Shot%202016-05-24%20at%209.55.35%20AM.png)

**Comment by ilikeorangutans** [comment]
@scottbaggett Themekit attempts to guess the content type of all files using Go's [`http.DetectContentType`](https://golang.org/pkg/net/http/#DetectContentType) which seems to work fairly accurately. 

I've tried to reproduce the error locally but all font files I fed to Themekit were recognized as `application/octet-stream`.

Can you help me reproduce this by shedding a little more light on how you determined that they were uploaded as ASCII to shopify?

**Comment by scottbaggett** [comment]
Thanks for getting back to me. I will dig in a bit more and get back to you!

**Comment by tanema** [comment]
Closing because, this is stale. Please reopen if this is still an issue.
