### ISSUE TITLE
Interpolation of secrets into config.yml

### ISSUE THREAD

**Issue by rjocoleman** [Shopify/themekit#161]
Nice project, thanks! 

I'd like to commit my `config.yml` to my theme's repo but I don't want to store my API secrets in repo.
Is there a current best practise for this?

If not how do you feel about a PR for a method to interpolate these?

I can think of a few quick methods to do this:
1. via flags `theme watch --notify=/tmp/shopify.update --api-key=foo --password=bar` (not very user friendly)
2. Parsing of an optional file like `.credentials.yml` that gets merged in to the configuration struct if it exists.
3. Something based around `ENV` - in the Ruby world it's not uncommon to use a `.env` type file that contains secrets and then specify these in the YAML file that's then parsed prior to to unmarshaling e.g.
   
   ``` yaml
   ---
   theme_id: <%= ENV['THEME_ID'] %>
   ```
   
   I'd do this via [`text/template`](https://golang.org/pkg/text/template/) like so:
   
   ``` yaml
   ---
   theme_id: {{getenv "THEME_ID"}}
   ```
   
   then you could `THEME_ID=foobar theme watch --notify=/tmp/shopify.update` or use something externally that loads a `.env` file.. etc.

In all cases the usage order is important in case multiple values are specified.

**Comment by jtgrenz** [comment]
I'm not sure I understand the usefulness here. With ruby .env files, normally you need separate environment keys for production and development, so it makes sense in this case since they would need to change on the fly, but themekit is always gonna use the same set of keys; unless you're workflow is not what I'm imagining it to be. I've never had a need for this. 

Could you elaborate on the use case for this? Do you just have really complex configuration settings beyond the norm?

**Comment by rjocoleman** [comment]
1. `config.yml` with non-secrets to the theme repo so that all with access can use it easily.
2. Don't commit the api key secrets.

**Comment by tanema** [comment]
My next step of work on this repo is to integrate https://github.com/spf13/cobra and https://github.com/spf13/viper. This way you will be able to override config values with env variables. Also I would not need to include ruby into the project.

**Comment by rjocoleman** [comment]
thanks for the update @tanema. spf13/viper is very nice for this.

Also at no point was I suggesting to add Ruby, I'm sorry if that was unclear.
