### ISSUE TITLE
JSON content saved as a single line

### ISSUE THREAD

**Issue by illarionvk** [Shopify/themekit#165]
When using `./theme download` command to download all theme files, JSON file content is saved as a single line instead of pretty output. If I download it with a single file command, the JSON is saved correctly:

```
./theme download config/settings_schema.json
```

The issue occurs with settings and locale files, i.e. all files with `.json` extension. I'm running themekit 0.3.6 on a Mac.

![themekit-json-issue](https://cloud.githubusercontent.com/assets/5012724/17102165/a3d8d870-5278-11e6-80e1-0a7e4b5845d1.png)

**Comment by ilikeorangutans** [comment]
Without having looked into it, could you check the line breaks in this file?

**Comment by illarionvk** [comment]
`./theme download` outputs a single line JSON, no line breaks. Individual file download mode outputs indented JSON with Unix (LF) line breaks.

**Comment by ilikeorangutans** [comment]
@illarionvk I just downloaded a few files (.json, .liquid) using Themekit 0.3.6 on Mac OS X and linebreaks look fine. Do you see anything I'm missing or need to do differently to reproduce this?

**Comment by chryton** [comment]
@ilikeorangutans @illarionvk I was just able to recreate this via using `./theme download` to batch download the theme. When downloading via `./theme download config/settings_data.json`, it renders out with the correct line breaks. I can offer a screencast if it'd be helpful

If it matters, this was an issue with the theme gem as well.

**Comment by ilikeorangutans** [comment]
Hmmm. Is it possible that the linebreaks are changed serverside?

**Comment by illarionvk** [comment]
Thanks for the confirmation, @chryton.

@ilikeorangutans The issue with line breaks occurs only when you download the entire theme with `./theme download` command and only for JSON files. I guess bulk download mode and individual download mode use different functions. Could you check?

**Comment by illarionvk** [comment]
I use this workaround for now:

```
./theme download && ./theme download config/*.json locales/*.json assets/*.json
```

The command downloads the entire theme first, then JSON files get downloaded using the individual download command

**Comment by emiliobool** [comment]
I was trying to figure out a different issue so I set mitmproxy, and I got one line locale json files, so I removed the proxy and it was still happening, so just to make sure I wasn't going crazy I looked at older backups from a few hours ago and the files where normal, somehow the issue randomly appeared

no idea what triggers it, specially since it didn't happen just a few hours ago

illarionvk solution fixed it though

**Comment by emiliobool** [comment]
actually I have a vague idea on what could cause it, I think it started to happen after I used the replace command, and that probably triggers an update event on shopify side and then it formats the json files, but as stated above somehow bulk and individual differ somehow so that's probably it

**Comment by illarionvk** [comment]
Shopify JSON files' content is prettified (indented) in API responses, you can see it if you try to fetch the `settings_schema.json` via API in the browser:

```
/admin/themes/#{theme_id}/assets.json?asset[key]=assets/settings_schema.json&theme_id=#{theme_id}
```

The one line JSON bug occurs on ThemeKit side and only when the bulk download command is used. `shopify_theme` Ruby gem doesn't have this issue.

![screen shot 2016-08-18 at 09 41 15](https://cloud.githubusercontent.com/assets/5012724/17765834/723bb22a-6528-11e6-85f3-a2c31ab6caa7.png)
