### ISSUE TITLE
Feature Request: `--v` To view current installed version

### ISSUE THREAD

**Issue by chryton** [Shopify/themekit#166]
## Reasoning
Most command line tools allow you to see what version of the tool you are running and this can help triage a multitude of issues before elevating the problem.

## Use Cases
- Troubleshooting/Verifying ThemeKit bugs
- User checking whether or not they are up to date
- Troubleshooting development environment issues (machines running different versions)
- Verify installed version when creating CI/VM environments

**Comment by csaunders** [comment]
You can get version information by simply typing `theme version` which gives you the following output:

```
> build/development/theme version
Theme Kit v0.3.6
```

Failing to provide a subcommand or by passing in `-h` or `--help` when running the program lists all the available commands, one of which is `version`

```
> build/development/theme -h
Usage: theme <operation> [<additional arguments> ...]
  Valid operations are:
    upload <file> [<file2> ...]:
        Add file(s) to theme
    download [<file> ...]:
        Download file(s) from theme
    watch:
        Watch directory for changes and update remote theme
    configure:
        Create a configuration file
    bootstrap:
        Bootstrap a new theme using Shopify Timber
    update:
        Update application
    remove <file> [<file2> ...]:
        Remove file(s) from theme
    replace [<file> ...]:
        Overwrite theme file(s)
    version:
        Display themekit version
```

Sounds like this is already a solved problem, but I'll let those cool cats at Shopify like @chrisbutcher, @burke and @ilikeorangutans to make the call since I just make beer for a living.

**Comment by chryton** [comment]
@csaunders, @chrisbutcher, @burke and @ilikeorangutans: I do now see version under the available commands though have encountered another problem: the lists of commands are displayed in different orders per flag *and* each time you run them the order is different. 

Examples:
http://i.rocktc.de/1affA/5c2qVKlp
http://i.rocktc.de/1jvIo/4LZfhG2o

I'd expect that list to be consistent (alphabetical would make the most sense) between each call.

If anything, this also comes back to a documentation problem as that list is not entirely reflected in the docs: http://themekit.cat/docs/

**Comment by chryton** [comment]
@chrisbutcher, @burke and @ilikeorangutans If you'd like, I can close this issue and open a new one for the inconsistent returns for the help commands so that it is a bit more clear as to what we are trying to fix.

**Comment by chrisbutcher** [comment]
That'd be great, thanks @chryton & @csaunders !
