### ISSUE TITLE
Server responded with HTTP 403

### ISSUE THREAD

**Issue by crissmancd** [Shopify/themekit#167]
I'm just trying to get this set up. I have Theme Kit installed properly. I've created the config.yml file and configured it correctly. When I try to download the theme I get the following error:

Server responded with HTTP 403; please check your credentials.

Here's the config.yml file (hiding the actual values)

development:
  access_token: ###
  password: ###
  store: ###
  theme_id: 141131462
  bucket_size: 40
  refill_rate: 2
  ignore_files:
    - config/settings_data.json

I don't know what I'm missing. Thanks

**Comment by gabormeszoly** [comment]
@crissmancd hi, what is the solution?

**Comment by ewilliam** [comment]
@crissmancd ran into the same issue - what'd you do to fix?

**Comment by scottzirkel** [comment]
In your Private App, change the permissions of "Theme templates and theme assets" to Read & Write. Should download after that.

**Comment by gabormeszoly** [comment]
I'll try, thanks @scottzirkel

**Comment by gabormeszoly** [comment]
its working, thanks @scottzirkel
