### ISSUE TITLE
Theme watch requires 2 saves to update

### ISSUE THREAD

**Issue by jonnycobra** [Shopify/themekit#168]
When using `theme watch` I have to save a theme file twice. The first save removes it from the server, the second does the update. Is this a bug or an issue with my config? Using v0.3.6

**Comment by jonnycobra** [comment]
Still have this issue. Normal? Or am I doing something wrong?

**Comment by Cam** [comment]
#188

**Comment by Cam** [comment]
I'm seeing exactly the same behaviour on v0.4.2
