### ISSUE TITLE
replace command hangs and does nothing

### ISSUE THREAD

**Issue by canardos** [Shopify/themekit#172]
As mentioned by **cshold** in issue https://github.com/Shopify/themekit/issues/97, `theme replace` hangs and doesn't do anything at all.

I'm running on Win7x64. Cloned skeleton theme into local folder, created config.yml with standard settings (using password) and ran command.

**Comment by markmakes** [comment]
I'm getting the same running ElCap on Mac. Another developer and I have the same config. His works, mine doesn't.

**Comment by markmakes** [comment]
Re-installing doesn't seem to fix anything either. Just FYI

**Comment by chrisbutcher** [comment]
@canardos @markmakes Thanks for reporting this. Can you run `theme version` and let us know what version you're running?

**Comment by markmakes** [comment]
Theme Kit v0.4.2

Thanks for looking into this

**Comment by canardos** [comment]
Theme Kit v0.3.6, which was the latest at the time although it seems there was a flurry of releases two weeks ago.

**Comment by gescribano** [comment]
Same thing happening to me. Cloned Timber theme into local folder, created config.yml with standard settings (using password) and ran command.
I'm on mac. 
Theme Kit v0.4.2
Is there a workaround? Should we do the opposite way? install manually the Timber theme on the shop and then download?

**Comment by gescribano** [comment]
I found out that my private app needed theme read write permissions. 
The theme download command told me that. But I guess the replace command does not catch that error and just hangs.

**Comment by chrisbutcher** [comment]
Thanks all. @gesscribano your description gives me enough to reproduce this 👍

**Comment by chrisbutcher** [comment]
I was able to reproduce the `theme replace` hang by removing "Theme templates and theme assets" read/write permissions via the private app editing UI (/admin/apps/private/<id>)

Other commands error out with slightly more useful output, but at least do not hang. `theme watch` and `theme upload` both incorrectly respond with `[403]Cannot remove files that would make a theme invalid.`

 cc: @tanema

**Comment by tanema** [comment]
fixed by https://github.com/Shopify/themekit/pull/208

**Comment by markmakes** [comment]
Much appreciated fellas!
