### ISSUE TITLE
theme upload does nothing, after refactor PR, when given no filename args

### ISSUE THREAD

**Issue by chrisbutcher** [Shopify/themekit#176]
After https://github.com/Shopify/themekit/commit/11f0837ecc0eb42578ed9cc307e8cd79b6b4793f

Running `theme upload` does nothing, and prints no error message

![image](https://cloud.githubusercontent.com/assets/1916444/17751517/703cd726-6495-11e6-924a-08b44c57d644.png)

cc: @cshold

**Comment by chryton** [comment]
Can confirm this is happening on my local as well.

**Comment by chrisbutcher** [comment]
Found the issue. This function should not have been removed in a previous attempt to refactor https://github.com/Shopify/themekit/blob/e5b4b2a5ca8bfab146a6283d934d142174a2b46a/commands/upload.go#L59
