### ISSUE TITLE
Theme `upload templates/*` or `templates/**/*` Does Not Upload Customers Folder

### ISSUE THREAD

**Issue by chryton** [Shopify/themekit#177]
I've run a few releases off of the previous version without this problem. Returns with error `LoadAsset: File is a directory`.

I can upload the folder using `theme upload --env=staging templates/*/*` but that seems counterintuitive.

cc: @cshold

**Comment by cshold** [comment]
@chrisbutcher @m-ux Thoughts on this? I agree, `theme upload templates/*` I would think would upload everything, not fail on folders.

**Comment by chrisbutcher** [comment]
@chryton Have you tried `theme upload templates/**/*` ?
I believe this is the correct glob syntax to mean all subfolders (**) and files (*)

**Comment by chryton** [comment]
@chrisbutcher Same issue: http://i.rocktc.de/15dxn/BGX4hsBW

**Comment by chryton** [comment]
Weird thing is that `theme replace` _seems_ to do this correctly but that is a much slower process than upload.

**Comment by chryton** [comment]
@chrisbutcher @cshold any updates on this? Still a major blocker when deploying a theme.
