### ISSUE TITLE
upload does not print operation status of last file

### ISSUE THREAD

**Issue by n-kort** [Shopify/themekit#180]
Running `upload <file> [<file2> ...]` does not give any feedback about the last file, but seems to succeed regardless. When uploading a single file no success/error is printed at all.

Version v0.4.2 on El Capitan (but same thing on earlier version I had installed, probably 0.3.x).

**Comment by Antman261** [comment]
I've been experiencing this too, it's driving me nuts! Especially when I was trying endlessly to upload a single file and thinking it was failing silently...
