### ISSUE TITLE
Theme Kit Update Command Prompt

### ISSUE THREAD

**Issue by neilfish** [Shopify/themekit#183]
Hello,

After I last entered "Theme Watch" in my command prompt in order to sync my API with my Shopify store, I got a message that there has been an update for Theme Kit. It says I need to type "Theme Update" in order to update, however, I can't type anything in my command prompt after this message! It's basically frozen, just with a blinking cursor. How can I get around this to start using my API again?

Thanks,

Neil

**Comment by chryton** [comment]
@neilfish You need to exit out of theme watch to update. What platform are you on? If you are using Terminal on a Mac you can use `ctrl + c` to exit out and then run `theme update` and after it is complete you can turn `theme watch` back on

**Comment by neilfish** [comment]
@chryton Thanks! I got it to update. However, now I'm getting an error message in the command prompt after I type "Theme Watch" that says the following:

_could not load environment "development": missing theme_id. Error: "strconv.parseint: parsing "": Invalid syntax"_

Any tips?

Thanks a bunch,

Neil

**Comment by chryton** [comment]
@neilfish there was a change with the newest version of ThemeKit that fixed an issue with Theme IDs (you can read about it here: https://github.com/Shopify/themekit/issues/157) so I would double check that you are using the correct Theme ID and have the config file setup with the correct syntax.

Beyond that, I am not sure where to look. I'm just here trying to fix some other issues. :)

**Comment by neilfish** [comment]
Thanks Chryton. I updated my YML file with the theme ID and got it working. All good!

**Comment by chryton** [comment]
Hi @neilfish since this is seemingly resolved, could you go ahead and close this issue? Thanks!
