### ISSUE TITLE
theme download not working 

### ISSUE THREAD

**Issue by Zlerp** [Shopify/themekit#186]
I did the configure with my API key/password/site url, it created the config.yml file with the correct information.

but when i type "theme download" It fails quietly with nothing new created.

Any ides how to fix this issue?

Thanks,
Zlerp

**Comment by jvillalobos22** [comment]
I'm having the same issue. Just installed ThemeKit for the first time and can't get the `theme download ` command to work properly. It just executes quietly and nothing is added to my current directory. At this point, I have no way of developing this theme locally. Any help is appreciated.

**Comment by pirate-matt** [comment]
Had the same described issue.  Took about 3-4 times of running the command for it to work successfully, but it **did eventually work.**

_@Zlerp & @jvillalobos22  have you made any progress with getting it to work?  Maybe try running it a few times._

Recently updated my version of themekit to :Theme Kit v0.4.2 (not sure if this is related).  Anyone know of any logs or anything I could look at to see what occurred?  Potentially a network issue?

**Comment by jvillalobos22** [comment]
@pirate-matt I've tried running the command multiple times with no success. Most of the time it just runs with no error and nothing happens but sometimes it will actually output the error
```Server responded with HTTP 403; please check your credentials.```
I've double checked my credentials and I have everything thats required when running the configure command. Not sure what is causing the server error. I feel like this is an issue that was introduced in the most recent commit, having to do with HTTP timeouts. This is my first time using Themekit so I've never had a working version installed.

**Comment by pirate-matt** [comment]
@jvillalobos22 

Something else to try: make your `config.yml` looks like this (this is more spartan than what the configure command gives you).  _(I've removed actual data but kept in some numbers and alphas so you have an accurate idea of what needs to be there.)_

```yml
development:
  theme_id: 444444444
  password: b444b4444b4444bb444b44b4bb4bbb44
  store: not-my-actual-store.myshopify.com
```

and make sure the the password value is the private app password, not your personal user password.  (To get a private app password check out [`Step 2: Set Up API access` of this resource](https://www.shopify.com/partners/blog/95401862-3-simple-steps-for-setting-up-a-local-shopify-theme-development-environment))

**Comment by mhgbrown** [comment]
@pirate-matt's response got me going. I was getting ```unexpected end of JSON input``` with all the configuration parameters in the [example configuration](http://themekit.cat/docs/#config-example).  The specific configuration that was producing the error was ```proxy: http://localhost:8080```. I removed that and 👌

**Comment by jvillalobos22** [comment]
Ok so I finally was able to get it working. Turns out the issue didn't lie in Themekit's configuration but rather with Shopify's permissions. After creating the private app, you must go into the App's settings and adjust the permissions to allow 'Read and write access' to Theme templates and theme assets as these were set to 'no access' by default. The instructions for Themekit are outdated all over the internet so maybe Shopify should spend sometime updating their tutorials.

**Comment by thisislawatts** [comment]
@jvillalobos22 I think the permissions settings for Private Apps is a fairly new feature within Shopify.
I got stumped on it myself today. I think it's probably worth submitting a PR to the `gh-pages` branch adding a note about this.

Do you want to do this? Otherwise I could pull something together over the weekend.

**Comment by tanema** [comment]
I added some documentation in a recent pull request that should clear up the permissions issues.

**Comment by Zlerp** [comment]
@jvillalobos22 haha it always soemthing stupid, damn permissions... Started a new job so i put this down for a while but i started working on building some sites again so i figured id check out this threads updates. Thanks for figuring it out greatly appreciate it bud!!

**Comment by krisdahl** [comment]
Seems like wouldn't be that hard to have it output the error if getting a 403

**Comment by tanema** [comment]
@krisdahl A 403 response code just means you do not have permission to access a resource. There is no indicator why you do not have permission. This could mean many things like you do not have your access rights setup correctly as in this case, but it could also mean you have an incorrect theme id, or an invalid password. None can be determined from a simple 403 status code.

**Comment by thewebfashionisto** [comment]
Thank you @pirate-matt that works for me! I've used the Shopify password instead of the App password.
