### ISSUE TITLE
Local error reporting seems to be broken

### ISSUE THREAD

**Issue by Cam** [Shopify/themekit#187]
`goroutine 5 [chan receive, 1 minutes]:
github.com/Shopify/themekit.SetErrorReporter.func2()
	/Users/chris/go/src/github.com/Shopify/themekit/error_reporter.go:58 +0x45
created by github.com/Shopify/themekit.SetErrorReporter
	/Users/chris/go/src/github.com/Shopify/themekit/error_reporter.go:64 +0x68`

I have around 8 lines like that after receiving `fatal error: unexpected signal during runtime execution`

~/Users/chris doesn't exist on the machine I am getting this error on. Should ThemeKit be trying to run an error report from a user that doesn't exist?

**Comment by tanema** [comment]
This will be fixed with newer versions, debug stack traces are removed.
