### ISSUE TITLE
theme watch doesn't start workers

### ISSUE THREAD

**Issue by cassidyclawson** [Shopify/themekit#193]
Hi all,

Both the shopify_theme gem and the themekit binary have spontaneously developed the same problem for two developers when we setup a new test store using a shopify partner account.

The problem is that running theme watch simply doesn't do anything. It hangs for a moment then brings you back to the terminal command prompt with no error message of any kind. 

theme check says "Shopify API is accessible and configuration is valid"

What's going on? I suspect this may have to do with my new partner account store seeing as this issue started when we switched over. 

Thanks!

**Comment by justalever** [comment]
Also having this issue. Rather upsetting because I REALLY don't want to have to use the browser interface.

**Comment by justalever** [comment]
@cassidyclawson Oddly enough I just figure out the problem minutes after posting my first comment. Head to your Private Apps section and toggle on the permission settings to **Read and Write**

**Comment by cassidyclawson** [comment]
Absolutely right, Adam. You beat me to posting the answer but we also cracked it yesterday.
Found it by looking at the switch statement in the watch command and checking the response object's code and found 404. It appears this case is not caught in the switch and so doesn't "say" a useful error message.
I'd make a PR but it doesn't appear anyone is merging them?
Cassidy Clawson
(831) 247-3750

		_____________________________

**Comment by tanema** [comment]
PR's are welcome I don't know why you would get the impression they are not.

**Comment by tanema** [comment]
@cassidyclawson Can you verify that this is still an issue? With the newest version 0.4.3 I have verified that it starts up the workers and will return a 403 (albeit with a misleading error message that will be changed in the next version) when your permissions are incorrect.
