### ISSUE TITLE
Ruby Fail

### ISSUE THREAD

**Issue by yondershore** [Shopify/themekit#196]
hey guys. everything was working until i had to restart my Mac. opened Terminal, typed "theme -h" and got the command list. typed "theme watch" and got this:

/Library/Ruby/Gems/2.0.0/gems/launchy-2.4.3/lib/launchy.rb:34:in 'rescue in open': Failure in opening uri nil with options {}: undefined method 'to_hash' for nil:NilClass (Launchy::Error)
	from /Library/Ruby/Gems/2.0.0/gems/launchy-2.4.3/lib/launchy.rb:40:in 'open'
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:117:in 'open'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in 'run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in 'invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in 'dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in 'start'
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.25/bin/theme:26:in '<top (required)>'
	from /usr/bin/theme:23:in 'load'
	from /usr/bin/theme:23:in '<main>'

i know this is a bone head thing, but i'm stuck.

thanks'

**Comment by jtgrenz** [comment]
@yondershore it looks like you might have the old theme gem on your path.  Try uninstalling the theme gem and make sure that the path to the themekit executable is on your path.

**Comment by yondershore** [comment]
thanks.. how to uninstall?

**Comment by jtgrenz** [comment]
try `gem uninstall theme`

**Comment by tanema** [comment]
Closing since this is not a problem with this repo
