### ISSUE TITLE
Automatic Installation on Mac doesn't work

### ISSUE THREAD

**Issue by Tdum** [Shopify/themekit#205]
<img width="888" alt="capture d ecran 2016-09-29 a 16 01 34" src="https://cloud.githubusercontent.com/assets/8091423/18957098/127c027a-865e-11e6-847b-86d3395bcd8d.png">

**Comment by tanema** [comment]
Hey thanks for the heads up. we are looking into this right away.

**Comment by tanema** [comment]
Hey sorry about that, I have updated the website but it will take a little while before it shows so while you wait you can install with this `curl https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | python`

**Comment by a-s-f** [comment]
hmm that got rid of that other error but still not working. 
![screenshot 2016-09-29 11 29 41](https://cloud.githubusercontent.com/assets/16754665/18960550/25617c56-8638-11e6-95a3-ef85a00861b6.png)

**Comment by tanema** [comment]
It doesnt look like you added it to your bashrc.

**Comment by a-s-f** [comment]
got it thanks @tanema  !
