### ISSUE TITLE
locales, config Not Being Uploaded

### ISSUE THREAD

**Issue by lloydh** [Shopify/themekit#211]
Whether I run a straight 'theme replace' or explicitly try to 'theme upload locales/de.json' (for example), the CLI exits without any feedback and without uploading anything.

My setup isn't ignoring these directories and I can't see any config to whitelist them.

I'm running theme kit on macOS Sierra, Ruby 2.3.0

**Comment by lloydh** [comment]
Hi tanema,
I ran the install script yesterday so I'm guessing it's the latest stable version.
I've also discovered that assets aren't being uploaded so it's just templates and snippets that are working for me!

**Comment by lloydh** [comment]
I can provide some insight…

My config.yml ignore_files contained 'js' as I wanted to exclude an uncompiled src js directory — what I didn't realises was that this was matching against any files containing 'js' in the filename or extension, including json.

Changing my ignore to 'js/' solved the problem, though I'm not sure if the aggressive matching is the expected behaviour?

**Comment by tanema** [comment]
hey thanks, that is helpful feedback. I will talk to the other maintainers about what should be expected. The agressive matching really helps powerful filtering but situations like this happen. Maybe in the future I will output a warning that a file is ignored due to a pattern.

**Comment by tanema** [comment]
Okay, I figured instead of neutering the file globbing I will document this better. I have added it to the planning for this year (https://github.com/Shopify/themekit/issues/128)
