### ISSUE TITLE
Is there an option for specifying a subdirectory to watch?

### ISSUE THREAD

**Issue by adamwooding** [Shopify/themekit#216]
Hi there, 
I have a 'deploy' directory where all of my gulp tasks output to. Is it possible for me to store the theme config.yml file in my top level directory, and have it reference the deploy directory?

That way tasks can be run from the top level directory without having to change to the subdirectory to run theme tasks.

Is there a way to do this?

Thank you very much :)
Adam

**Comment by tanema** [comment]
Hey @adamwooding can you give me an example of what your directory structure looks like? Could't you use something like foreman to be running the gulp scripts in the top directory and run your theme task in your child directory in parallel?
