### ISSUE TITLE
When saving a very large CSS.liquid file the file gets cut off

### ISSUE THREAD

**Issue by amit0001** [Shopify/themekit#218]
Hi,

I am using the standard configuration.

Sometimes, not sure exactly when but very often, the file upload gets stopped and the file only uploads partially. The file gets stuck in this state until I manually paste using the admin console.

Thanks
Amit

**Comment by tanema** [comment]
Duplicate of https://github.com/Shopify/themekit/issues/200 I will be releasing 0.4.4 later today and that will fix your problem.

**Comment by amit0001** [comment]
Fixed. Thanks!
