### ISSUE TITLE
command not found: theme ,even after calling echo or export

### ISSUE THREAD

**Issue by Tr1po** [Shopify/themekit#219]
Hi,
I am working with Theme Kit last few weeks. It worked perfectly. However, today I tried to start my environment(in same folder where I was working on Friday). All commands with theme are not working because of this message `zsh: command not found: theme` .

I tried to reinstall Theme kit (installation without any problems), even manually put export path to .zshrc and .bashrc...both options had no result. I am desperate and no longer know what to try.

Here is for example shown one of many attemps.
![screen shot 2016-10-10 at 13 56 36](https://cloud.githubusercontent.com/assets/19331847/19235352/89612e74-8ef1-11e6-800c-c31933e0b21b.png)

Thanks for your advices.

**Comment by shanetheboland** [comment]
@Tr1po how did you solve this? I’m having a similar problem

**Comment by tanema** [comment]
@shanetheboland 

- did you run the commands outputted from the installation script?
- did you verify that theme exists at `~/.themekit/theme`?
- are you using a bash shell or something else?

**Comment by shanetheboland** [comment]
Figured it out.
1. My .bash_profile was a mess.
I added `PATH="/Users/shane/.themekit:$PATH"` to fix this.
2. I had to uninstall the shopify_theme gem. It also uses the `theme` command.
