### ISSUE TITLE
theme download does not download all files

### ISSUE THREAD

**Issue by japherwocky** [Shopify/themekit#221]
We have a theme that is also tracked in a github repository.  Something (seems like Langify or an admin) managed to delete a CSS file.

To try to check for anything else that may be missing, I cloned the repository, ran `rm assets/*`, then `theme download`.

yikes, nearly 60 files are missing!

However, I notice that some of those files are actually still being served.  I can see them in the web interface, and I can run `theme download assets/specific_file_name` to download them.

wildcard arguments, eg `theme download assets/*.png` or `theme download assets` or `theme download assets/*` don't work.  I feel like they did before this update?

this is kind of terrible guys, if we can't trust `theme download` to actually download files.

**Comment by KaBrau08** [comment]
I have the same issue, and the theme watch it's failing

**Comment by tanema** [comment]
What are you ignored files? Ignored files are now applicable to downloading.

**Comment by japherwocky** [comment]
```
  ignore_files:
    - "*.txt"
    - "*.swp"
    - "*~"
    - ".git*"
```

a subset of files not being downloaded:

```
        deleted:    assets/gingeniousben.png
        deleted:    assets/giphy.gif
        deleted:    assets/happyending.scss
        deleted:    assets/headingVa
        deleted:    assets/heldermiranda.png
        deleted:    assets/himalayanhitman.png
        deleted:    assets/home-size-extended.jpg
        deleted:    assets/home-size-standard.jpg
        deleted:    assets/home-slider-1.jpg
        deleted:    assets/home-slider-2.jpg
        deleted:    assets/home-slider-3.jpg
        deleted:    assets/home-slider-4.jpg
        deleted:    assets/homePageChange.css
        deleted:    assets/homePageChange.css.liquid
        deleted:    assets/icheck.min.js
        deleted:    assets/icon-01.svg
        deleted:    assets/icon-03.svg
        deleted:    assets/inner-hero.jpg
        deleted:    assets/insta-2.png
        deleted:    assets/insta-3.png
        deleted:    assets/insta-4.png
        deleted:    assets/insta-5.png
        deleted:    assets/insta-6.png
        deleted:    assets/insta-7.png
        deleted:    assets/jeremyyongch.png
        deleted:    assets/jquery-migrate-1.2.1.min.js
        deleted:    assets/jquery.chic.min.js
        deleted:    assets/jquery.currencies.min.js
        deleted:    assets/jquery.cycle2.carousel.min.js
        deleted:    assets/jquery.cycle2.min.js
        deleted:    assets/jquery.min.js
```

**Comment by tanema** [comment]
@japherwocky try taking out some of your ignore files. for instance your `.git*` is filtering your gif files. `.git*` is interpreted as a regex and that means you should have the form `\.git.*`

**Comment by tanema** [comment]
That should clear up the filtered files.

**Comment by tanema** [comment]
@japherwocky  Also as a side note `theme download assets/*`would have only ever worked if you already had the files on you machine because it would be expanded into a list of the files already in that directory. It still functions that way.

Can you please update your themekit to the 0.4.6, check your ignores, and confirm if your files are still empty? Thank you.

**Comment by chryton** [comment]
I am also seeing this on 0.4.6. Specifically if `ignores:` is blank but `ignore_files` is set as in a case such as this:

```
production:
  theme_id: 11111111
  password: 123678
  store: store-dev.myshopify.com
  concurrency: 4
  ignores:
  ignore_files:
    - "node_modules/*"
    - "src/*"
    - "*.html"
    - .jshintignore
    - .eslintrc.json
    - "*.sublime-workspace"
    - "*.sublime-project"
    - "package.json"
    - "gulpfile.js"
```

If I run `theme download --env=production` with the above I get a short list of files that it says has changed but it empties out every file within the theme on my local machine.

**Comment by tanema** [comment]
@chryton every single file? Also it seems like no one is using the regex syntax properly and every one is just expecting a * glob syntax. I will have to take this into account.

**Comment by chryton** [comment]
@tanema ~82/85 files emptied out. I can send you a screencast via email when I'm back in the office in the morning.

**Comment by japherwocky** [comment]
I've completely removed my ignore_files section, I'm getting mixed results.  Modified files are empty, deleted are missing:

```
modified:   assets/Daily_Carry.jpg
        deleted:    assets/KeySmarts, Still Images, Smaller, Compressed.zip
        modified:   assets/core.css
        modified:   assets/gallery3.jpg
        modified:   assets/gallery4.jpg
        modified:   assets/garate55.png
        modified:   assets/gingeniousben.png
        modified:   assets/giphy.gif
        deleted:    assets/happyending.scss
        deleted:    assets/headingVa
        modified:   assets/heldermiranda.png
        modified:   assets/home-size-standard.jpg
        deleted:    assets/home-slider-1.jpg
        deleted:    assets/home-slider-2.jpg
        deleted:    assets/home-slider-3.jpg
        deleted:    assets/home-slider-4.jpg
        deleted:    assets/homePageChange.css
        deleted:    assets/insta-7.png
        deleted:    assets/jeremyyongch.png
        deleted:    assets/jquery-migrate-1.2.1.min.js
        deleted:    assets/jquery.chic.min.js
        deleted:    assets/jquery.currencies.min.js
        deleted:    assets/jquery.cycle2.carousel.min.js
        deleted:    assets/jquery.min.js
        modified:   assets/keysmart_v2.svg
        modified:   assets/keysmart_v2.ttf
        modified:   assets/keysmart_v2.woff
        modified:   assets/kurt_head.jpg
        deleted:    assets/ly-rtl.css
        modified:   assets/milkywayGalaxy.png
        modified:   assets/nater2389.png
        modified:   assets/option_selection.js
        modified:   assets/pablocunha.png
        modified:   assets/play.png
        modified:   assets/prefixfree.min.js
        modified:   assets/select2.js
        modified:   assets/styles.gift-card.scss
        modified:   assets/suitguy.jpg
        modified:   assets/walter.jpg
        modified:   assets/white_arrow.png
        modified:   assets/younggirl2.jpg
        modified:   config.yml
        modified:   config/settings_data.json
        modified:   layout/theme.liquid
        modified:   snippets/ly-static-string.liquid
        modified:   templates/article.liquid
        modified:   templates/cart.liquid
        modified:   templates/collection.liquid
        modified:   templates/collection.pro.liquid
        modified:   templates/gift_card.liquid
        modified:   templates/index.liquid
```

It looks like the missing files are consistently the tail end of the alphabet.

**Comment by japherwocky** [comment]
Also - maybe 50/50 I hit the 30 second timeout, and nothing happens.  When it succeeds, I don't get the error message (but files are messed up).  Maybe it's a race condition with that timeout?

**Comment by tanema** [comment]
@japherwocky thanks for the effort, I am thinking you are right about the race condition. Can you send me your config.yml to tim.anema@shopify.com and then I will send you a build without concurrency in download and we can check if that may be the case.

**Comment by tanema** [comment]
@japherwocky So I just published some fixes for downloading and you can update your themekit to 0.4.7. However with your config I noticed that your theme is quite large so it is timing out. if you set your timeout in your config file to this `timeout: 60000000000` that will set it to 60 seconds and then the timeout won't happen. I know that isn't a very good value for a timeout so I have also created an issue here: https://github.com/Shopify/themekit/issues/226 to take care of that. Please try out the new version with the timeout and let me know how it goes.

**Comment by tanema** [comment]
Closing because the PR seems to have fixed @japherwocky issue.
