### ISSUE TITLE
Timeout when using replace

### ISSUE THREAD

**Issue by amit0001** [Shopify/themekit#231]
Hi,

When issuing a theme replace command on a large theme, after a while the command stops with the message:
Theme Kit timed out after 30s seconds

Is this configurable somehow? Is anything replaced until the timeout?

Thanks
Amit

**Comment by tanema** [comment]
Hi @amit0001 you can increase your timeout by adding `timeout: 60s` to your configuration. Usually you will experience a timeout if there is a very large single file being uploaded.

**Comment by amit0001** [comment]
After updating the timeout to 180s it worked. Thanks!

**Comment by Oyagizem** [comment]
Hello, where is config file?
