### ISSUE TITLE
Cannot update Theme Kit for Debut Theme

### ISSUE THREAD

**Issue by joshiefishbein** [Shopify/themekit#238]
I may be using a version so old that `theme update` or the like do not work for me. Terminal explains that this is not a valid command.

The reason why I am trying to update is because I am trying to develop for the Debut theme, but because the `/sections` directory is new, Theme Kit errors saying:

    sections/slideshow.liquid' is not in a valid file for theme uploads
    Files need to be in one of the following subdirectories: layout/ assets/ config/ snippets/ templates/ locales/

It does this for each file in the directory. Is my Theme Kit version out of date? Is there something else that is wrong?

**Comment by tanema** [comment]
Hey @joshiefishbein can you please tell me the output of `which theme`? It looks like you are running the theme gem still and not this version of theme kit. Current theme kit supports the sections folder.

**Comment by joshiefishbein** [comment]
@tanema thanks for getting back to me so quickly. Here's the output of `which theme`:
    
    /usr/local/bin/theme

**Comment by tanema** [comment]
what about `theme version`

**Comment by joshiefishbein** [comment]
@tanema `theme version` responds with: `Could not find command "version".`

**Comment by arypbatista** [comment]
I think you are running `shopify_theme`. Try reinstalling themekit.

**Comment by arypbatista** [comment]
If you are on Linux or MacOSX: maybe you have installed themekit but you didn't added to our PATH.

**Comment by tanema** [comment]
Thanks for helping out @arypbatista! @joshiefishbein you are using `shopify_theme` gem. You can remove this by running `rm $(which theme)` then install theme kit using `curl https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | python` Make sure to follow the instruction at the end of the installation to add theme kit to your path.

**Comment by joshiefishbein** [comment]
Ok Thanks so much for the support @tanema and @arypbatista !!
