### ISSUE TITLE
JSON files are indented with tabs instead of spaces

### ISSUE THREAD

**Issue by illarionvk** [Shopify/themekit#239]
Thank you for resolving the [JSON pretty-printing issue](https://github.com/Shopify/themekit/issues/165).

In 0.4.7, lines in JSON files are now indented with tabs instead of spaces. Multiple coding style conventions recommend indenting JS code with spaces:

- [Node](https://github.com/nodejs/node/blob/master/.editorconfig) — 2 spaces
- [NPM](https://docs.npmjs.com/misc/coding-style) — 2 spaces
- [AirBnB](https://github.com/airbnb/javascript#whitespace) — 2 spaces
- [Mozilla](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style) — 2 spaces

Could you set the indentation for theme's JSON files to 2 spaces?

**Comment by tanema** [comment]
Oh yes that isn't right! Thanks for letting me know.

**Comment by illarionvk** [comment]
Thank you, I hope the new release is coming soon. I'm using this workaround for now:

```
./theme download && find . -name '*.json' -maxdepth 2 -mindepth 2 | parallel -j 1 'cat {} | json_reformat -e | sponge {}'
```

This command reformats JSON after the download. You'll need [YAJL](http://lloyd.github.io/yajl/), [GNU parallel](https://www.gnu.org/software/parallel/) and `sponge` from [moreutils](https://joeyh.name/code/moreutils/). On a Mac, both can be installed via Homebrew:

```
brew install yajl
brew install moreutils --without-parallel
brew install parallel --force
```
