### ISSUE TITLE
Docs Down

### ISSUE THREAD

**Issue by chryton** [Shopify/themekit#241]
http://themekit.cat/ is currently down after the latest release.

**Comment by tanema** [comment]
Yes please see here https://shopify.github.io/themekit/ I will be updating the binary later today so there is no reference to that domain any more.

**Comment by chryton** [comment]
@tanema Ah, thanks; we didn't see that change. Is there any plans to add a redirect from that domain?

**Comment by tanema** [comment]
Yes it *should* have already been done but in the works.
