### ISSUE TITLE
Windows Download 404

### ISSUE THREAD

**Issue by Lomejook** [Shopify/themekit#244]
Hi, where I can download the windows 64bits distribution? 

This link is not available:

https://github.com/Shopify/themekit/releases/download/0.5.0/windows-amd64.zip

**Comment by Lomejook** [comment]
Docs links are wrong, you should update to the last release

https://github.com/Shopify/themekit/releases/download/v0.5.1/windows-amd64.zip

**Comment by tanema** [comment]
Thanks for letting me know. I have fixed the download links now.
