### ISSUE TITLE
ThemeKit downloads wrong theme when bootstrapping

### ISSUE THREAD

**Issue by tekhaus** [Shopify/themekit#248]
Followed the instructions to bootstrap a new theme, which correctly created a new instance of Timber (2.2.2) in the shop, however when it fetched assets, it appears to have downloaded the **Debut** theme files (as evidenced by the sections folder among other things).
![screenshot](https://cloud.githubusercontent.com/assets/1009347/20121186/eeaec8a6-a5c4-11e6-9881-ed9a65bb0db4.jpg)

**Comment by tanema** [comment]
This is interesting https://github.com/Shopify/themekit/blob/master/cmd/bootstrap.go#L20 is the settings for the paths to Timber so if it is downloading Debut it is happening upstream. I will have to get back to you on this.

**Comment by tanema** [comment]
@tekhaus I have gotten the maintainers of Timber and Debut involved in this and I will get back to you when they find anything.

**Comment by driespieters** [comment]
I also tried setting up a new theme with bootstrap. Themekit successfully created a new theme in the store but downloaded the store's published theme.

(So I assume @tekhaus his published theme was Debut)

**Comment by tanema** [comment]
hey @driespieters thanks! that really sheds some light on what is happening! This is a bug I can fix.

**Comment by tekhaus** [comment]
@driespieters @tanema yep, my store was using Debut as it's published theme (as I assume all brand new Dev stores do currently)
