### ISSUE TITLE
Lots of errors with v0.5.x

### ISSUE THREAD

**Issue by foobartel** [Shopify/themekit#249]
Hi, 
after updating Themekit to the latest version 0.5.1 I get lots of errors that files couldn't upload correctly. A few times the process completely crashed after such errors. This has not happened so far with any of the last 4 previous versions.  `theme upload <file>` seems to work without problems.
Cheers, Holger

```
theme watch
Watching for file changes for theme 152714887 on host xyz.myshopify.com 
Received Create event on templates/product.liquid
[404]Asset Perform Create to templates/product.liquid at host <xyz.myshopify.com>
	Status text: Not Found
	Errors: Not Found
Received Create event on templates/product.liquid
[404]Asset Perform Create to templates/product.liquid at host <xyz.myshopify.com>
	Status text: Not Found
	Errors: Not Found
Received Create event on templates/product.liquid
[404]Asset Perform Create to templates/product.liquid at host <xyz.myshopify.com>
	Status text: Not Found
	Errors: Not Found
^CCleaning up watchers
```

**Comment by AlphaHasi** [comment]
Same here. On Mac OS X El Capitan (10.11.6).

It also prints "File not in project workspace." a lot. There is no hint about what file this message is, it just comes up again, again and again.

**Comment by tanema** [comment]
Hey @foobartel there was an error that was unhandled refferred to in the #246 issue that has been taken care of. However I have seen the 404 errors as well and they are coming from shopify and not theme kit, I cannot help those.

@AlphaHasi I just released 0.5.2 that specifies the file name that the event happens on so you will know which file it is referring to.

Please try out the new release and let me know if it helps at all.

**Comment by AlphaHasi** [comment]
Hi @tanema, thanks for your fast help!

The complete message showed me now that the folder ".idea" is not in workspace. So my bad: that is a folder from PhpStorm that I now added to "ignore_files". Strange that it never complained before. This error message are gone. 

The messages: "Status text: Not Found/Errors: Not Found" are another thing.

Thanks!

**Comment by tanema** [comment]
@AlphaHasi Yes the newer version of theme kit is more verbose. All errors are reported rather than just swallowing the errors.

**Comment by chryton** [comment]
Seeing something similar on 0.5.2 using `theme replace` that is halting the replace:

```
[0]Asset Perform Update to assets/store.min.css.liquid at host <>
	Status text:
	Errors: none
```

**Comment by tanema** [comment]
@chryton how large is the file that you are editing? The timeout is not specifically on the http request so if it takes longer than 30s to upload it will timeout. I might raise the timeout because that timeout is a bit low for large files.

**Comment by chryton** [comment]
@tanema I have my timeout in the config set to `timeout: 60000000000`.

The files vary. I am getting it on some liquid files that range from 42 bytes up to 6kb and images that range from 28kb to 300kb.

**Comment by tanema** [comment]
It may just connection issues that I cannot do anything about except recover from. I will look into this further. A lot of these errors may be shopify related and theme kit is only passing on the error to the users.

As a side note when specifying your timeout you can use the format of `60s` for sixty seconds or even `1m` for one minute.

**Comment by chryton** [comment]
@tanema ah, thanks for the note on the time out; I was using what you had said a while back to do.

**Comment by AdamCraven** [comment]
Hi @tanema, Can reproduce same error as OP, but with small SVG file. It uploaded fine first time, but `theme watch` and then file modification and it will give OPs error. Using theme upload, there's no error. Using themekit 0.5.2.

**Comment by tanema** [comment]
Thanks @AdamCraven for the extra information.
