### ISSUE TITLE
Same errors as 0.5.1

### ISSUE THREAD

**Issue by tobypowell** [Shopify/themekit#250]
have to save multiple times to get the file to save and upload, generally getting this error 9 times out of 10:

Received Create event on assets/main-style.scss.liquid
[404]Asset Perform Create to assets/main-style.scss.liquid at host <hipsterfy-theme.myshopify.com>
	Status text: Not Found
	Errors: Not Found

**Comment by tanema** [comment]
Duplicate of #249
