### ISSUE TITLE
Default ignore_files

### ISSUE THREAD

**Issue by liam-hennessy** [Shopify/themekit#251]
A suggestion for an enhancement: Since many themekit users will also use version control software, how about adding a default list of files that are safe for themekit to ignore?

This would reduce the noise in the output of `theme watch`. Currently, without manually configuring each of my config.yml files, I see lots of this:
```
Received Create event on layout/.svn/tmp/all-wcprops
[422]Asset Perform Update to layout/.svn/tmp/log at host <example.myshopify.com>
	Status text: Unprocessable Entity
	Errors: Theme files may not be stored in subfolders
		Missing {{content_for_header}} in the head section of the template
		Missing {{content_for_layout}} in the body section of the template
		Must have a .liquid file extension
[404]Asset Perform Create to layout/.svn/tmp/entries at host <example.myshopify.com>
	Status text: Not Found
	Errors: Not Found

```

By **ignoring .svn folders by default**, there would be less API calls to Shopify, less storage required by Shopify, and a better experience for theme developers.

For example, a Sublime Text plugin that watches for changes to files and uploads them to a web server using SFTP ignores the following patterns by default:
```
        "\\.sublime-(project|workspace)",
        "sftp-config(-alt\\d?)?\\.json",
        "sftp-settings\\.json",
        "/venv/",
        "\\.svn",
        "\\.hg",
        "\\.git",
        "\\.bzr",
        "_darcs",
        "CVS",
        "\\.DS_Store",
        "Thumbs\\.db",
        "desktop\\.ini"
```

**Comment by tanema** [comment]
@liam-hennessy Yeah I think this has been requested enough times that I should look into more complex default ignores. Thanks!
