### ISSUE TITLE
Theme Watch not working - "Error: Could not watch directory `xxx/directory-path/`: too many open files"

### ISSUE THREAD

**Issue by pkavanaghjr** [Shopify/themekit#253]
Hello,

I was using theme kit without any issues for a few weeks until one day it just stopped working and started throwing errors. There have been a few different errors that have occurred over the last few themekit version updates. Ive been in contact with Tim from Shopify and weve tried to resolve this with no luck. So heres some of my errors and our progress:

Originally had an issue connecting to the host. I had no issue visiting the site and running `theme upload` worked as it should.
![screen shot 2016-10-12 at 2 58 12 pm](https://cloud.githubusercontent.com/assets/19740619/20223274/891d3edc-a7fe-11e6-9406-39b9b6691e25.png)

I believe there was a themekit version update between these two screenshots, and heres the errors i started receiving:
![screen shot 2016-10-13 at 3 36 03 pm](https://cloud.githubusercontent.com/assets/19740619/20223277/8b904164-a7fe-11e6-80e2-a6b5ed9b5009.png)

And now currently I am receiving these errrors:
![screen shot 2016-11-11 at 10 55 59 am](https://cloud.githubusercontent.com/assets/19740619/20223437/52d4ad6e-a7ff-11e6-9283-d21fad39660d.png)

**Comment by joshiefishbein** [comment]
This has also been happening to me.

When I do `theme watch -e development` it will work fine. When I do `theme watch -e production` after it returns this same error.

**Comment by tanema** [comment]
@joshiefishbein thanks for the extra info! @pkavanaghjr and I have been puzzled about this for a while now.

**Comment by tanema** [comment]
Hey so here is an issue linked with our issue https://github.com/fsnotify/fsnotify/issues/129 I think if I add better default ignores from this issue https://github.com/Shopify/themekit/issues/251 and setup the file watcher to not watch files that are ignored then I might be able to have this work more reliably.

A couple questions:

- Do you use git or svn in these projects that are giving you issues?
- do you use processors that keep a lot of files around like `.sass-cache`
- do you use a text editor that uses a lot of dot files to track changes?

**Comment by signal-intrusion** [comment]
I've had a similar issue. There was an easy workaround, but I don't know if it will help you: http://blog.mact.me/2014/10/22/yosemite-upgrade-changes-open-file-limit

**Comment by joshiefishbein** [comment]
@tanema 

- Yes I use git, and the repo root is the same as the config.yml location
- Yes on some of the projects I've used this on I've used Compass that auto-creates a .sass-cache
- I use Sublime at the moment, I don't believe I'm using it in a way that creates a trail of dot files. However, macOS sometimes leaves the `.DS_Store` hanging around.

**Comment by tanema** [comment]
@pkavanaghjr I just release version 0.6.0, can you please try it out? I have added more default ignores and less directory watching so it will use fewer file descriptors. If that does not work can you also please try @signal-intrusion solution?

**Comment by tanema** [comment]
@pkavanaghjr Has confirmed that the new release has fixed this issue.

**Comment by namurray** [comment]
I am using v 0.7.5 and get this error

**Comment by tanema** [comment]
@namurray Are you on OSX and did you try the guide in the FAQ? https://shopify.github.io/themekit/faq/#i-am-getting-the-error-could-not-watch-directory-too-many-open-files

**Comment by namurray** [comment]
yes OSX, I am curious though because you said this was fixed in version 0.6

**Comment by tanema** [comment]
@namurray I can't really *fix* it, only mitigate it as much as possible. OSX has a very low file descriptor limit and so if your theme has a sufficient amount of files, this can still happen. The watch command needs a file descriptor for every file that it watches. You could also mitigate it yourself by adding ignores for files that you don't often edit like *.png, *.jpg ect.

**Comment by namurray** [comment]
i tried ignoring all images in the asset folder and still got the error :/ like it didnt ignore anything.

i have trouble with version 0.7 tbh. on another machine i have an older version and it works fine (not sure which off top of my head). i was able to start watch by just deleting all the images in the asset folder...but none of my saves were actually picked up.

on my other machine, i did a theme update and had the same issue with the watch not working (on a PC, no big asset folder, no other errors), and a rollback fixed it.

**Comment by tanema** [comment]
Okay @namurray can you please email me your shop domain and which theme you are working on to tim.anema@shopify.com and I will take a look. Also any extra config you have in youy config.yml

Also do you have other folders like a node_modules folder?
