### ISSUE TITLE
Small Feature Request - Show state of themeId on theme watch

### ISSUE THREAD

**Issue by justinmetros** [Shopify/themekit#257]
This is very opinionated but I had added it to my fork of gulp-shopify-upload before moving to ThemeKit, and found it very helpful.

Its awesome that when you run `theme watch` it lets you know the themeId. e.g.
`Watching for file changes for theme 123456789 on host mysite.myshopify.com`

What I found very helpful, and eliminates some second guessing when moving between published and unpublished themes was to also expose the state of the themeId. e.g.
`Watching for file changes for theme 123456789 ( main ) on host mysite.myshopify.com`
`Watching for file changes for theme 123456789 ( unpublished ) on host mysite.myshopify.com`

Its a tiny little thing but at a glance makes it easy to know if the changes we're about to make are going to the right spot. There's been many times I have run the wrong command by accident, or didn't swap out to a new theme id before running theme watch and had a brief 'oh crap that was close' moment. 

Just throwing this out there. I don't know GO so I'm pretty much useless there. Would contribute if I could.

Thanks for all the great work on ThemeKit, it rocks!

**Comment by sdn90** [comment]
+1 on this and an addition:

The Ruby CLI had the command `theme open` which opens the shop in a browser with `?preview_theme_id=THEME_ID`. This is extremely helpful when you are using the workflow with multiple themes on 1 shop.

The Ruby CLI did not output the URL though, which is annoying when needing to share with other people because Shopify does a redirect and removes the query string.

**Comment by tanema** [comment]
Hey thanks for the suggestions, @justinmetros I should be able to do this no problem.

@sdn90 I should be able to do this. I can also output the link to the console as well as open it.

**Comment by tanema** [comment]
Hey so with PR #260 that finishes up these request, these features will be in the next release.
