### ISSUE TITLE
theme watch not uploading new image assets

### ISSUE THREAD

**Issue by PTcampbell** [Shopify/themekit#258]
Since the latest update when I add a new asset to the directory I get this…

```
Received Update event on assets/.dat.nosync022e.Q628cQ
Successfully performed Update operation for file assets/.dat.nosync022e.Q628cQ to xxx.myshopify.com
```

For some reason it wont upload image assets. Am I missing something?

Thanks in advance!

**Comment by tanema** [comment]
Are you confused because it says update? Or does the asset not upload? It seems like the image asset uploaded successfully?

**Comment by PTcampbell** [comment]
Thanks for the response. The asset doesn’t upload at all.

**Comment by tanema** [comment]
How are you creating this file? .dat.nosync022e.Q628cQ is not an image file it seems like an application data file.

**Comment by PTcampbell** [comment]
I'm not sure what that file is – it's just the response I was getting when I renamed the "logo.png" file in the assets directory. At the moment though, when I drag any image into the assets directory I am getting no response from "theme watch".

**Comment by PTcampbell** [comment]
I am just moving images into the asset folder. Should this not sync? I also
tried “theme upload” which did not recognise any of the new images in the
assets folder.

I am not sure what the .dat files are – I can’t see them anywhere.

**Comment by tanema** [comment]
Hey @PTcampbell can you please tell me a few things

- Your OS with version
- Your text editor
- Your workflow (any processors)
- Your images adding/editing workflow.
- Your Theme Kit version.

**Comment by PTcampbell** [comment]
Thanks Tim.

   - I’m on 10.12.2 Beta (16C48b)
   - I’m using Atom (latest)
   - No preprocessors to speak of
   - Images are being created with sketch – simply exporting .pngs or .svgs
   into the assets directory – that or I will drag existing assets into the
   folder.
   - ThemeKit version is 0.5.3

**Comment by tanema** [comment]
@PTcampbell Also do you have any ignored files in your config?

**Comment by PTcampbell** [comment]
No ignored files :/

**Comment by tanema** [comment]
Hey @PTcampbell I am unable to reproduce this at all. Do all of your other assets respond as expected like your javascript in the assets folder?

**Comment by PTcampbell** [comment]
Existing assets such as SCSS and liquid files are responding. It's only new files such as images which don't upload. :/ 

Thanks

**Comment by PTcampbell** [comment]
I ripped it up and started again and everything is well again – sorry to have lead you down the garden path. Thanks for your help.

**Comment by tanema** [comment]
So you were using ignore patterns then?

**Comment by PTcampbell** [comment]
Yes – my bad 🙈

In my config I had …

  ignore_files:
    - config/settings.html
    - "*.png"
    - "*.jpg"

**Comment by teewuane** [comment]
I just discovered that Shopify does not support nested folders in assets of all places! I'd like to sit in on the discussion as to why that is.
