### ISSUE TITLE
Errors: SSL required

### ISSUE THREAD

**Issue by lineker** [Shopify/themekit#262]
Hi,

I'm running on macOS 10.12.1
ThemeKit - Shopify Theme Utilities 0.5.3
Installed using : curl https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | python

command that I'm trying to run: 
theme download

error:

[403]Assets Perform Retrieve at host <mystore.myshopify.com>
	Status text: Forbidden
	Errors: SSL required

any idea why?

**Comment by tanema** [comment]
Hi @lineker can you please send me your config file to tim.anema@shopify.com?

**Comment by tanema** [comment]
Also are you using a proxy of any kind?

**Comment by tanema** [comment]
Hey @lineker, the problem is that your provided the `https://` to the store config. Please omit that from your config so it looks like `store: mystore.myshopify.com` and it will work.

**Comment by tanema** [comment]
I will make a not of making this better so it is more apparent what is wrong.
