### ISSUE TITLE
Wildcards in theme download / upload

### ISSUE THREAD

**Issue by ksr583** [Shopify/themekit#264]
Would like to be able to use wildcards when downloading or uploading, for example:
```
theme download --env=staging assets/*.scss
theme upload --env=production snippets/homepage-*.liquid
```

**Comment by ksr583** [comment]
Ok now I'm a bit confused. This seems to work sometimes and not others, or I made a mistake a few times.

**Comment by tanema** [comment]
haha @ksr583 it is because the wildcards work if the files already exist on the local machine so your shell completes the glob with the file names.

You are correct though. Theme kit should support this feature, I will look into it.

**Comment by japherwocky** [comment]
If nothing else, please, let us do `theme download` to grab everything remotely.

This used to work and was key for keeping things in sync with a git repo.  As it stands, I guess it's back to the drawing board for a workflow that lets my team use git.

**Comment by tanema** [comment]
@japherwocky does theme download no longer work like that?

**Comment by japherwocky** [comment]
I'm really sorry actually, this was my fault, it hasn't changed at all - running the command from inside a subfolder gives a kind of cryptic error that I was interpreting wrong.

sorry sorry sorry, ignore that comment!
