### ISSUE TITLE
Theme download does not respect directory setting in config

### ISSUE THREAD

**Issue by stewartknapman** [Shopify/themekit#268]
I currently have a folder structure of:

   Client/
     -- Theme1/
     -- Theme2/
     -- config.yml

Inside my config i have a directory set up for Theme1/ and running `theme watch` from the client directory works as expected. A file changed inside the Theme1 folder is updated on the store. Magic.

But when I run `theme download` from the same place it pulls down the theme into the current Client/ directory, not Theme1/.

**Comment by tanema** [comment]
@stewartknapman thanks! I will look into it.

**Comment by tanema** [comment]
What version of themekit are you using?

**Comment by tanema** [comment]
I cannot reproduce this on version `0.5.3` the most current version.

**Comment by stewartknapman** [comment]
@tanema I'm also on version `0.5.3` I installed it fresh today.

**Comment by tanema** [comment]
Hey @stewartknapman The problem is that the directory config is not read in from the config file. I will fix this soon. You can workaround this by passing in the `--directory` flag.

**Comment by stewartknapman** [comment]
@tanema Thanks for the update
