### ISSUE TITLE
new Command wizard

### ISSUE THREAD

**Issue by tanema** [Shopify/themekit#283]
There should be a better interface to the command to get started with editing themes. There should be one command that sets the user up, step by step without them having to know more than one command.

## Design

- Get User Credentials
  - enter shop domain
  - enter private app password
- Choose New Action
  - Work on existing theme
    - List of the users existing themes.
    - Select an existing theme.
  - Duplicate exiting theme
    - List of users themes to duplicate
    - Select an existing theme to duplicate
  - Create a new theme from template
    - List of templates to start from
    - Select a template or Provide URL to fetch template from
- Prompt user to optionally name that theme.
- Save config.yml with the password/store/theme_id
- Download new theme.

## What this would change.

This would ideally remove the `bootstrap`, and `configure` commands. However with this process we may also be able to remove the `download` command since you would only download all files when you create a new theme.

## Items to discover

- [ ] Use email/password to authenticate api calls
- [ ] Create private apps remotely (I don't think so)
- [x] List existing themes?
- [x] duplicate existing theme
- [ ] A good list of existing templates

**Comment by chryton** [comment]
Could an option be to duplicate a theme to start new from? Though at that point you are basically creating a CLI for most of the existing theme admin.

**Comment by tanema** [comment]
@chryton duplication would be an good feature as well. Ideally I would love theme kit to be able to serve this purpose and minimize the amount of back and forth between Shopify admin and the command line. The problem is finding enough bandwidth for me to implement it.

**Comment by chryton** [comment]
> The problem is finding enough bandwidth for me to implement it.

That is the struggle.

**Comment by tanema** [comment]
closing in favour of #344
