### ISSUE TITLE
Keep losing themekit

### ISSUE THREAD

**Issue by brightonmike** [Shopify/themekit#284]
Hello.

Might be me being daft but for some reason Themekit keeps disappearing off my Mac. I'm a Mac newb so like I say, could be me being daft. I follow these steps:

Firstly, I run:
`curl https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | python`

Then it tells me to run:

`echo 'PATH="/Users/name/.themekit:$PATH"' >> ~/.bashrc
source ~/.bashrc
`

With name being my Mac user name. It then all works - but when I re-boot the Mac, I get:
`theme: command not found`

If I repeat the above steps, it comes back. So for some reason it's not installing permanently it's getting wiped. I haven't had such problems with other terminal line tools.

**Comment by tanema** [comment]
This sounds like you are using a non bash shell so it works once you source your `.bashrc` but otherwise when you open your terminal the `.bashrc` is not sourced.
