### ISSUE TITLE
Theme replace is not uploading file

### ISSUE THREAD

**Issue by frehner** [Shopify/themekit#287]
Just barely updated to the latest themekit version -- no other changes. 

Suddenly, `theme replace` is not uploading one of my files -- it happens to be my `theme.css` file, so my store has outdated CSS.

I don't have any ignore statements at all. 

If I manually say `theme upload assets/theme.css` it works. 

It's possible that other files are getting ignored/not uploaded as well, but I've only noticed the CSS file. I have tested making small changes to other files, and they seem to work, so I'm not sure where to go from here.

Using MacOS

**Comment by tanema** [comment]
Is theme.css in your root directory or your assets directory?

**Comment by frehner** [comment]
@tanema In the assets directory. Sorry for not specifying that :)

**Comment by tanema** [comment]
What happens when you run `theme replace assets/theme.css`?

**Comment by tanema** [comment]
Does the file upload while using `theme watch`?

**Comment by frehner** [comment]
@tanema that updated the file correctly. So then I made another change and just did the `theme replace` again and it didn't upload. So for some reason the whole theme replace command just misses that file.

**Comment by frehner** [comment]
@tanema `theme watch` works correctly as well.

**Comment by tanema** [comment]
Can you please email me your config to tim.anema@shopify.com I will take a look.

**Comment by frehner** [comment]
If I just take out the secrets and post it here is that ok? Or do you want the secrets as well? Since this config file is used to deploy to my live theme on my live site, I'm somewhat hesitant to to give out the secrets, ya know? :)

**Comment by tanema** [comment]
Yup that is fine as long as you are okay with sharing your store domain. Or you can just email me your store domain and I can get the rest of the data.

**Comment by frehner** [comment]
```
blue:
  password: xxxxx
  store: xxx.myshopify.com
  theme_id: xxx
  bucket_size: 40
  refill_rate: 2
```

I'll send over the other details.

**Comment by tanema** [comment]
Ah I understand now, this is because of your `theme.css.map` This makes themekit assume that theme.css is a compiled version of `theme.css.map` You could probably fix this by moving your map somewhere else or by rolling back your theme kit versions by using `theme update --version=<your last version>` although I am not sure how why this would have worked in previous versions.

**Comment by frehner** [comment]
Oh really? Interesting. I'll just have my SASS job output a .map file and see if that solves it for the moment... though having a css .map file is always nice, but not a deal breaker.

**Comment by tanema** [comment]
I can have a small fix in the future that will make it so that you can add `*.map` to your ignores and it will clear up these issues. You probably shouldn't be uploading them to shopify anyways.

**Comment by frehner** [comment]
Any particular reason why they shouldn't be in Shopify? They're only downloaded if devtools is open and they just show the uncompiled SASS source files instead of the the minified CSS files, so AFAIK there's nothing secret in them... but I'm always willing to learn more.

**Comment by tanema** [comment]
Only theme specific files should be stored on shopify, development files should not be. Not a hard law just a guideline.

**Comment by frehner** [comment]
Ok, I can see that point of view. I would contend that having access to SASS sourcemaps is pretty theme specific, and since themes can only be developed on Shopify (as opposed to a localmachine) that they're kind of necessary to be uploaded to help out development...

But nothing major in any case. :D 

I just tested out the removal of the theme.css.map file and you are correct that my theme.css file was uploaded. Thanks for helping me figure this out!
