### ISSUE TITLE
No timeout message

### ISSUE THREAD

**Issue by ButsAndCats** [Shopify/themekit#288]
Downloading a theme today with a lot of files I got the log:
`[development] Fetching assets from *****.myshopify.com`
but then the command stopped running without downloading any files or any message.

I resolved the issue by adding `timeout: 90s` to the config on a hunch but it would be handy to know if the command had timed out. I think this used to be a feature of themekit.

**Comment by tanema** [comment]
Thanks @ButsAndCats I will look into it because it by default has a value of 30s so it should timeout no matter what.
