### ISSUE TITLE
Sections is deleted on save

### ISSUE THREAD

**Issue by jjui** [Shopify/themekit#294]
Hi there, 

Got a quirk - and can be related to 0.6.1 as I just updated. 

There was a strange wrapping behavior I noticed in `theme.liquid` > `#MainContent` (in my case) just after the update. Only two sections were in the right place (within my ID) and the others where beneath. As nothing were really affected, I did a sidenote and continued my business. 
Then, the... 

**Issue**: 
* Almost every custom section were deleted after uploading `settings_data.json` and changing new parameter in Customize theme > General settings. The only sections left were the two first. 

* So ofc tried to rebuild the index in Customize theme but when adding a new section, the recreated section is appearing beneath the button ´Add section´ on save. 

* And when adding another section it is replacing the latest section added, also appearing beneath the add-button, but leaving the two not deleted sections intact.

* The new - and only section possible to add - is neither rendered on front end.

Clues? 

I will downgrade themekit and try to rebuild meanwhile.

**Comment by jjui** [comment]
This was caused by a extra `</div>`, the strange thing is that this broke the backend. 
Will ofc colse this leaving a thaught: How can the extra `</div>`break the backend?

**Comment by tanema** [comment]
@jjui Hey I was just replying I am glad your figured it out. I will talk to the theme developers about handling this. It probably should have replied with a syntax error.

**Comment by tanema** [comment]
@jjui Which commands were you using? `theme replace`? Did you get any errors from uploading or did you get a successful message?
