### ISSUE TITLE
watch not detect the changes under templates/customers

### ISSUE THREAD

**Issue by mustafahlvc** [Shopify/themekit#295]
"theme watch" don't detect the changes under templates/customers/ folder.

I have tried the versions it didn't work for v0.6.0 and v0.6.1

**Comment by tanema** [comment]
hey @mustafahlvc thanks for letting me know I will look into this.

**Comment by sarhov** [comment]
+ still not working

**Comment by tanema** [comment]
@mustafahlvc I have tested this and it seems to be working in v0.6.1. Do you have any ignore patterns in your config.

**Comment by sarhov** [comment]
my installed version is 0.61 and it is not working yet, in ignore, I have only settings json

http://u.sarhov.com/2hAqKIR

**Comment by tanema** [comment]
@mustafahlvc are you also using windows

**Comment by mustafahlvc** [comment]
Yes @tanema  i'm also using windows. I have ignore patterns but i had removed and tested it. not fixed.

**Comment by mustafahlvc** [comment]
@tanema I have tested with macOs and it works. Seems the issue happen only for windows.
