### ISSUE TITLE
Error when start theme watch

### ISSUE THREAD

**Issue by KKurek97** [Shopify/themekit#296]
I have an error when i run theme watch:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x4721cc]

goroutine 1 [running]:
panic(0x781700, 0xc042006080)
        /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1af
github.com/Shopify/themekit/kit.(*FileWatcher).watchDirectory.func1(0xc04237c6c0, 0x10f, 0x0, 0x0, 0x9777a0, 0xc042265020, 0x0, 0x0)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/kit/file_watcher.go:68 +0x5c
path/filepath.walk(0xc0421eea20, 0x101, 0x97d2a0, 0xc04233f140, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:372 +0x235
path/filepath.walk(0xc042376400, 0xf5, 0x97d2a0, 0xc04233f020, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0421c9680, 0xe8, 0x97d2a0, 0xc04233ec60, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc042344fc0, 0xdf, 0x97d2a0, 0xc04233eb40, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc042341880, 0xd2, 0x97d2a0, 0xc04233e720, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0420471e0, 0xc7, 0x97d2a0, 0xc042323e60, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc04232f380, 0xba, 0x97d2a0, 0xc042323b00, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc04232d550, 0xab, 0x97d2a0, 0xc0423238c0, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc042326140, 0x9e, 0x97d2a0, 0xc042323560, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc04231ae60, 0x95, 0x97d2a0, 0xc042322180, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0421eb5f0, 0x88, 0x97d2a0, 0xc0421e3e00, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0421c5c80, 0x7c, 0x97d2a0, 0xc0421cec60, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0421100e0, 0x6f, 0x97d2a0, 0xc042216660, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0421c2930, 0x69, 0x97d2a0, 0xc0421bef00, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0421be3c0, 0x5c, 0x97d2a0, 0xc0421be420, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0423654a0, 0x51, 0x97d2a0, 0xc042365500, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc042275770, 0x44, 0x97d2a0, 0xc04202f860, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc042042200, 0x3a, 0x97d2a0, 0xc04202e6c0, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0423681b0, 0x2d, 0x97d2a0, 0xc042173aa0, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc042368db0, 0x23, 0x97d2a0, 0xc042367f20, 0xc0420c1960, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0420c14e0, 0x16, 0x97d2a0, 0xc0420390e0, 0xc0420c1960, 0x0, 0x1)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.Walk(0xc0420c14e0, 0x16, 0xc0420c1960, 0x16, 0xc0420898e8)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:398 +0xdc
github.com/Shopify/themekit/kit.(*FileWatcher).watchDirectory(0xc042104540, 0xc0420c14e0, 0x16, 0x0, 0x0)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/kit/file_watcher.go:78 +0xc6
github.com/Shopify/themekit/kit.newFileWatcher(0xc04224c3c0, 0xc04213bf10, 0xc04225ffa0, 0x17, 0x99a1c0, 0xc, 0xc, 0xc042268200, 0x3, 0x4, ...)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/kit/file_watcher.go:62 +0x207
github.com/Shopify/themekit/kit.ThemeClient.NewFileWatcher(0xc04224c3c0, 0xc04213bf10, 0xc04225ffa0, 0x17, 0x99a1c0, 0xc, 0xc, 0xc042268200, 0x3, 0x4, ...)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/kit/theme_client.go:44 +0xc2
github.com/Shopify/themekit/cmd.watch(0xc04213fe00, 0x1, 0x1, 0x0, 0x0)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/cmd/watch.go:43 +0x3aa
github.com/Shopify/themekit/cmd.glob..func6(0x9970e0, 0x9b6c38, 0x0, 0x0, 0x0, 0x0)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/cmd/watch.go:28 +0x59
github.com/Shopify/themekit/vendor/github.com/spf13/cobra.(*Command).execute(0x9970e0, 0x9b6c38, 0x0, 0x0, 0x9970e0, 0x9b6c38)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/vendor/github.com/spf13/cobra/command.go:599 +0x23b
github.com/Shopify/themekit/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x996860, 0x996a80, 0x995dc0, 0x0)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/vendor/github.com/spf13/cobra/command.go:689 +0x36e
github.com/Shopify/themekit/vendor/github.com/spf13/cobra.(*Command).Execute(0x996860, 0x0, 0xc0420389c0)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/vendor/github.com/spf13/cobra/command.go:648 +0x32
main.main()
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/cmd/theme/main.go:9 +0x38

**Comment by tanema** [comment]
What version are you running

**Comment by KKurek97** [comment]
0.6.1

**Comment by tanema** [comment]
What OS are you using and did it work until recently? Do you have a config.yml? Are you providing any arguments to `theme watch`

**Comment by KKurek97** [comment]
windows 10 64-bit, i have a valid config.yml becauce theme download works and ilm not providing any arguments

**Comment by tanema** [comment]
Is this your first time using theme kit or did it work until recently?

**Comment by KKurek97** [comment]
Second time and in my old project works well

**Comment by KKurek97** [comment]
Any ideas?

**Comment by tanema** [comment]
Sorry I have not had a moment to look into it I will get back to you when I do.

**Comment by tanema** [comment]
It seems like there is a critical error while theme kit it setting up file watchers. I have a PR in progress to handle these errors in a more graceful way so it will be more apparent what the actual issue is.
