### ISSUE TITLE
Reading Body

### ISSUE THREAD

**Issue by KaBrau08** [Shopify/themekit#299]
I have the following issue whith "theme download" command:

- Status: Ok
- Errors: Client timeout exceeded while reading a body.

**Comment by tanema** [comment]
please try and increase your timeout limit by setting `timeout: 60s` in your configuration.

**Comment by plisvb** [comment]
Hi,

I'm allso getting the same issue: `Status: 200 OK
	Errors: net/http: request canceled (Client.Timeout exceeded while reading body)`
Increased the timeout to 60s didn't help.

**Comment by tanema** [comment]
@plisvb @KaBrau08 That exact error message is the message you get when your request times out. This either means that your connection is slow or your request is large. You should keep increasing the timeout until it works again. As a note, your request would be large if your project has any large files in it like video files or very large images.

**Comment by charlesemarsh** [comment]
theme download --timeout 420s

This fixed it for me

**Comment by tanema** [comment]
@charlesemarsh Thanks for confirming this.
