### ISSUE TITLE
Ability to whitelist files/folders instead of ignoring

### ISSUE THREAD

**Issue by stevebosworth** [Shopify/themekit#300]
Working on a project which does not build into a `dist/` before using themekit to upload and I'm trying to whitelist the relevant folders because we have so many folders/files at the root of the project that aren't part of the theme itself.

We tried using a regex but negative lookaheads are not supported by go's regex implementation.  We also tried using negated globs to whitelist the `assets/ config/ layout/ locales/ snippets/ templates/` folders.  This works with `theme watch` but not with `theme replace`.

Our folder structure looks like this:

```
.DS_Store
.bundle/
.dev/
.git/
.gitignore
.jscsrc
.jshintrc
.ruby-version
.scss-lint.yml
.themekit-ignore
Gemfile
Gemfile.lock
Procfile
README.md
Rakefile
_sprockets/
application.yml.dist
application.yml.ejson
assets/
browserslist
circle.yml
config/
config-dev.yml
config-staging.yml
config-staging.yml.example
config.yml
dev.yml
layout/
lib/
locales/
node_modules/
package.json
service.yml
shipit.yml
snippets/
spec/
templates/
theme-builds/
```

we only want to upload:

```
assets/ 
config/ 
layout/ 
locales/ 
snippets/ 
templates/
```

**Comment by tanema** [comment]
With the release of `0.6.1` theme kit should only watch those directories and nothing in the root directory. Which version are you using?

**Comment by tanema** [comment]
well actually only 
```bash
templates/customers
assets
config
layout
snippets
templates
locales
sections
```

**Comment by stevebosworth** [comment]
oh cool, I think I'm still on 0.6.0.  Will try out 0.6.1

**Comment by stevebosworth** [comment]
@tanema watch works great for 0.6.1 but it would still be great to either extend those defaults to `upload` and `replace` or add the ability to use a whitelist for those commands

**Comment by tanema** [comment]
oh yeah I should be scoping the local assets for upload and replace to be only part of the project as well. I will look into that when I get back.
