### ISSUE TITLE
Invalid theme_id or theme domain

### ISSUE THREAD

**Issue by jaythanelam** [Shopify/themekit#314]
Hi_ I'm trying to setup my local environment with ThemeKit and I continue to get the following error:

Invalid configuration: invalid theme_id,invalid store domain must end in '.myshopify.com'

despite have the correct url in place. here's what i'm running

`theme configure --password=[I have this ready] --store=[https://master-tool-machine-ergonomics.myshopify.com] --themeid=[165366476]`

**Comment by tanema** [comment]
Take out the protocol from your store param (https://)

**Comment by jaythanelam** [comment]
When I do so I still get the following message:

09:53:25 Invalid configuration: invalid theme_id,invalid store domain must end in '.myshopify.com'

**Comment by tanema** [comment]
Are you including those brackets?

**Comment by jaythanelam** [comment]
yep

`Jaythans-MacBook-Pro:MTM-theme jaythanelam1$ theme configure --password=[fe83640b78a7a364454cbd50d0f59e84] --store=[master-tool-machine-ergonomics.myshopify.com] --themeid=[165366476]`

**Comment by jaythanelam** [comment]
done and done! thank you that worked.

**Comment by Deltaspectro** [comment]
tuve el mismo problema, a mi me funciono poner el siguiente codigo:  theme get --list -p=password -s="shop-url.myshopify.com"

**Comment by Deltaspectro** [comment]
@tanema it works for me only with the quotes

**Comment by vemuez** [comment]
I removed the brackets haha. Forgot to do that. Also, password and the url shouldn't be wrapped with quotes.

**Comment by DownUndered** [comment]
> @tanema it works for me only with the quotes

Same for me. Works with quotes only

**Comment by joe-bb** [comment]
Make sure you are in the right folder, if you aren't you will get `invalid environment [development]: (missing store domain,missing password)`. Just figured it out

**Comment by valenstical** [comment]
> Make sure you are in the right folder, if you aren't you will get `invalid environment [development]: (missing store domain,missing password)`. Just figured it out

@joe-bb you saved my life.

**Comment by ette1277** [comment]
I really need help getting this
 invalid environment [development]: (missing theme_id,missing store domain,missing password)

**Comment by gigabrigade** [comment]
![Screenshot 2024-07-04 110542](https://github.com/Shopify/themekit/assets/170924817/813746a3-e5c8-4fbf-9703-bc2f3d0412df)

how to solve this anyone
