### ISSUE TITLE
Unable to add a new environment

### ISSUE THREAD

**Issue by johndwells** [Shopify/themekit#317]
Perhaps I'm doing something wrong, but I've added a "test" environment to my config.yml, specified the same sorts of settings for the development and production environments (changing values as necessary of course), but when I try to then download the theme with `theme download --env=test`, I get:

    nvironment=test does not exist in this environments list

Aside from editing the config.yml file, how else do we add a new environment into the mix?  This is the essence of my config.yml:

    production:
      password: ABCDEFG
      theme_id: "12345"
      store: mystore.myshopify.com
      timeout: 60s
      directory: mystore-12345
    development:
      password: ABCDEFG
      theme_id: "123456"
      store: mystore.myshopify.com
      timeout: 420s
      directory: mystore-123456
    test:
      password: ABCDEFG
      theme_id: "1234567"
      store: mystore.myshopify.com
      timeout: 420s
      directory: mystore-1234567

_I should note that I'm running version 0.6.1 due to waiting for this bug #312 to come out in the next release)_

**Comment by tanema** [comment]
I cannot reproduce this. I added a test environment without problem. Are you able to specify other environments with the env flag? What OS are you on?

**Comment by johndwells** [comment]
Thanks @tanema - actually no, I've just tried `theme download --env=production` and this too throws the error.

I'm on macOS Sierra, version 10.12.2.

It appears as though the `download` command specifically that throws this; I've been able to successfully use `theme watch --env=test` and `theme open --env=test`.

**Comment by tanema** [comment]
I still cannot reproduce this. Does download work if you use `theme download --env=development` ?

**Comment by johndwells** [comment]
_sigh_. Sorry, in terminal I'd missed a dash in my parameter flag. Ugh. :(

**Comment by tanema** [comment]
haha no problem! cheers
