### ISSUE TITLE
"Client.Timeout exceeded while awaiting headers" error on OS X. Cannot download theme. 

### ISSUE THREAD

**Issue by adrianocr** [Shopify/themekit#318]
23:25:13 Assets Perform Retrieve at host <[REDACTED].myshopify.com>
	    Status: 0
	    Errors: Get https://[REDACTED].myshopify.com/admin/themes/[REDACTED]/assets.json?fields=key,attachment,value: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by tanema** [comment]
Did you try raising your timeout?

**Comment by adrianocr** [comment]
@tanema raise the timeout of what in specific? I don't understand what is throwing the `Client.Timeout exceeded while awaiting headers` error at me. I tried the `--timeout` flag with 2m and then with 10m (which would be crazy) but the error still persists.

**Comment by tanema** [comment]
@adrianocr can you please send me your config.yml to tim.anema@shopify.com?

**Comment by tanema** [comment]
This seems like a shopify API issue, any other theme on your shop works however your live one does not. I may be related to it's size however there is not much to confirm that. I will keep this issue open while I get the API people to look into it.

**Comment by adrianocr** [comment]
That's a client's (dev) store. I'd rather not have you guys in there if possible. So I created a separate store and uploaded the theme to theme it. Emailed you the new config file. 

I also have a zip file with the theme if you guys want that.

**Comment by tanema** [comment]
I am seeing a lot of github traffic to this issue lately. If you are having this issue still please comment on this issue. Themekit no longer requests all files at once so this should no longer be an issue if you are on the most recent version of themekit. Please comment on this issue if you are still seeing this error message.

**Comment by stoneddesigner** [comment]
Still having this issue.

```
[development] Asset Perform Update to assets/from_Windsor_longsml.jpg at host ***.myshopify.com
        Status: 0
        Errors: Put https://***.myshopify.com/admin/themes/8076066852/assets.json: net/http: request canceled (Client.Timeoutexceeded while awaiting headers)

[development] Asset Perform Update to assets/P9558sml.jpg at host ***.myshopify.com
        Status: 0
        Errors: Put https://***.myshopify.com/admin/themes/8076066852/assets.json: net/http: request canceled (Client.Timeoutexceeded while awaiting headers)

[development] Asset Perform Update to assets/welcome-WCX17sml-f486e068f6.jpg at host ***.myshopify.com
        Status: 0
        Errors: Put https://***.myshopify.com/admin/themes/8076066852/assets.json: net/http: request canceled (Client.Timeoutexceeded while awaiting headers)
```

Steps to replicate:

1. Grab 10 stock images from Pexels, ranging from 5Mb to 15Mb.
2. Copy.
3. Paste into Shopify assets folder while `theme watch` is running.
4. Watch the errors pour in.

I also can access the file in some cases and it displays "Source file is empty".

I'm on MacOSX High Sierra 10.13.0 and I'm using ThemeKit 0.7.5 darwin/amd64 with VSCode's integrated terminal. I installed ThemeKit via Homebrew _today_ on a fresh install of High Sierra.

The issue kind of fixes itself when I copy and paste the files individually again to replace the old assets.

**Comment by cleo06** [comment]
Same issue 

14:16:55 [development] Received Update event on assets/ourstory.png
[development] Asset Perform Update to assets/ourstory.png at host georgie-porgie-test.myshopify.com
	Status: 0 
	Errors: Put https://georgie-porgie-test.myshopify.com/admin/themes/12939886650/assets.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by dankiv** [comment]
Got the same issue. It happens when you have a slow wifi connection, especially it's related to upload speed

**Comment by keidarcy** [comment]
Check local network connection.

**Comment by haotan19** [comment]
It happens to me sometimes. Personally, I will just be switching back and forth between cellular data and my wifi.
