### ISSUE TITLE
Updating 'settings_data.json' before all section files have uploaded leading to erroneous error

### ISSUE THREAD

**Issue by ruairiphackett** [Shopify/themekit#321]
Depending on what order theme files upload during `theme upload`, you can receive erroneous error messages stating that block types 'must be defined in schema' even though they are.

Here is a screenshot of the error occurring (happened as part of running `slate deploy` on one of the themes in the https://github.com/Shopify/shopify-themes repo):

![https://screenshot.click/2017-01-20_11-37-48.png](https://screenshot.click/2017-01-20_11-37-48.png)

The block types mentioned are defined correctly in the slideshow section schema.

It looks like that section file with the necessary schema was uploaded after the `settings_data.json` file, which could be what is causing the error:

![https://screenshot.click/2017-01-20_13-55-15.png](https://screenshot.click/2017-01-20_13-55-15.png)

[Here's a log of the output from `theme upload`](https://gist.github.com/ruairiphackett/2f1a85a53c95b677bdc28d0c0540850c), I aborted the upload after this.

@tanema @NathanPJF

**Comment by tanema** [comment]
Fixed in https://github.com/Shopify/themekit/pull/271 please update your themekit.
