### ISSUE TITLE
Linux version uploading JSON instead of theme template

### ISSUE THREAD

**Issue by philleif** [Shopify/themekit#322]
Running themekit in an Ubuntu VM and instead of uploading the theme files, it writes this JSON up to Shopify.

The files work perfectly when I use theme on OSX.

<img width="1307" alt="screen shot 2017-01-22 at 3 18 55 pm" src="https://cloud.githubusercontent.com/assets/18747/22185547/1f4688a6-e0b6-11e6-981b-3dc240759e7b.png">

<img width="1644" alt="screen shot 2017-01-22 at 3 18 00 pm" src="https://cloud.githubusercontent.com/assets/18747/22185539/00cdb2b4-e0b6-11e6-8836-639d467ef6ea.png">

{"filter":false,"title":"collection.set.001.liquid","tooltip":"/templates/collection.set.001.liquid","undoManager":{"mark":30,"position":30,"stack":[[{"start":{"row":39,"column":18},"end":{"row":40,"column":0},"action":"insert","lines":["",""],"id":1},{"start":{"row":40,"column":0},"end":{"row":40,"column":12},"action":"insert","lines":["            "]}],[{"start":{"row":40,"column":12},"end":{"row":41,"column":0},"action":"insert","lines":["",""],"id":2},{"start":{"row":41,"column":0},"end":{"row":41,"column":12},"action":"insert","lines":["            "]}],[{"start":{"row":41,"column":12},"end":{"row":42,"column":0},"action":"insert","lines":["",""],"id":3},{"start":{"row":42,"column":0},"end":{"row":42,"column":12},"action":"insert","lines":["            "]}],[{"start":{"row":40,"column":0},"end":{"row":42,"column":12},"action":"remove","lines":["            ","            ","            "],"id":4,"ignore":true},{"start":{"row":40,"column":0},"end":{"row":42,"column":0},"action":"insert","lines":["","",""]}],[{"start":{"row":40,"column":0},"end":{"row":42,"column":0},"action":"remove","lines":["","",""],"id":5}],[{"start":{"row":39,"column":18},"end":{"row":40,"column":0},"action":"remove","lines":["",""],"id":6}],[{"start":{"row":39,"column":18},"end":{"row":40,"column":0},"action":"insert","lines":["",""],"id":7},{"start":{"row":40,"column":0},"end":{"row":40,"column":12},"action":"insert","lines":["            "]}],[{"start":{"row":40,"column":12},"end":{"row":41,"column":0},"action":"insert","lines":["",""],"id":8},{"start":{"row":41,"column":0},"end":{"row":41,"column":12},"action":"insert","lines":["            "]}],[{"start":{"row":40,"column":12},"end":{"row":41,"column":0},"action":"insert","lines":["",""],"id":9},{"start":{"row":41,"column":0},"end":{"row":41,"column":12},"action":"insert","lines":["            "]}],[{"start":{"row":41,"column":12},"end":{"row":42,"column":0},"action":"insert","lines":["",""],"id":10},{"start":{"row":42,"column":0},"end":{"row":42,"column":12},"action":"insert","lines":["            "]}],[{"start":{"row":33,"column":26},"end":{"row":34,"column":0},"action":"insert","lines":["",""],"id":11},{"start":{"row":34,"column":0},"end":{"row":34,"column":14},"action":"insert","lines":["              "]}],[{"start":{"row":34,"column":14},"end":{"row":35,"column":0},"action":"insert","lines":["",""],"id":12},{"start":{"row":35,"column":0},"end":{"row":35,"column":14},"action":"insert","lines":["              "]}],[{"start":{"row":34,"column":14},"end":{"row":35,"column":14},"action":"remove","lines":["","              "],"id":13}],[{"start":{"row":34,"column":12},"end":{"row":34,"column":14},"action":"remove","lines":["  "],"id":14}],[{"start":{"row":34,"column":10},"end":{"row":34,"column":12},"action":"remove","lines":["  "],"id":15}],[{"start":{"row":34,"column":8},"end":{"row":34,"column":10},"action":"remove","lines":["  "],"id":16}],[{"start":{"row":34,"column":6},"end":{"row":34,"column":8},"action":"remove","lines":["  "],"id":17}],[{"start":{"row":34,"column":4},"end":{"row":34,"column":6},"action":"remove","lines":["  "],"id":18}],[{"start":{"row":34,"column":2},"end":{"row":34,"column":4},"action":"remove","lines":["  "],"id":19}],[{"start":{"row":34,"column":0},"end":{"row":34,"column":2},"action":"remove","lines":["  "],"id":20}],[{"start":{"row":33,"column":26},"end":{"row":34,"column":0},"action":"remove","lines":["",""],"id":21}],[{"start":{"row":22,"column":14},"end":{"row":23,"column":0},"action":"insert","lines":["",""],"id":22},{"start":{"row":23,"column":0},"end":{"row":23,"column":8},"action":"insert","lines":["        "]}],[{"start":{"row":23,"column":8},"end":{"row":24,"column":0},"action":"insert","lines":["",""],"id":23},{"start":{"row":24,"column":0},"end":{"row":24,"column":8},"action":"insert","lines":["        "]}],[{"start":{"row":44,"column":10},"end":{"row":44,"column":12},"action":"remove","lines":["  "],"id":24}],[{"start":{"row":44,"column":8},"end":{"row":44,"column":10},"action":"remove","lines":["  "],"id":25}],[{"start":{"row":44,"column":6},"end":{"row":44,"column":8},"action":"remove","lines":["  "],"id":26}],[{"start":{"row":44,"column":4},"end":{"row":44,"column":6},"action":"remove","lines":["  "],"id":27}],[{"start":{"row":44,"column":2},"end":{"row":44,"column":4},"action":"remove","lines":["  "],"id":28}],[{"start":{"row":44,"column":0},"end":{"row":44,"column":2},"action":"remove","lines":["  "],"id":29}],[{"start":{"row":43,"column":12},"end":{"row":44,"column":0},"action":"remove","lines":["",""],"id":30}],[{"start":{"row":43,"column":10},"end":{"row":43,"column":12},"action":"remove","lines":["  "],"id":31}]]},"ace":{"folds":[],"scrolltop":0,"scrollleft":0,"selection":{"start":{"row":43,"column":10},"end":{"row":43,"column":10},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":0},"timestamp":1485115630626,"hash":"6c5462a00bc48a00667f956ebb21ddbfacc15e97"}

**Comment by tanema** [comment]
Is that JSON from another file in your project?

**Comment by tanema** [comment]
Actually what editor are you using because this all looks like data that might come from your editor. I have no idea why it would be uploaded to the server but your editor might be doing something weird with swap files. Can you try a different editor as well?

**Comment by tanema** [comment]
@philleif Also you may want to edit your one screenshot to not include your shop domain. It is not good to release any more information than is necessary.

**Comment by philleif** [comment]
Oh - good idea.

I'm trying to use the Cloud9 Editor - everything is fine in Atom. Might be something I have to take up with them :/
