### ISSUE TITLE
Windows x64 config issues

### ISSUE THREAD

**Issue by acomms** [Shopify/themekit#331]
Hey there, i'm having issues with configuring after installation on Windows 10 x64

When trying to run 
`theme configure --password=[your-password] --store=[you-store.myshopify.com] --themeid=[your-theme-id]`
I get the following error
`Error: Invalid configuration: invalid theme_id,invalid store domain must end in '.myshopify.com'`

Both theme_id, and store domain are correct. Haven't been able to locate an existing config.yml file at the default path "C:\\Users\\User Name\\config.yml"

**Comment by tanema** [comment]
Hey @acomms there is no "default path" for a config file. The config file should be outputted to the current directory that you are in. Are you filling in the fields or are you running that command exactly as you have put it in this issue?

**Comment by acomms** [comment]
Hey @tanema , apologies for wasting your time. Was just a dumb syntax error on my part (was leaving in the square brackets). I'm a noob

**Comment by tanema** [comment]
No problem, I should probably make a note in the docs to omit the brackets. Cheers!
