### ISSUE TITLE
error updating from 0.6.3 to 0.6.4

### ISSUE THREAD

**Issue by jamesmthornton** [Shopify/themekit#332]
When I run theme update command in my local themekit directory it says "Updating from 0.6.3 to v0.6.4 and then says:
> Error: Could not update and had to roll back. open /usr/local/bin/.theme.new: permission denied

I've checked my config.yml, created and used the password from a new private app, created a new instance of theme kit, cleaned up watchers, made sure I had superuser privileges in terminal, restarted terminal, still can't get it to update. Any thoughts would be appreciated!

on Mac OS X 10.12.2 (Sierra) machine

**Comment by tanema** [comment]
It seems like something is messed up with the permissions on your installation of themekit. I would say remove themekit (`rm /usr/local/bin/theme`) and to be safe remove the update file and any old themekit files (`rm /usr/local/bin/.theme.new`, `rm -rf ~/.themekit`) then reinstall themekit.

**Comment by jamesmthornton** [comment]
ah ok! just deleted and installed the master and it worked, thanks Tim!

**Comment by joelbrennan0** [comment]
As a windows user, running PowerShell as administrator fixed permissions error for me.

**Comment by shaj1215** [comment]
I know this issue is closed, but for those developers that has the issue specially on mac, just use `sudo theme update` that will solve the case. Thanks :)

**Comment by haroldao** [comment]
> As a windows user, running PowerShell as administrator fixed permissions error for me.

Thanks. Same for me ✅
