### ISSUE TITLE
0.6.5 new progress bar breaks upload

### ISSUE THREAD

**Issue by raulmontejo** [Shopify/themekit#333]
After updating to 0.6.5 and running an upload command I get the below indefinitely and must force quit and rollback to 0.6.4 to keep working 😞 
```
$ theme upload assets/main.scss.liquid -e production
[production]: 1 / -1 [\]   0 %
```

**Comment by joshrps** [comment]
I'm having the exact same issue. Is there an easy way to roll back?

**Comment by tanema** [comment]
I have confirmed this, I will have a fix for this tomorrow.

**Comment by tanema** [comment]
`v0.6.6` was just released with a fix for this issue.

**Comment by raulmontejo** [comment]
@tanema beautiful - thank you!
