### ISSUE TITLE
Theme replace works fine but theme watch does not when inside a symlinked directory

### ISSUE THREAD

**Issue by blindMoe** [Shopify/themekit#336]
So I believe this is because I am in a sym linked directory but when I simply do:

`theme watch`

and update files.. nothing happens

But when I do: `theme replace snippets/foobar.liquid` it works as expected.  That let me know that my config is setup properly and my api secret was authorizing.

I then ran this:

`theme watch -d ./`

That made it work!  I am not sure why but I can only guess that it has to do with me being in a sym linked directory.

**Comment by tanema** [comment]
Oh that is interesting, I will look into that.

**Comment by tanema** [comment]
@blindMoe I can fix this pretty easily but it would help to know why you are working through symlinks in the first place so I can take into account certain use cases.

**Comment by blindMoe** [comment]
@tanema I use symlinks because I also use grunt / bower to build my theme.  I basically have a symlink pointing to the dist directory of my app.   It is the same type of setup used in the Foundationify theme.

**Comment by tanema** [comment]
@blindMoe awesome thanks that sheds some light on it!
