### ISSUE TITLE
flag provided but not defined: -password

### ISSUE THREAD

**Issue by cameronroe** [Shopify/themekit#338]
I'm getting this issue when passing the password like this:

```sh
theme bootstrap --password=mypassword --store=test-store.myshopify.com
```

Error: 

```sh
flag provided but not defined: -password
```

**Comment by cameronroe** [comment]
Also, [your-api-password] is misleading... Is it the password or the API secret?

**Comment by tanema** [comment]
There are detailed documents about what password it is referring to. http://shopify.github.io/themekit/#get-api-access What version of themekit are you using? I cannot reproduce that error and it seems like it is from an old flag parsing library that we no longer use.

**Comment by cameronroe** [comment]
I didn't realize that the app needed to be a private app directly in the store vs an app for a partner account. May want to add a disclaimer for where the app should be created from.

**Comment by cameronroe** [comment]
Yep. This isn't working. I'm running OSX 10.9.5. The error is consistent, even with the correct password.

```
$ theme configure --password=asdflkjasdlfkjasdf --store=xxxxx.myshopify.com --themeid=asdflkjasdflkjads
```

**ERROR:**
```
flag provided but not defined: -store
```

**Comment by tanema** [comment]
Again, what version are you on because that error you are receiving seems like it is from an old version.

**Comment by cameronroe** [comment]
Theme Kit v0.4.7

**Comment by tanema** [comment]
Please reinstall or update your themekit. The most recent version of themekit is `v0.6.9`

**Comment by cameronroe** [comment]
Thanks. Looks like it's not updated on homebrew though:

```
$ brew info themekit
shopify/shopify/themekit: stable v0.6.7
Theme Kit is a tool kit for manipulating shopify themes
https://shopify.github.io/themekit/
Not installed
From: https://github.com/shopify/homebrew-shopify/blob/master/themekit.rb
```

**Comment by tanema** [comment]
Yeah the homebrew recipe is behind a few patches but if install 0.6.7 and run `theme update` it will get the most recent version. The `update` command was introduced in 0.5.x

**Comment by cameronroe** [comment]
I got it. Looks like I had `shopify_theme` installed from ruby gems. All set. It's working 👍
