### ISSUE TITLE
Include docs on readme

### ISSUE THREAD

**Issue by cameronroe** [Shopify/themekit#339]
Nice docs on the website. But would be great to have them on the readme as well.

**Comment by tanema** [comment]
I disagree, there is documentation that is linked in the readme and the command line outputs thorough instructions. Both are substantial. I don't need another set of reduntant docs to maintain when they are just a click away.

**Comment by cameronroe** [comment]
It's just a CLI tool. Why does the documentation honestly need to be so elaborate? But that's fine. Seems like it would be more of a hassle to maintain a doc website vs a readme.. just saying.
