### ISSUE TITLE
ignore config.json (or give more verbose error)

### ISSUE THREAD

**Issue by japherwocky** [Shopify/themekit#345]
After mucking around with custom bootstraps, I ended up with a stray `config.json` in the root of a shop's folder.  Trying to run theme commands gives this error:

    $ theme watch
    Error: json: cannot unmarshal array into Go value of type kit.Configuration

Ideally.. it would not try to load a JSON file, or at least go for the .yml first?  If nothing else though, could we get a less cryptic error message?

Even something silly like "config file: </full/path/to/file/> is invalid" would've saved me a good bit of puzzling!

**Comment by tanema** [comment]
Thanks, I never considered precedence when searching for a config file but I will make yml take precedence over json since it really isn't the recommended config pattern.

**Comment by japherwocky** [comment]
nice!

**Comment by tanema** [comment]
@japherwocky just a heads up the fix won't be deployed for a little while, thanks for reporting the bug!
