### ISSUE TITLE
macOS high CPU usage on `theme watch`

### ISSUE THREAD

**Issue by ckhatton** [Shopify/themekit#349]
There is a high CPU usage when the theme watch command is left active for large periods of time. It makes my macbook fans run on high. The current solution is to exit it, and start the theme watch command again.

I know it only happens when the theme watch is active for a large period of time, but I thought I would mention it in case there is a process loop that is multiplying itself.

(I originally posted the issue [here](https://github.com/Shopify/shopify_theme/issues/235) forgetting the app has moved to this repo)

**Comment by tanema** [comment]
Hey thanks for letting me know. About how long would you say it has to run? An Hour or longer? Is it just CPU usage or have you checked your memory usage as well?

**Comment by ckhatton** [comment]
Hey Tim!

It's after an hour or so - hence why it isn't normally noticeable.

> I have 'activity monitor' always running in my dock to watch out for high CPU usage, as it useful to spot when a program is spiralling out of control 😏 

As far as I remember, it is just CPU usage. I am sure I would have mentioned about a memory leak, if so.

If you have a mac handy...
- Open up Activity Monitor.
- Go `View > Dock Icon > Show CPU Usage' (Not a requirement, it just useful to visually see what the cores are doing).
- Walk away for an hour or so to carry on with daily chores, and then come back to the mac.

> It still happens if you walk away, do daily chores, or not - I have notice the issue even when actively working with themekit, over an hour or so.

:octocat:

**Comment by tanema** [comment]
Okay thanks I will look into it thanks!

**Comment by tanema** [comment]
Hey @ckhatton I cannot reproduce this. Do you have any other programs running at the same time? 

I need a few other bits of information:
- themekit version
- macOS version
- memory size
- are you running an IDE or editor at the same time
- are you running anything else like slack?

Cheers.

**Comment by ckhatton** [comment]
Okay sure.

- themekit version **0.6.4**
- macOS version **10.12.3**
- memory size **16GB**
- are you running an IDE or editor at the same time **yes, Atom**
- are you running anything else like slack? **yes, Slack**

I am running `theme watch` now to see if I can still reproduce the issue.

🐟

**Comment by ckhatton** [comment]
This is after an hour...

![Screenshot 01](https://www.evernote.com/shard/s384/sh/3bebf961-8a79-41a6-afe3-bda52e17fa32/878e7cf717f4d934/res/a5a17df2-8de1-43ac-b30e-bd1d7f3932d3/skitch.png?resizeSmall&width=832)

This is after 5 hours. The 'theme' process recorded with 11.2 MB of RAM allocated...

![Screenshot 02](https://www.evernote.com/shard/s384/sh/7ad8099e-81d4-4475-bc90-93f3679ee0fc/aa1988ba0705cfed/res/931c06d3-98fc-44aa-9449-8a530a74719d/skitch.png?resizeSmall&width=832)

To be fair, it hasn't been as bad as it has been in the past, but there is an issue still present. :suspect:

**Comment by tanema** [comment]
Thanks I will look into it and see what can be done about it. There shouldn't be much running when it has nothing to process but maybe I am missing some sort of edge case.

**Comment by tanema** [comment]
This is interesting, maybe you should try upgrading but I have been running watch all day and it stays hovering around 14%. You should try updating but also I will be releasing a new version soon with a new version of go that may help it.
 
![image](https://cloud.githubusercontent.com/assets/463193/23320240/e3be0852-faa7-11e6-9fc7-6ddb5034e139.png)

When profiling it, there is nothing that increases more than it should.

**Comment by tanema** [comment]
It seems like if it is anything it will be something in Go because out of all of the top processes being used, anything from themekit is not even in the top ten.

![screen shot 2017-02-24 at 4 20 36 pm](https://cloud.githubusercontent.com/assets/463193/23321413/705357ae-faad-11e6-9147-667368b106af.png)

**Comment by ckhatton** [comment]
How did you output those stats?

Here is another screenshot after updating themekit to the latest version (v0.6.9). The CPU time is similar to yours, though it's only run about an hour as the macbook went to sleep.

![Screenshot 03](https://www.evernote.com/shard/s384/sh/64291a4a-4dbd-45db-8313-49b13f4ed23a/1c674048ec0cf62d/res/3d86886a-2439-4232-974e-b7043327ba43/skitch.png?resizeSmall&width=832)

**Comment by tanema** [comment]
Those stats are done through Go's profiling libraries. [I added them permanently in this PR for easy profiling in the future.](https://github.com/Shopify/themekit/pull/352)

**Comment by raulk** [comment]
Also facing this issue on mac 10.10.4 with go1.7.4 darwin/amd64

**Comment by tanema** [comment]
@raulk are you compiling themekit yourself? What is themekit's peak usage?

**Comment by DanWebb** [comment]
+1. mac 10.12.3 themekit 0.6.9

Started at 0.6%

<img width="1054" alt="screen shot 2017-03-07 at 21 45 26" src="https://cloud.githubusercontent.com/assets/5038459/23700007/04de2bfe-0424-11e7-9eee-72d1a706e91f.png">

Left it on overnight, roughly 12 hours later of inactivity it's at 24.8%.

<img width="1051" alt="screen shot 2017-03-08 at 10 30 44" src="https://cloud.githubusercontent.com/assets/5038459/23700014/0dc97cbe-0424-11e7-9988-0896f4d6b79f.png">

Doesn't seem as bad as @ckhatton but the issue is still evidently present.

**Comment by raulk** [comment]
@tanema Nope. I'm not compiling themekit myself. So upgrading Golang in my system has no relevance.

The issue is pretty severe on my end. It actually prevented my Mac from going to sleep last evening. When I came to it this morning, the fans were at full speed and the CPU was at ~90%.

**Comment by tanema** [comment]
@raulk okay thanks for the update. That is really not good.

**Comment by ckhatton** [comment]
That's what I used to have, but I never noticed the sleep issue as the fans were already audible enough to make me investigate what was going on. I imagine something has updated on my system for it not be such a big issue now 🦑

**Comment by tanema** [comment]
Hey all, I managed to refactor out some things that were running in the watch event loop and got the cpu usage down to < 1%. I will keep testing it for the next little while and let you know how it goes.

**Comment by ckhatton** [comment]
Good work! I will monitor it next time I run `theme watch` 🦂

**Comment by tanema** [comment]
I just released `v0.6.10`, please update and try it out!
