### ISSUE TITLE
Internal Server Error uploading .scss.liquid or .js.liquid files

### ISSUE THREAD

**Issue by liamjmc** [Shopify/themekit#354]
When using either the upload or watch command on a .scss.liquid or .js.liquid file an internal server error message is given. A standard .liquid file seems to upload correctly using both commands.

I've tried rolling back to different versions (0.6.9. 0.6.7, 0.6.5) but had no joy. It was working correctly 24 hours ago and there have been seemingly no changes to the store and our local dev environment. 

We have tried this on both Windows 10 and macOS and seem to have the same issue.

**Comment by tanema** [comment]
There was an AWS outtage that caused our CDN to fail. This has been cleared up now.
