### ISSUE TITLE
Windows 10 path length limit strikes again

### ISSUE THREAD

**Issue by CalebBabin** [Shopify/themekit#355]
So I have a project that uses the node package gulp and some other dependencies, I can run "theme upload" and "theme watch" just fine before running npm install, but when I do it crashes because I assume it's trying to access a file beyond the limit of windows path length limit.

When I try to run "theme watch" with gulp installed in the directory I get this 
[36m14:52:12[0m GetFileAttributesEx D:\GitHub\my-shopify-theme\node_modules\gulp\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\normalize-package-data\node_modules\validate-npm-package-license\node_modules\spdx-correct\node_modules\spdx-license-ids\spdx-license-ids.json: The system cannot find the path specified.

In my config.yml file I have
ignores:
    - config/themekit_ignores

and in config/themekit_ignores I have
.git
node_modules
node_modules/
node_modules/**/*
sass_cache
LICENSE
assets/scss
assets/scss/*
*.scss
package.json
gulpfile.js
README.md

and when I have the node modules installed "theme upload" it gives me 
`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x474936]

goroutine 42 [running]:
panic(0x791780, 0xc04200a090)
        /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1af
github.com/Shopify/themekit/kit.findAllFiles.func1(0xc0423d3320, 0x105, 0x0, 0x0, 0x9917a0, 0xc0423b4de0, 0x0, 0x0)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/kit/asset.go:116 +0x36
path/filepath.walk(0xc0423a0a50, 0xef, 0x997320, 0xc0424081e0, 0xc04229f300, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:372 +0x235
path/filepath.walk(0xc0424016c0, 0xde, 0x997320, 0xc0424080c0, 0xc04229f300, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc042400540, 0xd1, 0x997320, 0xc0423edce0, 0xc04229f300, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0423c7e10, 0xc4, 0x997320, 0xc0423edb00, 0xc04229f300, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0423f8d80, 0xb7, 0x997320, 0xc0423ed740, 0xc04229f300, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0423e5a40, 0x9a, 0x997320, 0xc0423ec480, 0xc04229f300, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0423d53b0, 0x8d, 0x997320, 0xc0423d77a0, 0xc04229f300, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc04239f280, 0x76, 0x997320, 0xc0423c4b40, 0xc04229f300, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0423bcb60, 0x69, 0x997320, 0xc0423c47e0, 0xc04229f300, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0423bc5b0, 0x64, 0x997320, 0xc0423c4360, 0xc04229f300, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0423b71a0, 0x57, 0x997320, 0xc0423b7200, 0xc04229f300, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0423b0640, 0x4c, 0x997320, 0xc0423ae300, 0xc04229f300, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc04237cec0, 0x3f, 0x997320, 0xc0423a34a0, 0xc04229f300, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc04237c1c0, 0x35, 0x997320, 0xc0423770e0, 0xc04229f300, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc04236af90, 0x28, 0x997320, 0xc042371e60, 0xc04229f300, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc04236ab70, 0x23, 0x997320, 0xc042371860, 0xc04229f300, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.walk(0xc0422b22c0, 0x16, 0x997320, 0xc04213b260, 0xc04229f300, 0x0, 0x997301)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:376 +0x34b
path/filepath.Walk(0xc0422b22c0, 0x16, 0xc04229f300, 0xc04213b200, 0x0)
        /usr/local/Cellar/go/1.7.1/libexec/src/path/filepath/path.go:398 +0xdc
github.com/Shopify/themekit/kit.findAllFiles(0xc0422b22c0, 0x16, 0x2, 0xc0422b22c0, 0x16, 0x0, 0x0)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/kit/asset.go:122 +0x16c
github.com/Shopify/themekit/kit.loadAssetsFromDirectory(0xc0420c34e0, 0x16, 0x0, 0x0, 0xc0422bbc90, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/kit/asset.go:129 +0x103
github.com/Shopify/themekit/kit.ThemeClient.LocalAssets(0xc04227e500, 0xc04229f220, 0xc0422b21e0, 0x17, 0x9b42e0, 0xc, 0xc, 0xc04228c300, 0xc, 0x10, ...)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/kit/theme_client.go:74 +0x63b
github.com/Shopify/themekit/cmd.upload(0xc04227e500, 0xc04229f220, 0xc0422b21e0, 0x17, 0x9b42e0, 0xc, 0xc, 0xc04228c300, 0xc, 0x10, ...)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/cmd/upload.go:34 +0xc7
created by github.com/Shopify/themekit/cmd.forEachClient.func1
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/cmd/theme.go:174 +0x1ff`

**Comment by tanema** [comment]
What themekit version are you using. The current themekit version doesn't upload or watch anything that isn't in one of the allowed folders `templates/customers, assets, config, layout, snippets, templates, locales, sections` and it has been this way for a while.

**Comment by tanema** [comment]
Also you can ignore all node_modules with `node_modules/*`

**Comment by tanema** [comment]
Closing this because lack of feedback and it seems likely that this is a problem that is fixed in newer versions of themekit. Please reopen if you have updated to the current version and still have the problem.
