### ISSUE TITLE
Downloaded and ran installer for windows-64...got v0.4.2...update command runs but doesn't update

### ISSUE THREAD

**Issue by gurustump** [Shopify/themekit#359]
I'm a front-end developer working with Shopify for the first time. Attemped to install Shopify Theme Kit on a PC (Windows 10 64-bit) using the installer I downloaded from http://shopify.github.io/themekit/ from the link labeled "windows-64." The link goes to https://github.com/Shopify/themekit/releases/download/v0.6.9/themekit-setup-64.exe and the download worked as expected. I launched the installer on my system and that worked as expected.

After setting up an API key from the somewhat outdated instructions on http://shopify.github.io/themekit/ (the API/private app page looks slightly different than your screenshots), I then tried to run the bootstrap command, using the password I had just generated and the name of the store I've been hired to work on. I got the following output in my terminal:

flag provided but not defined: -password

I did some googling, and found this issue already here on github: https://github.com/Shopify/themekit/issues/338 . I checked my version of themekit from the command line and got this:

Theme Kit v0.4.2

Apparently, even though I only downloaded the installer an hour ago, and even though the file is labeled v0.6.9, it is in fact an older version. I attempted to use the update command in my terminal to get the latest, and got this output: 

D:\Development\sandbox\fidgetly>theme update
Updating from v0.4.2 to v0.6.9

D:\Development\sandbox\fidgetly>theme version
Theme Kit v0.4.2

Looking back at issue 338, I see that in one comment in the stack, tanema said that the update command was introduced in version 0.5x.

It looks like I need to update to the latest version, but the update command doesn't work for the version I have, and I cannot get the latest version because it is not available on the site. If that conclusion is correct, please overwrite the current windows-64 installer with the actual v0.6.9, and then respond to me so I know I can go get it. If my conclusion is wrong, please let me know what I need to do to get updated to v.0.6.9. Thanks much!

**Comment by tanema** [comment]
Hey @gurustump is this the first time you have used themekit? There is no way that the windows installer could install that version since I just built the windows installer for v0.6.5. Do you have the themes gem installed?

**Comment by gurustump** [comment]
I must not, since I don't even know what that is.

**Comment by tanema** [comment]
Please post the output of the `where theme`

**Comment by gurustump** [comment]
D:\Development\sandbox\fidgetly>where theme
c:\program files\theme kit\theme.exe
C:\Program Files (x86)\themekit\theme.exe

**Comment by gurustump** [comment]
Well that's interesting...is it possible I actually have an older version of themekit running on this computer?
The fact that it's in both program files and program files (x86) makes my head spin.

**Comment by tanema** [comment]
You can delete the one in Program Files that would have been installed by an old program. The new installer will put the executable in the correct position.

**Comment by gurustump** [comment]
Okay, will do

**Comment by tanema** [comment]
To clarify, the exe in the `Program Files (x86)` is the correct exe

**Comment by gurustump** [comment]
Yes...I suspect I may have to update my path

**Comment by tanema** [comment]
You might have to take the old path out. The new installer would have added the new path to your env already.

**Comment by gurustump** [comment]
Right. Checking that now

**Comment by gurustump** [comment]
old path entry deleted

where theme now only outputs the x86 directory

**Comment by tanema** [comment]
Excellent now what is the output of `theme version`

**Comment by gurustump** [comment]
theme version is reported as 0.6.9
Hey, thanks for your help, I think that it was an error on my fault, and you sniffed it out for me :)

**Comment by tanema** [comment]
No problem, happy to help!
