### ISSUE TITLE
error connecting to proxy http://http_proxy:

### ISSUE THREAD

**Issue by burakkaptan** [Shopify/themekit#360]
Hello, 

When I type this command: 
`theme bootstrap --password=[your-password] --store=[your-store.myshopify.com]` with my own password and url, I'm getting error. I also made Theme templates and theme assets "Read and Write" in my admin page. Here is the screenshot: 
http://i.hizliresim.com/ZZVQy0.png

I'm really struggling with this issue. Looked at similar issues on the internet but no luck. I couldn't find the solution. Thanks for your help in advance.

**Comment by tanema** [comment]
Hey @burakkaptan do you have an HTTP_PROXY or http_proxy environment variable?  It seems like you do and it is conflicting with a standard library of Go. When Go does a Get  request it looks for that environment variable in case the request needs proxying.

**Comment by burakkaptan** [comment]
Hi @tanema , thanks for the reply. I don't think, I understand the explanation here. I have a few questions. How can I make sure that I have Go, how to find those proxy variable? Should I delete them? 
I appreciate your help. Best

**Comment by burakkaptan** [comment]
@tanema I use wampserver. Is that what you're asking for ? Can I create another variable for Go?

**Comment by tanema** [comment]
You do not need Go and to find out those variables please run the following commands: `echo %HTTP_PROXY%` and `echo %http_proxy%` Please let me know the output of them. It may be that wamp is setting one of those variables.

**Comment by burakkaptan** [comment]
I typed those commands on command line, however nothing showed up. Only thing what I got: "http_proxy"
My OS is Windows 8

**Comment by tanema** [comment]
Well it does seem like one of those variables contains the text "http_proxy" So you should run `set http_proxy=` and `set HTTP_PROXY=` that should clear those variables and get you running on themekit.

**Comment by tanema** [comment]
However that will only clear those variables for the session while the command is open. To fully clear them you will have to go into your system settings and find the HTTP_PROXY/http_proxy variable and delete it.

**Comment by burakkaptan** [comment]
Thank you, it works now

**Comment by tanema** [comment]
Awesome! Cheers.
