### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by red2678** [Shopify/themekit#367]
It would be nice if there was a place on the website where we could see changes between versions.

**Comment by tanema** [comment]
All changes are tracked in the releases https://github.com/Shopify/themekit/releases would you still like a file containing all of that information?

**Comment by red2678** [comment]
Well, I did state, "... on the website..." but that will do to. Thanks.

**Comment by red2678** [comment]
@tanema Awesome. Will this changelog be displayed on the site or just on GitHub in a file?

**Comment by tanema** [comment]
I have decided to keep the change information in the releases section. Generating a changelog from already existing and public resources seems like needlessly duplicating information and adding extra maintenance load to a repo I already have little time to work on.
