### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bradytford** [Shopify/themekit#370]
I'm getting the following error, all of the sudden. Using Windows 10 and cmd, worked a few days ago on this shop. Let me know if you need any more info.

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x8 pc=0x769f37]

goroutine 1 [running]:
github.com/Shopify/themekit/kit.Environments.GetConfiguration(0xc0422b0e40, 0x85fc30, 0xb, 0x0, 0x0, 0xa52320)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/kit/environments.go:71 +0x77
github.com/Shopify/themekit/cmd.generateThemeClients(0xc0420a5bf8, 0x0, 0x0, 0xc0420a5c20, 0x6a838d)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/cmd/theme.go:143 +0x4f7
github.com/Shopify/themekit/cmd.glob..func3(0xa53000, 0xa74158, 0x0, 0x0, 0x0, 0x0)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/cmd/download.go:25 +0x53
github.com/Shopify/themekit/vendor/github.com/spf13/cobra.(*Command).execute(0xa53000, 0xa74158, 0x0, 0x0, 0xa53000, 0xa74158)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/vendor/github.com/spf13/cobra/command.go:599 +0x3f0
github.com/Shopify/themekit/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa53880, 0x0, 0x0, 0x869800)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/vendor/github.com/spf13/cobra/command.go:689 +0x340
github.com/Shopify/themekit/vendor/github.com/spf13/cobra.(*Command).Execute(0xa53880, 0x13, 0x0)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/vendor/github.com/spf13/cobra/command.go:648 +0x32
main.main()
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/cmd/theme/main.go:27 +0x72

**Comment by tanema** [comment]
What command are you running? Did you just update? Did you change your config at all?

**Comment by bradytford** [comment]
I'm running theme download, but it also happens for theme watch. I haven't changed anything recently, though there was a windows update for x64 systems last week.

**Comment by tanema** [comment]
I meant did you update themekit recently? It sounds like there is something wrong with your config file. Please make sure that your config file is in UTF8 encoding and that you are using spaces instead of tabs. Please confirm if any of these things has an effect because we had in house dev experience this but didn't narrow down the issue. I would at least like to create a nice error message.

**Comment by tanema** [comment]
I just did some testing and if your config looks like this 

```
development:
  password: password
  theme_id: "123"
  store: can-i-buy-a-feeling.myshopify.com
prod:
  password: password
  theme_id: "123"
  store: can-i-buy-a-feeling.myshopify.com
test:
```

And then try and run the test environment, you would get the same error. Does any of your config look like this? I can make a better error for this in the future.

**Comment by bradytford** [comment]
No tabs and utf8 confirmed.

**Comment by bradytford** [comment]
My config just has the dev settings.

**Comment by tanema** [comment]
Can you please send me your config to tim.anema@shopify.com?

**Comment by bradytford** [comment]
Done

**Comment by tanema** [comment]
Have you always had your config like this and it worked? Because your development config should be indented (with spaces) beneath the development label like my example above. That will fix your issue.

**Comment by bradytford** [comment]
Okay thanks. I guess it's possible that my IDE changed my indent settings.

**Comment by tanema** [comment]
Okay I will add an appropriate error message indicating that the issue could be a problem with indentation. Thanks!

**Comment by bradytford** [comment]
Confirmed that PhpStorm auto changed the indent somehow.
