### ISSUE TITLE
Documentation of commands

### ISSUE THREAD

**Issue by cresharper** [Shopify/themekit#373]
Hi,

Working on migrating to this since the shopify_theme gem isn't supported anymore. Upon following the documentation when I ran the configure command with credentials I got this error:

`split': bad URI(is not URI?): https://--themeid=[180785167]/admin/assets.json (URI::InvalidURIError)`

I ran the command in the format specified, so:

`theme configure --password=[my-password] --store=[my-store.myshopify.com] --themeid=[your-theme-id]`

However, when I ran it in this format it worked fine:

`theme configure api_key password connors-development-store.myshopify.com theme_id`

I'm not sure if I did something wrong on my end or the docs need to be updated but I wanted to bring it to light.

**Comment by tanema** [comment]
Have you deleted the theme gem? because that second format is not correct for themekit. Please paste here the output of `which $(theme)`

The documents are always up to date and updated when the commands change at all. Please check them out here http://shopify.github.io/themekit/commands/

**Comment by cresharper** [comment]
Thanks for responding @tanema - no, I did not delete the gem. I installed themekit via brew. 

my stack trace for that command is as follows:

```
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/usr/bin/file
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/usr/bin/file
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/usr/bin/FILE
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/usr/bin/command
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/usr/bin/open
/usr/bin/open
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/usr/bin/FILE
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/usr/bin/FILE
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/usr/bin/FILE
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/Users/chmd/.rvm/gems/ruby-2.0.0-p648/bin/theme
/usr/bin/as
/usr/bin/file
```

If it's helpful, the error that is returned when I run the command in the proper format is:

`/Users/chmd/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/uri/common.rb:176:in `split': bad URI(is not URI?): https://--themeid=[180785167]/admin/assets.json (URI::InvalidURIError)`

**Comment by tanema** [comment]
Yup you are still using the theme gem please run `rm $(which theme)`

**Comment by cresharper** [comment]
ok great thanks a lot @tanema !
