### ISSUE TITLE
Upload & override ignored files

### ISSUE THREAD

**Issue by sqbiz** [Shopify/themekit#374]
Is it possible to force upload a file, overriding anything that has been ignored in the config? In my case, I ignore `settings_data.json` to avoid accidentally overwriting any changes that my client has made in their admin. But, I occasionally download it, upload it to a preview/development theme, make adjustments, then do another download/upload to sync these settings back to the live theme.

It's not really a problem to just comment out the ignored file, but it's an easy thing to forget to change back.

**Comment by tanema** [comment]
Yeah I can add an `--no-ignore` flag to force skip file filtering. That shouldn't be too hard.

**Comment by sqbiz** [comment]
🙌
