### ISSUE TITLE
theme watch not watching new file

### ISSUE THREAD

**Issue by pfreema1** [Shopify/themekit#375]
Hello!

I've added a "sections" folder to an unsectioned theme I'm working on.  Inside I have a .liquid file, but when I make changes to the .liquid file, theme watch doesn't seem to be watching this new file.  When I open up the project within the Shopify dashboard->edit html/css, the new folder (sections) is there, but not the new .liquid file.  

Locally, the file is there and being updated when I save the project in Sublime Text, but the changes don't seem to be going through Theme Kit.  There is no "Received Update event on ****" in the Terminal, but all of the other files update fine.  Any ideas?

**Comment by tanema** [comment]
What version of theme kit are you using. When did you install it? Are you using the theme Gem? Did you restart your command?

**Comment by pfreema1** [comment]
Restarting the terminal fixed it.  Thank you!
