### ISSUE TITLE
ThemeKit installer obliterates system path on Windows

### ISSUE THREAD

**Issue by ddsol** [Shopify/themekit#376]
The ThemeKit installer removes the entire system path when it installs its own path as the system path for the entire system, thereby removing the original system path which could have been anything.

Now software all over the system is failing for all users.

**Comment by tanema** [comment]
Thanks for the heads up I will take down the windows installer immediately and will fix it in the near future.

**Comment by tanema** [comment]
What version of MS?

**Comment by ddsol** [comment]
Windows 8.1

**Comment by tanema** [comment]
64/32 arch?

**Comment by ddsol** [comment]
64 bitses

**Comment by tanema** [comment]
Okay I have taken the link out of the docs. My apologies for the inconveniences that this has caused. I will be in touch here when it is fixed.

**Comment by tanema** [comment]
Unfortunately this seems to be a limitation of NSIS the program we use to generate our installers. You your PATH was already long to begin with, editing the PATH var would truncate it. Windows users will have to use manual installs until another solution can be found.

**Comment by ddsol** [comment]
You could just delete / comment out / conditionally not exectute the part that installs the path and possibly add some info on how to manually add it.

**Comment by tanema** [comment]
The path variable is the most complex part of the installation and exactly the part of the install that the installer was created for. The rest is just moving the (already downloaded with the executable) binary. It feels like users might as well already just follow the instructions. 

I notice that you are referring to multiple users. Are you installing themekit using an automated system?

**Comment by ddsol** [comment]
No, just installing it. I just noticed the path wasn't the system path at all but the user's path. Oops! I fixed the comment.
