### ISSUE TITLE
'Reloading because of config changes' sorta messes up my workflow

### ISSUE THREAD

**Issue by flannelJesus** [Shopify/themekit#377]
I'm not sure if this is an 'issue' or just something I need advice on how to fix my work flow. In any case, I'll describe what's going wrong for me.

On the previous version of Theme Kit, I would have a git branch for my development theme and a git branch for my live theme. They'd both start out at the same commit before any dev work - let's just say commit A - and then I'd add commit B, C and D onto the development branch, which would all be watched and uploaded live to my development theme. When I'm ready to apply the new commits to the live theme, I'd stop watching, checkout my Live branch (still on commit A), change my config.yml to point to my Live theme, do a 'theme watch' again, and then fast-foward my Live branch to my Dev branch, which would then of course add commit B, C, and D to my local files, and theme-watch would update the relevant files on my live theme as well.

But after updating Themekit, I can no longer just fast-forward a branch and have it work. In fact I've even tried cherry-picking commits instead of fast-forwarding, and that doesn't work either. I keep getting this message in my console: Reloading because of config changes

I'm on Windows 10 using GitKraken. I'm guessing that the git system, in its process for fast-forwarding a branch, is changing the config.yml back to the 'dev' theme, and then changing it back again to the 'live' theme.

So how can I set it up to apply commits to the theme I specify, without it messing with the config.yml file?

As I'm coming to the end of this post, I half-expect you to just say 'Don't watch config.yml in git'. If that's your answer, and that's the correct thing to do, then I won't. (I have it as a private repo, so privacy isn't my worry).

**Comment by tanema** [comment]
What you want to do is make another `production` environment in your config with all of your live site config. Then when you have switched to your master branch and merged in your changes you would run `theme replace --env=production` This would deploy your theme in one go and it a much safer operation in terms of file states. This makes sure that your whole theme is exactly as you expect it to be.

**Comment by flannelJesus** [comment]
just to be clear, you're suggesting that my config.yml file look like this?

    development:
      password: xxxx
      theme_id: "1"
      # dev theme id = 1
      store: rydale.myshopify.com
    
    production:
      password: xxxx
      theme_id: "2"
      # live theme id = 2
      store: rydale.myshopify.com


And then   `theme replace --env=production` would make sure my current local files update to my production theme?

**Comment by tanema** [comment]
Correct!

**Comment by flannelJesus** [comment]
Well that seems easy enough! TY. Is that obvious enough in the docs for future users? Because that path of applying development changes onto another theme is ideal.

For the record, before I started what I currently do to update my live theme, I worked on my dev theme, then *duplicated the entire theme* in shopify, and then made that new theme live, which takes absolutely ages. I think users of this package would benefit from advise on the best workflow for how to deal with development themes and live themes.

**Comment by flannelJesus** [comment]
@tanema I have a question: when you use 'theme replace', it seems to work quite slowly. This isn't a big problem necessarily, but what I'm worried about is that there is a big time between when one file is changed and another file is changed in the process of updating a theme.

EG as the 'theme replace' is looking for changed files, it finds one very early in the process and changes it, and then it finds another one very late in the process and changes it, but in the 5 minutes between seeing those changes, the site might be broken.

Does it update the theme as it finds the changes, or does it keep a list of the changes it finds and then applies all the changes at the end?

**Comment by tanema** [comment]
Theme replace, just uploads every file in your theme and removes any file in the remote theme that is not your theme. This would be the same process you would get when you upload all of your files using your other method of deploy.

**Comment by flannelJesus** [comment]
Yes I know that it uploads them, my question is about the process of uploading them. When I do 'theme replace', it takes about 5 minutes to run as it's looking for changes to the files. So during that 5 minutes, if it finds a change to one file at the beginning, and a change to a different file at the end, do the two files get uploaded nearly 5 minutes apart? Or does it wait until the end of the 'looking for changes' process to upload the changed files?
