### ISSUE TITLE
Only throttle multiple env uploads if they reference the same store

### ISSUE THREAD

**Issue by t-kelly** [Shopify/themekit#386]
Noticed this while uploaded the same theme to three different stores when using the `--allenvs` flag. We should be able to upload them them at the same time without needing needing to throttle, no?

**Comment by tanema** [comment]
I will look into doing this and I will have to make sure with the API team that the limit is per domain and not on client.

**Comment by t-kelly** [comment]
Should be domain - [this code that uploads updated themes to multiple domains](https://github.com/Shopify/shopify-themes/blob/master/tasks/upload.js#L10) works just fine.

**Comment by tanema** [comment]
Yes I confirmed with the API team and there is an open PR to fix this.

**Comment by t-kelly** [comment]
![image](https://media.giphy.com/media/yXVO50FJIJMSQ/giphy.gif)
