### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by vpinto551** [Shopify/themekit#387]
Hi,

I installed 64-bit windows version of theme kit and am having the following error running the theme bootstrap 

$ theme bootstrap -p shopify -s test-theme-kit.myshopify.com
Error: Cannot create a theme. Last error was: Theme request encountered status at host test-theme-kit.myshopify.com
        Status: 401 Unauthorized
        Errors: [API] Invalid API key or access token (unrecognized login or wrong password)

I have checked the password and it is correct. I have tried theme kit versions 0.6.9, 0.6.10 & 0.6.11 and have the same error.

Any idea what I am doing wrong?

Best Regards/Vivian

**Comment by tanema** [comment]
Hey Vivian, this is not an installation issue. Have you followed the api access setup on the docs site? https://shopify.github.io/themekit/#get-api-access

**Comment by XiaoZhaoxiaaa** [comment]
how can I install  the theme  in git

**Comment by tanema** [comment]
@XiaoZhaoxiaaa I am not sure I understand
