### ISSUE TITLE
`theme watch` doesn't delete a file in store admin

### ISSUE THREAD

**Issue by alvin-ahn** [Shopify/themekit#392]
Hi Team!

If I delete a file from local while `theme watch` is on, it will empty the file in a store admin but the file itself is not getting deleted. 

Thank you!

**Comment by tanema** [comment]
Hey @alvin-ahn can you please tell me a few bits more of information?

- OS
- Shell
- Themekit version
- Text editor
- How did you delete the file (through your editor/command line/file exporer)

cheers,

**Comment by tanema** [comment]
I cannot reproduce this using command line remove using Finder, command line and/or vim. Can you please give me any extra information?

**Comment by alvin-ahn** [comment]
@tanema 

Hi Tim!

Sorry it was my first time creating a GH issue for this repo so didn't know the format.

OS: macOS Sierra Version 10.12.4
Shell: zsh
Themekit version: 0.6.11
Text Editor: Both Atom and Sublime
I deleted the file through my editor.

Deleting a file using Sublime Text: https://screenshot.click/16-33-iv47m-r2ozo.mp4

The file still exist but empty https://screenshot.click/16-34-0n44t-idlrg.mp4

**Comment by tanema** [comment]
Ah okay I get it now. It turns out that Atom/Sublime Rename the folder to go in the trash rather than deleting them. I will have to figure out a cross platform way to catch when this happens

**Comment by tanema** [comment]
This has actually surfaced the problem that renaming doesn't work either.
