### ISSUE TITLE
No source files for linux amd64 on v6.12 release

### ISSUE THREAD

**Issue by jonathan-bird** [Shopify/themekit#398]
@tanema you forgot to release the other source files in the latest v6.12 release, now my install script fails on circle ci :(

What needs to be added: 
2.43 MBdarwin-amd64.zip
2.13 MBlinux-386.zip
2.3 MBlinux-amd64.zip
2.13 MBwindows-386.zip
2.31 MBwindows-amd64.zip

**Comment by jonathan-bird** [comment]
Because I get the error:
```
Downloading themekit from github.com//Shopify/themekit/releases/download/v0.6.12/linux-amd64.zip
Installing themekit to /home/ubuntu/.themekit
Traceback (most recent call last):
  File "<stdin>", line 137, in <module>
  File "<stdin>", line 78, in install
  File "<stdin>", line 99, in __unzip
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

```

**Comment by tanema** [comment]
👋  Hey @jonathan-bird this time it wasn't an accident. I have been trying to move the deploy to single source on the CDN. It looks like you are using an old version of the install script so you might want to update with the current one that uses the CDN. If you are not using that script please point your ulrs to: ```
https://shopify-themekit.s3.amazonaws.com/{{ themekitversion }}/darwin-amd64/theme
https://shopify-themekit.s3.amazonaws.com/{{ themekitversion }}/windows-amd64/theme.exe
https://shopify-themekit.s3.amazonaws.com/{{ themekitversion }}/windows-386/theme.exe
https://shopify-themekit.s3.amazonaws.com/{{ themekitversion }}/linux-amd64/theme
https://shopify-themekit.s3.amazonaws.com/{{ themekitversion }}/linux-386/theme
```

**Comment by jonathan-bird** [comment]
Ohhhhh I see :) yes I'm using v6.1 which tried to find it. Can I use v6.12
then? Just worried about anything acting differently or breaking. Haven't
looked at the script in a while.

Should I expect anything?

Thanks!

**Comment by tanema** [comment]
What do you mean you are using 6.1? It seems like you are using the themekit install script which has always grabbed the latests themekit even when it was getting it from github. I am referring to this script https://github.com/Shopify/themekit/blob/master/scripts/install

**Comment by jonathan-bird** [comment]
Nope had been using 6.1 and tried other versions but all were trying to get
6.12.

Its midnight here so I'll try to find the logs tomorrow. But what should I
be using? 6.12 and it'll work?

**Comment by tanema** [comment]
Again, what do you mean you are using 6.1?

Also yes, there are no significant changes between 6.1 and 6.12, it also seems like you have been testing again the most recent versions anyways with out realizing it.

**Comment by jonathan-bird** [comment]
As in I curl 6.1 not master in the url.

**Comment by tanema** [comment]
Okay so that doesn't change the fact that the install script that you are curling looks for the most recent release, which is why it is looking for 6.12. You should be curling from master because no matter what, the install script will always look for the most recent release.

**Comment by jonathan-bird** [comment]
Yeah thats what I thought was happening. Will give it a go in the morning.

Thanks mate

On 26 May 2017 12:31 am, "Tim Anema" <notifications@github.com> wrote:

Okay so that doesn't change the fact that the install script that you are
curling looks for the most recent release, which is why it is looking for
6.12. You should be curling from master because no matter what, the install
script will always look for the most recent release.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Shopify/themekit/issues/398#issuecomment-304024836>,
or mute
the thread

**Comment by tanema** [comment]
👍  Cheers, I am closing this issue since nothing is broken but if you need further support you can ask questions here.

**Comment by jonathan-bird** [comment]
The issue that I keep getting is as follows (permission error on /usr/local/bin/theme). Never used to happen on old versions

```
curl https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100  1535  100  1535    0     0  24567      0 --:--:-- --:--:-- --:--:-- 45147
Fetching release data
Downloading version v0.6.12 of Shopify Themekit
Traceback (most recent call last):
  File "<stdin>", line 44, in <module>
  File "<stdin>", line 19, in install
  File "<stdin>", line 40, in __download
IOError: [Errno 13] Permission denied: '/usr/local/bin/theme'

curl https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | python returned exit code 1

Action failed: curl https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | python
```

**Comment by jonathan-bird** [comment]
It works if I set the ownership beforehand. But never used to have to do that.

```
sudo chown -R $(whoami) /usr/local/bin && sudo chmod -R 755 /usr/local/bin
```

**Comment by tanema** [comment]
Please refer to the documentation website on the appropriate curl command (I am out of office). This is because theme kit is now installed in /usr/local/bin. A more appropriate location for command line tools.

**Comment by tanema** [comment]
Hey @jonathan-bird just checking in. Let me know when you have everything working. 👍

**Comment by jonathan-bird** [comment]
Seems to be working now :)
