### ISSUE TITLE
I receive a socket error -- is this the place to mention it?

### ISSUE THREAD

**Issue by tylerehc** [Shopify/themekit#399]
<img width="1429" alt="screen shot 2017-05-28 at 12 50 07 pm" src="https://cloud.githubusercontent.com/assets/5703326/26528142/3be7267c-43a4-11e7-8ac0-dd5bd3d43f8c.png">

**Comment by tylerehc** [comment]
could it be because i'm connecting to a dev store?

**Comment by tanema** [comment]
You are using the `shopify_theme` ruby gem that is deprecated. Please remove it using `gem uninstall shopify_theme` or simple `rm $(which theme)` then follow the install instructions on the themekit website: https://shopify.github.io/themekit/
