### ISSUE TITLE
theme watch only works if file(s) changed during watch

### ISSUE THREAD

**Issue by expomas** [Shopify/themekit#400]
When I run 'theme watch' on my local machine, and I have already changed local files, nothing happens, just infinite 'Watching for file changes...'.  However, if I change a local file WHILE 'theme watch' is running, is does update the Shopify server version.  I'm using Mac OS, with the defaults created via command line as per the documentation.

**Comment by tanema** [comment]
Yes because nothing is `watching` those changes.

**Comment by expomas** [comment]
OK, so, before I change anything locally, I need to run 'theme watch', and any changes I make locally if 'theme watch' is not running will never be updated on the server?  The documentation makes it sound like the 'theme watch' command checks for any differences between local and server, but maybe that's my misinterpretation.
