### ISSUE TITLE
Installation issue, macOS

### ISSUE THREAD

**Issue by gtstllv** [Shopify/themekit#401]
Attempted automatic installation, but can't get Theme Kit to work or install properly, receiving multiple errors. Please advise!

```
Fetching release data
Downloading version v0.6.12 of Shopify Themekit
Traceback (most recent call last):
  File "<stdin>", line 44, in <module>
  File "<stdin>", line 19, in install
  File "<stdin>", line 40, in __download
IOError: [Errno 2] No such file or directory: '/usr/local/bin/theme'
```

**Comment by tanema** [comment]
Please paste the full command that you are running to install themekit.

**Comment by gtstllv** [comment]
`curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python`

**Comment by tanema** [comment]
Okay it seems like your default python installation is python3 (which is not normal on OSX) and the script is written for python2. You can either use [2to3](https://docs.python.org/2/library/2to3.html) to translate the script or use python2 `curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python2`

**Comment by gtstllv** [comment]
Can you (briefly) explain why python3 would not be normal/regular? We are running a fresh macOS installation, currently 10.12.5 and did not install any version of python manually.

**Comment by tanema** [comment]
That is interesting. Up until recently (this issue) python2 was the default python on OSX which is why this script was written for python2. I will have to do some research to see if that has changed.

**Comment by gtstllv** [comment]
Actually just checked with `python --version`. It's 2.7.10…

**Comment by tanema** [comment]
Okay then for some reason when you run that command you are using python 3 some reason because I get the exact same error if I try to use the script with python3 and no error with python 2.7.13

**Comment by tanema** [comment]
If you run the previous command I pasted I am sure it will work `curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python2`

**Comment by gtstllv** [comment]
Hm, results in:

`sudo: python2: command not found`
`(23) Failed writing body`

**Comment by tanema** [comment]
Okay let's step back for a second. Can you make sure that `/usr/local/bin` exists?

**Comment by gtstllv** [comment]
Created it manually & everything works fine. Thx.

**Comment by tanema** [comment]
created what? Did that directory not exist?

**Comment by gtstllv** [comment]
`/usr/local` did exist, but `/usr/local/bin` did not. It that unusual? `bin` It exists one level up > `/usr/bin`, but that's a different folder though, correct?

**Comment by tanema** [comment]
`/usr/local/bin` doesn't exist on a new install of OSX but usually exists because of other software install. I will add some handling for this to the install script. Just checking though, once you created that directory and the install ran fine, was the `theme` command available/usable?

**Comment by gtstllv** [comment]
Yes, `theme` seems to work perfectly fine!

**Comment by tanema** [comment]
okay excellent, I will add a fix in the install script for this case. Thanks for your patience while figuring this out!
