### ISSUE TITLE
Snippet input setting type: Can't give it a label or id

### ISSUE THREAD

**Issue by ButsAndCats** [Shopify/themekit#403]
I am trying to add a "snippet" to my section `{% schema %}` like this:
```
{
   "type": "snippet",
   "label": "Snippet",
   "id": "snippet"
}
```
This is as per the [documentation.](url)
However I get the following log in the theme kit:
```
11:05:26 [development]Asset Perform Update to sections/foo.liquid at host foobar.myshopify.com
	Status: 422 Unprocessable Entity
	Errors: Invalid block 'snippet': setting with id="snippet" 'id' is not a valid attribute
		Invalid block 'snippet': setting with id="snippet" 'label' is not a valid attribute
```
It upload correctly if I ommit the label and id, but is useless because I cannot reference the snippet in my code.

**Comment by ButsAndCats** [comment]
With further testing can confirm that:

- This also doesn't work in the browser based code editor
- This does work in the settings_schema.json, but not inside a sections `{% schema %}` tag

**Comment by tanema** [comment]
Hey @ButsAndCats This is definitely not a themekit bug but it does seem like you have found a theme bug. I would recommend that you contact shopify support https://help.shopify.com/questions/new and they will be in touch.
