### ISSUE TITLE
Cannot open "live" theme preview

### ISSUE THREAD

**Issue by NikitaAvvakumov** [Shopify/themekit#405]
TK version 0.6.12

Setting `theme_id` to `live`, with or without quotes, in config.yml or with a CLI flag, generates preview URL as `https://shop_url/?preview_theme_id=live`, which then produces the "Theme cannot be previewed because it's missing one of these required files:..." error message in the browser. Replacing "live" with live theme's numerical ID works as a fix, although the theme is opened with a "You are currently previewing..." footer (which didn't use to happen for live themes? 🤔 ).

Should the generated preview URL omit the `preview_theme_id` param if `theme_id` is set to `live`?

**Comment by tanema** [comment]
Hey @NikitaAvvakumov it seems you are right. I have found that I can leave the `preview_theme_id` blank like this `https://shop_url/?preview_theme_id=` and it would work. I want to still have that parameter in case the live shop is password protected still. I will make a fix for this in the near future.

**Comment by NikitaAvvakumov** [comment]
Great, thanks @tanema!
