### ISSUE TITLE
theme download includes liquid and non-liquid versions of assets

### ISSUE THREAD

**Issue by atomgiant** [Shopify/themekit#41]
I used the theme download (using phoenix v0.2.0) for a theme that has .js.liquid assets, and the end result is both a .js and .js.liquid version of the asset are downloaded.

For example, if you have a file called assets/site.js.liquid, the download ends up grabbing assets/site.js and assets/site.js.liquid.

I would expect only the .js.liquid files to be downloaded.

**Comment by bman-80stees** [comment]
@csaunders Will this be addressed soon?  It actually causes some grief in the workflow using github considering it downloads files not being used for editing when making commits. There are more changes than there actually are. "styles.css" and "styles.css.liquid" are both downloaded to the local directory and git sees the "new" styles.css as a change when nothing had changed to styles.css.liquid.

**Comment by csaunders** [comment]
The work around for now just add those files to your gitignore.

http://stackoverflow.com/questions/10755655/git-ignore-tracked-files
