### ISSUE TITLE
Cannot unzip latest release for manual installation on Mac OS X 10.6.8

### ISSUE THREAD

**Issue by ninjapanda** [Shopify/themekit#411]
Downloaded this: https://shopify-themekit.s3.amazonaws.com/v0.6.12/darwin-amd64/theme

Tried unzipping with The Unarchiver but failed.

Tried unzipping via Terminal but failed:

```
$ unzip theme 
Archive:  theme
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of theme or
        theme.zip, and cannot find theme.ZIP, period.
```

**Comment by tanema** [comment]
It is not a zip, it is a binary. I am not sure if the files on the CDN have ever been a zip. Why are you trying to unzip it?

**Comment by tanema** [comment]
I am going to close this because it is not a supported use case and something else is the problem. Please feel free to add any comments to this issue and I will see them.

**Comment by ninjapanda** [comment]
@tanema - sorry for the late reply.

The [instructions](https://shopify.github.io/themekit/) were to unzip.
 
![screen shot 2017-06-15 at 12 20 20 pm](https://user-images.githubusercontent.com/399812/27191272-4e022026-51c5-11e7-8f83-6266c19ed664.png)

It should be indicated that these are binary files, and also would be helpful to include instructions on how to compile them, or link to a 3rd party tutorial. Thanks!

**Comment by tanema** [comment]
They are binaries in the fact that you download and run them. You don not need to compile. I will take out the unzip instructions.

**Comment by tanema** [comment]
okay I updated the instruction. Thank you for pointing it out!
