### ISSUE TITLE
theme command not found after curl installation (Mac OS X 10.6.8 Snow Leopard)

### ISSUE THREAD

**Issue by ninjapanda** [Shopify/themekit#414]
Perhaps related to #410 (it's the same Macbook)
```
$ curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python
Fetching release data
Downloading version v0.6.12 of Shopify Themekit
Theme Kit has been installed at /usr/local/bin/theme
To verify themekit is working simply type "theme"
$ theme
-bash: theme: command not found
```

**Comment by tanema** [comment]
Can you please paste the results of `echo $PATH` in this issue. You may need to add `/usr/local/bin` to your PATH variable.

**Comment by tanema** [comment]
You can do that by adding `PATH=$PATH:/usr/local/bin` to your `~/.bashrc` and then restart your terminal.

**Comment by ninjapanda** [comment]
```
$ echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/git/bin:/usr/X11/bin
```
Also, the computer did not initially have a `~/.bashrc` and after creating one and adding `PATH=$PATH:/usr/local/bin` via nano, `theme` command is still not found.

**Comment by tanema** [comment]
sorry about that please edit that so that is says `export PATH=$PATH:/usr/local/bin`

**Comment by ninjapanda** [comment]
Edited `~/.bashrc` and restarted Terminal. `theme` command still not found.

**Comment by tanema** [comment]
Can you please confirm that `/usr/local/bin/theme` exists?

**Comment by ninjapanda** [comment]
I cannot access `/usr/local/bin` from Terminal or Finder. Permission denied despite being on Admin account. `sudo` also does not work. Not confident enough to try `chmod` operations. Any suggestions?

**Comment by tanema** [comment]
You should just run `sudo chmod -R 755 /usr/local/bin` that will make it accessible for every user on the system as it should be.

**Comment by ninjapanda** [comment]
I thought `/usr/local/bin` is unaccessible as a security precaution? Anyway, `/usr/local/bin/theme' does exist. This is what happens when invoking it:
```
$ /usr/local/bin/theme ; exit;
dyld: Symbol not found: _SecCertificateCopyNormalizedSubjectContent
  Referenced from: /usr/local/bin/theme
  Expected in: flat namespace

Trace/BPT trap
logout

[Process completed]
```

**Comment by tanema** [comment]
Okay, I am sorry but I cannot support you. This error is because your machine is a 32bit OS and cannot run this themekit in a compatible way.

**Comment by ninjapanda** [comment]
Sorry, I knew I had a 64-bit machine, but did not realise the OS was in 32-bit mode. I have it in 64-bit mode now, and `theme` command now works, but the same error message:
```
dyld: Symbol not found: _SecCertificateCopyNormalizedSubjectContent
  Referenced from: /usr/local/bin/theme
  Expected in: flat namespace

Trace/BPT trap
```

**Comment by tanema** [comment]
Yes I am sorry I can only support OS 10.7 and up.

**Comment by tanema** [comment]
Yes sorry, it wasn't until this issue that I was aware of this limitation.
