### ISSUE TITLE
Feature Request: Output Template ID in Console. 

### ISSUE THREAD

**Issue by yuchant** [Shopify/themekit#415]
It's great to get console updates confirming which Shop the plugin is uploading assets to, but there's no mention of which template we are uploading to.

I propose a one-time initialization print (if it's not applicable to most users) to give us confidence in which environment is being loaded.

This will passively give developers critical information about the automation happening behind the scenes.

Thanks for the great plugin, either way!

**Comment by tanema** [comment]
I am sorry but I don't think I understand. Currently themekit outputs which environment it is operating under for every operation. I assume you know how your environments are setup because you set them up so you you know what shop and theme you are changing.

**Comment by tanema** [comment]
I am going to close this because I don't think this is necessary both because we already output the environment for every command and I don't think most people memorize their theme id but they have setup their config properly once.
