### ISSUE TITLE
Ability to add a default URL in the settings schema

### ISSUE THREAD

**Issue by builtbylane** [Shopify/themekit#418]
### What I expected to happen
add a default url to a "type" url in the settings_schema

### Steps to reproduce
in your `settings_schema.json` file
add this as an option
``` json 
{
        "type": "url",
        "id": "redirect_url",
        "label": "URL to redirect the site",
        "default": "https://google.com/"
  },

error: 
```
	Status: 422 Unprocessable Entity
	Errors: Section 1: setting with id="redirect_url" 'default' is not a valid attribute
```

### My Environment

OS (including version): MacOS 10.12.5 
Themekit version: 0.6.12
Ignore Files(if any):

**Comment by tanema** [comment]
Sorry this is a themes issue not a themekit issue. Themekit is only a tool to interact with themes like the online theme editor. Please contact Shopify support for this.
