### ISSUE TITLE
Slate deploy error coming from themekit and ignore file

### ISSUE THREAD

**Issue by Zoombara** [Shopify/themekit#421]
### What I expected to happen
I expect my deployment to succeed without an error.

### What actually happened
[16:06:17] Transfer Failed: 16:06:17 [development]Asset config/settings_data.json filtered based on ignore patterns

### Steps to reproduce
1. Add settings_data.json to ignore_files
2. Slate deploy
3. Deploys with error message

### My Environment
config.yml:
development:
  password: d1ace74494437d35d2xxxxxxx
  theme_id: 18941xxxxx
  store: osxxxxx.myshopify.com
  ignore_files:
    - config/settings_data.json

OS (including version): Windows 10
Themekit version: 0.6.6
Slate version: 0.10.0

### Additional Info
When looking for solutions I stumbled upon what appears to be the source of the error.
https://github.com/Shopify/themekit/blob/master/kit/theme_client.go#L173

**Comment by tanema** [comment]
If the rest of your deploy completed successfully then I can see no reason why this is an issue. This is themekit warning you that you are trying to deploy an ignored file.

**Comment by Zoombara** [comment]
The rest of the deployment completes successfully. The issue is that I am currently integrating Slate with internal tools like Bamboo and having a warning (for something intentionally ignored) rise up as an error instead of a warning causes the deployments to flag as failed.

**Comment by tanema** [comment]
Hey @Zoombara, this will no longer happen in themekit however you will have to wait for slate to update to the most current release.
