### ISSUE TITLE
Skipping files after upload

### ISSUE THREAD

**Issue by chryton** [Shopify/themekit#432]
### What I expected to happen
Themekit should upload files when they are changed in the `assets/` folder.

### What actually happened
Themekit uploads the files once then skips it.

### Steps to reproduce

1. Update to themekit 0.7.0
3. Make change to a file in assets
2. Upload a file in the assets folder (example: theme.scss.liquid)
2. Returns `[development] Successfully performed Update on file assets/theme.scss.liquid`
3. Make a different change to a file in assets
2. Upload a file in the assets folder (example: theme.scss.liquid)
4. Returns `[development] skipping Update of assets/theme.scss.liquid`

### My Environment

OS (including version): OSX 10.12.6
Themekit version: 0.7.0

### Other Notes

This appears to be happening to any file type within the theme folder structure including *.liquid, *.css, *.scss, *.js, *.jpg, *.png.

**Comment by tanema** [comment]
It seems like you have caught a critical bug, it is hard to tell when it was updated when the command is not running. I will have to roll back the release.

**Comment by chryton** [comment]
@tanema seeing this issue again in `v0.7.3`. We tried blowing away the lock file but after an initial upload, it skipped the files.

**Comment by tanema** [comment]
The files are being checked with a checksum when validating an upload action. If the file has changed it should definitely pick it up. Have the files changed at all? themekit will now skip files that have the same time as on the server and the same checksum as the manifest.

**Comment by chryton** [comment]
Seems to be working as you said now. May have been something with the theme lock file as I didn't have the problem after I cleared it out or a few, rapid changes may have had the requests come back too late.
