### ISSUE TITLE
cannot update to 0.7.0 after particular update sequence

### ISSUE THREAD

**Issue by desm** [Shopify/themekit#433]
### What I expected to happen
I successfully updated 0.6.12 to 0.7.0. When I thought I was experiencing issues with the new version, I downgraded back to 0.6.12. When I wanted to upgrade back to 0.7.0, I expected to be able to.

### What actually happened
It is refusing to update to 0.7.0. 
If I run ```theme update --version=v0.7.0```, the error message is: "Error: version v0.7.0 not found". 
If I run ```theme update```, then the error message is "Error: no applicable update available".

### Steps to reproduce

1. using version 0.6.12 of theme kit, run ```theme update``` (in my case, this step worked successfully and updated theme kit to version 0.7.0)
2. downgrade back to 0.6.12 using ```theme update --version=v0.6.12```
3. try upgrading back to 0.7.0 using by either using ```theme update --version=v0.7.0``` or ```theme update```.

### My Environment

OS (including version): OS X El Capitan 10.11.6
Themekit version: 0.6.12
Ignore Files(if any):

**Comment by tanema** [comment]
Yes I have rolled back the deploy so users will not continue updating to a version that will break their workflow. I have removed it from the release feed.
