### ISSUE TITLE
Theme watch is uploading files inside an ignored folder

### ISSUE THREAD

**Issue by stewartknapman** [Shopify/themekit#435]
While running `theme watch` files inside a template folder that is nested inside an ignored folder are still being uploaded.
This is not breaking anything or stopping me from doing something, it's just more of an oddity I found.

My theme structure is this:
```
_src/ js/templates/my-template.jst
assets/
config/
layout/
locales/
snippets/
templates/
.themeignore
config.yml
```

config.yml includes:
```
  ignores:
  - .themeignore
```

the .themeignore includes:
```
_src
node_modules
```

### What I expected to happen
I'd expect that any file inside the templates folder nested inside the ignored `_src` file would not be uploaded by the theme watch command.

### What actually happened
Themekit tries to upload these files.
Because this is not an accepted file type it throws an error:
```
17:04:07 [development] Received Update event on templates/keyboard-symbols-groups.jst
17:04:09 [development]Asset Perform Update to templates/keyboard-symbols-groups.jst at host the-knit-studio-dev.myshopify.com
	Status: 422 Unprocessable Entity
	Errors: Must have a .liquid file extension
```
Workaround would be to rename the nested folder.

### Steps to reproduce

1. Setup a nested template file
2. Ignore it's parent folder
3. run theme watch and update a file inside the nested templates folder

### My Environment

OS (including version): OSX 10.11.6
Themekit version: ThemeKit - Shopify Theme Utilities 0.6.12
Ignore Files(if any): see above.

**Comment by tanema** [comment]
This will be fixed in the 0.7.x series of the command https://github.com/Shopify/themekit/releases/tag/v0.7.0, It was addressed in this PR https://github.com/Shopify/themekit/pull/407 Path matching and checking was addressed more strictly in that PR.

**Comment by tanema** [comment]
Also thank you very much for the well documented Issue! Great work!

**Comment by stewartknapman** [comment]
Magic, thanks.
Also having the heading prompts inside the issue description field made it really easy give you good details.
