### ISSUE TITLE
Theme upload hanging since update to new version

### ISSUE THREAD

**Issue by christraverse** [Shopify/themekit#436]
### What I expected to happen

Upload of theme files on watch or upload commands.

### What actually happened

Since updating to the newest version of theme kit I can no longer upload or watch files.  Watch doesn't notice file changes, and if I try to `theme upload --env development` i get the following `[development]: 0 / 0 [|] -9223372036854775808 %` where the line inside `[|]` spins constantly.

Nothing else has been changed from this being a working environment other than the themekit update, and I have double checked the password, theme_id and store name regardless.  If I downgrade back to 0.6.12 it continues to work as expected.

### My Environment
OS (including version): Windows 10
Themekit version: 0.7.0

**Comment by tanema** [comment]
Hey @christraverse can you paste a copy of your config here with fake credentials? For instance to you have a directory setting?

**Comment by tanema** [comment]
I was able to reproduce this by trying to upload a project with no files, but I am assuming that you have files since it worked with the other version.

**Comment by NathanPJF** [comment]
@tanema Just wanted to let you know that I was experiencing this hanging spinner issue as well in 0.6.12.  I've tested out the latest changes you've made to 0.7.0 and it appears to have addressed it 😄

**Comment by tanema** [comment]
Okay I released 0.7.1 today with saftey checks to fix this. Please re-open if it is still a problem.
