### ISSUE TITLE
watch and upload no longer working with ThemeKit 0.7.1 windows/amd64

### ISSUE THREAD

**Issue by leglock** [Shopify/themekit#440]
### What I expected to happen
While running `theme watch` command, any local changes should be uploaded to Shopify as I save them

### What actually happened
None of the changes are being picked up by watch, no output on console is happening. I have also tried to run the upload command on a specific file and that does not seem to do anything either.

I double checked and my API credentials I am using have read/write permissions enabled in my private app. I also have no ignore patterns or files defined in my config.yml.

I tried blowing away my configuration and recreating it with 0.7.1, the result is the same. 

### Steps to reproduce

1. Run `theme watch`
2. Make changes locally to your theme files

### My Environment

OS (including version): Windows 10 Pro v1703 build 15063.540
Themekit version: 0.7.1 windows/amd64
Ignore Files(if any): no ignore patterns defined

**Comment by tanema** [comment]
Hey @leglock I will look into this right away.

**Comment by leglock** [comment]
Thanks @tanema. I just rolled back to v0.6.9 and watch is working again, so I don't think my environment is causing this.

**Comment by smartsal** [comment]
Same issue here too. I just updated and the watch command doesn't detect any local changes.
I then rolled back the previous version by replacing with the old theme.exe file and it works now: https://i.gyazo.com/59765c0b77ca41030546451e26abc504.png

So it looks the real issue is with the theme.exe file - in case this helps the devs pinpoint the problem.

**Comment by tanema** [comment]
Yeah the filepath matching became more strict in this version and windows likes to use it's own path separator so I bet I have a "/" where I am supposed to be using platform independant separator. I should have it figured out soon.

**Comment by smartsal** [comment]
ok cool, I'm on a Windows 10

**Comment by tanema** [comment]
Hey @leglock and @smartsal please install this fixed version to verify the fix by running `theme update --version=v0.0.0-rc0.7.2` Once you can tell me that it is correctly working I can merge the changes and make a official release.

**Comment by leglock** [comment]
@tanema Just gave it a try and it is working for me.

**Comment by smartsal** [comment]
@tanema just updated to v0.0.0-rc0.7.2 and it works for me too.
