### ISSUE TITLE
Problem running `theme watch` after upgrade to 0.7.2

### ISSUE THREAD

**Issue by georgemandis** [Shopify/themekit#447]
### What I expected to happen

When I run `theme watch` from my Shopify themes I expect it to watch for changes in the directory and upload them as they are changed. This was working fine prior to upgrade.

### What actually happened

Running `theme watch` works just fine, and it correctly observes changes to files in the directory. Where the problem lies is that it does not upload the file and instead gives me this message:

`[development] No collection name provided`

This happens consistently for all my themes.

### Steps to reproduce

1. Configure a theme using the command line per the instructions: `theme configure --password=[your-password] --store=[you-store.myshopify.com] --themeid=[your-theme-id]`
2. Change into the theme directory and run `theme download` and then `theme watch`
3. Make a change to any of the theme files.

### My Environment

OS (including version): macOS 10.12.6
Themekit version: 0.7.2 (I'm unsure what i was previously using, but I first installed it a few months ago)
Ignore Files(if any): None

### General Notes

I can still run `theme replace` and `theme upload` just fine, along with all the other commands as far as I know. I've tried deleting the configuration file and recreating it using the new version, but it looks exactly the same.

Any guesses?

**Comment by tanema** [comment]
Can you try deleting your `theme.lock` file and see if this fixes your issue. This isn't a solution but rather helping me see if your lock file is in a bad format.

**Comment by tanema** [comment]
Also what is the exact output. You see the `Received` message but do you see the message that the event failed or succeeded?

**Comment by georgemandis** [comment]
Thanks for the quick response. I did try deleting `theme.lock` but it made not difference. Here's the full message copy-and-pasted:

```
12:35:07 [development] Watching for file changes on host ______.myshopify.com
12:35:17 [development] Received Update event on
[development] No collection name provided
```

I don't see any indication if the event failed or succeeded, but I can confirm the changes I make don't get uploaded to the host. I've tried running this with the `--verbose` tag but I don't get any additional information.

**Comment by tanema** [comment]
Yeah it is really bizarre, the problem is that there is no filename there. That ` Received Update event on _______` is missing a filename so the error comes from the lock file trying to set a entry without a filename. I am not sure why this would only happen to you in watch since all of these things use the same mechanisms. By the way if this is blocking you the original version that you most likely were using is 0.6.12 and you can revert to that by using the command `theme update --version=v0.6.12` I will try and get this sorted soon though.

**Comment by georgemandis** [comment]
I'm sorry — I should have clarified. the `_____` part was the correct subdomain.

One other detail maybe worth mentioning: I'm using Go 1.7.1. I don't do much with Go and have no idea if this would be a factor.

I'll probably downgrade for now but maybe leave this open in case others experience the same problem?

**Comment by tanema** [comment]
I knew that is what you meant I was saying that there was also a file name missing from the `Received event` message.

Your Go version has nothing to do with this, themekit is a compiled binary.

**Comment by tanema** [comment]
Can you please give me full details about how you are doing this and information about your setup? For instance are you providing it with a directory config? I ask this because in the steps to reproduce you said this:

> Change into the theme directory and run theme download and then theme watch

When `theme configure` creates the config in the current directory you shouldn't have to change directories after that command. 

Any more information you can provide me would be a great help because I cannot reproduce this.

**Comment by mmaauu** [comment]
Hi! I've the same probelm. I've updated to the new version, and when I run theme watch and change any file in the directory,  and I get:

```
$ theme watch
11:41:59 [development] Watching for file changes on host xxx-xxxxx.myshopify.com
11:42:22 [development] Received Update event on
[development] No collection name provided
```
Do you know what's going on? Thanks!

**Comment by tanema** [comment]
@mmaauu If you could give me more information I could probably help you.

**Comment by mmaauu** [comment]
@tanema, what more info do you need? How can I get it? Thanks!

**Comment by tanema** [comment]
Please provide me with
- OS (including version)
- Steps to reproduce and please paste the whole commands (with private data omitted) that you ran.
- An example of your configuration.

**Comment by mmaauu** [comment]
OS: Win7 Professional Ver 6.1 (Build 7601, SP 1)

The whole commands are the same I've posted before:
 ```
$ theme watch
11:41:59 [development] Watching for file changes on host vaja-custom.myshopify.com
11:42:22 [development] Received Update event on
[development] No collection name provided
 ```
What I was trying to do is copyng some files to assets folder while theme watch.
Until the recent update it was working perfectly.

My config file:

 ```
development:
  password: XXXXXXXXXXX	
  theme_id: "154769475"
  store: XXXXXXXX.myshopify.com
```

Plase let me know if you need anything else. Thanks!

**Comment by georgemandis** [comment]
Hi @tanema — my note where I said "Change into the theme directory..." was misleading. When I created the configuration file, downloaded the current theme and ran `theme watch` that was all within the same directory. 

My config file looks identical to @mmaauu, for what it's worth.

I'll try to relay more information later.

**Comment by tanema** [comment]
Do either of you have a `THEMEKIT_DIRECTORY` environment variable or pass in a directory config through your config file?

**Comment by mmaauu** [comment]
@tanema, yes, I have webkit directory in the path enviroment variable.

**Comment by tanema** [comment]
is it named `THEMEKIT_DIRECTORY` and what is it's value?

**Comment by tanema** [comment]
Can you please update to a patched version for this issue by running `theme update  --version=v0.0.0-issue447` and then try to run theme watch again. It should at least output a better error for us to work with.

**Comment by mmaauu** [comment]
Sorry, I didn't understand your previous question, I don't have THEMEKIT_DIRECTORY variable, I just have the path to the themekit installation in the PATH envioronment variable.

I've updated to the version you sent, this is the output of watching a created file:

 ```
$ theme watch
14:12:27 [development] Watching for file changes on host XXXXX.myshopify.com
[development] loadAsset: File is a directory
 ```

**Comment by tanema** [comment]
Well that is bizarre, I did not expect that error message. I have no idea how that is happening. What text editor are you using?

**Comment by mmaauu** [comment]
I've copied a image file ( png ) from one directory to the one that is being watched by themekit. I also used command line touch to create a file. Both the same result.

**Comment by tanema** [comment]
What is the full path to your working directory? Change you name if you need to I just want to see if it contains special characters or something.

**Comment by mmaauu** [comment]
The full path is C:\Program Files\Theme Kit

**Comment by tanema** [comment]
Sorry no I meant your working directory. The directory that you are editing your theme.

**Comment by mmaauu** [comment]
Sorry, working directory is C:\Shopify Themes\site-custom

**Comment by georgemandis** [comment]
I want to chime-in and say that I also updated to patched version v0.0.0-issue447 and saw the exact same message @mmaauu saw.

I'm using TextMate on macOS.

**Comment by tanema** [comment]
Hey @mmaauu you will want to re-upload `assets/73ag_AD_cuerpo_GG.png`  while running my tests I corrupted that file. I am really very sorry about that.

I still cannot re-produce this issue on windows or OSX even with your exact config and your theme files. There has to be some detail I am missing.

**Comment by tanema** [comment]
Also as a side

**Comment by mmaauu** [comment]
Hi @tanema! Is there any solution for this? Can I rollback to the previous version, it was working good, how can I do?
Don't worry about the theme, this is a development and testing site, by the way, how could you get to access this theme and files? 
Thank you very much for your help!

**Comment by tanema** [comment]
Hey @mmaauu, thanks for being understanding I felt really bad about that. As for access to you shop, I am a shopify employee and you had your domain in the command output above. I am able to access some data for support reasons.

You can roll back your command to the last completely stable version by running `theme update --version=v0.6.12`

**Comment by tanema** [comment]
Hey @mmaauu and @georgemandis  

Can you once again install this patched version and see the error outputted by running this: `theme update --version=v0.0.0-issue447`

And again to rollback to the previous version you can run `theme update --version=v0.6.12`

This will most likely not fix it but at least give me a clear error message with file paths to compare and narrow down this issue.

**Comment by georgemandis** [comment]
Here's the message I now see:

Watching for file changes on host _____.myshopify.com      
[development] Could not locate asset /Users/georgemandis/Projects/clients/client-project/shopify-theme/templates/collection.liquid in the directory /Users/georgemandis/clients/client-project/shopify-theme

I can confirm that `/Users/georgemandis/Projects/clients/client-project/shopify-theme/templates/collection.liquid` exists though.

**Comment by tanema** [comment]
Wait though, there is a difference between where the file event is happening and where the config root folder is

Config root: `/Users/georgemandis/clients/client-project/shopify-theme`
File Event: `/Users/georgemandis/Projects/clients/client-project/shopify-theme`

Are you using a sym-linked directory maybe?

**Comment by tanema** [comment]
Yeah I have confirmed that if I try to run `theme watch` in a symlinked directory I get the same errors, however I cannot run upload and replace but you said that those run fine still.

**Comment by tanema** [comment]
Okay I just updated the `v0.0.0-issue447` version to eval symlinks before everything else so if you run  `theme update --version=v0.0.0-issue447` again and I hope we have figured this out.

**Comment by mmaauu** [comment]
Hi @tanema, sorry for the delay... this version works right for me! Great!! Thank you very much for all your help!

**Comment by georgemandis** [comment]
Working for me as well! It must have been the symlinks. Good catch.

**Comment by mmaauu** [comment]
In my case, I think that there are no symlinks involved, but anyway it worked fine

**Comment by adamchipperfield** [comment]
I'm having a similar issue but instead of telling me it's watching for changes, it just gives me an "Access Denied" error. Could these be related? #454
