### ISSUE TITLE
`theme download` jumps to 100%, doesn't download anything

### ISSUE THREAD

**Issue by Brittliff** [Shopify/themekit#452]
Happens since 0.7.2 update. `theme download` shoots straight from 0 to 100%, nothing downloads. Deleting the lock file fixes, but that might be obvious. 😄 

Happy to provide some more feedback as all of this is pretty generic, let me know what you need!

Config is barebones: development, password, theme_id, store

### What I expected to happen
`theme download` should have grabbed files from the server.
### What actually happened
It didn't!
### Steps to reproduce

1. Update to 0.7.2 from previous.
2. `theme download`

### My Environment

OS (including version): Win 10 latest.
Themekit version: 0.7.2
Ignore Files(if any): None.

**Comment by tanema** [comment]
So this is a feature of the newest version, if there are no updates to the files remotely and all versions match your manifest, it won't waste the bandwidth downloading a file that hasn't changed and will skip it. If you run `theme download -v` you will see `[environment] skipping [filename]`

If however you know some of the files have changed and they were not downloaded please confirm that.

**Comment by Brittliff** [comment]
I thought it may have been something like this when I found the lock file, but I was pretty sure there were remote changes - though I'm probably just mistaken. It's late here now so if it's cool I'll leave this open and confirm in the morning.

Thanks for your (and anyone else involved) work on this feature btw, I think it's the only complaint I could have come up with if somebody asked me about Theme Kit!

**Comment by tanema** [comment]
No problem, you can confirm this later I would definitely want to know it is working. 👍

**Comment by tanema** [comment]
Also as a note to anyone who comes in this issue wondering about this as well, you can skip the checking with the `--force` or `-f` flag and not have to delete your `theme.lock` file.

**Comment by Brittliff** [comment]
Tried this on two different terminals, seemed to work fine on one but redownload everything on the other. It may just be because I was messing with the lock files though, so I'll close this off and it can serve as a notice to anyone else who comes along with the same issue.

Will keep running with the verbose flag for a few days and report back if I see anything odd. Thanks again!
