### ISSUE TITLE
Access Denied when trying to run `theme watch`

### ISSUE THREAD

**Issue by adamchipperfield** [Shopify/themekit#454]
### What I expected to happen
I usually run `theme watch` without any issues whenever I want to start working on a project. I expect to run it, and get the "Watching for file changes on host..." then continue with my work.

### What actually happened
I ran `theme watch`, it gives me "15:46:41 readlink C:\Users\Hp\My Documents: Access is denied." and nothing else. I've tried re-installing, updating and running the command prompt in administrator mode, but no luck.

### My Environment
OS: Windows 7
Themekit version: 0.7.2 windows/amd64
Directory: C:\Users\Hp\My Documents\Adam\Personal\Shopify\end-clothing-store

**Comment by tanema** [comment]
I think this is probably a duplicate of #447 If you install the patched version from that issue with this command `theme update --version=v0.0.0-issue447` and confirm that it fixes it.

After that you can rollback to 0.6.12 by running `theme update --version=v0.6.12`

**Comment by adamchipperfield** [comment]
Thanks @tanema. I installed the patch but received the error "Could not load any valid environments" when running `theme watch`.

**Comment by tanema** [comment]
Okay are you using re-usable config in your yaml? there is this issue that will be in the next release as well https://github.com/Shopify/themekit/issues/446

**Comment by adamchipperfield** [comment]
Nope. I'm just working on one theme.

**Comment by tanema** [comment]
so you config looks like this?

```
development:
  theme_id: "105886"
  password: d4ea8492765de378d9676c
  store: [shop].myshopify.com
```

**Comment by adamchipperfield** [comment]
Yes. `theme_id` and `password` are the other way around, but I'll assume that wouldn't make a difference.

**Comment by tanema** [comment]
I updated that patched version with all those fixes incorporated into it. If you update again to that version with the command `theme update --version=v0.0.0-issue447` and try again and let me know how it goes.

**Comment by adamchipperfield** [comment]
I tried the above but was giving the same error. I've tried removing all theme files (including config.yml) and attempted to re-configure all over again. However, it gives the same error ("Could not load any valid environments")! Even if I manually create the config.yml file and run `theme download` I get the same error.

**Comment by tanema** [comment]
Hey can you send me your `config.yml` to tim.anema@shopify.com and I will take a look at what is going on.

**Comment by tanema** [comment]
Hey @adamchipperfield The newest version was released today. If you could update to the newest version and check if your issues have been fixed that would be great. 

As always, you can rollback to 0.6.12 by running `theme update --version=v0.6.12` if it is still not working for you.

**Comment by adamchipperfield** [comment]
Unfortunately this didn't work. It worked perfectly on my Mac but not my PC. Must be something to do with permissions on my PC. I will keep trying. Thanks.

**Comment by adamchipperfield** [comment]
I've created a new directory and tried `theme configure` but I'm getting "Invalid configuration: invalid project directory: readlink C:\Users\Hp\My Documents: Access is denied". Any idea?

**Comment by tanema** [comment]
Hey @adamchipperfield this is an error that happens when you are using a symlinked/shortcut directory but don't have full access to it. If you run your command line in Administrator it will work but you should not normally have to do this. I would be very surprised that the `watch` command worked in the 0.6.x series because it was using the same symlink eval. I would say check permissions on all of the directories up to your working directory. Or create a directory in a different place and work there.

**Comment by adamchipperfield** [comment]
Just tried in the desktop (out of My Documents) and it worked like a dream! I will look to sorting My Documents directory out for the future. Thanks for your help!
