### ISSUE TITLE
Bootstrap a theme from a Github repo URL

### ISSUE THREAD

**Issue by t-kelly** [Shopify/themekit#457]
It is currently possible to bootstrap a theme from a `.zip` file. I'm not sure if this means a zip file on your computer or remotely via a URL -- or both? 

It would be cool if you could also bootstrap from a Github repo. This could allow you to create and maintain your own custom boilerplate theme which you can use to get started on a new project.

Thoughts?

**Comment by tanema** [comment]
This isn't a restriction of themekit, it is a restriction of the themes API https://help.shopify.com/api/reference/theme#create. They require a zip file from a publicly accessible link. To get this changed you will need to approach the Themes Editor team.

**Comment by t-kelly** [comment]
Ah I think I misunderstood how the command worked.

I thought that it unzipped the theme locally, called `create` using the API, and then uploaded the files with `theme replace`. Rereading the docs, I can see where I was wrong.

If we want this for Slate, I now feel that the best approach would be to: 
1. Download the theme from wherever the user chooses
2. Call `slate zip` 
3. Call `theme bootstrap` with the new zip and theme name specified at setup

Thoughts?

**Comment by tanema** [comment]
I can't just upload a zip file. I would love to but the themes api AFAIK does not support file uploads. Like I said it will only accept a src url to a zip.

**Comment by tanema** [comment]
@t-kelly You can always ask the theme editor team about supporting file uploads through that API but their bandwidth is usually pretty low.
