### ISSUE TITLE
0.7.x not uploading changes

### ISSUE THREAD

**Issue by QuintinS** [Shopify/themekit#459]
### What I expected to happen

I'm running a Grunt task to compile and save theme SCSS to files. When runnning this task, the new file is picked up by Grunt and uploaded. After updating to 0.7.1 and then 0.7.3, however, this stopped working. I had to roll back to 0.6.4 to get it working again.

### My Environment

OS (including version): MacOS 10.12.6 Sierra
Themekit version: 0.7.1 and 0.7.3
Ignore Files(if any):

**Comment by tanema** [comment]
Has the file changed at all? I know you are compiling it but if the file contents have not changed since the last time, the checksum would be the same. If you run `themekit upload --force` it will upload without checking the manifest if that is what you want.

**Comment by tanema** [comment]
You can also see that it was deliberately skipped by running `theme upload -v` Themekit will output `[development] skipping assets/filename.js` for files that do not require an upload.

**Comment by QuintinS** [comment]
Hi Tanema; yes, the file did change.

**Comment by tanema** [comment]
Okay can you please provide me with steps to reproduce then. Please include 

- an example scss file 
- your grunt task
- details of what order that you do things (run grunt, edit file, check logs, ...)

**Comment by QuintinS** [comment]
### Grunt Task

Apologies, this is lengthy.

`
/*global module:false*/
module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
    // Task configuration.
    jshint: {
      options: {
        curly: true,
        eqeqeq: true,
        immed: true,
        latedef: true,
        newcap: true,
        noarg: true,
        sub: true,
        undef: false,
        unused: false,
        boss: true,
        eqnull: true,
        globals: {
          document: true,
          window: true,
          console: true,
          alert: true,
          Image: true,
          $: true,
          _: true,
          jQuery: true,
          verificationNumbers: true,
          Shopify: true,
          Currency: true
        }
      },
      gruntfile: {
        src: 'Gruntfile.js'
      },
      assets: {
        src: ['dist/js/*.js']
      }
    },
    uglify: {
      options: {
        mangle: false
      },
      dist: {
        files: {
          'theme/assets/jquery.ajax-cart.min.js': 'dist/js/jquery.ajax-cart.js',
          'theme/assets/jquery.free-shipping.min.js': 'dist/js/jquery.free-shipping.js',
          'theme/assets/bootstrapify-option-selection.min.js': 'dist/js/bootstrapify-option-selection.js',
          'theme/assets/jquery.instagram.min.js': ['bower_components/jquery-instagram/dist/instagram.js', 'dist/js/jquery.instagram.js'],
          'theme/assets/jquery.tap.js': 'dist/js/jquery.tap.js'
        }
      }
    },
    concat: {
      dist: {
        src: ['dist/js/base.js', 'dist/js/images.js', 'dist/js/facebook-gallery.js', 'dist/js/recover-password.js'],
        dest: 'theme/assets/_base.js'
      },
      wufoo: {
        src: [
        'dist/scss/bootstrapify_variables.scss.liquid',
        'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_variables.scss',
        'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_forms.scss',
        'dist/scss/wufoo.scss'
        ],
        dest: 'theme/assets/_wufoo.scss.liquid'
      },
      styles: {
        src: [
          'dist/scss/bootstrapify_mixins.scss.liquid',
          'dist/scss/bootstrapify_variables.scss.liquid',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_variables.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_hide-text.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_opacity.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_image.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_labels.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_reset-filter.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_resize.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_responsive-visibility.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_size.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_tab-focus.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_text-emphasis.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_text-overflow.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_vendor-prefixes.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_alerts.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_buttons.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_panels.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_pagination.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_list-group.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_nav-divider.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_forms.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_progress-bar.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_table-row.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_background-variant.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_border-radius.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_gradients.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_clearfix.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_center-block.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_nav-vertical-align.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_grid-framework.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_grid.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_normalize.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_print.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_glyphicons.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_scaffolding.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_type.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_code.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_grid.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_tables.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_forms.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_buttons.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_component-animations.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_dropdowns.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_button-groups.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_input-groups.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_navs.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_navbar.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_breadcrumbs.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_pagination.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_pager.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_labels.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_badges.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_jumbotron.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_thumbnails.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_alerts.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_progress-bars.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_media.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_list-group.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_panels.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_responsive-embed.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_wells.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_close.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_modals.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_tooltip.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_popovers.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_carousel.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_utilities.scss',
          'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_responsive-utilities.scss',
          'dist/scss/bootstrapify_overrides.scss.liquid',
          'dist/scss/_animate.scss',
          'dist/scss/_mixins.scss',
          'dist/scss/main.scss',
          'dist/scss/_forms.scss',
          'dist/scss/_brand.scss',
          'dist/scss/_header.scss',
          'dist/scss/_frame.scss',
          'dist/scss/_12becomes1.scss',
          'dist/scss/_front-page.scss',
          'dist/scss/_contact-form.scss',
          'dist/scss/_guidance-carousel.scss',
          'dist/scss/_stockists.scss',
          'dist/scss/_contact.scss',
          'dist/scss/_footer.scss',
          'dist/scss/_about.scss',
          'dist/scss/_privacy-policy.scss',
          'dist/scss/_keep-company.scss',
          'dist/scss/_qanda.scss',
          'dist/scss/_glossary.scss',
          'dist/scss/_science.scss',
          'dist/scss/_reviews.scss',
          'dist/scss/_my-ag.scss',
          'dist/scss/_awards.scss',
          'dist/scss/_products.scss',
          'dist/scss/_pages.scss',
          'dist/scss/_cart.scss',
          'dist/scss/_news.scss',
          'dist/scss/_our-story.scss',
          'dist/scss/_wechat-modal.scss'
        ],
        dest: 'theme/assets/_base.scss.liquid'
      }
    },
    sass: {
      dist: {
        files: {
          'theme/assets/checkout.css.liquid': 'dist/scss/checkout.scss'
        }
      }
    },
    copy: {
      main: {
        files: [
          // grab js files from bower
          {
            expand: true,
            cwd: 'bower_components/bootstrap-sass-official/assets/javascripts/bootstrap/',
            src: '*.js',
            dest: 'theme/assets/'
          },
          {
            expand: true,
            cwd: 'bower_components/isotope/dist/',
            src: 'isotope.pkgd.min.js',
            dest: 'theme/assets/'
          },
          {
            expand: true,
            cwd: 'bower_components/typeahead.js/dist/',
            src: 'typeahead.js',
            dest: 'theme/assets/'
          },
          {
            expand: true,
            cwd: 'bower_components/uniformThumbnails/dist/',
            src: 'jquery.uniform_thumbnails.min.js',
            dest: 'theme/assets/'
          },
          {
            expand: true,
            cwd: 'bower_components/jquery-zoom/',
            src: 'jquery.zoom.min.js',
            dest: 'theme/assets/'
          },
          {
            expand: true,
            cwd: 'bower_components/jquery-colorbox/',
            src: 'jquery.colorbox-min.js',
            dest: 'theme/assets/'
          },
          {
            expand: true,
            cwd: 'bower_components/orderly/dist/',
            src: 'jquery.orderly.min.js',
            dest: 'theme/assets/'
          },
          {
            expand: true,
            cwd: 'bower_components/jquery/dist/',
            src: 'jquery.*',
            dest: 'theme/assets/'
          },
          {
            expand: true,
            cwd: 'bower_components/shipping-calculator/',
            src: 'jquery.cart.min.js',
            dest: 'theme/assets/'
          },
          // grab required respond js and cross-domain files from bower
          {
            expand: true,
            cwd: 'bower_components/respond/dest/',
            src: 'respond.min.js',
            dest: 'theme/assets/'
          },
          {
            expand: true,
            cwd: 'bower_components/respond/cross-domain/',
            src: 'respond-proxy.html',
            dest: 'theme/assets/'
          }
        ]
      }
    },
    shopify_theme_settings: {
      settings: {
        options: {
          templates: ['settings/templates']
        },
        files: {
          'theme/config/settings.html': [
            'settings/branding.yml',
            'settings/colour.yml',
            'settings/design.yml',
            'settings/layout.yml',
            'settings/homepage.yml',
            'settings/homepage-slider.yml',
            'settings/typography.yml',
            'settings/blog.yml',
            'settings/products.yml',
            'settings/collections.yml',
            'settings/sidebar.yml',
            'settings/navigation.yml',
            'settings/footer.yml',
            'settings/cart.yml',
            'settings/age-verification.yml',
            'settings/localization.yml',
            'settings/money.yml',
            'settings/social.yml',
            'settings/advanced.yml'
          ]
        }
      }
    },
    compress: {
      zip: {
        options: {
          archive: 'Bootstrapify.zip'
        },
        files: [{
          expand: true,
          cwd: './theme/',
          src: ['assets/**', 'config/**', 'layout/**', 'snippets/**', 'templates/**', 'locales/**']
        }]
      }
    },
    watch: {
      gruntfile: {
        files: '<%= jshint.gruntfile.src %>',
        tasks: ['jshint:gruntfile']
      },
      jshint: {
        files: '<%= jshint.assets.src %>',
        tasks: ['jshint:assets']
      },
      uglify: {
        files: 'dist/js/*.js',
        tasks: ['uglify']
      },
      concat: {
        files: ['dist/js/*.js','dist/scss/*.scss*'],
        tasks: ['concat']
      },
      sass: {
        files: 'dist/scss/*.scss',
        tasks: ['sass']
      },
      shopify_theme_settings: {
        files: 'settings/*.yml',
        tasks: ['shopify_theme_settings']
      }
    }
  });

  // These plugins provide necessary tasks.
  grunt.loadNpmTasks('grunt-contrib-jshint');
  grunt.loadNpmTasks('grunt-contrib-uglify');
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-contrib-sass');
  grunt.loadNpmTasks('grunt-contrib-copy');
  grunt.loadNpmTasks('grunt-contrib-concat');
  grunt.loadNpmTasks('grunt-contrib-compress');
  grunt.loadNpmTasks('grunt-shopify-theme-settings');

  // Default task.
  grunt.registerTask('default', ['jshint', 'uglify', 'copy', 'concat', 'sass', 'shopify_theme_settings', 'compress']);
};
`

**Comment by QuintinS** [comment]
Watch watches the `dist/js/*.js` files, and the `dist/scss/*scss` files. Concatinates and uglifies them and saves them as a new file in the theme/assets folder.

**Comment by estrattonbailey** [comment]
I can confirm this as well.

**Operating system**: macOS Sierra `10.12.5`
**Themekit version**: `0.6.12` (homebrew default)

`0.6.12` works just fine. When I run `theme update`, it updates me to `0.7.3` and file watching stops working. `theme upload` also does nothing as far as I can tell.

I'll just stay on an older version for now, nbd.

**Comment by tanema** [comment]
Hey @QuintinS can you install this patched version and verify that it works as you would expect it to? You can install it by running `theme update --version=v0.0.0-rc0.7.4`

**Comment by Martynasmarcenko** [comment]
Hi All, the same problem, running `theme update --version=v0.0.0-rc0.7.4` didn't solve it.

**Comment by tanema** [comment]
@Martynasmarcenko Can you tell me what exactly is happening. And can you delete your `theme.lock` and try again?
