### ISSUE TITLE
Suggestion: switch for CI friendly output

### ISSUE THREAD

**Issue by maghis** [Shopify/themekit#463]
We are currently using CircleCI to push a final version of a branch to a preview theme in shopify (using the "replace" command).

Unfortunately the web based output visualization of this tools does not work particularly well with the current progress bar, it would be great to have a switch to make it more "quite" and get maybe up update every 10% of progress.

**Comment by tanema** [comment]
If you pass in the --verbose flag it will disable the progress bar and out the file operations instead. Would that suite your needs better?
