### ISSUE TITLE
Proxy configuration help

### ISSUE THREAD

**Issue by estrattonbailey** [Shopify/themekit#464]
**Operating system:** macOS Sierra 10.12.6
**Themekit version:** 0.6.12

Really really sorry if this is covered elsewhere but I've spent an hour last night and one this morning trying to track down an answer and haven't found anything. 

I actually downgraded from v0.7.3 as I mentioned in #459, but I'm seeing the same error regardless. I guess the real question here is **what does the proxy config param do?** Currently, I can't tell that it does anything at all, other than break the upload process. I was hoping that it would perform similar functionality to Slate with a localhost approximation of the remote site, but opening the localhost URL in my browser shows `ERR_CONNECTION_REFUSED` as well.

In the latest themekit version, it actually kills the script entirely. Also, if I remove the proxy from my config, everything uploads as usual. Error I'm seeing:
```
08:11:29 [development] Proxy URL detected from Configuration: http://localhost:8888 SSL Certificate Validation will be disabled!
08:11:30 [WARN] Error while fetching manifest info for environment development from shopify,
Please check that your config file has the correct config for development
Assets Perform Retrieve at host <recreo-dev.myshopify.com>
	Status: 0 
	Errors: Get https://recreo-dev.myshopify.com/admin/themes/179676109/assets.json?fields=key%2Cupdated_at: proxyconnect tcp: dial tcp [::1]:8888: getsockopt: connection refused
```
```
development:
  password: <pw>
  theme_id: <id>
  store: recreo-dev.myshopify.com
  proxy: "http://localhost:8888"
```
Let me know what else I can provide! Thanks for your work.

**Comment by tanema** [comment]
The proxy config is for running a proxy for all requests to shopify. This is normally used by myself to run a mitmproxy to track and record all requests. It is also useful if you are experiencing issues with a firewall.

**Comment by estrattonbailey** [comment]
Ahhh, thanks very much! Sorry for the bother :)

**Comment by Developer-Amit** [comment]
@tanema Actually I don't understand how this worked for @estrattonbailey 
What changes you did in the config, I'm getting the same error Can you please help me, How can I fix it?
Please
Thanks in advance!

**Comment by anupve90** [comment]
Remove the proxy from the config file.
After that it will work !
