### ISSUE TITLE
v0.7.4 no longer tracks multiple environments correctly

### ISSUE THREAD

**Issue by akitchen** [Shopify/themekit#466]
First off, thanks for the awesome tool! It has helped me have a more sane workflow with working with shopify templates, so 🍻 

I have a local working directory with a config.yml configured for multiple copies of a theme (live, development, etc.).

Upon updating to v0.7.4, ```theme download``` re-downloads the entire theme. if I then download a different theme from the same config, the already-downloaded theme is removed from the theme.lock and will be downloaded again once I switch back to that environment. Previously, this worked as expected.

It seems that themekit is no longer able to track multiple environments correctly in this release.

**Comment by tanema** [comment]
Okay I can confirm this I will have a fix to release shortly

**Comment by akitchen** [comment]
Awesome, thank you!
