### ISSUE TITLE
Version difference manual vs. homebrew installation

### ISSUE THREAD

**Issue by leeuwd** [Shopify/themekit#468]
### What I expected to happen

That the latest stable version is installed, regardless of installation method.

### What actually happened

Manual installations installs `0.7.5`, homebrew installs `0.6.12`.

### Steps to reproduce

```shell
curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python
theme version 
# ThemeKit 0.7.5 darwin/amd64
```

```shell
brew tap shopify/shopify
brew install themekit
# ThemeKit - Shopify Theme Utilities 0.6.12
```

### My Environment

OS (including version): macOS Sierra
Themekit version: `0.7.5` or `0.6.12`
Shell: Fish

**Comment by tanema** [comment]
Yes this is not a bug, I do not release the version on homebrew when there is a Minor Version change until the series is completely stable. As themekit can update itself you can update to that series if you want.
