### ISSUE TITLE
RE-installed Atom now Theme Kit will not publish my changes

### ISSUE THREAD

**Issue by james-zedd** [Shopify/themekit#469]
Just re-installed Atom this morning and now theme kit will not publish my changes.

Every time I save the file through Atom I get the following: 

```
Status: 409 Conflict
Errors: There have been changes to this file made remotely.
```
This worked fine yesterday. I suspect it has something to do with the Atom re-install.

Any help is appreciated.

Themekit version: 0.7.5

**Comment by tanema** [comment]
did you try running `theme download` to retrieve any changes from the server?

**Comment by james-zedd** [comment]
Hi tamema. That fixed it.
