### ISSUE TITLE
Themekit with Shopify Plus -- generated password too short? 

### ISSUE THREAD

**Issue by adrianocr** [Shopify/themekit#470]
### What I expected to happen

I'm the developer for a client with a Shopify Plus store. I had him go into private apps and generate some credentials. Screenshot: https://cl.ly/3j0c4221100G

The password that shopify generated looks much shorter than it usually does. I'm assuming this is a shopify plus thing? Passwords usually look like `6ab8458ded922c337c7c48b76c3bbd7c`

### What actually happened

Shopify generated a password that seems to be too short for use with themekit

### Steps to reproduce

1. generate private app in shopify plus
2. add credentials to themekit config
3. try to download theme via `theme download`

### My Environment

OS (including version): macOS 10.12.6
Themekit version: latest
Ignore Files(if any): none

**Comment by tanema** [comment]
Hey @adrianocr this is more of an issue to contact your Plus representative. I am not sure if this is an issue if themekit still works properly however it would be good to contact your representative anyways.

**Comment by adrianocr** [comment]
@tenema well the issue is that themekit is unable to pull in the theme because it thinks the password is wrong. Even though that's the password that was generated by shopify. So is the issue with the shopify platform or is it themekit? Or both?

**Comment by tanema** [comment]
Okay,

**Comment by adrianocr** [comment]
@tanema they have been contacted but we're awaiting a reply. In the meantime is there a private setting where I can send you a copy of those credentials so you can try to replicate?

**Comment by tanema** [comment]
You can send me the shop domain, that is all I need to tim.anema@shopify.com

**Comment by tanema** [comment]
hey @adrianocr I logged into that shop and I looked into the private apps of that shop and even found a private app called Slate Dev Environment, that password was not short and it was valid to download the theme files. You may need to ask for those credentials again from your client.
