### ISSUE TITLE
Automatic Installation Not Working

### ISSUE THREAD

**Issue by matthew1534** [Shopify/themekit#472]
### What I expected to happen
Used: `curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python`  to install Shopify Theme Kit using the Terminal

### What actually happened
nothing - didn't install

### Steps to reproduce

1. enter `curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python` in the terminal
2. enter user password when it asks for it and hit the enter key
3. nothing happens
4. after a while the new command line appears (not quite sure what this is called!)
5. type `theme` into the Terminal and the Terminal returns `-bash: theme: command not found`

Here is what I typed into the Terminal and how it responded:

```
Last login: Mon Oct  2 12:51:25 on ttys000
$ curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python
Password: MYPASSWORD
$
```

### My Environment

OS (including version): MacOS High Sierra version 10.13
Themekit version: N/A
Ignore Files(if any): N/A

[Edited to remove personal information]

**Comment by tanema** [comment]
What is your python version? Some other things you can try are just downloading the file with the curl command and then running it separately. I am not yet on OSX 10.13 but I will see if I can try it out by this afternoon

**Comment by matthew1534** [comment]
@tanema Thanks for your help - turns out it was an issue with my connection - when I tried to just download the file via the terminal it failed. All working now I have changed to a different network. Thanks again, Matthew
