### ISSUE TITLE
Uploading section files doesn't trigger scss rebuild

### ISSUE THREAD

**Issue by cameroncowden** [Shopify/themekit#473]
Hey! Firstly - thanks so much for all your hard work on theme kit. It's makes our lives 100x easier. 👍 

### Description of issue
I'm running theme watch to make changes to a section file which uses the scss option for the stylesheet tag, like so:
`{% stylesheet 'scss' %}`
The file is uploaded without error and changes to the markup can be immediately seen in the theme preview. Changes to the scss aren't included in the theme preview until a section file is saved via the online editor.

### Steps to reproduce

1. Modify a section which is using an scss stylesheet tag while running theme watch.
2. Open the theme preview in your browser 
3. Check if the new scss styles are being applied.

### My Environment

OS (including version): Mac/Sierra 10.12.4
Themekit version: 0.7.5
Ignore Files(if any):     
    - config/settings_data.json
    - "*.gif"
    - "*.jpg"
    - "*.png"

**Comment by tanema** [comment]
Hey @cameroncowden themekit's responsibility is to just get the files to Shopify and then Shopify processes the content. So are you seeing the changes reflected in the online editor? If so I will file a bug with the editor people.

**Comment by cameroncowden** [comment]
It's interesting - if I pull up the file I changed in the online editor, it shows the new (correct) contents, but the save button is blue upon opening the file (vs grey), and prompts to save unsaved changes if you try to close it (even though no changes were made in the editor). Opening the file online and clicking save does trigger the SCSS rebuild, (also creates the conflict error message upon subsequent attempts to upload the file via themekit).

**Comment by tanema** [comment]
Okay that definitely sounds like a bug in the editor, I will contact the editor team.

**Comment by cameroncowden** [comment]
Thanks so much!
