### ISSUE TITLE
Theme Replace - Update the "Last Edited" Date

### ISSUE THREAD

**Issue by shampto3** [Shopify/themekit#477]
We have two themes on our production site. Once changes are made, we use themekit to automatically deploy to the currently inactive theme. Then once we are ready to go live with our changes, we simply publish the inactive theme that has the changes.

Currently, when we deploy the changes to the inactive theme the "Last Edited" column does not change. It simply shows the last date when we manually edited the theme via the admin portal. We would like this to show the last date that we automatically deployed changes to the theme via themekit as well.

Is there an already implemented solution for this? I've been looking through the docs and can't seem to find any configuration for this. It's not a big deal, but would be nice to have in the near future.

**Comment by tanema** [comment]
Hey @shampto3 this seems like it might be a bug in the Shopify API. I will contact them for this.

**Comment by shampto3** [comment]
Thanks so much for your help. Please keep me posted on their response.

**Comment by tanema** [comment]
Okay so unfortunately I have clarified with the themes team and they said that this is on purpose. The Last Edited value displayed on the admin is only meant to reflect edits made within shopify Admin.

**Comment by shampto3** [comment]
Thanks @tanema for looking into this for me. Sorry to hear about the response, but it's not the end of the world - more of a nice to have kind of thing.
