### ISSUE TITLE
Replacing sections and config files with different schemas causes Unprocessable Entity errors

### ISSUE THREAD

**Issue by ruairiphackett** [Shopify/themekit#478]
### What I expected to happen

When replacing a theme, all valid theme files would be replaced without `422 Unprocessable Entity` errors

### What actually happened

When using `theme replace` to replace the files of a theme with those of another, errors can occur where `invalid type values` for blocks are mistakenly detected:

<details><summary>Example replacing Venture with Supply</summary>
<img src="https://screenshot.click/2017-10-20_14-04-07.png">

Supply has the block values listed in the error message, but they don't exist in Venture. Examples:

https://github.com/Shopify/supply/blob/master/src/config/settings_data.json#L95
https://github.com/Shopify/supply/blob/master/src/config/settings_data.json#L102
</details><br>

It seems that the type values from the theme you are uploading do not exist in the theme that is being replaced and as a result, the 422 errors occur.

This results in an incomplete theme upload/replace.

A current workaround is to manually replace the contents of `settings_data.json` and `settings_schema.json` with empty values in the code editor on the admin.

### Steps to reproduce

1. Clone the [Venture repo](https://github.com/Shopify/venture), build the theme (using slate tools) and push it to a theme
2. Do the same with [Supply](https://github.com/Shopify/supply), and replace the theme from step 1 using `theme replace`
3. The errors shown in the screenshot above should occur

### My Environment

OS (including version): [Mac OSX High Sierra](https://user-images.githubusercontent.com/16187958/31822926-4c00d65a-b5a2-11e7-8310-25b744c05deb.png)

Themekit version: Issue seen on 0.7.5 and 0.6.12
Ignore Files(if any):
```
    - node_modules/
    - "*.md"
    - "*.yml"
    - "*.zip"
    - "*.*~"
```

The issue was also seen by @chrisberthe and @bczegeny

**Comment by tanema** [comment]
Yeah, this is an order of operations issue. I am not sure how I can accommodate this but I will think about it for a while. One main problem is that I always defer updating settings_data.json to after everything else to make sure that the templates and sections are available for when the data is changed. Do you have an idea what the best order would be?

something like this possibly?:

- schema
- templates
- config_data

**Comment by ruairiphackett** [comment]
Great, thanks for looking at this @tanema, apologies for the delay responding!

To get around this issue it looks like `config/settings_schema.json` and `config/settings_data.json` would need to be updated before the schemas, but you mention that this creates another issue.

>I always defer updating settings_data.json to after everything else to make sure that the templates and sections are available for when the data is changed

I'm not sure what this means 🙃  Could you explain it more?

**Comment by tanema** [comment]
I can refer to the issue that you opened at the beginning of this year :P https://github.com/Shopify/themekit/issues/321 Because of that I deferred updating `settings_data.json` to be uploaded after absolutely every other file is updated. This ensures that the schema is updated before the settings_data.json so that Presets are defined already.

**Comment by ruairiphackett** [comment]
Haha, I don't know what I want obviously 😄 

Seeing that `theme replace` completely replaces the theme on your store with the contents of the local one, could we do this perhaps?

- Replace the files in the current order
- If `settings_data.json` is also being updated by the `theme replace` (i.e. it isn't in the ignored files), use the local version to check if the schemas are correct, instead of the existing one on the store

Just so I understand what's going on, what check do you make for `Unprocessable entity` during `theme replace`? Is it one of these:

- Check if the presets defined in the template schemas exist in `settings_data.json`
- Check if the settings defined in `settings_data.json` exist in the schemas
- Something else?

**Comment by tanema** [comment]
I don't load files at all, themekit really only deals with filenames and then just pushes files to the server. The `Unprocessable entity` errors come from Shopify while trying to process your file changes. Themekit has no logic on what is a valid theme/schema/liquid at all. All of that logic resides in Shopify and is validated when the files are pushed to the server.

**Comment by tanema** [comment]
I have no idea how to facilitate this complete replace of one theme with another. It seems like there is an interdependence between section schemas and settings_data->sections. I would need some functionality from the API to disable validation or something like that which I am not sure is a great idea.

I think ultimately I need to close this issue because

- Themekit is a tool meant for developing on the same theme and not switching themes
- Switching from one theme to another should be done from the admin via Publishing
- I cannot support this complex change over without introducing some way to alter the sections during the changeover and I don't ever want to introduce behavior that could damage a theme.

**Comment by ruairiphackett** [comment]
@tanema Thanks for the explanation, I'm delighted to learn more about Themekit 🙂 

I'm looking into a workaround on our end that might allow us to achieve the replace as is. I might have some questions around that, but I'll contact you in slack about it as this isn't an issue that should be fixed in Themekit as you say.
