### ISSUE TITLE
Theme Kit vs Slate

### ISSUE THREAD

**Issue by ADTC** [Shopify/themekit#480]
What's the difference between Theme Kit and Slate? A bit of info in the Readme will be helpful.

**Comment by tanema** [comment]
Slate is a bunch of tooling built on top of Themekit. Themekit is more just a client with the themes API, letting you use whichever tools you need on top. Slate has an opinionated set of tools that Shopify uses to develop its own themes. I will update the Docs accordingly.

**Comment by tanema** [comment]
Closing this as a duplicate of the same issue you opened on Slate as well as my documentation Issue.

**Comment by ADTC** [comment]
No problem. I have made a reference to this issue from the duplicate.
