### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by gregorskii** [Shopify/themekit#489]
Hi there,

I have a pretty interesting use case. We are using the themekit tool to deploy a single theme to multiple stores. We have one "dev" store and 22 public stores. All stores use the same theme and settings from the dev store per the requirements.

We used this tool to deploy to all the stores by manipulating the multiple environments for each store (https://shopify.github.io/themekit/configuration/#config-file).

I am finding that the themekit tool crashes when uploading ~300 files to each store.

Granted this is not an intended use for this tool, I wanted to see what you think about the error I am getting.

### What I expected to happen

Upload to (n) stores at the same time.

### What actually happened

Error:

```
runtime: out of memory: cannot allocate 524288-byte block (1342177280 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x784bd4, 0xd)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:596 +0x7c
runtime.largeAlloc(0x7dbf8, 0x448c00, 0x41baacb0)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/malloc.go:797 +0xdb
runtime.mallocgc.func1()
	/usr/local/Cellar/go/1.8/libexec/src/runtime/malloc.go:690 +0x31
runtime.systemstack(0x11006000)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/asm_386.s:337 +0x5e
runtime.mstart()
	/usr/local/Cellar/go/1.8/libexec/src/runtime/proc.go:1132

goroutine 273 [running]:
runtime.systemstack_switch()
```

### Steps to reproduce

1. Setup deployment for 10+ stores
2. Upload the theme to these stores
3. See error? :)

### My Environment

OS (including version):

Mac OSX 10.12.6 (16G1036)
Macbook Pro 15inch 2015 16gb ram

Also failing on a AWS Windows Jenkins box, but also fails on macbook so its likely just an issue with total memory.

Themekit version:

ThemeKit 0.7.5 darwin/amd64

Ignore Files(if any):

```
resources
.gitignore
.DS_Store
```

`resources` is a folder we use gulp to build into `assets`.

**Comment by tanema** [comment]
Wow! Okay this makes sense because I never anticipated running any of these commands on that many shops concurrently. (Actually when themekit started they weren't event concurrent) This will take quite a while for me to come up with a solution for. I know some fast small wins however I cannot say a single fix will solve this for you. I will get back to you on this soon.

**Comment by gregorskii** [comment]
Awesome, I meant this to be more information as what I am doing is quite off the intended purpose. But if it could be improved for odd use cases, great! But no rush. I am going to do batches of uploads to solve my immediate needs.

Thank you!

**Comment by tanema** [comment]
Hey @gregorskii, please try v0.8.0. It handles loading of local assets a bit better. They only get loaded just before being sent to shopify's servers however this is no limit currently to make sure that too many will get loaded at the same time concurrently. So this may help the problem but not quite fix it yet.
