### ISSUE TITLE
Ignores are not respected when using theme replace --force

### ISSUE THREAD

**Issue by gregorskii** [Shopify/themekit#490]
### What I expected to happen

Ignores are respected even when using --force. My thinking is that using --force is to ignore deltas between local and remote and force an upload. However the --ignore or ignore_file should be respected even with `--force`.

Essentially it should ignore first, force second.

### What actually happened

Ignored files were removed from the server.

### Steps to reproduce

1. Setup a theme, store, and themekit config
2. Add an image to the Shopify admin panel for a theme that is not local
3. Add the image to the ignore file or ignore argument
4. Run `theme replace --force`

Result:

The image on the remote server is gone.

### My Environment

OS (including version):

Mac OSX 10.12.6 (16G1036)
Macbook Pro 15inch 2015 16gb ram

Themekit version:

ThemeKit 0.7.5 darwin/amd64

Ignore Files(if any):

```
resources
.gitignore
.DS_Store
```

resources is a folder we use gulp to build into assets.

**Comment by tanema** [comment]
👍  I will look into this.

**Comment by gregorskii** [comment]
Thank you, I was able to solve my immediate need by using `theme update` instead, it ignores remote files that are not in your local.

I think it still stands that replace could honor the ignores, but it’s possible this just needs to be confirmed as a use case for update and reflect this in the documentation for the two commands.

**Comment by tanema** [comment]
Hey @gregorskii I took a look at this today and it works as expected. I see you are ignoring a file called resources which may be a directory that you are ignoring? If it is the directory in question this should be 

```yaml
ignore_files:
    - resources/ # with the following slash
```

This would properly ignore the whole directory. You can see these rules in the ignores documentation https://shopify.github.io/themekit/ignores/

If I have misunderstood please provide an example ignore pattern that you are finding not to work.

**Comment by gregorskii** [comment]
Hi there,

The ignore is correctly working. That folder is compiled by gulp into assets (as Shopify won’t allow folders in assets). The issue I was having is it would replace sub files of the assets folder even if they were ignored.

**Comment by tanema** [comment]
And your ignores would look something like this correct?

```yaml
ignore_files:
    - assets/ignore_this.jpg
```

**Comment by gregorskii** [comment]
It’s was using a theme kit ignore file using a wildcard for files:

/assets/mw*.jpg

**Comment by gregorskii** [comment]
I tested the wildcard. It was matching the paths. The issue was the remote files matching the path were removed from the theme. Does the theme kit ignore also ignore files on remote? Even if they are not local? That was the concern.

**Comment by tanema** [comment]
Yes they are but it may be that the path matching is done incorrectly against the remote paths. Thanks for the good example it will help testing this.

**Comment by gregorskii** [comment]
Awesome let me know if I can provide any more info. I am on mobile but if you need anything else tracked down or locked up please let me know.

Thanks!

**Comment by tanema** [comment]
Okay I still cannot reproduce this. This is the steps I have taken

- `touch assets/testimage.jpg`
- `theme upload assets/testimage.jpg`
- add to config:
```yaml
  ignore_files:
    - /assets/test*.jpg
```
- `theme replace -fv`
- there is no output in the console of it removing the file and the file is still on the server.

Can you follow these same steps and verify yourself. Can you identify anything I am missing in my setup?

**Comment by gregorskii** [comment]
Interesting. That is pretty much exactly what I did.

We used upload instead of `replace`. So if this cannot be reproduced ill just close it, and if anyone comes across it again there will be more examples.

:)
