### ISSUE TITLE
Drains battery like a 🚛

### ISSUE THREAD

**Issue by larsenwork** [Shopify/themekit#491]
### What I expected to happen
Being able to use my brand new macbook pro with theme-kit watch running in the background

### What actually happened
It drains the battery like crazy.

Screenshot is taken just after I stopped theme watch just to verify that it wasn't my terminal (hyper) that was the culprit

<img width="434" alt="screen shot" src="https://user-images.githubusercontent.com/3859425/32728079-46b000dc-c87f-11e7-8cb8-eeb9384b1797.png">

### Steps to reproduce

1. Run `theme watch`
2. Don't be connected to a power outlet 

### My Environment

OS (including version): macOS High Sierra 10.13.1
Themekit version: v0.7.5
Ignore Files(if any):

**Comment by tanema** [comment]
Hey @larsenwork can you tell me what the CPU usage themekit has while running watch? Normally `watch` runs with less than 1% of CPU usage so I am not sure how it is killing your battery.

**Comment by larsenwork** [comment]
Starting out on a "fresh" `theme watch` it only has a energy impact 20-30 which still seems like 100x of what a simple watch task should require.
![screen shot 1](https://user-images.githubusercontent.com/3859425/32731245-9b7193d8-c889-11e7-8259-dafec57e2674.png)

But since the avg. is this high it could be that it slowly increases over time (I often have it running for a couple of days)?

CPU hovers around 2% also on a "fresh" start
![screen shot 2](https://user-images.githubusercontent.com/3859425/32731348-daa64a8a-c889-11e7-9003-c02c1b370178.png)

This is my machine fwiw
```
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
2,3 GHz Intel Core i5
```

**Comment by tanema** [comment]
I am not sure how much I can do about this. It seems dependant on the size of the theme. I have tried it on a few of my own and the smaller ones came around 10 and a larger one around 15. It may have to do with the underlying library I use for FS events. It uses polling to make the fs event processing FileSystem independent and easier to be cross-compiled.

My CPU usage for both themes I have seems to be less than 1% as well. Are you developing a particularly large theme?

**Comment by larsenwork** [comment]
Sorry for the slow reply. It's still happening though. I don't know what constitutes a big theme but mine is maybe 5.9mb and 320 items.

**Comment by alankimo** [comment]
Hi @larsenwork, I have the same issue, theme kit drains my battery so hard. Can you fix it or find a better client to work with shopify?

**Comment by joshiefishbein** [comment]
@larsenwork Chiming in here – could this have anything to do with Hyper actually being an Electron app? And like all Electron apps, Hyper could be using more resources than necessary...

Do you have the same issues using Mac's native Terminal or something more universal like iTerm?

**Comment by tanema** [comment]
@larsenwork While working on v0.8.0 I was able to narrow down a leak that would cause themekit to leak resources while watching files. This may have caused these CPU issues. Please update to 0.8.0 and let me know if this help alleviates your CPU/Energy usage issues.

**Comment by larsenwork** [comment]
@tanema cheers, currently 0.6.12 is the latest that you've published `npm view @shopify/themekit dist-tags` so if it's not ready for release I'd suggest doing a `npm publish --tag beta` or something like it so we can test it

**Comment by tanema** [comment]
Nope the current version released is v0.8.0 If you have 0.6.12 installed you can simply run `theme update` to get the latest.

**Comment by tanema** [comment]
@larsenwork wait are you using slate? If you are using slate then, I cannot help yet. The slate team will have to update their version, but I will let them know.

**Comment by larsenwork** [comment]
Looks good so far — I'll close this for now :)

**Comment by samueltlg** [comment]
I'm getting very large CPU usage for the current release (1.0.1). When starting theme watch, CPU usage begins and remains at between 15-20%. I'm also using a fast machine. Apart from the essential config settings, my remaining config is:

```yaml
  ignore_files:
    - config/*
    - notes/*
    - node_modules/*
    - ./package.json
    - ./package.lock.json
    - prepros*
    - ./.vscode/*
    - liquid-testing/*
    - local-files/*
    - ./README.md
    - tests/*
    - src/*
    - webpack*.js
    - ./tsconfig.json
```

Perhaps it has something to with this (the ignore_files). The node_modules folder isn't terribly large, and neither are any of the others

**Comment by tanema** [comment]
Hey @samueltlg please open a new issue for this and I will look into it.

**Comment by samueltlg** [comment]
Thanks - have submitted an issue (#664)
