### ISSUE TITLE
Download => Exceeded 2 calls per second for api client

### ISSUE THREAD

**Issue by larsenwork** [Shopify/themekit#500]
### What happened
Downloading results in `Exceeded 2 calls per second for api client.`

### What I expected to happen
Downloading the theme without errors. Works without hickups on other stores with exact same setup.

### Steps to reproduce

1. `theme download`  using password from private app
2.
```
error downloading asset: Asset Perform Retrieve to  at host leo-no.myshopify.com
        Status: 429 Too Many Requests
        Errors: Exceeded 2 calls per second for api client.
```

### My Environment

OS (including version): macOS
Themekit version: ThemeKit 0.7.5 darwin/amd64 or @shopify/themekit 0.6.12
Ignore Files(if any): 
```
src/*
node_modules/*
config.yml
config.yml.example
README.md
package.json
.gitignore
.git
.DS_Store
themekit_ignores
webpack.config.js
yarn.lock
npm-debug.log
yarn-error.log
config/settings_data.json
assets/happyending.js
assets/bold-memberships-salt.liquid
```

**Comment by larsenwork** [comment]
Update: also happens on some of my other stores.

**Comment by tanema** [comment]
Are you running multiple themekit instances? I may have to tweak the throttle again but themekit right now is supposed to be pinned at 2 calls per second

**Comment by larsenwork** [comment]
@tanema no, only running one

**Comment by larsenwork** [comment]
Can't reproduce any more

**Comment by Sanfam** [comment]
@tanema This may not be related, and I'm keeping this issue closed but I thought I'd chime in.  We had this crop up when multiple developers shared one "private app" access key.  Each was unware of having stepped on the others' toes.  creating a private app for themekit per-developer resolved this.

**Comment by cjreeve** [comment]
This happened to me. What caused this is that I was watching changes via `theme watch` and downloading at the same time with `theme download`. I think this tried to upload each file it just downloaded, which led to the warning. After stopping the watch tool I was able to download again without issue.

**Comment by milkymura** [comment]
on windows  .. you should only have one themekit.exe running. Ending the others fixed my issue


![image](https://user-images.githubusercontent.com/11899020/61105345-7b900e00-a42e-11e9-9e40-62ff44851f47.png)
