### ISSUE TITLE
Should asset manifest (theme.lock) be removed.

### ISSUE THREAD

**Issue by tanema** [Shopify/themekit#502]
I get a lot of negative feedback on the asset manifest (theme.lock) so I am not sure if the manifest and file checking is even helping anyone. Please vote how you feel about this feature in themekit.

[![](https://api.gh-polls.com/poll/01C4Q9C9VG6X39764HCRY4C9NB/Remove%20asset%20manifest)](https://api.gh-polls.com/poll/01C4Q9C9VG6X39764HCRY4C9NB/Remove%20asset%20manifest/vote)
[![](https://api.gh-polls.com/poll/01C4Q9C9VG6X39764HCRY4C9NB/Keep%20asset%20manifest)](https://api.gh-polls.com/poll/01C4Q9C9VG6X39764HCRY4C9NB/Keep%20asset%20manifest/vote)
[![](https://api.gh-polls.com/poll/01C4Q9C9VG6X39764HCRY4C9NB/Don't%20have%20an%20opinion)](https://api.gh-polls.com/poll/01C4Q9C9VG6X39764HCRY4C9NB/Don't%20have%20an%20opinion/vote)

**Comment by joshiefishbein** [comment]
Is this referring to the Theme.lock pattern or is there a separate asset manifest that isn't immediately shown to theme developers?

**Comment by tanema** [comment]
Yes the theme.lock is the asset manifest. I will change the description and title to better describe it.

**Comment by joshiefishbein** [comment]
Perhaps its use-case ended up being more of a minority than originally planned, but I don't think its entirely useless for the point you made on #493 – being that we have no control over merchants editing files with the Shopify online theme editor. Some merchants would never want to touch that and respect their dev flow, some merchants do end up touching files a lot. So this feature's usefulness could be different from merchant to merchant.

I've been using `--force` without a problem since I opened that ticket. Maybe, instead of removing this feature, we make its usage determined by a flag for shop developers to use when they know the tool is useful. Maybe something like `--use-lock`? It's default state would be false, making this something that developers intentionally opt into instead of something to intentionally opt out of.

@tanema what do you think?

**Comment by cameroncowden** [comment]
I think it makes sense for developers that don't use other version tracking in their workflow, as it can be a nice sanity check, but it can be inconvenient when other VCS are in place.

Would it be possible to have this as an option, enabled by default, that we could disable on a per-environment basis? E.g. a setting in config.yml

**Comment by joshiefishbein** [comment]
@tanema Tim this voting integration is accidentally logging my page scroll clicks. At this point it's given me three votes (2 Remove, 1 No Opinion). Know that my real vote is No Opinion, as I'm hoping for just a more passive way to keep this feature.

**Comment by hoghug** [comment]
any update on this? has it been implemented yet?

**Comment by thannes** [comment]
I vote to remove it. It is not of any use in my experience, and **if anyone is using this for version control they should not**.

**Comment by tanema** [comment]
Okay, I am giving this until the end of the week, I think the addition of the asset manifest has caused more trouble both as a maintainer of themekit and for the users of themekit. It would have been better had shopify exposed checksums instead of timestamps but I cannot convince them of this. Unless there is some reason to keep it, I will be starting work on removing it in a week. 

@thannes the asset manifest was never for version control and it never had been sold that way. It was meant to try to provide some confidence in deploying your code so that you did not overwrite your client's theme files.

**Comment by tanema** [comment]
I have completed initial work on a new version of themekit without the asset manifest. For those who wish to live without the manifest, please try out v0.8.0 prerelease by running `theme update --version=v0.8.0-prerelease`

It has removed the manifest but it has also added better error reporting. Also `theme bootstrap` has been renamed to `theme new` as well as a command `theme get` has been added that will create a config.yml file for you and download. (basically `theme configure` with auto downloading)

It would really help me to ensure the deploy of the new version if you would try it out and report any issues you encounter.

**Comment by tanema** [comment]
I will be releasing v0.8.0 at the beginning of next week unless there is any feedback of weird behavior.

**Comment by tanema** [comment]
v0.8.0 has been release today and the asset manifest has been removed
