### ISSUE TITLE
Delete Themekit via Terminal.app

### ISSUE THREAD

**Issue by randyribaudo** [Shopify/themekit#503]
No Longer Want Themekit

OS: MacOS High Sierra 10.13.2
Themekit version: 0.7.5

**Comment by tanema** [comment]
This is in the documentation: https://shopify.github.io/themekit/faq 

```
rm $(which theme)
```

**Comment by randyribaudo** [comment]
When it prompts me and I say yes it gives me an error: Permission denied

**Comment by tanema** [comment]
Then use `sudo`, this is not a themekit issue. I cannot provide support for shell usage.

**Comment by randyribaudo** [comment]
tanema, I am knew to this stuff so I am not sure what you are addressing and I don't appreciate the perceived attitude.
