### ISSUE TITLE
theme download returns 'Error while fetching manifest info for environment development from shopify'

### ISSUE THREAD

**Issue by lsnix** [Shopify/themekit#504]
### What happened
Theme download is not working.

theme download
12:57:00 [WARN] Error while fetching manifest info for environment development from shopify,
Please check that your config file has the correct config for development
Assets Perform Retrieve at host <mystore.myshopify.com>
	Status: 0
	Errors: Get https://mystore.myshopify.com/admin/themes/380XXXX25/assets.json?fields=key%2Cupdated_at: net/http: TLS handshake timeout

By default all config are set for 'development' environment. Is there a way to know my theme is under development environment ? Does shopify have 'environment' assigned to themes ? Waht am I missing ? 

### What I expected to happen

Download all files under the theme.

### Steps to reproduce

1. mkdir new | cd new 
2. theme configure --password=XXXX --store=mystore.myshopify.com --themeid=380XXXX25
3. theme download

### My Environment

cat config.yml
development:
  password: XXXX
  theme_id: "380XXXX25"
  store: mystore.myshopify.com

OS (including version): macOS Sierra 10.12.5
Themekit version:

theme version
ThemeKit 0.7.5 darwin/amd64

Ignore Files(if any):

**Comment by tanema** [comment]
Usually `TLS handshake timeout` is a sign of a poor connection or that you are going through a proxy that is preventing a valid connection. I would recommend trying it again with a different connection. As for the environment, `development` is the default environment. You can see it in your configuration.

**Comment by tanema** [comment]
This will no longer be a problem in v0.8.0 (released today) since the asset manifest has been removed from themekit.
