### ISSUE TITLE
Switching branches in git doesn't upload changed files 

### ISSUE THREAD

**Issue by markcooper** [Shopify/themekit#505]
### What happened
When changing branches, a running ```theme watch``` leaves artifacts of previous branch, doesn't detect changed files and upload them.

### What I expected to happen
I would expect that changing branches would result in the correct files for that branch being uploaded to the server.

### Steps to reproduce

1. Start ```theme watch```
2. Change branches
3. Observe that files/file versions from previous branch remain deployed on server

### My Environment

OS (including version): High Sierra 10.13.3
Themekit version: v0.7.5
Ignore Files(if any): none

**Comment by tanema** [comment]
This was done by design so that accidental full overwrites did not happen. You can see this behaviour because when you checkout a new branch you will see that the watch command reloads to make sure that it has the most up to date configuration.
