### ISSUE TITLE
Trying to open a preview page for the theme

### ISSUE THREAD

**Issue by francescacosta** [Shopify/themekit#506]
### What happened
I've downloaded my theme, confiqured the config.yml, all worked well untill I tried to get to it to open in a preview

when running the command **theme open --env=production**

I get the error "Could not load any valid environments"

The password is fine, and everything downloaded well without errors

### My Environment

OS (including version): High Sierra 10.13.3
Themekit version: latest one downloaded today
Ignore Files(if any):

**Comment by tanema** [comment]
sorry if this is a stupid question but you have a production environment setup in your config?

**Comment by cameroncowden** [comment]
Similar error happening for me as of the last few weeks, but without error message. 

\> run theme open -e=staging
\> correct url is printed in console
\> new chrome window opens (regardless of existing chrome windows/tabs)
\> nothing happens (where themekit should paste/put url in chrome and trigger navigation)
\> manually copy and paste url from terminal into chrome

**Comment by tanema** [comment]
@cameroncowden Thanks for helping, however, I think that is unrelated. I have been having a similar issue with chrome opening blank windows.

**Comment by francescacosta** [comment]
No! I'm sorry I didn't see anything about putting a production environment setup, where can I find this information :)

**Comment by tanema** [comment]
@francescacosta You can see how the configuration looks here: https://shopify.github.io/themekit/configuration/#config-file specifying an environment is just selecting one of those configs by name. There is nothing special about the names and production would be just another named config.

**Comment by francescacosta** [comment]
sweet thanks, totally missed that! All good now
