### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'urlopen'

### ISSUE THREAD

**Issue by jordantomax** [Shopify/themekit#508]
### What happened
Using Python3, `__init__` this line:
`self.release = json.loads(urllib.urlopen(Installer.LATEST_RELEASE_URL).read().decode("utf-8"))`
Throws the error:
`AttributeError: module 'urllib' has no attribute 'urlopen'`

### What I expected to happen
That there is a check for if `urlopen` exists and to handle appropriately based on Python version

### Steps to reproduce
1. Install Themekit using Python3 on a Linux machine

### My Environment
I am running into this on CircleCI using a Linux machine with Python3

**Comment by tanema** [comment]
Yes the script is written using Python2, Please use that if available.
