### ISSUE TITLE
Allow editing email templates as part of theme

### ISSUE THREAD

**Issue by avishai** [Shopify/themekit#509]
I would suggest allowing email templates to be overwritten directly in the theme, so that it's easier for developers to integrate their themes with Shopify's built-in notifications.  Currently it's extremely tedious to develop and test customizations to the transactional email templates.

**Comment by tanema** [comment]
I would contact Shopify support to properly log this because themekit has nothing to do with how themes actually work. It is just a client for the themes API. Going through support will add to our resources of this request and get that information to the correct people
