### ISSUE TITLE
Theme upload locales error

### ISSUE THREAD

**Issue by maedisophie** [Shopify/themekit#513]
Hi There,

I am getting the following error when using Theme Upload.
Asset Perform Update to templates/customers at host baharistore.myshopify.com
Status: 422 Unprocessable Entity
Errors: Must have a .liquid file extension

I don't know whats wrong, i just folowing step from https://shopify.github.io/themekit/#installation

Please help me to fix this.
Thanks

### My Environment

OS (including version):Windows 10
Themekit version: ThemeKit 0.7.5 windows/amd64
Ignore Files(if any):

**Comment by tanema** [comment]
Does the file have the `.liquid` file extension?

**Comment by maedisophie** [comment]
thank you for replying, it's has succeeded no more error

**Comment by kenkami1995** [comment]
Hi @maedisophie 
I also faced this kind of error. 
Could you please let me know how to fix this kind of issue?

Thank you.
