### ISSUE TITLE
getting a 401 when trying to download theme

### ISSUE THREAD

**Issue by thomasfaller** [Shopify/themekit#514]
Hey guys!

### What happened

- I installed ThemeKit through a curl | python command as suggested on the documentation. That went well.
- Created config file using *theme configure --password=[xxxxxxxxx] --store=[xxxxxxx.myshopify.com] --themeid=1234567*
- When I tried downloading my theme with the *theme-download* command, it gave me a 401 error in the following:

```
[WARN] Error while fetching manifest info for environment development from shopify,
Please check that your config file has the correct config for development
Assets Perform Retrieve at host <test-hw-store.myshopify.com>
        Status: 401 Unauthorized
        Errors: [API] Invalid API key or access token (unrecognized login or wrong password)
```
I checked that I created the proper private app to get an API key, I also double-checked that the theme dropdown was set to *read and write* permissions in the permissions panel.

### What I expected to happen

Is there like a period I should wait for the API to be functional? I did try to download the theme a couple of minutes only after creating the API.
Or am I doing something wrong?
I followed the instructions [here](https://shopify.github.io/themekit/) but perhaps I missed a step.

### Steps to reproduce

1. Create config file
2. Create API
3. Download Theme

### My Environment

OS (including version): MacOS 10.11.6
Themekit version:  ThemeKit 0.7.5 darwin/amd64
Ignore Files(if any):

**Comment by tanema** [comment]
I just want to verify 2 things
- do you run the command without the square brackets
- you don't specify the (http) protocol on your store.

**Comment by thomasfaller** [comment]
@tanema Thanks, actually I was using my Shopify password rather than the API password... aha
well, lesson learned 😅
