### ISSUE TITLE
How do I update theme files using the new master files?

### ISSUE THREAD

**Issue by abrambailey** [Shopify/themekit#515]
I am using the supply theme and wondering on best practices to get the new master files to update my local themekit repo.

**Comment by tanema** [comment]
I am not sure what you are asking. Can you provide me with a bit more information?

**Comment by abrambailey** [comment]
The supply theme files I have are very old and I want to update them, so I need to merge my modifications into the new theme files?

**Comment by tanema** [comment]
I suggest that you 

- start a new repo with the new code
- deploy it to a non-live theme
- make your changes to look how you want it
- deploy it to the live theme, overwriting your old theme.

**Comment by abrambailey** [comment]
"start a new repo with the new code" ... Can you explain how to do this step? Where do I get the new supply code? I tried creating a second version of Supply in my production site so I could edit that code, but unfortunately Shopify doesn't allow you to have two versions of Supply... The button says "Added" and is disabled on the Supply theme.

**Comment by abrambailey** [comment]
Is there a way to initialize a new repo using one of the freely available shopify themes, like Supply?

**Comment by tanema** [comment]
- To start a new theme from a theme from the theme store click. If you are viewing Supply, you click the button that says "Add Supply"
- If you already have supply and want to duplicate it to start another, click the actions dropdown beside your supply theme and click duplicate to create a copy of that theme. 
- Then you can download the files using themekit to wherever you please. 
- If you have theme code that is not on your online store, use the `upload theme` button to upload a zipped folder of that code to create a new theme

This is not a technical issue of themekit and the github issues are not support. If you have further issues, please contact shopify support. They can assist you far better than I can.

**Comment by abrambailey** [comment]
Not having a way to initialize with a stock theme is most definitely in themekit territory, but I accept that this isn't possible, and will use the supplied workaround. Thanks!
