### ISSUE TITLE
ThemeKit should respect default Shopify API limits

### ISSUE THREAD

**Issue by yuchant** [Shopify/themekit#518]
### What happened
`theme download` caused `429 Too Many Requests` error.

### What I expected to happen
I should never see an error. It should just download slower.

### Steps to reproduce

1. Download Themekit
2. Configure a project with many files (359 for me)
3. Run `theme download`

### My Environment

OS (including version): OSX 10.13.3
Themekit version: 0.7.5
Ignore Files(if any): none

**Comment by tanema** [comment]
Do you have multiple instances of themekit running? Themekit has a throttle in place to respect the limit so this error usually only happens when multiple instances are running.

**Comment by yuchant** [comment]
@tanema That's probably it! I probably had another instance buried somewhere. I'll post back if I see it again and check instances. Thank you!
