### ISSUE TITLE
SASS file broke

### ISSUE THREAD

**Issue by dirtandrust** [Shopify/themekit#520]
### What happened

On Friday 11 Jun 2018 I ran "theme watch" and somehow a scss error occurred, it wasn't there when I logged off, shut down my work on Monday last week and the Shopify website stilodesign.myshopify.com was working fine (sorry I have to keep it password locked for now so you won't be able to see it).

### What I expected to happen

I expected to run "theme watch" and have scss files compile but this didn't happen they broke instead. Meaning the entire theme wouldn't load. I could not figure out how to fix it, as I could not find the referenced error.

### Steps to reproduce
![themekit-error](https://user-images.githubusercontent.com/1700664/41206191-8e7ff9ce-6d54-11e8-8c1b-c28a224bc39d.jpg)

1. Run "theme watch" on a directory that's already had several successful commits
2. Tried to fix by deleting the lock file and by running sass watch on my own; this did not help
3. Tried to fix by doing "theme update" but all this did was wipe out my theme customisations, still don't know where these are kept? I copied and pasted the json settings but these still did not bring back the fonts and colours I chose in Customize.

[Screenshot of the error](http://dirtandrust.com/themekit-error.jpg).

### My Environment

OS (including version): El Capitan 10.11.5
Themekit version: ThemeKit 0.7.5 darwin/amd64
Ignore Files(if any): none

I definitely can't use Themekit if this is going to happen, any help appreciated.

**Comment by tanema** [comment]
I have no idea how you got this error because this is a ruby error and themekit does not use ruby (or check the sass) at all. I can't believe that Shopify would send back this error either. Is this a new project?

Also your theme config settings are stored in `config/settings_data.json` so if that file is uploaded, it will overwrite your config settings.

Did you find a way to correct the issue?

**Comment by dirtandrust** [comment]
I do run ruby sass but in this case I ran theme watch and it wasn’t updating the css file from the sass file; in fact it won’t update on the web interface either - I have to add css to both sass file and css file manually for changes to take effect.

Cheers
----
Nathaniel Flick
Dirt and Rust, Limited (NZ)
dirtandrust.com

Skype: nathaniel.flick
Mobile: +64 22 308 8194

**Comment by tanema** [comment]
Do you have a themekit error and not a ruby sass error? because it seems like if you sass file is not getting updated, that would be why it wouldnt be updated on the web either.

**Comment by dirtandrust** [comment]
Not sure, is there a log I can check?

Cheers
----
Nathaniel Flick
Dirt and Rust, Limited (NZ)
dirtandrust.com

Skype: nathaniel.flick
Mobile: +64 22 308 8194

**Comment by tanema** [comment]
No, if you are running theme watch, all of the important output is output to stdout

**Comment by dirtandrust** [comment]
can you check the stilodesign shopify site and confirm scss file is working again? 

Cheers
----
Nathaniel Flick
Dirt and Rust, Limited (NZ)
dirtandrust.com

Skype: nathaniel.flick
Mobile: +64 22 308 8194

**Comment by cameroncowden** [comment]
@dirtandrust scss compilation is handled server side by shopify. You upload the file ```styles.scss.liquid```, and reference it in the theme as ``` {{ 'styles.scss.css' | asset_url | stylesheet_tag }}```, and when you upload an updated ```styles.scss.liquid``` file, shopify will compile it into ```styles.css```. If there is a scss compilation error, themekit does not report it - rather, the output css file will contain a single line saying "Failed to compile SCSS file".

**Comment by dirtandrust** [comment]
The problem I’m seeing, though, is when I’m no longer using Themekit I edit the .scss file and .css file does not update - I have to edit both files. Is this still the case or is it fixed for Stilo Design shopify site?

Cheers
----
Nathaniel Flick
Dirt and Rust, Limited (NZ)
dirtandrust.com

Skype: nathaniel.flick
Mobile: +64 22 308 8194

**Comment by cameroncowden** [comment]
@dirtandrust Are you editing the .scss file locally or through the web editor? Also when you say you have to edit both files - there should be no .css file available to edit either locally or via the web editor, as it is compiled behind the scenes and served directly to the browser (the compiled .css output from the .scss file is not part of the theme assets).

**Comment by dirtandrust** [comment]
I see now we’re getting closer to me understanding how this works. 

I’m linking to the .css file in the theme.liquid master template, but what I need to do is link to the scss file, but when I do that, the styles break. 

When I do this: {{ ‘themestyles.scss.css' | asset_url | stylesheet_tag }} the styles break for the theme. So what can I do to get the theme working with this scss file? Do I do this or something else?: {{ ‘themestyles.scss.liquid' | asset_url | stylesheet_tag }}

Cheers
----
Nathaniel Flick
Dirt and Rust, Limited (NZ)
dirtandrust.com

Skype: nathaniel.flick
Mobile: +64 22 308 8194

**Comment by cameroncowden** [comment]
Hmm, your first syntax seems correct. Could there be a compilation error within the scss? If you use the ```{{ ‘themestyles.scss.css' | asset_url | stylesheet_tag }}``` tag, can you see in Dev Tools > Network, if there's a css file called themestyles.scss.css? If so try clicking into it to inspect the contents. (You could also test this by removing all the content from the file except a single simple css rule and see if that loads in correctly) Also maybe make sure that the file in the assets folder is just called 'themestyles.scss.liquid'. 

Another thing you could try is downloading one of the free themes which uses an scss stylesheet and copy/pasting it into your theme to see if it will work.

**Comment by cameroncowden** [comment]
Also just noticed that in your ```{{ ‘themestyles.scss.css' | asset_url | stylesheet_tag }}``` line the first ' is a backtick instead of a single quote. If it's the same in the theme file it might break it.

**Comment by tanema** [comment]
Thank you @cameroncowden for the support! This seems to have been a liquid error and not a themekit error so I am closing this.
