### ISSUE TITLE
'theme download' is not downloading files and no error is received

### ISSUE THREAD

**Issue by rajasajidmanzoor** [Shopify/themekit#524]
### Theme files are not downloading
I have installed theme kit using manual way.
I have created a folder name 'fashion-theme' and added a blank file config.yml in side the folder. 
In config.yml i have following code
`development:
    password: New-App-Password
    theme_id: 40908259386
    store: urflavor.myshopify.com
`
Then i went to CMD, cd to the fashion-theme folder and run command `theme download`
This the result
![image](https://user-images.githubusercontent.com/5917783/42017979-25a3cc86-7aca-11e8-8f91-77c5ada776d6.png)

But in folder, No files are shown in folder.

![image](https://user-images.githubusercontent.com/5917783/42017997-3774e666-7aca-11e8-8cf7-6e090bf0775e.png)

### What I expected to happen
It should download theme files

### My Environment

OS (including version): Windows 10
Themekit : 0.7.5 windows/amd64
Ignore Files(if any): None

**Comment by rajasajidmanzoor** [comment]
Hello, I have also tried creating a new config file using the following command 

`>theme configure --password=[PASSWORD] --store=urflavor.myshopify.com --themeid=[THEMEID] `

But there is no config.yml file created in the folder. 

![image](https://user-images.githubusercontent.com/5917783/42075110-ca7be1a8-7b88-11e8-9dcf-b0b10d194f50.png)

**Comment by tanema** [comment]
Are you creating the config file inside the fashion-theme folder?

**Comment by tanema** [comment]
I believe this might have been caused by the asset manifest which has been removed from v0.8.0. This should no longer be an issue.
