### ISSUE TITLE
Proper use of `theme replace` for specific theme

### ISSUE THREAD

**Issue by miloszivojinovic** [Shopify/themekit#525]
Please redirect me to the proper answer if there already is one.

Is this a valid command if I wanted to run _theme replace_ for a specific development theme environment (theme that is not live currently):
`theme replace -e=nameOfDevTheme
`

Thanks!

**Comment by tanema** [comment]
Yes you guessed it correctly, as long as `nameOfDevTheme` is defined in your config.yml and it has the appropriate theme ID then it will work like that. If you want to see more options on any command in themekit you can run `theme --help` or for a specific command use `theme replace --help` to give more contextual help messages.
