### ISSUE TITLE
Page reloads

### ISSUE THREAD

**Issue by malyi** [Shopify/themekit#527]
### What happened
Hi Guys, i am not sure that i am reporting in right branch but please try to fix the bug with Shopify admin:
I am using theme editor (web version in Shopify admin) and when i am creating new snippet whole page is reloading. There wasn't this bug before. Please fix it.

### What I expected to happen
When you create a new snippet there must be popup that snippet was created and new snippet tab become open

### Steps to reproduce
1. Open any Shopify store on any mac/Windows -- Firefox, Chrome
2. Go to Theme editor and open any snippet
3. Try to create new snippet

### My Environment

OS (including version): WIndows 10
Themekit version: it's web version (Shopify admin)
Ignore Files(if any):

**Comment by tanema** [comment]
Sorry this is the wrong place to report this issue, please contact shopify support.
