### ISSUE TITLE
Liquid Syntax error -- when there is no syntax error

### ISSUE THREAD

**Issue by alankimo** [Shopify/themekit#530]
### What happened
Theme kit give me this syntax error:
<img width="396" alt="captura de pantalla 2018-07-19 a la s 12 31 03" src="https://user-images.githubusercontent.com/7260466/42959949-12c8ce4a-8b50-11e8-8b45-7a182779ac9e.png">

But my code is this:
`{{ saw_variant_compare_at_price | minus: saw_variant_price | money | append: ' + IVA' }}`

And to theme kit work I need to do this:
`{{ saw_variant_compare_at_price |minus: saw_variant_price |money |append:' + IVA'}}`

Basicly erase all the gaps for filters and the final gap before "}}", then, theme kit works... and after I restore the gaps to get the original code line, save and... works, can somebody help me to avoid this ?

**Comment by alankimo** [comment]
Hi @tanema sorry for answer late.

- Nop, I don't copy & paste the line of code, in fact, the error always appears when I write the code.
- Sublime Text 3
- I figure out because is solved when I remove all the spaces and save.
- Spanish ISO

Thanks for the help :)

**Comment by tanema** [comment]
I have been looking into this but I cannot reproduce this. Can you see if you can reproduce this in the online editor? If this happens to you in the online editor, please open a support request with shopify.

**Comment by tanema** [comment]
I am going to close this since.
- it seems stale
- it is not an issue with themekit
- No one else has reported this issue

I have a feeling that for some reason you had some zero-width characters within your files and this was a fluke. If you have a way to reproduce this, please re-open
