### ISSUE TITLE
Confusing end of file error when I try to update files locally and have them sync with Shopify

### ISSUE THREAD

**Issue by mwgraziano** [Shopify/themekit#534]
### What happened

Working within the Atom IDE, when I make a change to any file within the theme, I get output similar to the following and no update occurs: 

![screen shot 2018-08-09 at 12 46 51 pm](https://user-images.githubusercontent.com/1749944/43913359-c345bc00-9bd2-11e8-9c0d-cd36ad243fe9.png)

### What I expected to happen

For the desired file to be updated and the change reflected both locally within the browser and on Shopify within the admin section.

### Steps to reproduce

1. Run slate via "npm run start:dev".
2. Make a local change in your favorite IDE.
3. Slate/Themekit attempts to sync and outputs failure.

### My Environment

OS (including version): macOS High Sierra 10.13.6
Themekit version: slate and slate-tools v0.14.0
Ignore Files(if any): node_modules, dist, deploy.log

**Comment by tanema** [comment]
If you use another editor, this does not happen? This happens on all file?

**Comment by mwgraziano** [comment]
It doesn't seem to matter what editor I use. I have been using Atom but also tried just manual changes with vi. Regardless of the file changed, the error is always the same - it complains about "themes/[theme_id]/assets.json".

**Comment by mwgraziano** [comment]
What is assets.json anyway? It's not a file within the theme code itself, so I'm not sure where it is coming from. The theme seems to build just fine locally.

**Comment by tanema** [comment]
I am not sure, that seems more related to slate and not themekit. Maybe you should open an issue on https://github.com/Shopify/slate

**Comment by mwgraziano** [comment]
Okay, thanks! I'll give that a try.

**Comment by tanema** [comment]
I think this will be taken care of by the Slate team and will have to be addressed when they update slate to the current version of themekit.
