### ISSUE TITLE
Pre-release v0.8.0 theme maxes computer resources

### ISSUE THREAD

**Issue by joshiefishbein** [Shopify/themekit#535]
### What happened
Pre-release v0.8.0 `theme` maxes computer CPU resources and maxes out battery energy impact:

<img width="746" alt="screen shot 2018-08-10 at 4 03 17 pm" src="https://user-images.githubusercontent.com/7484028/43979056-734bb980-9cb7-11e8-85b1-25918ab72ab2.png">
<img width="814" alt="screen shot 2018-08-10 at 4 04 21 pm" src="https://user-images.githubusercontent.com/7484028/43979057-735cbf00-9cb7-11e8-829b-b65719083c76.png">

I noticed this after I updated and ran `theme watch` and started updating files in my theme. Everything works as expected, it just sucks up a lot of energy and slows down my computer's UI responsiveness noticeably.

Full disclosure: my Mac is in the group of late-2016 MBPs that are suffering performance problems at the OS level, so this might not necessarily be themekit. But the only other programs that do this to my MBP are video editing applications, computer games, and Chrome when I have a million windows open. I've never felt this type of slowdown with task runners and watchers before.

### Steps to reproduce

1. `theme update --version=v0.8.0-prerelease`
2. `theme watch`
3. Open Activity Monitor

### My Environment

OS (including version): macOS 10.13.6 (High Sierra)
Themekit version: v0.8.0
Ignore Files(if any):
```yml
ignore_files:
  - "*.gif"
  - "*.jpg"
  - config/settings_data.json
  - src/
  - emails/
  - node_modules/
  - bower_components
  - bower.json
  - package.json
  - Gruntfile.js
  - theme.lock
```

**Comment by joshiefishbein** [comment]
That actually sounds familiar – but to my other experiences with this OS bug actually. In this scenario I'm only running `watch` and immediately editing files. No sleep involved here.

**Comment by tanema** [comment]
Oh holy hell, I did not have to test long to confirm this! 
![image](https://user-images.githubusercontent.com/463193/43980212-4d667788-9cbb-11e8-89d4-45661353637f.png)

I will definitely be looking into fixing this.

**Comment by joshiefishbein** [comment]
If nothing major changed in v0.8.0 that would be causing this, it could be related to #491

**Comment by tanema** [comment]
no, that kind of cpu usage indicate something has changed for sure. I will look into it.

**Comment by tanema** [comment]
Okay @joshiefishbein I found a the issue and fixed it. If you run `theme update --version=v0.8.0-prerelease` it will reinstall version 0.8.0 with the patch I just added.

**Comment by joshiefishbein** [comment]
FIXED 🎉 

<img width="645" alt="screen shot 2018-08-10 at 5 02 47 pm" src="https://user-images.githubusercontent.com/7484028/43981308-4cf16408-9cbf-11e8-81bb-77771bab9951.png">

**Comment by tanema** [comment]
Once again thanks for testing and doing this extra back & forth with me. It really is priceless. I don't get the luxury of error reporting and usage stats like normal applications.
