### ISSUE TITLE
Using themekit with npx needs 'npx shopify-themekit'

### ISSUE THREAD

**Issue by agentlewis** [Shopify/themekit#543]
### What happened
I decided to setup my library following the node pattern of making all dependencies local. Previously I have added the node_modules/.bin folder to my path. On this project I decided to start using 'npx' as it is a designed way of doing this. When I set this up I discovered 'npx theme' did not work and instead I needed to use 'shopify-themekit'

### What I expected to happen
'npx theme' would work

I realise this may be a result of the npm name 'theme' already being taken. So I am unclear how to resolve this. Plus its not exactly an urgent issue - work arounds are easy!

### Steps to reproduce

1. 'npm install --save-dev shopify-themekit
2. 'npx theme'

### My Environment
node 10.9.0
npm 6.4.0

OS (including version): Ubuntu mate 1.18.0
Themekit version: 0.6.12
Ignore Files(if any):

**Comment by agentlewis** [comment]
oh I feel so silly - never mind me: I didn't realise by using npx I was using the other [node-themekit](https://github.com/Shopify/node-themekit). Never mind I uninstalled it and switched to using this library :)

It could be worth updating node-themekit to give users a notice that active work is being done on this project instead.

Thank for the great work!

**Comment by tanema** [comment]
Hey! I am in the process of updating node-themekit! node-themekit is just a wrapper around this project thought.
