### ISSUE TITLE
Invalid environment error when attempting `theme deploy` on v.0.8.0

### ISSUE THREAD

**Issue by erickzhao** [Shopify/themekit#545]
### What happened

When upgrading Theme Kit to `v0.8.0`, I can't seem to get `theme deploy` to work.

This is the command I'm running from the `dist` folder of my theme, with my `config.yml` located in the parent folder.
```
$ theme deploy --nodelete --env development --config ../config.yml sections/article-template.liquid
invalid config invalid environment []: (missing password)
```

It seems to be reading my `config.yml` properly, as reading an invalid file path throws a completely different error. I also _do_ have my password inside the config, as it works on `0.7.5` just fine.

### What I expected to happen

I was running the same command in `0.7.5` but with `theme upload`, and it seemed to work.

```
$ theme upload --env development --config ../config.yml sections/article-template.liquid
An update for Themekit is available. To update please run `theme update`
[development]: 1 / 1 [====================================================================] 100 %
```
### Screenshot
![image](https://user-images.githubusercontent.com/16010076/44487667-d6f1bb80-a624-11e8-8f93-a3739306a505.png)

### Steps to reproduce

This is my folder structure:
```
my-theme
  |-- 📂dist
  |   |-- 📂sections
  |      |-- 📄 article-template.liquid
  |-- 📄 config.yml
```

1. Go into `/dist` folder
2. Run command.

### My Environment

OS (including version): macOS 10.13.6 (17G65) (High Sierra)
Theme Kit version: `0.8.0 darwin/amd64`

**Comment by tanema** [comment]
I merged a fix that will no longer validate the whole config on load but rather only validates the requested environments. This will be released in the `v0.8.1`
