### ISSUE TITLE
Existing files are being downloaded

### ISSUE THREAD

**Issue by efekurnaz** [Shopify/themekit#547]
### What happened
'theme download' code downloads all files each time I run it.

### What I expected to happen
Should only download modified files.

### My Environment

OS (including version): MacOS 10.13.6
Themekit version: 0.8.0
Ignore Files(if any):

**Comment by tanema** [comment]
The version checking/asset manifest has been removed in v0.8.0. For more information please refer to the discussion in this issue: https://github.com/Shopify/themekit/issues/540
