### ISSUE TITLE
Theme Deploy (without -n) Fails to Sync Files Randomly

### ISSUE THREAD

**Issue by mwtidd** [Shopify/themekit#548]
### What happened

While using 'theme deploy' found that assets that exist on my file system were not properly deployed to Shopify.

i.e. LIQUID ERROR (LINE 103): COULD NOT FIND ASSET SNIPPETS/HEADER-ICONS.LIQUID

I can confirm that header-icons.liquid exists on the file system.

Also prior to the deployment the file existed in Shopify

Also, it may be worth noting that the files that fail to upload vary from one run to the next.

Also 'theme deploy' has 495 actions and 'theme deploy -n' has 248 actions.

### What I expected to happen
All files on Shopify to be deleted and replaced with all of the files on my file system.

### Steps to reproduce

1. run 'theme deploy' without -n on windows 10
2. find files that were deleted from shopify but not replaced

### My Environment

OS (including version): Windows 10
Themekit version: 0.8.0
Ignore Files(if any): none

-----------------------------------------------------------------------------------------------

I understand that version checking has been removed, but the fact that previous versions defaulted to only delta deployments, the new default behavior can result in unintended deployments. This paired with the issue I ran into could lead to catastrophic results if run against a production theme.

**Comment by tanema** [comment]
> Also 'theme deploy' has 495 actions and 'theme deploy -n' has 248 actions.
Since this is exactly double the amount of actions this seems like there might be an issue with windows paths on deploy. 

Windows paths might be trying to remove `snippets/header-icons.liquid` while trying to upload `snippets\header-icons.liquid` I will have to check this, sorry for the inconvienience.

**Comment by tanema** [comment]
I have a PR to fix this and you can try out the fix by updating using:

```
theme update --version=v0.8.1-prerelease
```

You should see the deploy actions be more uniform now.

**Comment by mwtidd** [comment]
Tim, thanks for the quick turn around on this. I figured it would be an issue with my OS's training wheels.

I've confirmed the change resolved the issue I was seeing. Closing the issue.

**Comment by tanema** [comment]
@mwtidd Thanks for helping me debug this! The official release of v0.8.1 won't be for a while but that pre-release will be available for a while if you need to reinstall it or install it on another machine. Thanks again.
