### ISSUE TITLE
Does not gracefully handle when Shopify returns 404

### ISSUE THREAD

**Issue by csaunders** [Shopify/themekit#55]
The application crashes instead of simply printing out the error. When a 404 happens, still raise an error but include detailed information (error code, etc.)

/cc @stevebosworth

**Comment by csaunders** [comment]
Is this still an issue? Do you have any replication steps @stevebosworth?

**Comment by stevebosworth** [comment]
I have not seen it in a while so it's possible this is resolved.  I'm not sure how you'd trigger a 404 to check tho

**Comment by csaunders** [comment]
I found it. PR will be going up soon.
