### ISSUE TITLE
theme watch restarts when switching branches in Git

### ISSUE THREAD

**Issue by justinmetros** [Shopify/themekit#553]
### What happened
When I stopped my watcher and switched git branches in another window, my watcher started back up again. Have been using themekit since day one and first time seeing this issue. Just updated to 0.8.0.
 
### What I expected to happen
Stopping the watcher stops the watcher

### Steps to reproduce
1. Two terminal windows open. One for Git one for Themekit. `$ theme watch` then kill it:  ^C
2. Switch Branches in Git
3. Theme watch starts again and begins uploading files that were modified ( the now out of date ones )

### My Environment

OS (including version): macOS High Sierra 10.13.6
Themekit version: 0.8.0 darwin/amd
Ignore Files(if any): 
    - ".DS_Store"
    - "Thumbs.db"
    - ".Trashes"
    - config/settings_data.json

**Comment by tanema** [comment]
You stopped the watcher (ended the process) and then checked out another branch and the process restarted? :o

**Comment by justinmetros** [comment]
Exactly

**Comment by tanema** [comment]
Okay some follow up questions:
- Have you been able to do this more than once?
- What shell are you using?
- Are you confident that the command stopped? (themekit will restart the watch command if the config.yml has changes)

**Comment by justinmetros** [comment]
- yes
- Hyper 2.0.0
- yes, I got the normal prompt after stopping the watcher

I'm not sure how to best create a repro for something like this...

**Comment by tanema** [comment]
Okay I even downloaded hyper to try and recreate this and the only time I (*thought*) I recreated it was when I still had themekit running in the other terminal. 

One last follow up question, how can you tell it is still running? Does your command line continue to output? Do you check `top`?

**Comment by tanema** [comment]
Okay I have a PR that hopefully would solve this issue here https://github.com/Shopify/themekit/issues/553 

You can try it out and see if it solves your issue by updating to the v0.8.1-prerelease

```
theme update --version=v0.8.1-prerelease
```
