### ISSUE TITLE
Theme deploy erasing files but not uploading all files from local machine

### ISSUE THREAD

**Issue by Kavinci** [Shopify/themekit#556]
### What happened
When doing a `theme deploy` on an existing theme deletes files but does not deploy all files from local machine. After the deploy finishes, checking Shopify theme shows many missing files. Doing more deploys removes more and more files from the Shopify theme and deploying less and less files. I did try making changes to some files and deploying them and it seems to selectively not update some files. Using the `-nodelete` flag turned off the delete function and files are no longer missing but will likely leave unused files in Shopify.

### What I expected to happen
When running `theme deploy` the theme on Shopify should be deleted and the local copy should replace the Shopify theme leaving out the `ignore_files:` list.

### Steps to reproduce

1. `theme download` Download Shopify theme
2. `theme deploy` Deploy the local theme
3. Check Shopify preview for consistency

Note: This could be a size issue. Download count shows 290 and first deploy shows 533. During the second deploy count is 446 and checking Shopify shows more files are missing compared to first deploy.

### My Environment

OS (including version): Windows 10 Pro 10.0.16299
IDE: VS Code
Themekit version: Latest 0.8.0
Ignore Files(if any):

 - "*.map"
    - "*.origin"
    - ".gitignore"
    - "config.yml"
    - "package-lock.json"
    - "README.md"
    - "*.log"
    - "yarn.lock"
    - ".cache/*"
    - "node_modules/*"
    - "src/*"
    - "package.json"

**Comment by Kavinci** [comment]
Not sure if the output I am experiencing is helpful but I don't believe it is normal compared to the single line download bar.

Output for first deploy:
```
$ theme deploy
[development] 10s file is cri[development] 107|533 [===============>--------------------------------------------------------------]  20 %
[development] 120|533 [=================>------------------------------------------------------------]  23 %
[development] 139|533 [===================>----------------------------------------------------------]  26 %
[development] 142|533 [====================>---------------------------------------------------------]  27 %
[development] 144|533 [====================>---------------------------------------------------------]  27 %
[development] 210|533 [==============================>-----------------------------------------------]  39 %
[development] 261|533 [=====================================>----------------------------------------]  49 %
[development] 275|533 [=======================================>--------------------------------------]  52 %
[development] 533|533 [==============================================================================]  100 %
Done in 316.27s.
```

output of second deploy:
```
$ theme deploy
[development] 0|446 [------------------------------------------------------------------------------]  0 %
[development] 14|446 [=>----------------------------------------------------------------------------]  3 %
[development] 20|446 [==>---------------------------------------------------------------------------]  4 %
[development] 35|446 [=====>------------------------------------------------------------------------]  8 %
[development] 79|446 [=============>----------------------------------------------------------------]  18 %
[development] 102|446 [=================>------------------------------------------------------------]  23 %
[development] 116|446 [===================>----------------------------------------------------------]  26 %
                      is[development] 172|446 [=============================>------------------------------------------------]  39 %
[development] 305|446 [====================================================>-------------------------]  68 %
[development] 446|446 [==============================================================================]  100 %
Done in 228.83s.
```

**Comment by tanema** [comment]
Ah can you run `theme deploy -v` I think those stutters in your progress bar are errors and the bar outputs over top of them. I am trying to work on a fix for that, but don't have a solution yet.

The errors may be liquid errors, I have seen in the past some times when snippets are required but the snippet is not first uploaded then a liquid error would be returned from shopify.

**Comment by tanema** [comment]
Oh! Also there is currently a problem with windows deploys as referenced here: https://github.com/Shopify/themekit/issues/548

You can fix this by running:
```
theme update --version=v0.8.1-prerelease
```

Or reverting to 7.5 until the release of 8.1 by running 
```
theme update --version=v0.7.5
```

**Comment by Kavinci** [comment]
I did use the verbose flag when I was investigating and I believe the error was something along the lines of "File is important and removing it would cause theme to fail" but the verbose didn't output the file it was trying to delete. 

I did not encounter the windows path issue that was linked with missing dependancies.

I can try again and provide more details on Monday.

**Comment by Kavinci** [comment]
The verbose deploy looks like this:
`theme deploy -v`
```
[development] Updated assets/ProximaNova-Bold.woff2
[development] Deleted snippets/social-meta-tags.liquid
[development] Deleted assets/variables.js.liquid
[development] Deleted templates/customers/order.liquid
[development] this file is critical and removing it would cause your theme to become non-functional
[development] Updated snippets/product-image-srcset.liquid
[development] this file is critical and removing it would cause your theme to become non-functional
[development] Deleted snippets/contact-hero.liquid
[development] Deleted snippets/shappify-select.liquid
[development] Deleted assets/circle_bg.png
```

Unfortunately it doesn't tell me what file that is referring to and based on the count, 580, I do not think it is the file before or after it.

Which results in the development theme to throw errors of missing data (highlighted for clarity):

![image](https://user-images.githubusercontent.com/17324971/44659950-fcd7e100-a9d3-11e8-99bf-5289135894fe.png)

After further inspection of the verbose output it looks like the missing files were updated first and then deleted according to the order of the output tasks.

**Comment by tanema** [comment]
Did you try updating to the pre-release?

**Comment by Kavinci** [comment]
Not yet. I will try that next.

**Comment by Kavinci** [comment]
Looks like the pre-release has the issue fixed.
