### ISSUE TITLE
Can't upload theme, needs production password?

### ISSUE THREAD

**Issue by tmyie** [Shopify/themekit#557]
### What happened

I've run theme upload and theme watch, it hangs on 0% and never uploads any changes to the site. It says I need a password, but I don't have any for the production environment. I re-used the development password, but it obviously isn't working. 

### My Environment

OS (including version): Sierra 10.12.1 (16B2657)
Themekit version: Latest 
Ignore Files(if any): none

**Comment by tanema** [comment]
@tmyie can you try the pre-release of v0.8.1 by running `theme update --version=v0.8.1-prerelease` there was an issue with themekit validating all environments in the config file when it should only validating the one you want.

>but I don't have any for the production environment.
You don't have another environment called production in your config file?

**Comment by tanema** [comment]
I believe this is because of the improper validation on a whole config file. I will close this for now but please re-open if the prerelease does not work for you.
