### ISSUE TITLE
Watch re-uploads files when you commit in git

### ISSUE THREAD

**Issue by stevebosworth** [Shopify/themekit#56]
I noticed that themekit `watch` will re-upload all the files included in a git commit.

i.e. 
```
On branch feature-whatever
Your branch is up-to-date with 'origin/feature-whatever'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   layout/theme.liquid
        modified:   templates/search.liquid

no changes added to commit (use "git add" and/or "git commit -a")
```
```
git commit -m "updated some stuff" -a
```
will cause `theme.liquid` and `search.liquid` to be uploaded to your store.  I would expect this only to happen on save, not after committing changes in git.

**Comment by csaunders** [comment]
Idea:

- Watch for changes on the current branch if the theme is a git repo.
- When the theme changes kill all the watchers
- Stop all the workers
- Drain the job queue
- Invoke a replace of all the files
- Restart the workers
