### ISSUE TITLE
Regression on error reporting for `theme deploy` in version `0.8.0`

### ISSUE THREAD

**Issue by erickzhao** [Shopify/themekit#562]
### What happened

When an error is produced when uploading files to Shopify servers (via `theme deploy`), errors briefly flash on console before disappearing. A side effect is that the progress bar is duplicated upon erroring.

![screencast 2018-09-01 01-21-13](https://user-images.githubusercontent.com/16010076/44942677-8e08d800-ad85-11e8-915a-98299eb61cc9.gif)

Relevant frame from the above GIF showing the error message:

![image](https://user-images.githubusercontent.com/16010076/44942963-2fdef380-ad8b-11e8-8394-213b22f093fc.png)

### What I expected to happen

The error is shown on the console and stays there. Example output from `0.7.5`:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/16010076/44942655-fb683900-ad84-11e8-832f-ccb799e66752.png">

### Steps to reproduce
1. Have some kind of faulty file that the server can't process (in my case, I duplicated a schema setting ID in `sections/product.liquid`).
2. Run `theme deploy`.

The above screenshots were taken just by running `theme update` to switch between Theme Kit versions, without any changes to the files.

### My Environment

OS (including version): macOS High Sierra 10.13.6 (17G2208)
Theme Kit version: `0.8.0` and `0.8.1-prerelease`

**Comment by tanema** [comment]
Hey @erickzhao I have noticed that this was happening and am working on a fix. Thank you!
