### ISSUE TITLE
`theme download --no-ignore` no longer works

### ISSUE THREAD

**Issue by Schnouki** [Shopify/themekit#564]
### What happened

Trying to download an ignored file with `theme download --no-ignore <filename>` no longer works:

```
% grep -A3 ignore_file config.yml
  ignore_files:
    - assets/algolia_config.js.liquid
    - assets/manifest.json
    - config/settings_data.json

% theme download -e production --no-ignore config/settings_data.json
[production] Warning, this is the live theme on <SHOP_NAME>.
No file paths matched the inputted arguments
```

Surprisingly, `deploy` still works:

```
% theme deploy -e development --no-ignore config/settings_data.json
[development] 1|1 [==============================================================================]  100 %
```

### What I expected to happen

With ThemeKit 0.7.5 and the exact same configuration and command, my `config/settings_data.json` was downloaded. I'd expect the same thing to happen :)

### Steps to reproduce

1. Add `config/settings_data.json` to `ignore_files` in `config.yml`
2. Run `theme download --no-ignore config/settings_data.json`
3. Weep

### My Environment

OS (including version): Arch Linux (up-to-date)
Themekit version: 0.8.0, also reproduced with 526154d (compiled locally)
Ignore Files(if any):
```
  ignore_files:
    - assets/algolia_config.js.liquid
    - assets/manifest.json
    - config/settings_data.json
    - "\\.*"
    - /(#|~)$/
    - /\/\..*/
```

**Comment by tanema** [comment]
This will be fixed in the newest verison. You can try out the prerelease by updating using:

```
theme update --version=v0.8.1-prerelease
```

**Comment by Schnouki** [comment]
Okay, you fixed that *way* too quickly. Now you're making the rest of us developers look bad in comparison! :wink: 
But seriously, thanks a lot!
