### ISSUE TITLE
Themekit reverting code changes

### ISSUE THREAD

**Issue by ashanderie** [Shopify/themekit#567]
### What happened

Any updates to our code base through Themekit is seemingly reverted back to the previous state 1 - 2 hours later.

I can confirm this is happening because when checking the file "index.liquid" within the Shopify theme edit code functionality, there is version 162 (the new version) uploaded at 11:26 AM and the current version (the old code) uploaded seemingly now but without any changes on my computer.

My latest attempt to fix this issue is to replace the current versions with version 162 within the Shopify theme edit functionality and see what will happen. 

### What I expected to happen

Updated code to not get reverted!?

### Steps to reproduce

1. Theme watch
2. Made changes to code base
3. Changes are successfully updated
4. Checking 1 - 2 hours later, code is reverted back to the previous version

### My Environment

OS (including version): Windows 10 Pro 17134.228
Themekit version: 0.8.0 windows/amd64
Ignore Files(if any):

**Comment by tanema** [comment]
This is definitely not an issue with themekit unless you still have themekit running when all of this happens. Please open a ticket with shopify. Are you working in your own shop or as a contractor for a merchant? Is it possible that someone else is uploading changes? Are you changing git branches while themekit is running?

**Comment by ashanderie** [comment]
I've been using Themekit to commit all of our changes, including the ones mentioned above. I even copied and pasted the new code into Shopify directly as mentioned above as well. It seems that 30 - 40 minutes later, something reverts it back to the previous code!

There is no one else making changes to our site and I'm only running theme kit, so no git repos involved with this site.

**Comment by tanema** [comment]
> I even copied and pasted the new code into Shopify directly as mentioned above as well. It seems that 30 - 40 minutes later, something reverts it back to the previous code!

Please open a support ticket with Shopify, this seems to be a bug in your online store.

**Comment by ashanderie** [comment]
Okay, already did that. They are escalating this issue so we'll see what they say. I've been using Themekit for the past 2 years for this theme without any issues until now...
