### ISSUE TITLE
Themekit 0.8.0 not uploading files OS X 10.13.4

### ISSUE THREAD

**Issue by jasonbuehler** [Shopify/themekit#568]
### What happened
I am trying to use themekit to deploy my theme to a couple different shops, each time it shows what appears to be success but when I go to look at the files in Shopify admin my changes are not reflected. 

### What I expected to happen
When I use deploy it should upload my files.

### Steps to reproduce

1. Use homebrew to install themekit 0.8.0
2. try to deploy a theme using > theme deploy --env=development
3. sit back and scratch head as to why the changes didn't happen. :)

### My Environment

OS (including version): 10.13.4
Themekit version: 0.8.0 (homebrew)
Ignore Files(if any): config/settings_data.json, *.swp

**Comment by tanema** [comment]
Are you using a previously deploy config/theme?

**Comment by jasonbuehler** [comment]
Yes, do I need to recreate it with 0.8.0 or something?

**Comment by tanema** [comment]
No, what is the output of the command? Did you install 0.8.0 using homebrew or did you update it using themekit?

**Comment by tanema** [comment]
If there is no output at all and this is a fresh install, it may be that it was corrupted during install, can you try uninstalling it using homebrew and reinstalling it using the curl script?

```
curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python
```

**Comment by jasonbuehler** [comment]
I actually had to remove and reinstall homebrew not long ago, and so it was a fresh install of 0.8.0. I tried uninstalling that and using the script to no avail, here is the output:

```
~/workspace/sitspots_theme (master)* $ brew uninstall themekit
Uninstalling /usr/local/Cellar/themekit/v0.8.0... (3 files, 8.4MB)
~/workspace/sitspots_theme (master)* $ curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python
Password:
Fetching release data
Downloading version v0.8.0 of Shopify Themekit
Validated binary checksum
Theme Kit has been installed at /usr/local/bin/theme
To verify themekit is working simply type "theme"
~/workspace/sitspots_theme (master)* $ theme deploy config/settings_schema.json
[development] Warning, this is the live theme on sitspotsdev.
[development] 0|1 [------------------------------------------------------------------------------]  0 %
[development] 1|1 [==============================================================================]  100 %
```

**Comment by tanema** [comment]
okay please run `theme deploy config/settings_schema.json -v` it looks like there is an error but currently 0.8.0 ovewrites error output, a known bug.

**Comment by jasonbuehler** [comment]
Ah, ok, there is an error. So I need to pass the -v flag to see errors when they come up in 0.8.0? I can make that work until the bug is resolved. I verified that this worked, thanks for figuring it out!
