### ISSUE TITLE
theme deploy on ignored file

### ISSUE THREAD

**Issue by arjunbanker** [Shopify/themekit#569]
### What happened
I was deploying a file that was marked as ignore in config (basically, wanted to push settings_data to isolated dev store), but without the --no-ignore flag, and themekit appears to hang as follows. I figured it out, but the first time it happened, I was waiting for a few minutes, which is an opportunity for improvement.

 theme deploy -e storename config/settings_data.json 
[storename] Warning, this is the live theme on storename.
[storename] 0|1536183151 [------------------------------------------------------------------------------]  0 %
^C

config.yml:
...
 ignore_files:
  - config/settings_data.json

^^ note large int, non-increasing progress bar

### What I expected to happen
Error message indicating that the specific file is ignored and will not be deployed, and that the user should use the --no-ignore flag to force update

### Steps to reproduce

1.  add config/settings_data.json to ignore_files in config.yml
2. theme deploy -e storename config/settings_data.json 

### My Environment

OS (including version):mac os
Themekit version:
Ignore Files(if any):
 ignore_files:
  - config/settings_data.json

**Comment by tanema** [comment]
Hey this is a know bug and is fixed in the pre-release. Please update to the prerelease by running `theme update --version=v0.8.1-prerelease`

**Comment by tanema** [comment]
Closing because this is fixed
