### ISSUE TITLE
When using get theme im not getting any files but it look like its downloading

### ISSUE THREAD

**Issue by DMKITServices** [Shopify/themekit#571]
### What happened
i am trying to download my theme to my local HDD in E:\Shopify-Themes>
so i do the following command
E:\Shopify-Themes>theme get -p=password1 -s=site address -t=theme id  -v

i put in the -v to see what was going on 

[development] Successfully wrote assets/ajax-loader.gif to disk
[development] Successfully wrote assets/gift-card.js to disk
[development] Successfully wrote config/settings_schema.json to disk
[development] Successfully wrote assets/lazysizes.min.js to disk
[development] Successfully wrote assets/theme.js to disk
[development] Successfully wrote locales/en.default.json to disk
[development] Successfully wrote assets/theme.scss.liquid to disk
[development] Successfully wrote layout/password.liquid to disk
[development] Successfully wrote assets/vendor.js to disk
[development] Successfully wrote config/settings_data.json to disk
[development] Successfully wrote layout/theme.liquid to disk
[development] Successfully wrote locales/pt-PT.json to disk
[development] Successfully wrote locales/de.json to disk
[development] Successfully wrote locales/es.json to disk
[development] Successfully wrote locales/fr.json to disk
[development] Successfully wrote locales/it.json to disk
[development] Successfully wrote sections/collection-filters.liquid to disk
[development] Successfully wrote locales/ja.json to disk
[development] Successfully wrote sections/advanced-content.liquid to disk
[development] Successfully wrote sections/article-content.liquid to disk
[development] Successfully wrote locales/pt-BR.json to disk
[development] Successfully wrote sections/brand-list.liquid to disk
[development] Successfully wrote sections/footer.liquid to disk
[development] Successfully wrote sections/cart-template.liquid to disk
[development] Successfully wrote sections/columns.liquid to disk
[development] Successfully wrote sections/featured-articles.liquid to disk
[development] Successfully wrote sections/map.liquid to disk
[development] Successfully wrote sections/gallery.liquid to disk
[development] Successfully wrote sections/featured-collections.liquid to disk
[development] Successfully wrote sections/header.liquid to disk
[development] Successfully wrote sections/featured-content.liquid to disk
[development] Successfully wrote sections/featured-product.liquid to disk
[development] Successfully wrote sections/image-content.liquid to disk
[development] Successfully wrote sections/link-block.liquid to disk
[development] Successfully wrote sections/featured-products-subsection.liquid to disk
[development] Successfully wrote sections/list-collections-template.liquid to disk
[development] Successfully wrote sections/featured-products.liquid to disk
[development] Successfully wrote sections/password-header.liquid to disk
[development] Successfully wrote sections/search.liquid to disk
[development] Successfully wrote sections/newsletter.liquid to disk
[development] Successfully wrote sections/product-template.liquid to disk
[development] Successfully wrote sections/password-content.liquid to disk
[development] Successfully wrote sections/quotes.liquid to disk
[development] Successfully wrote sections/password-footer.liquid to disk
[development] Successfully wrote snippets/drawer-nav.liquid to disk
[development] Successfully wrote sections/rich-text.liquid to disk
[development] Successfully wrote sections/slideshow.liquid to disk
[development] Successfully wrote snippets/collection-grid-item.liquid to disk
[development] Successfully wrote snippets/collection-list-item.liquid to disk
[development] Successfully wrote sections/video.liquid to disk
[development] Successfully wrote snippets/comment.liquid to disk
[development] Successfully wrote snippets/bgset.liquid to disk
[development] Successfully wrote snippets/icon-arrow-up.liquid to disk
[development] Successfully wrote snippets/icon-close.liquid to disk
[development] Successfully wrote snippets/icon-arrow-down.liquid to disk
[development] Successfully wrote snippets/icon-bag.liquid to disk
[development] Successfully wrote snippets/icon-arrow-left.liquid to disk
[development] Successfully wrote snippets/icon-cart.liquid to disk
[development] Successfully wrote snippets/icon-arrow-right.liquid to disk
[development] Successfully wrote assets/ico-select.svg.liquid to disk
[development] Successfully wrote snippets/icon-arrow-thin-right.liquid to disk
[development] Successfully wrote snippets/icon-arrow-thin-left.liquid to disk
[development] Successfully wrote snippets/icon-plus.liquid to disk
[development] Successfully wrote snippets/icon-instagram.liquid to disk
[development] Successfully wrote snippets/icon-pinterest.liquid to disk
[development] Successfully wrote snippets/icon-pin.liquid to disk
[development] Successfully wrote snippets/icon-facebook.liquid to disk
[development] Successfully wrote snippets/icon-play.liquid to disk
[development] Successfully wrote snippets/icon-lock.liquid to disk
[development] Successfully wrote snippets/icon-hamburger.liquid to disk
[development] Successfully wrote snippets/icon-shopify-logo.liquid to disk
[development] Successfully wrote snippets/icon-minus.liquid to disk
[development] Successfully wrote snippets/icon-quote.liquid to disk
[development] Successfully wrote snippets/icon-rss.liquid to disk
[development] Successfully wrote snippets/icon-pause.liquid to disk
[development] Successfully wrote snippets/icon-search.liquid to disk
[development] Successfully wrote snippets/icon-vimeo.liquid to disk
[development] Successfully wrote snippets/product-card.liquid to disk
[development] Successfully wrote snippets/no-blocks.liquid to disk
[development] Successfully wrote snippets/icon-snapchat.liquid to disk
[development] Successfully wrote snippets/social-meta-tags.liquid to disk
[development] Successfully wrote snippets/icon-youtube.liquid to disk
[development] Successfully wrote snippets/icon-tumblr.liquid to disk
[development] Successfully wrote snippets/icon-twitter.liquid to disk
[development] Successfully wrote templates/blog.liquid to disk
[development] Successfully wrote templates/404.liquid to disk
[development] Successfully wrote templates/article.liquid to disk
[development] Successfully wrote snippets/social-sharing.liquid to disk
[development] Successfully wrote templates/customers/addresses.liquid to disk
[development] Successfully wrote templates/collection.liquid to disk
[development] Successfully wrote templates/customers/account.liquid to disk
[development] Successfully wrote templates/cart.liquid to disk
[development] Successfully wrote templates/gift_card.liquid to disk
[development] Successfully wrote templates/password.liquid to disk
[development] Successfully wrote templates/page.liquid to disk
[development] Successfully wrote templates/customers/order.liquid to disk
[development] Successfully wrote templates/search.liquid to disk
[development] Successfully wrote templates/list-collections.liquid to disk
[development] Successfully wrote templates/customers/login.liquid to disk
[development] Successfully wrote templates/product.liquid to disk
[development] Successfully wrote templates/page.contact.liquid to disk
[development] Successfully wrote templates/customers/register.liquid to disk
[development] Successfully wrote snippets/site-nav.liquid to disk
[development] Successfully wrote snippets/image-width.liquid to disk
[development] Successfully wrote templates/customers/activate_account.liquid to disk
[development] Successfully wrote templates/customers/reset_password.liquid to disk
[development] Successfully wrote templates/index.liquid to disk

### What I expected to happen
i expect the files to appear in E:\Shopify-Themes but there is noting there
are they going elsewhere??

### My Environment

OS windows 10 64bit
Themekit version: ThemeKit 0.8.0 windows/amd64
Ignore Files(if any):NA

**Comment by tanema** [comment]
A few questions to help figure this out.

- Do you have a directory config either on a config file or an environment variable called THEMEKIT_DIRECTORY
- Do you have full access to this directory? If you run your command line as administrator, does this succeed?

**Comment by DMKITServices** [comment]
i think i found it .
it seems to have uploaded it to my c drive in 
C:\VTRoot\HarddiskVolume25\Shopify-Themes\dmk-trans-am

i didn't want it there.
how do i make it go to my E:\Shopify-Themes

**Comment by tanema** [comment]
themekit would not place any files anywhere unless told. Please check your config for any directory setting. Or is it possible that `C:\VTRoot\HarddiskVolume25` is a mounting point for your E drive, because it can't be a coincidence that the `Shopify-Themes` directory exists there. Themekit would not create that directory

**Comment by tanema** [comment]
@DMKITServices Did you figure out why your files went to an unexpected place?

**Comment by tanema** [comment]
Closing because it seems like this was a configuration or environment issue and not an issue with themekit.
