### ISSUE TITLE
Specifying flags through command line and env variables still requires a config.yml 

### ISSUE THREAD

**Issue by samkim** [Shopify/themekit#578]
### What happened
Tried to issue `download` and `deploy` commands by specifying credentials through command line args as well as environment variables without a config.yml file but commands failed with error:
   > Could not find config file at ..

Calling an initial `get` creates a config.yml but looking to issue commands without doing this.

### What I expected to happen
The cli would use the given credentials without checking for the existence of a config.yml file.

### Steps to reproduce

1. From a directory without a config.yml file, specify password, store url, and theme id as command line flags.
2. Setting the corresponding environment variables results in the same error.

### My Environment

OS (including version): Mac OS Sierra 10.12.6
Themekit version: ThemeKit 0.8.1 darwin/amd64
Editor (including version): vim 8.1 
Ignore Files(if any): None

**Comment by tanema** [comment]
Okay, this is a regression, themekit should allow a configless setup.

**Comment by tanema** [comment]
What version were you using before? Was it a 0.6x series or 0.7.x series because it seems like the 0.7.x would have this same problem as well.

**Comment by tanema** [comment]
Okay so I can run `theme get -p=[password] -s=[store] -t=[theme_id]` without a config but I cannot run deploy without a config file.

**Comment by tanema** [comment]
@samkim Okay I have a PR to handle this. Please install it and test it by running `theme update --version=v0.8.2-prerelease`

**Comment by mathieuforest** [comment]
Any ETA for v0.8.2? And is node-themekit will be updated too?

Thanks!

**Comment by tanema** [comment]
@mathieuforest I am not sure I will release until the new year. This because the next release will have to be a v1.0.0 release because of breaking changes and right now I am sure plenty of shops are changing their themes for Christmas traffic. I do not want to interrupt that flow. When I release that version though I will check with the team that maintains node-themekit as well to see if they would like to update to that version.
