### ISSUE TITLE
Directory config is not working in v1.0.0-pre

### ISSUE THREAD

**Issue by stewartknapman** [Shopify/themekit#600]
**Describe the bug**
Running theme watch, with a directory set in config.yml, will not push changes when files inside the directory are updated.

**To Reproduce**
1. Set directory in config.yml i.e. `directory: theme/`
2. Run `theme watch`
3. Save any file inside the theme directory

**Expected behavior**
Updated files will be pushed.

**Environment (please complete the following information):**
- ThemeKit 1.0.0 darwin/amd64

**Additional context**
Workaround: moving the theme files outside of the directory into the root level.

**Comment by tanema** [comment]
Heya! I am aware of this and have a fix in the same branch that I am fixing the watching command in. If this is blocking you currently, let me know and I can get that fix into the 1.0.0-pre sooner.

**Comment by stewartknapman** [comment]
No rush, I just came across it is all. Most of our projects don't use this anyway.
Cheers!
