### ISSUE TITLE
Arrays in settings_data.json

### ISSUE THREAD

**Issue by hoghug** [Shopify/themekit#605]
I  wrote this to Shopify support, but I figure this is worth trying here. 

I've noticed what I think is a bug in the settings_data.json file, maybe its a Theme Kit issue. This is a big issue for us since I use the settings_data.json to store arrays of templates, used to exclude/include certain content, whether or not the current page template is in a list. This has stopped working for me all of a sudden, and its being inconsistent. It might be something that Theme Kit doesn't like the settings_data.json to store anything other than a simple string as a value. 

This is a long screen capture, I'm just trying to demonstrate how manipulating settings_data.json either from my local text editor, or within the Shopify theme editor produces different results.

https://www.useloom.com/share/645b500f25ea4c6ab702c3533ddf0928

1. settings_data.json has an array, "exclude_ss_tags", in the "current" settings.
2. Save settings_data.json with Theme Kit watching, updates on server
3. There is a block on the template just to simply output the "settings.exclude_ss_tags"
4. Nothing shows. And when using the Shopify theme file editor, that key/value pair isn't even on the file.
5. Manually copy+paste "exclude_ss_tags" into settings_data.json using the Shopify theme file editor.
6. Refresh the page. The array is outputted as just a string on the page. That' fine, its outputting something.
7. Go back to my text editor, with Theme Kit watching, save settings_data.json to trigger an update
8. Refresh the page, the array as a string is now gone. Also gone from the settings_data.json while viewed in the Shopify theme file editor. 

I could store the array as a long string (I did this before) since JSON does not allow for line breaks, and I try my best to keep this file organized and neat. If there are alternative solutions, I'm all ears, but I do believe this to be some sort of bug because it has been something that has worked in the past for me.

**Environment:**
 - OS: macOS 10.14
 - Themekit version: 0.8.1
 - Editor: Sublime 3

**Comment by hoghug** [comment]
This is what I got back from a Plus Support FED

```
I understand you're having trouble getting some data you'd like to access as an array in the theme code to save to the settings_data.json file. It seems to save if you add the array data within the theme editor, but outputs as a string on the storefront. If you add the array via ThemeKit, it seems to get validated out before the update reaches the theme.

This is expected: apart from the arrays setting up the homepage sections, the data types that are valid for settings data are strings, numbers, and booleans.
```

**Comment by tanema** [comment]
Okay so it seems like it is an API validation, and they are saying that you are not able to use arrays in your settings_data.json? Maybe you can you a comma delimited string?

This does, however, seem like it is not a themekit bug but rather an (expected?) validation on the APIs. Did support mention how that isn't really consistent and if anything is being done about that?

**Comment by hoghug** [comment]
They mentioned the same solution of a comma delimited string, which I've done before, the issue is we have some VERY LONG lists, so having them on their own line made legibility much easier.

Its just odd that they won't validate it since it can be inputted with the shopify file editor. But I'll make a push for that to be changed.


<img width="432" alt="screen shot 2019-01-08 at 4 05 21 pm" src="https://user-images.githubusercontent.com/6405882/50866589-59bead00-135f-11e9-9587-e15956c112e3.png">

**Comment by hoghug** [comment]
Shopify FED was able to problem solve. They copied our theme and added an array to `settings_data.json`, it worked. 

https://screenshot.click/08-58-1phvs-t0wgy.mp4

I'm in the process of removing all my arrays and re-adding them 1 by 1 to see where the issue is. But so far, after adding 1, Theme Kit was able to correctly upload my `settings_data.json` file.
