### ISSUE TITLE
Polyfilling

### ISSUE THREAD

**Issue by umxr** [Shopify/themekit#606]
how do you polyfill theme kit so that you can use es6/es7 in older browsers

**Comment by tanema** [comment]
Hey, @umxr this isn't really a question for themekit. Themekit is really only a tool to get your files to and from Shopify. If however, you are using [slate](https://github.com/shopify/slate) I believe they provide a lot of that functionality for you. Slate is really just a wrapper around themekit with tooling and project structure already laid out for you. If you are just starting with theme development I recommend starting with slate.
