### ISSUE TITLE
Downloading to windows 10

### ISSUE THREAD

**Issue by Hamaerox** [Shopify/themekit#615]
When trying to follow the initial steps given for the installation guide under the readme at:https://shopify.github.io/themekit/#linux--macos

The procedure for actually installing on a windows 10 computer varies from the specified instructions.

**To Reproduce**
Try following the steps for installing on windows. If followed step by step you will see upon trying to load the exe file in theme kit, it does nothing as a few of the steps cannot be completed.

**Expected behavior**
Theme kit to work propperly

**Additional context**
Very easily fix if you look around in a few other files/places but uncommon for a traditional user and may confuse others.

**Comment by tanema** [comment]
Hey @Hamaerox, Thank you for this issuse, I have heard rumours but no one opened an issue. Can you explain what exactly varies for the specific instructions? Where the problems arise?

**Comment by tanema** [comment]
Closing as duplicate of https://github.com/Shopify/themekit/issues/618 because it has more detail

**Comment by Allin1Services** [comment]
Mine has more detail. What other info can I give you?
