### ISSUE TITLE
Using the notify flag does not create or update the target file

### ISSUE THREAD

**Issue by NikolaDonchev** [Shopify/themekit#616]
**Describe the bug**
Trying to use the notify flag to generate the update file

**To Reproduce**
1. run command 'theme watch -e [something] --notify=/tmp/theme.update' 

**Expected behavior**
A file to be created that will update on a file change. Even if I manually create the file - still nothing.

**Environment (please complete the following information):**
 - OS: macOS 10.14.3
- Themekit version: v1
 - Editor: VS Code

**Comment by tanema** [comment]
This may be because of your permissions on that file/folder. You can run this example for yourself

- start `theme watch --notify=notify.txt`
- in another terminal run `fswatch -o notify.txt` in the same directory as your theme
- change a file in your theme.

**Comment by NikolaDonchev** [comment]
Hi @tanema, this unfortunately doesn't help. The file gets created successfully but nothing gets updated. No difference even if I change the permissions of the file.

**Comment by tanema** [comment]
Did you try using fswatch like my example? fswatch I believe comes standard on OSX so you should be able to do so without installing anything. The file only gets touched, this means only timestamps are changing, is there something else that you are expecting?

**Comment by tanema** [comment]
What are you using to watch the notify file? It wouldn't happen to be gulp, would it? We have another issue open here #607 where other users have experienced problems with gulp not picking up changes because gulp no longer watched timestamps.

**Comment by NikolaDonchev** [comment]
Hi @tanema many thanks for the replies! I am luckily not using gulp anymore, only webpack. I got it to work, had some permission issues. Thanks again!
