### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by darylknight** [Shopify/themekit#617]
**Describe the bug**
I'm setting up ThemeKit locally for the first time to start working with Shopify. Following the guide at https://www.shopify.com/partners/blog/95401862-3-simple-steps-for-setting-up-a-local-shopify-theme-development-environment, the very first step is to run this command:

`curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python`

That gives this error:

```
darylknight:Sites darylknight$ curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python
Password:
  File "<stdin>", line 1
    404: Not Found
       ^
SyntaxError: invalid syntax
```

**To Reproduce**
1. run `curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python`

**Expected behavior**
ThemeKit should be installed

**Environment (please complete the following information):**
 - OS [e.g. iOS]: MacOS 10.14.3
- Themekit version [e.g. v0.7.5]: Unknown
 - Editor [e.g. atom, sublime]: Didn't get that far.

**Comment by tanema** [comment]
Thanks for pointing that out, I will have someone update the install script. The most up to date instructions can be found on our doc site https://shopify.github.io/themekit/

`curl -s https://shopify.github.io/themekit/scripts/install.py | sudo python`

**Comment by tanema** [comment]
I have updated the blog post. Thanks again for pointing it out!

**Comment by darylknight** [comment]
No worries - thanks for updating. Just FYI, looks like you've got a syntax error there now that's breaking the article formatting:

![image](https://user-images.githubusercontent.com/1250017/54192411-8a86a400-44c0-11e9-9504-79540e3f1a30.png)

**Comment by tanema** [comment]
Thanks again @darylknight another wysiwyg editor strikes again!
