### ISSUE TITLE
ThemeKit Download in PowerShell Windows 10

### ISSUE THREAD

**Issue by Allin1Services** [Shopify/themekit#618]
We are using Windows 10 (64 bit) 
Opening up Powershell ISE and Powershell ISE (x86) As Admin then copying the link for 
Windows Automatic Powershell Installation from https://shopify.github.io/themekit/ will not give anything but an error:

PS C:\Windows\system32> (New-Object System.Net.WebClient).DownloadString("https://shopify.github.io/themekit/scripts/install.ps1") | powershell -command -
Exception calling "DownloadString" with "1" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."
At line:1 char:1
+ (New-Object System.Net.WebClient).DownloadString("https://shopify.git ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
I have ran out of ideas on how to fix this or download theme. The manual way of downloading theme has too little of instructions. Can you please help? I really need this installed.

**Comment by tanema** [comment]
Hey thanks for logging this. If you are stuck by this you can use the manual installation instructions here: https://shopify.github.io/themekit/#windows-installation

Can you explain where you get stuck on the manual installation instructions? That will help me make those better as well.

- create the folder `C:\Program Files\Theme Kit`
- download themekit from a link in the [manual installations](https://shopify.github.io/themekit/#manual-installation)
- put that `theme.exe` file into `C:\Program Files\Theme Kit`
- You will then need to add ``C:\Program Files\Theme Kit` to you `PATH` environment variable. You can find really [in-depth instructions here](https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/)
- Then  open cmd.exe and type in `theme` to ensure that it is installed

I am looking at solutions for making this easier, thank you for your patience.

**Comment by Allin1Services** [comment]
Thank you

**Comment by Hamaerox** [comment]
The in-depth instructions are the correct way to do it on windows 10 for the environment variable. In my previous post that was sinced closed that is the issue. The environemtn variable placement was different then the instructions

**Comment by tanema** [comment]
Okay thanks I have updated our manual instructions to include the link I used previously since it seems to explain it in a very thorough and successful way. I am working on a chocolatey package now which is slow going however since I am working on a VM.

**Comment by tanema** [comment]
Okay, I have submitted a chocolatey package for review. I will close this issue if/when it gets approved and is installable.

**Comment by Aly-76** [comment]
I tried installing via Powershell and experienced the same error. I only tried the Powershell installation as the manual installation isn't working for me either (Windows 10)

**Comment by tanema** [comment]
Please see the above conversation about what is being done. Thank you.

**Comment by Aly-76** [comment]
The instructions in the link didn't work https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/

**Comment by tanema** [comment]
@Aly-76 did you restart your shell after adding the environment variable?

**Comment by tanema** [comment]
Themekit has now been approved by chocolatey, it is now installable with the choco command. Please refer to the the documentation for more.

**Comment by Aly-76** [comment]
Yes I restarted my terminal however, I am still experiencing issues trying to install Theme Kit on Windows

Microsoft Windows [Version 10.0.17134.648]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Aly>"C:\Program Files\Theme Kit\theme.exe"
Theme Kit is a tool kit for manipulating shopify themes

Theme Kit is a fast and cross platform tool that enables you to build shopify themes with ease.

Complete documentation is available at https://shopify.github.io/themekit/

Usage:
  theme [command]

Available Commands:
  configure   Create a configuration file
  deploy      deploy files to shopify
  download    Download one or all of the theme files
  get         Get a theme and config from shopify
  help        Help about any command
  new         New will create theme using Shopify Timber
  open        Open the preview for your store.
  publish     publish a theme
  remove      Remove theme file(s) from shopify
  update      Update Theme kit to the newest version.
  version     Print the version number of Theme Kit
  watch       Watch directory for changes and update remote theme

Flags:
  -c, --config string              path to config.yml (default "C:\\Users\\Aly\\config.yml")
  -d, --dir string                 directory that command will take effect. (default current directory)
  -e, --env stringArray            environment to run the command (default [development])
  -h, --help                       help for theme
      --ignored-file stringArray   A single file to ignore, use the flag multiple times to add multiple.
      --ignores stringArray        A path to a file that contains ignore patterns.
      --no-ignore                  Will disable config ignores so that all files can be changed
      --no-update-notifier         Stop theme kit from notifying about updates.
  -p, --password string            theme password. This will override what is in your config.yml
      --proxy string               proxy for all theme requests. This will override what is in your config.yml
  -s, --store string               your shopify domain. This will override what is in your config.yml
  -t, --themeid string             theme id. This will override what is in your config.yml
      --timeout duration           the timeout to kill any stalled processes. This will override what is in your config.yml
      --vars string                path to an file that defines environment variables
  -v, --verbose                    Enable more verbose output from the running command.

Use "theme [command] --help" for more information about a command.

C:\Users\Aly>theme version
'theme' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Aly>

**Comment by tanema** [comment]
@Aly-76 if you do not have success with setting up your own PATH evironment variable please use the chocolatey package to install `choco install themekit`

**Comment by Aly-76** [comment]
I just installed Choco .. seems I dont have a sweet enough tooth as I hit errors

Progress: Downloading themekit 1.0.0... 100%
themekit not installed. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\themekit\tools' is denied.
themekit package files install completed. Performing other installation steps.
The install of themekit was NOT successful.
themekit not installed. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\themekit\tools' is denied.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 Access to the path 'C:\ProgramData\chocolatey\lib-bad' is denied.
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 Access to the path 'C:\ProgramData\chocolatey\lib-bad' is denied.
Maximum tries of 3 reached. Throwing error.
Cannot create directory "C:\ProgramData\chocolatey\lib-bad". Error was:
System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\chocolatey\lib-bad' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at chocolatey.infrastructure.filesystem.DotNetFileSystem.<>c__DisplayClass64.<create_directory>b__63()
   at chocolatey.infrastructure.tolerance.FaultTolerance.<>c__DisplayClass1.<retry>b__0()
   at chocolatey.infrastructure.tolerance.FaultTolerance.retry[T](Int32 numberOfTries, Func`1 function, Int32 waitDurationMilliseconds, Int32 increaseRetryByMilliseconds, Boolean isSilent)
   at chocolatey.infrastructure.filesystem.DotNetFileSystem.create_directory(String directoryPath)
   at chocolatey.infrastructure.filesystem.DotNetFileSystem.create_directory_if_not_exists(String directoryPath, Boolean ignoreError)
Access to the path 'C:\ProgramData\chocolatey\lib-bad' is denied.

C:\Users\Aly>

**Comment by Aly-76** [comment]
My mistake needed to ensure I was running my cmd as administrator https://www.thewindowsclub.com/how-to-run-command-prompt-as-an-administrator

**Comment by Aly-76** [comment]
Really appriciate your help :) Thank you for your patient.
