### ISSUE TITLE
Configuration File Issue

### ISSUE THREAD

**Issue by bman-80stees** [Shopify/themekit#62]
I set up this following the instructions, but for whatever reason, it will not accept my config.yml file. It keeps asking me to confirm something and I click yes and it fails. Please see the screen capture of this error. Can you direct me on how to overcome this issue? Am I missing something? Thanks!
![themekit-error-config file](https://cloud.githubusercontent.com/assets/6884590/9416731/6bb7caa0-4815-11e5-9229-0baebbc79b2e.jpg)

I'm using Windows 7 and downloaded the most recent x64 version of ThemKit from the website.

**Comment by bman-80stees** [comment]
Here is a screen capture of my configuration file:
![config-file-theme-kit](https://cloud.githubusercontent.com/assets/6884590/9417081/8483157e-4817-11e5-9810-aabbf1b99b0b.JPG)

**Comment by csaunders** [comment]
We've figured out the bug. You need a `development` environment. Add an empty or jokes key to your YAML and it will work.

I'll have a patch that fixes this up in the next release. Sorry about that :(

**Comment by bman-80stees** [comment]
Thanks!  I had figured that may have been the issue.
