### ISSUE TITLE
Themekit modify my config directory

### ISSUE THREAD

**Issue by IllidanMalar** [Shopify/themekit#621]
**Describe the bug**
When i execute "theme get -e dev" themekit rewrite my config.yml directory setting relative path with an absolute path. This behaviour make impossible to share my config with other user. 

**To Reproduce**
1. Set relative directory in config.yml (Es. **directory: prod**)
2. Execute "theme watch -e prod"
3. You'll find something like this: **directory: /Users/someUser/Documents/Shopify/someStore/prod**

**Expected behavior**
The line directory in the config.yml should remain unmodified.

**Environment (please complete the following information):**
 - OS: macOS Mojave vers.10.14.3
- Themekit version: v1.0.0
 - Editor: shell
 - Ignore:

**Comment by tanema** [comment]
If want to specify a directory then you should specify it with the `--dir` flag, `theme get` assumes that you are creating a new theme in that environment so it will use all the config you pass into the command to write to your config file. Otherwise it will use default settings.

**Comment by tanema** [comment]
Oh I see the problem now, I am saving absolute paths, sorry about the confusion. I can fix that! Thanks for the report!

**Comment by IllidanMalar** [comment]
Great great job!

**Comment by tanema** [comment]
1.0.1 has been released today and this was fixed in that release
