### ISSUE TITLE
'File' Contains Illegal Characters

### ISSUE THREAD

**Issue by justinmetros** [Shopify/themekit#622]
**Describe the bug**
Themekit skips files with the `~` charachter in them.

We use Slate to build our theme. ( And very sad to see that project is on ice ). 

`slate-tools deploy` has been failing a lot recently - giving tons of random '500 Internal Server Errors' when deploying.

Slate does create a config.yml matching the environment the build is in. So the backup plan was to: `cd dist && theme deploy`

This works well, no more 500 errors, but it gives an error on js bundles created by slate:

Example:
`[development] (assets/vendors~layout.theme.js) "assets/vendors~layout.theme.js" contains illegal characters`

**To Reproduce**
1. Build a theme out with `slate-tools deploy`
2. cd to dist directory
3. Run `theme deploy`

**Expected behavior**
Allow the `~` character generated by Shopify Slate

**Environment (please complete the following information):**
 - MacOS v10.14.2
- Themekit version: Latest ( 1.0.0 )
 - Editor: VS Code
 - Ignore: config/settings)data.json

**Additional context**
Since `slate-tools deploy` is failing, Themekit is a logical fallback. But refactoring Slate to change that character ( webpack default ) would be less than ideal.

**Comment by tanema** [comment]
This might be something I will have to talk to the Slate team about. I am not sure what the tilde is meant for but slate uses Themekit for uploading files so everything should work unless they are doing some sort of pre-processing. Thanks for opening the issue.

**Comment by justinmetros** [comment]
A bit more info, because I'm no webpack expert. 

When using Webpack's [SplitChunksPlugin](https://webpack.js.org/plugins/split-chunks-plugin/) for multi-page/multi-entrypoint configs, the `~` is the default separator. 

Info on it [here from Webpack readme](https://github.com/webpack/webpack/blob/master/examples/many)

Example from the output in readme that Themekit trips up on:
```
Entrypoint pageA = vendors~pageA~pageB~pageC.js vendors~pageA.js pageA~pageD~pageF.js pageA.js
Entrypoint pageB = vendors~pageA~pageB~pageC.js vendors~pageB.js pageB.js
Entrypoint pageC = vendors~pageA~pageB~pageC.js vendors~pageC.js pageC.js
```

The SplitChunks Plugin has as config for [automaticNameDelimiter](https://webpack.js.org/plugins/split-chunks-plugin/#configuration) but I don't see that exposed via any of the [Slate config files](https://shopify.github.io/slate/docs/slate-configuration). Which means forking and manually changing which is bad news bears for creating reliable installs.

Appreciate the assistance.

**Comment by tanema** [comment]
So I have confirmed that it is actually Shopify that is returning the error and even if you try and create a file in the web editor with the same character you will get the same error message. I assume this was not a problem in slate because it would compile all of your JS into a single file with a legal name, correct?

**Comment by justinmetros** [comment]
Ah, yes you are totally correct
 
When running `slate-tools` start - it starts an express server and creates the files with `~` in them, but they are served locally. 

On `slate-tools build` it generates the optimized files and then it works no problem. 

Will close this as it's a non-issue. Thank you for taking the time to look!
