### ISSUE TITLE
Themekit changing config.yml

### ISSUE THREAD

**Issue by IllidanMalar** [Shopify/themekit#630]
**Describe the bug**
When i execute "theme get -e someEnv" themekit rewrites my config.yml stripping away my comments, my empty lines and reordering my envs.

**To Reproduce**
1. set a config.yml with envs, empty lines and comments
2. execute "theme get -e someEnv"
3. look the new config.yml it's changed!

**Expected behavior**
If the config.yml is correct i think themekit should leave it unmodified.

**Environment (please complete the following information):**
- **OS**: macOS Mojave vers.10.14.3
- **Themekit version**: v1.0.0
- **Editor**: shell

**Comment by tanema** [comment]
I am sorry, I can't do anything about this. There is currently no yml parser or json parser that preserves comments and whitespace, at least not in go and I know from personal experience that there is limited support for these things in ruby as well. This is just something that I cannot support.

**Comment by IllidanMalar** [comment]
If I can ask a question, my doubt is this:

why "get" rewrite the config.yml file even if there are no errors?
Some commands like "watch" or "download" seems to read the config without modifying it, couldn't it be the same for the "get" command?

I'm probably not considering something, but if it were possible it would be a useful optimization.

Thank you!

**Comment by tanema** [comment]
Part of `theme get`s concern is ensuring your have a config and it is valid then writing it if it has any update. If you are just pulling down files you can run `theme download`

**Comment by tanema** [comment]
I am going to close this since I don't have an action item on this. `theme get`s behaviour in changing the config is documented in `theme get --help` and should be expected. If you think there is another way I can support you please either reopen or open a new issue. Cheers!
