### ISSUE TITLE
Change in subdirectory does not trigger upload of built asset during theme watch

### ISSUE THREAD

**Issue by colinmeinke** [Shopify/themekit#634]
This is an issue with Themekit v1.0.0, reverting to v0.8.1 fixes this issue. My guess is the issue was introduced in https://github.com/Shopify/themekit/pull/601.

I run my build process with Gulp. It takes the entry file at `/src/app.scss` and generates `/assets/app.css`, which is used in my `theme.liquid` template.

Directory structure:
```
- assets
  - app.css
- src
  - app.scss (build entry file)
  - components
    - helloWorld.scss (referenced by /src/app.scss)
```

When running `theme watch` I get the following behaviour:

- :white_check_mark: a direct change to `/assets/app.css` successfully uploads `/assets/app.css`.
- :white_check_mark: a change to the build entry file `/src/app.scss` triggers a build and successfully uploads `/assets/app.css`.
- :x: a change to `/src/components/helloWorld.scss` **does** trigger a build, updating `/assets/app.css` as expected, but `/assets/app.css` **is not** uploaded.

If I make a change to `/src/components/helloWorld.scss` and then `theme deploy assets/app.css` it does successfully upload the change, as expected.

Update: To clarify I have `gulp watch` running in a second terminal window which watches the `/src` directory for changes, and triggers a `/assets/app.css` build when a change is received.

**Comment by tanema** [comment]
This is a deuplicate of https://github.com/Shopify/themekit/issues/607 and an issue with Gulp and not themekit. Please see [this comment specifically](https://github.com/Shopify/themekit/issues/607) on how to workaround this.
