### ISSUE TITLE
Theme Replace does not upload all files and provides no feedback if there was a failure

### ISSUE THREAD

**Issue by csaunders** [Shopify/themekit#64]

**Comment by csaunders** [comment]
@stevebosworth, do a pull from master and see if this is still the case. There's a bunch of changes that have gone in that might fix up a bunch of issues.

Let me know if anything is still not working.

**Comment by stevebosworth** [comment]
Thanks @csaunders!!!

**Comment by stevebosworth** [comment]
Seems like this is still an issue.  I did a pull from master and tried `theme upload` and got the same error with `invalid argument` from one of the locales files

**Comment by csaunders** [comment]
I'll need to see your configuration and usage to figure out what is going
wrong.

On Tue, Sep 8, 2015 at 1:32 PM, Steve Bosworth <notifications@github.com>
wrote:

> Seems like this is still an issue. I did a pull from master and tried theme
> upload and got the same error with invalid argument from one of the
> locales files
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shopify/themekit/issues/64#issuecomment-138642720>.
>



-- 
Chris Saunders // Developer @ Shopify
