### ISSUE TITLE
Unable to upload fonts. Corrupted files 

### ISSUE THREAD

**Issue by acanales** [Shopify/themekit#641]
**Describe the bug**
Unable to load web fonts. Files are getting corrupted. 

**To Reproduce**
I created a file with the name of "Webfonts" inside the assets directory. Uploaded all my EOT,SVG and WOFF files and they seem to be getting corrupted. Whenever i load the page i get this error and fonts are unable to display. 

**Expected behavior**
Load the correct fonts. 

**Environment (please complete the following information):**
 - OS : Mojave 10.14.2
- Themekit version: ThemeKit 1.0.0 darwin/amd64
 - Editor: Sublime 3.1.1

**Additional context**
![Screen Shot 2019-06-12 at 12 34 18 PM](https://user-images.githubusercontent.com/916052/59373062-76944d80-8d0e-11e9-900c-48f5877cb438.png)
![Screen Shot 2019-06-12 at 12 33 59 PM](https://user-images.githubusercontent.com/916052/59373063-76944d80-8d0e-11e9-854e-b5112b7cbb0f.png)

**Comment by tanema** [comment]
Hey @acanales thanks for reporting this. I just have some follow up questions.

- Have you experienced this before? 
- Is it only happening on a single font, or all of them? 
- Do you get any errors while uploading them? 
- Is it only the WOFF files or all of the font files?

Generally themekit does not touch the contents of the files in any way so it should not be corrupting the fonts. I will try to reproduce this soon.

**Comment by acanales** [comment]
1. Yeah i always had this problem with themekit, mainly with icon fonts. Was never able to solve it. 
2. All of them
3. Not a single thing on the terminal (Attaching screenshots)
4. All of them

you can check out test site at 

https://cerveza-rrey.myshopify.com/products/kit-de-cerveza?variant=17279021383770

Product Title or "Kit de Cerveza" should have the new font RomanaBTWXX-Bold

**Comment by tanema** [comment]
I am sorry I did not realize this on the first reading of this issue. You are trying to create a directory `webfonts` inside the assets directory and uploading it? I believe your files are not being uploaded. I do however that you are getting an error on your icon font. So far I have not been able to replicate this.

**Comment by tanema** [comment]
Okay so I have not been able to reproduce, this. I have used every font type and uploaded them all. I believe your root cause is the fact that you are trying to use a nested folder. You cannot use a nested folder in the assets folder. If you move your fonts and retry and it still is happening please reopen this issue.
