### ISSUE TITLE
New Theme Sections and folder Structure not working

### ISSUE THREAD

**Issue by Hujjat** [Shopify/themekit#644]
**Describe the bug**
I have updated the theme kit to version 1.0.1 but the watch for new shopify update for sections aren't working. 

**Expected behavior**
It should upload any file in /pages directory. But it's not.  Here is the error
`(pages/article.liquid) this file is not part of your theme`

**Environment (please complete the following information):**
 - Windows 10:
- Themekit version [e.g. v1.0.1]:
 - Editor [vs code]:
 - Ignore:

**Additional context**

I still have to old folder structure. I just create a folder called */pages* and liquid files inside. But it can't upload those file to Dev stores. 

Thanks

**Comment by tanema** [comment]
Hey @Hujjat thanks for reporting this. Are you working on an old theme? I can reproduce this however it is shopify that is returning a 404 when trying to upload the pages/article.liquid so I will have to ask the sections team about the expected behaviour.

**Comment by tanema** [comment]
Okay, I talked to the team and they say that the sections feature currently only enabled on development stores which have the dev preview enabled.

You can find documentation for how to create a development store here: https://help.shopify.com/en/partners/dashboard/development-stores#create-a-development-store

And documentation on developer previews here:
https://help.shopify.com/en/api/versioning/developer-preview

If you are working on a dev-store with previews and it is still not working, I think you should contact support as they will be more likely to be able to help from there.

**Comment by Hujjat** [comment]
Hi @tanema 

Thanks for quick replay. 

Just want to add for future. We can't develop any new section features on old Dev stores. We should create a new Dev Store to be able to enable developer preview mode. 

Thanks
