### ISSUE TITLE
DNS problem while connecting to Shopify

### ISSUE THREAD

**Issue by illia108** [Shopify/themekit#645]
**Describe the bug**
**theme watch** gives:

DNS problem while connecting to Shopify, this indicates a problem with your internet connection

**To Reproduce**
1. run command 'theme watch'

**Expected behavior**
watch for file changes

**Environment (please complete the following information):**
 - MacOS High Sierra 10.13.6  
- Themekit version: 1.0.1

**Comment by tanema** [comment]
Hey @illia108 

This is an issue with Cloudflare https://www.cloudflarestatus.com/ which is causing widespread problems across a lot of the internet. 

Shopify is working on mitigating these errors as well and this is a wider platform issue rather than a themekit issue. You can monitor it here: https://status.shopify.com/

**Comment by illia108** [comment]
just realised that. sorry. can be closed

**Comment by gui-gui** [comment]
Sorry to be reopening this. But is this a intermitent problem?

I'm getting the same error but while trying to generate a new theme with

**To Reproduce**

```
theme new -p=mypassword -store=mystore -name=themename
```
**Expected behavior**

create the new theme

**Environment**
MacOS Catalina 10.15.5
ThemeKit 1.0.3 darwin/amd64

**Comment by stevenventimiglia** [comment]
It just started happening to me, too.  My internet connection is normal, Cloudflare's status is normal, and Shopify's status seems to be normal as well.

**Comment by wimhollebrandse** [comment]
Just in case anyone else runs into this problem, some examples out on the web use these args with a single hyphen/slash. This might have worked with earlier ThemeKit versions, but not anymore.

Use two hyphens for the args, so `theme new --p=mypassword --store=mystore --name=themename`

Regardless of this though, the ThemeKit CLI should really show at least a better error about invalid args and show a man- page or similar. Pretty shocking to have arg validation drop into some DNS network catch-all.
