### ISSUE TITLE
Online editor changes are applied in local

### ISSUE THREAD

**Issue by LuckyGStar** [Shopify/themekit#647]
**Is your feature request related to a problem? Please describe.**
While 2 developers are working in current store, I have noticed that my changes made in local are applied to online store but online store changes made by online editor are not applied to my local. Therefore, when I have deployed my changes to production, the changes made by another developer was erased. 
I hope this to be resolved. 

**Describe the solution you'd like**
It would be great if two way binding is implemented so that we can get update as soon as it is made in online editor.

Hope to hear soon.

Regards

**Comment by katiedavis** [comment]
Hi @LuckyGStar Thanks for bringing this to our attention! I've brought this issue to the team and we will look into it.

**Comment by tanema** [comment]
Hey, @LuckyGStar thanks for opening the issue. There are some major complications with implementing something like this. Themekit is backed by a simple HTTP API. This means there is no real 2-way communication. Also, themekit is not a continuously running process, so there would be no way to always give you the updated files without you initiating a command. Currently, that command would be `theme download` to get the most recent file changes. Even if we could have that sort of live update, it would cause more complications of overwriting your local files when another developer has made a change.

I do have good news though, I am working adding file version checking so it will make it harder to overwrite other developers work. I know that has been an issue for a while and we even had a previous version that had a buggy version check but it was removed (https://github.com/Shopify/themekit/issues/540) 

For now though you need to have a process in place for deployment.
- use version control and commit all your work
- run `theme download` before deploying to make sure you get all the recent changes and use your version control to see what exactly changed
- run `theme deploy` when you are finally ready.

**Comment by LuckyGStar** [comment]
Hi Tanema. Thanks for your reply. Yes. Maybe it would be impossible to use two-way binding with simple HTTP API call without js libraries. I will use git for version control. I have quick a couple of questions. (one is related with theme-kit and latter one isn't related)

- [ ] For getting latest update from online store theme, simple command **theme download** should be enough? no need for api_key and other credentials?
- [ ] The issue (#540) was removed in latest version? Now I am using **1.0.1** on Mac.
- [ ] (This is related with slate) I want to know if I can work with existing online themes with slate. Slate documents only mentioned about creating new themes. I want to know if I can work on updating existing theme with Slate. 

Many thanks. 

Regards

Andy

**Comment by tanema** [comment]
1. If your config is set up appropriately, `theme download` is all you need to run to download all of the files from online store
1. That feature was removed from before 1.0.0 It was causing a lot of problems and confusion.
1. If you want to use slate I would recommend starting with a slate template because the directory structure is different and it might be hard to migrate an existing project.

**Comment by LuckyGStar** [comment]
Thanks for your detailed description Tanema. 

Just wanted to confirm. 

1. ***theme download*** will update existing theme in local? not download again. Am I right?
2. So from ***v1.0.1***, only changed files will be deployed to online theme when I am using `theme watch` commend?
3. For using slate with existing online themes in my store, I should update theme to meed Gulp configuration and other dependencies? so it will be difficult to use them?

Regards

Andy

**Comment by tanema** [comment]
1. yes, theme download will download all the files from online store in that theme to your local files
2. When you run theme watch, it will upload and file you change.
3. yes.

**Comment by LuckyGStar** [comment]
Thanks for your help.

After starting work with GitHub for version control, everything gets easier. 

Thanks again. 

Best Regards

Andy
