### ISSUE TITLE
Disable writing to a published theme

### ISSUE THREAD

**Issue by raffi310** [Shopify/themekit#648]
It's becoming more and more of an issue as our company scales. 
Since themekit allows for live theme editing, this causes a potential risk for someone to accidentally have themekit update a theme that is live.

Our current flow: 
**Developer->ThemeKit->Shopify->Draft theme->Published theme**
The issue here is that the draft theme has an ID we connect to with `theme configure`. Once we publish the draft theme the ID we connected to now becomes a published theme. Each developer has to be aware that the ID they we were using needs to be updated. Just in case they connect to themekit after the fact without updating the theme id. 

It would be neat if there was a way to stop deploying code to a published theme via config.

Our current method is to communicate with one another and have them physically disconnect from the theme ID once admin published the theme.

**Comment by tanema** [comment]
Would the `readonly` config help? There is a `readonly` config that you can add to a single theme config to disable writing to it. https://shopify.github.io/themekit/configuration/

**Comment by raffi310** [comment]
I think your recommendation should work. Thank you.
