### ISSUE TITLE
connection refused When running theme watch or theme download

### ISSUE THREAD

**Issue by Developer-Amit** [Shopify/themekit#650]
**Describe the bug**
user@amitmishra:~/work/shopify-theme$ theme download
Get https://mystore.myshopify.com/meta.json: dial tcp: lookup mystore.myshopify.com on 127.0.1.1:53: read udp 127.0.0.1:33685->127.0.1.1:53: read: connection refused

**To Reproduce**
1. theme download
You will see the above error

**Expected behavior**
Should be downloaded all the theme files in my local

**Environment (please complete the following information):**
 - OS [Ubuntu 17.04]:
- Themekit version [ThemeKit 1.0.1 linux/amd64]:
 - Editor [VS code]:
 - Ignore:

**Additional context**
config.yml

```
  development:
  password: myapppassword
  theme_id: "123456"
  store: mystore.myshopify.com
  timeout: 120s
```

Also, I tried to add proxy into my config but same error
  proxy: "http://127.0.0.1:8080"

 $ theme watch
[development] Proxy URL detected from Configuration [http://127.0.0.1:8080] SSL Certificate Validation will be disabled!
Get https://mystore.myshopify.com/meta.json: proxyconnect tcp: dial tcp 127.0.0.1:8080: connect: connection refused

Many many thanks, I see lots of relevant issues here but not found any solutions.

**Comment by tanema** [comment]
Are you running a proxy? Are you behind some sort of proxy or firewall that might be blocking connections? The fact that the requests are being routed to localhost (127.0.0.1) is very strange, you have something set up in your environment that is interfering with the operation of Themekit.

**Comment by Developer-Amit** [comment]
@tanema Yes My network is under the firewall, but it doesn't have anything blocking except few suspicious things.
Even if I remove this line - proxy: "http://127.0.0.1:8080" from my config, it does not work too.
Yes I cross-checked I don't have anything rest of that config setup in the environment

**Comment by tanema** [comment]
> dial tcp: lookup mystore.myshopify.com on 127.0.1.1:53: read udp 127.0.0.1:33685->127.0.1.1:53: read: connection refused

This tells me that for some reason the DNS of your store domain is pointing at your localhost `lookup mystore.myshopify.com on 127.0.1.1:53` Are you using another application that is hosting something under that domain name on your computer? Can you check your hosts file for it?

**Comment by Developer-Amit** [comment]
@tanema My hosts file  `/etc/hosts` looking like this
```
127.0.0.1	localhost
127.0.1.1	user-OptiPlex-3020M

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
If I'm not setting any proxy params in the my config this showing default like `mystore.myshopify.com on 127.0.1.1:53` Either when I set another proxy like "http://127.0.0.1:8080" its showing then like this error
```
dial tcp: lookup mystore.myshopify.com on 127.0.1.1:8080: read udp 127.0.0.1:33685->127.0.1.1:8080: read: connection refused
```

**Comment by tanema** [comment]
This askubuntu forum post sounds very familiar https://askubuntu.com/questions/270479/what-is-my-dns-server

Can you make sure you are not using something like dnsmasq and/or make sure that your Primary DNS provider is valid?

**Comment by tanema** [comment]
I am going to close this now as it seems like a DNS config problem and not a problem with themekit.

**Comment by Developer-Amit** [comment]
Yes this doesn't worked for me, I don't found any proper solution to solve this problem, I decided to use another development tools.
Thanks
