### ISSUE TITLE
Internal Server Error deploying

### ISSUE THREAD

**Issue by adrianbourke** [Shopify/themekit#651]
Last deployment was in March, and occurred without issues.

Tried deploying today with a single line change, and are receiving errors for many files in the theme, eg. 
[development] (snippets/product-meta.liquid) Internal Server Error
[development] (sections/testimonials.liquid) Internal Server Error
[development] (templates/cart.drawer.liquid) Internal Server Error
[development] (templates/collection.liquid) Internal Server Error
[development] (templates/blog.liquid) Internal Server Error
[development] (sections/page-contact-template.liquid) Internal Server Error

Verbose doesn't provide any addition information as to what an "Internal Server Error" is.

Any ideas?

**Comment by tanema** [comment]
Internal server errors are errors from Shopify if this persists, please contact shopify support as they will be better to help you with this sort of thing
