### ISSUE TITLE
Missing <HTML> in theme.liquid

### ISSUE THREAD

**Issue by tms320c** [Shopify/themekit#652]
**Describe the bug**
layout/theme.liquid does not contain opening HTML tag

**To Reproduce**
1. read the source of the layout/theme.liquid

**Expected behavior**
Should have tag HTML after !doctype

**Environment (please complete the following information):**
 - OS Win10:
- Themekit version ThemeKit 1.0.1 windows/amd64:
 - Editor notepad++:
 - Ignore:

**Additional context**

**Comment by tanema** [comment]
Hey @tms320c thanks for reporting this, I will have it fixed soon.
