### ISSUE TITLE
Themekit compatibility with new schema options

### ISSUE THREAD

**Issue by shikkaba** [Shopify/themekit#655]
**Is your feature request related to a problem? Please describe.**
There is a new way to build themes which was just announced. It's in preview as of this moment, but I'd like to play around with it: [https://help.shopify.com/en/themes/development/section-themes](https://help.shopify.com/en/themes/development/section-themes)
Currently when I try out the new code, I get "Invalid schema: 'content' is not a valid attribute". 

**Describe the solution you'd like**
What is the timeline for this functionality being added to themekit so anyone developing with it won't fall behind, or be forced to use only the in store developer?

**Describe alternatives you've considered**
Waiting. Patiently. :)

**Comment by tanema** [comment]
Themekit already supports this. The sections feature currently only enabled on development stores which have the dev preview enabled.

You can find documentation for how to create a development store here: https://help.shopify.com/en/partners/dashboard/development-stores#create-a-development-store

And documentation on developer previews here:
https://help.shopify.com/en/api/versioning/developer-preview

If you are working on a dev-store with previews and it is still not working, I think you should contact support as they will be more likely to be able to help from there.

**Comment by shikkaba** [comment]
That was fast. 👍 

Thank you @tanema

**Comment by tanema** [comment]
@shikkaba You also can't develop any new section features on old Dev stores. You need to create a new Dev Store to be able to enable developer preview mode.
