### ISSUE TITLE
Deploy updates ignored files

### ISSUE THREAD

**Issue by Benecke** [Shopify/themekit#660]
In relation to #627

I just overwrote my settings_data.json (ignored file) on a live store using the deploy command and I can actually reproduce this.

Here's a screenshot from my terminal, showing the version, command and my config. I also added the theme.liquid file for testing but it gets updated as well as you can see here:

<img width="611" alt="grafik" src="https://user-images.githubusercontent.com/1921514/62852187-fd52b000-bce8-11e9-870d-a742fb2bf0f4.png">

Let me know if I should test anything else for you to help you reproduce.

**Comment by tanema** [comment]
Yes it looks like you have invalid yaml there. I am not sure why that isnt throwing an error.

Your ignore config should look like this:

```
ignore_files:
    - config/settings_data.json
    - locales/* 
    - layout/theme.liquid
```

**Comment by tanema** [comment]
Also your theme config looks pretty old, you can remove that bucket size and refil rate. Themekit no longer uses a leaky bucket throttle

**Comment by Benecke** [comment]
Thanks for letting me know @tanema 

Yes, I'm using themekit since the first release ❤️ and I guess that information simply slipped through for me. It seemed to continue to work and didn't give me any trouble until now. Maybe I also missed a release note about a new config format while being busy coding.

You should probably make sure it throws an error instead of working this way. Thanks again for the quick response, I will update the config on out repositories.

**Comment by tanema** [comment]
Unfortunately it is still valid Yaml so I cant even throw an error in this instance. Is your filter working now?

**Comment by Benecke** [comment]
Sorry, I missed your comment. Yes, it's working fine.
