### ISSUE TITLE
no ability to add og:image for social media sharing

### ISSUE THREAD

**Issue by jdusett1** [Shopify/themekit#667]
**Describe the bug**
"social media" section of theme editor only offers ability to change linked URLs

**To Reproduce**
1. theme - theme settings - social media

**Expected behavior**
ability to add image to be shared on social media 
**Environment (please complete the following information):**
- Themekit version [e.g. v1.0.0]:

**Comment by liamgriffin** [comment]
Hi @jdusett1 

There are a few methods for adding OG tags to a theme- one common way is to create a snippet containing the OG tags, and reference this within the `<head>` tags of `theme.liquid`. 

As an example of this, you can see the `social-meta-tags.liquid` file from the [Slate starter theme. ](https://github.com/Shopify/starter-theme/blob/master/src/snippets/social-meta-tags.liquid) We also have a blog post which goes into more depth how OG tags work on Shopify themes: [How Open Graph Tags can Optimize Social Media Experiences](https://www.shopify.ie/partners/blog/open-graph-tags)

Let me know if you have any other issues with this 

Liam

**Comment by liamgriffin** [comment]
Closing as this seems resolved.
