### ISSUE TITLE
Warn before interaction with live theme

### ISSUE THREAD

**Issue by Drex-luthor** [Shopify/themekit#670]
**Is your feature request related to a problem? Please describe.**
Currently, when you watch or deploy to a theme and it's the _live theme_ you get a message "Warning, this is the live theme on..." but it doesn't impose any checks to confirm you want to move forward

**Describe the solution you'd like**
I would prefer if there was a way for the CLI to ask "Are you sure you want to continue?" or something to that nature. Is there any way to implement a feature like this within the tool or using another package like commander/yargs?

**Comment by tanema** [comment]
So I generally try to stay out of the users way while they work. So in the past I added a configuration to make a configuration readonly. You can set your live theme config as readonly so that no changes can be made to it no matter what command is run.

**Comment by anulman** [comment]
@tanema Have you considered allowing a build flag, like `--force` or `--yes` for this? Other CLIs (e.g. [`apt-get`](https://superuser.com/questions/164553/automatically-answer-yes-when-using-apt-get-install)) use such a solution; I've found it an appropriate balance between developer ergonomics vs. potentially-destructive behaviour

**Comment by tanema** [comment]
Its not a bad idea. We could just block edits to a live theme and make them pass a `--force` flag to continue. Thanks @anulman
