### ISSUE TITLE
Cannot connect to my private app using ThemKit CLI

### ISSUE THREAD

**Issue by OliverHuntsman** [Shopify/themekit#671]
**Describe the bug**
I have followed the instructions, installed the latest brew and Xcode CLI in order to install Themekit, I have updated ThemeKit to the latest version all in Terminal on Mac OSX Catalina 10.15

I try the command 

`theme get --list -p=[your-password] -s=[you-store.myshopify.com]
`
I am expecting to get a list of the themes I can download and start to edit in VSCode

But, I get the following:-

`zsh: no matches found: -p[your-password]
`
I get the same error when I try to create a new theme

Am following these instructions

https://shopify.github.io/themekit/

I have tried to get the same results
```
-p
--p
-password
--password
```

**Comment by liamgriffin** [comment]
Hi @OliverHuntsman 

Just to confirm, when you created the private app from the store admin, you selected that the private app should have read and write access to theme assets to Theme templates and theme assets, correct?

You could also manually get the theme ID by navigating to the Theme Editor, by clicking on “Edit HTML/CSS”, and copy the theme ID number from the URL — it will be last several digits after ‘mystore.myshopify.com/admin/themes/’. 

Then you could run: 

`theme get --password=[your-api-password] --store=[your-store.myshopify.com] --themeid=[your-theme-id]
`

There are more detailed installation instructions for Theme Kit in [this blog post.](https://www.shopify.ie/partners/blog/95401862-3-simple-steps-for-setting-up-a-local-shopify-theme-development-environment)

Let me know if you're still seeing issues after trying the above.

**Comment by tanema** [comment]
I just ran it and it ran fine, then I added the square brackets and got the same error as you. The square brackets are just meant to indicate the space that you fill in and should not be included when you run the command.

**Comment by OliverHuntsman** [comment]
Ahhh, the square brackets - thank you!

**Comment by InesCV** [comment]
The same happened to me, it was the square brackets, I took them out and it worked perfectly.

**Comment by izuuuu** [comment]
I just downloaded the theme files via the Terminal. I have no idea how to access those files. To which location the files have been downloaded? I can't find the files. Any help would be deeply appreciated. Thanks!
