### ISSUE TITLE
"Watch" Not executing file changes on save.

### ISSUE THREAD

**Issue by kieran-doble** [Shopify/themekit#679]
Updated to version "ThemeKit 1.0.3 darwin/amd64" Watch no longer processes or updates files upon save.
Download and deploy still execute correctly. 

What do I need to test to see what's causing a problem?

**Comment by tanema** [comment]
What version did you update from? What OS are you running? 1.0.3 was a very innocuous release so it is confusing that it would break anything. Try installing 1.0.2 instead and see if that works and if it does not try installing 1.0.1.

You can do this by running `theme update --version=v1.0.2`

You are operating on a theme that was previously working right?

**Comment by kieran-doble** [comment]
I updated from 1.0.1. Installed 1.0.2 and that's where watch no longer works. Rolled back to 1.0.1 and it works again.

OS: OSX Catalina

**Comment by tanema** [comment]
Interesting, there is a change in 1.0.2 to check the checksum value of a file to make sure it has changed before you upload it. I know you probably have changed things but I have to ask, have you been testing by just saving the file?

**Comment by kieran-doble** [comment]
Oh right, I tested using both methods. saving changes to files as I was needing to update content etc. And by saving the file with no changes. 

I have updated to 1.0.2 again and the checksum is working correctly with Watch now.

**Comment by tanema** [comment]
Should I close this now then? Everything is working?

**Comment by kieran-doble** [comment]
Yes please. Thanks for you time Tim.

**Comment by propagandaCreative** [comment]
This was also an issue for me. I have a gulpfile watching my CSS changes, and v1.0.3 broke the watch functionality, for me. My gulpfile changes the modified date on the file it exports.
