### ISSUE TITLE
Make it possible to initialize a theme with arbitrary theme zip

### ISSUE THREAD

**Issue by csaunders** [Shopify/themekit#68]
Timber is great and all, but not everyone wants to use it. Perhaps an agency has their own baseline theme they use on all projects.

Instead of replacing how `theme bootstrap` works, instead another command could be added such as `initialize` which takes in a `--url` specifying where to go to download the theme.

`bootstrap` should probably become deprecated after this feature ships.

**Comment by tanema** [comment]
I added this functionality to the bootstrap command however in the future I would like to add all this functionality in the the `new` command described in #283
