### ISSUE TITLE
server misbehaving issue

### ISSUE THREAD

**Issue by matwa13** [Shopify/themekit#682]
Themekit version 1.0.2

I get such error when trying to run update command:

> Get https://shopify-themekit.s3.amazonaws.com/releases/latest.json: dial tcp: lookup shopify-themekit.s3.amazonaws.com on 82.209.243.241:53: server misbehaving

Also, I can't download, deploy or watch a remote theme 

Any thoughts?

**Comment by tanema** [comment]
@matwa13 Is this still currently the case? This looks like an issue with your DNS setup. It may be a transient issue and would have went away but if it has not you can look up how to set your DNS settings to use googles DNS servers temporarily to get working again.

**Comment by matwa13** [comment]
@tanema thanks. yes, it looks like the DNS issue
