### ISSUE TITLE
Cannot find binary to match your architecture [freebsd amd64]

### ISSUE THREAD

**Issue by rzymianin11** [Shopify/themekit#695]
Hello

I can't install this on my server. I tired by yarn, npm and curl, error on curl:

Cannot find binary to match your architecture [freebsd amd64]

How I can fix this?

Regards, Lucas.

**Comment by tanema** [comment]
We currently build and release for your arch https://github.com/Shopify/themekit/blob/master/Makefile#L21

What does is the output if you run `echo "$(uname) $(uname -m)"`

**Comment by rzymianin11** [comment]
FreeBSD amd64

**Comment by tanema** [comment]
Oh nevermind, I see it says amd64, that is your error message. That is confusing because normally amd64 arch identifies as freebsd x86_64
 https://github.com/Shopify/themekit/blob/master/docs/scripts/install.py#L25

**Comment by rzymianin11** [comment]
Check that screenshot, maybe will tell You more:

**Comment by rzymianin11** [comment]
`[mdg@s19]:</usr/home/mdg/domains/vingt.mdg.usermd.net>$ npm view @shopify/themekit

@shopify/themekit@1.1.3 | MIT | deps: 3 | versions: 18
Node version of ThemeKit
https://github.com/Shopify/node-themekit

keywords: themekit, shopify

bin: shopify-themekit

dist
.tarball: https://registry.npmjs.org/@shopify/themekit/-/themekit-1.1.3.tgz
.shasum: acd9d5b34b9552659d11dd9146bcb907f1a0e49a
.integrity: sha512-09OnlXMBnTYY5cK7r9Z4ZzFph/yuEcoxlbF/jE9ORSQZ7aQLAnLoRGBXDlmJdt8cBnVpCipjfpCBV9MaFJe3eQ==
.unpackedSize: 34.1 kB

dependencies:
bin-wrapper: 3.0.2    minimist: 1.2.0       simple-spinner: 0.0.5 

maintainers:
- antoine.grant <antoine.grant@shopify.com>
- chris.berthe <chris.berthe@shopify.com>
- goodforonefare <goodforonefare@gmail.com>
- harshal317 <harshal.brahmbhatt@shopify.com>
- huguestennier <hugues.tennier@shopify.com>
- ismail.syed <ismail.syed@shopify.com>
- lemonmade <chrismsauve@gmail.com>
- marytal <mary.briskin@shopify.com>
- nathanpjf <nathan.pj.ferguson@gmail.com>
- shopify-dep <npmjs+shopify-dep@shopify.com>
- themallen <mallorytypes@gmail.com>
- thomaskelly <thomas.kelly@shopify.com>
- tsov <tsov@me.com>
- wizardlyhel <helen.lin@shopify.com>

dist-tags:
latest: 1.1.3  

published 2 months ago by antoine.grant <antoine.grant@shopify.com>
[mdg@s19]:</usr/home/mdg/domains/vingt.mdg.usermd.net>$ npm install @shopify/themekit@1.1.3

> @shopify/themekit@0.6.12 postinstall /usr/home/mdg/domains/vingt.mdg.usermd.net/node_modules/@shopify/slate-sync/node_modules/@shopify/themekit
> node ./lib/cli.js install

|/usr/home/mdg/domains/vingt.mdg.usermd.net/node_modules/@shopify/slate-sync/node_modules/@shopify/themekit/lib/install.js:46
        throw runErr;
        ^

Error: No binary found matching your system. It's probably not supported.
    at BinWrapper.download (/usr/home/mdg/domains/vingt.mdg.usermd.net/node_modules/bin-wrapper/index.js:207:6)
    at BinWrapper.<anonymous> (/usr/home/mdg/domains/vingt.mdg.usermd.net/node_modules/bin-wrapper/index.js:178:9)
    at FSReqWrap.oncomplete (fs.js:153:21)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.1 (node_modules/mocha/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/popper/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open '/usr/home/mdg/domains/vingt.mdg.usermd.net/node_modules/pngquant-bin/node_modules/cross-spawn/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/usr/home/mdg/domains/vingt.mdg.usermd.net/node_modules/pngquant-bin/node_modules/bin-build/node_modules/cross-spawn/package.json'
npm WARN stylelint-webpack-plugin@0.10.5 requires a peer of stylelint@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @shopify/theme-cart@1.0.0-alpha.7 requires a peer of jquery@3.x but none is installed. You must install peer dependencies yourself.
npm WARN @shopify/theme-rte@1.0.0-alpha.7 requires a peer of jquery@3.x but none is installed. You must install peer dependencies yourself.
npm WARN @shopify/theme-variants@1.0.0-alpha.8 requires a peer of jquery@3.x but none is installed. You must install peer dependencies yourself.
npm WARN redbox-react@1.6.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN redbox-react@1.6.0 requires a peer of react-dom@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN typescript-eslint-parser@11.0.0 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @shopify/themekit@0.6.12 postinstall: `node ./lib/cli.js install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @shopify/themekit@0.6.12 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mdg/.npm/_logs/2020-03-04T13_54_21_772Z-debug.log
[mdg@s19]:</usr/home/mdg/domains/vingt.mdg.usermd.net>$ 
`

**Comment by tanema** [comment]
It seems like the node-themekit package does not support freebsd. https://github.com/Shopify/node-themekit/blob/master/lib/install.js#L20-L24

**Comment by rzymianin11** [comment]
Ok but why this trying to install this package, I write command: npm install @shopify/themekit@1.1.3

**Comment by tanema** [comment]
that is the package you are installing. If you want just plain themekit please refer to the installation instructions https://shopify.github.io/themekit/#installation

**Comment by rzymianin11** [comment]
I did:

curl -s https://shopify.github.io/themekit/scripts/install.py | python
Cannot find binary to match your architecture [freebsd amd64]
Please open an issue at https://github.com/Shopify/themekit/issues

**Comment by tanema** [comment]
What operating system are you on?

**Comment by rzymianin11** [comment]
I manually add this file but when I using yarn deploy I have error:

↑  Uploading to Shopify...

unknown command "upload" for "theme"

My Error unknown command "upload" for “theme"

**Comment by tanema** [comment]
Yeah that is because this file is only a binary. It is not a javascript package.

**Comment by rzymianin11** [comment]
Ok I figured out why this want install 0.6.12 not the latest. Versions 0.6.12 had command “upload”, latest version don’t have that command

**Comment by rzymianin11** [comment]
When I changed in @shopify/slate-sync/index.js command upload to deploy, all start works (line 80)

**Comment by rzymianin11** [comment]
Can I compile versions 0.6.12 to freebsd ? I need “upload” function because this function uploading single files, deploy uploading all files
