### ISSUE TITLE
theme deploy is oblivious to rate limiting + does not fail on errors

### ISSUE THREAD

**Issue by dgpokl** [Shopify/themekit#700]
**Describe the bug**

Two issues with `theme deploy` which make it unreliable to use especially in CI:

1. There is apparently a rate limit on the underlying API - I'm really excited that at least I get to know what the limit is, it's 4 requests per second according to the logs printed out below. Anyway, issue 1 is that although it seems like Themekit could monitor for this, or any other failure, and handle it in *some way* (waiting a few seconds and retrying this file would be the most naïve approach, better would be to learn from the failure and after finding a delay that is long enough, to stick to that for the rest of the deploy).

2. Themekit just prints a message and continues running in this case. I can't think of any case where this is useful behavior. Assuming the above is too complex to implement, Themekit should absolutely exit **immediately** with code 1 anytime there is an error like this. This is just CLI standard practice as far as I've ever seen outside of Shopify tools. It will allow developers to implement their own error handling. Currently the only workaround I can imagine would be super wasteful: run `theme deploy`, capture entire output and grep for this kind of message (are there other kinds?) and if we found them, sleep a while and deploy the whole theme again, repeating with fingers crossed. It seems like at least adding an option to exit on failure would be a good idea.
```
...
[development] (snippets/a-form.liquid) Exceeded 4 calls per second for api client. Reduce request rates to resume uninterrupted service.
[development] Updated templates/page.liquid
[development] (assets/template.cart.css.liquid) Exceeded 4 calls per second for api client. Reduce request rates to resume uninterrupted service.
[development] Updated assets/template.collection.css.liquid
[development] (assets/template.blog.alt.js.map) Exceeded 4 calls per second for api client. Reduce request rates to resume uninterrupted service.
...
```

**To Reproduce**
1. run `theme deploy --verbose` on 2 theme folders uploading 2 different themes in 2 different windows concurrently on a fast connection
2. see errors like `Exceeded 4 calls per second for api client....`
3. cry

**Expected behavior**
Either back-off and retry asset or just exit 1 and let the user/script handle it

**Environment (please complete the following information):**
 - OS [e.g. iOS]: buster
- Themekit version [e.g. v0.7.5]: whatever the latest version is, it doesn't seem to have a `--version` option

**Comment by tanema** [comment]
You are either using the same private app as another developer or your are running two instances because [themekit has a whole section of code that actually does all of the rate limiting](https://github.com/Shopify/themekit/blob/master/src/ratelimiter/rate_limiter.go). It can only tell its own usage though so if you are in one of these other two scenarios, then you will have problems
