### ISSUE TITLE
when `Invalid JSON in tag 'schema' ` happens, tell us which line 

### ISSUE THREAD

**Issue by xyyolab** [Shopify/themekit#702]
**Is your feature request related to a problem? Please describe.**
It will be helpful that `themekit` can tell me which line do I have a syntax error when `theme watch` with schema tag.
```
[development] (sections/image-slider.liquid) Invalid JSON in tag 'schema'
```

**Describe the solution you'd like**
A better error handling like `syntax error in line 145` .

**Describe alternatives you've considered**
If it's possible, I can try to pr to add this feature.

**Comment by tanema** [comment]
Sorry but this is the exact error message from the Shopify API. The API does not return line numbers. If you want support for this, then you will have to ask for it from the support line
