### ISSUE TITLE
Shopify theme : There is a layer of haze on my background pic

### ISSUE THREAD

**Issue by jiantaolovebingbing** [Shopify/themekit#709]
**Describe the bug**

**To Reproduce**
1. run command 'theme new --password=mypassword --store=store.myshopify.com --name=theme'
2. click the 'Customize' button and add a slideshow section ,then upload pic
3. there is a layer of haze on the slide background pic, u can see in the below pic

**Expected behavior**
This is a slideshow in shopify, I checked all the parent elements of the component, there is no corresponding css, it should be a css written separately by js, how can I remove the lager.

**Environment (please complete the following information):**
![original](https://user-images.githubusercontent.com/33253363/82326700-d65fa200-9a0f-11ea-9b1d-6353b627df64.png)
![shopify](https://user-images.githubusercontent.com/33253363/82326718-dcee1980-9a0f-11ea-8479-53c40592ba31.png)

**Additional context**

**Comment by jiantaolovebingbing** [comment]
![original](https://user-images.githubusercontent.com/33253363/82326973-3d7d5680-9a10-11ea-97c0-65b479630d60.png)

**Comment by liamgriffin** [comment]
We've flagged this with the internal Online Store Editor team here, but I'll close this issue as it's unrelated to Theme Kit.
