### ISSUE TITLE
Infinit fashion megastore Theme bug with product price

### ISSUE THREAD

**Issue by balagosh** [Shopify/themekit#713]
hi there, 

im using Infinit fashion megastore theme, in the product page, when user change color or variant, the price duplicate itself, this example will explain it better:
<a href="https://ibb.co/M778m7c"><img src="https://i.ibb.co/0rrBxrC/price.png" alt="price" border="0"></a>

thanks

**Comment by tanema** [comment]
This is not an issue with themekit, it is a problem with your theme. Please use the shopify forums for more support
