### ISSUE TITLE
Make Deploys Faster and Smarter

### ISSUE THREAD

**Issue by lmittmann** [Shopify/themekit#715]
**Is your feature request related to a problem? Please describe.**
Every time `theme deploy` is ran, all files of the the theme are uploaded. However, often only a few files actually changed. This is not only slow and inefficient but also error prone, as Shopifys API request limits are hit often, when a theme is deployed to multiple origins concurrently. 

**Describe the solution you'd like**
It would by great if `theme deploy` only deploys and updates those files, that are created, updated or deleted. Also the command should be more resilient to API request limits. Instead of exiting the command when the request limit is hit, the command could pause an retry to upload a file.

**Describe alternatives you've considered**
For now we we are restarting `theme deploy` in our CICD pipeline every time the deploy failed due to hitting the API request limit.

**Comment by tanema** [comment]
> API request limits

Themekit is throttled absolutely agains requests limits. If you are hitting the throttle then you are using the same api key and password for many instances of themekit.

**Comment by lmittmann** [comment]
> If you are hitting the throttle then you are using the same api key and password for many instances of themekit.

@tanema Yes, I use a single API key to deploy to different environments of the same shop concurrently. Is the rate limit hard coded to 2 rps or does it use the `Retry-After` header?

**Comment by lmittmann** [comment]
@andyw8 Thanks for the awesome release `v1.1.0`. All my deployments are >10x faster now.
