### ISSUE TITLE
Themekit needs an installer

### ISSUE THREAD

**Issue by csaunders** [Shopify/themekit#73]
We have a few approaches we can take for this:

- `curl | sh` installer (Linux & Mac OSX)
- homebrew recipe (OSX only)
- Nullsoft Scriptable Install System (Windows only)

I've never done anything like this before so I'm not too sure what the best approach for this would be.

**Comment by stevebosworth** [comment]
I assume homebrew and the installer would be the most popular but having a fallback for linux is good too.  Is there a lot of effort required to do all three?

**Comment by csaunders** [comment]
The main problem I have with homebrew is that it just targets a single platform. I'm going to give the installer script a try, which should at least get 2 platforms targetted.

Honestly, unixy systems are jokes. It's getting something that installs the application for Windows users that is the hardest.

**Comment by csaunders** [comment]
I've written up an installer for Linux and Mac and have tested it out on my vagrant box as well as on my Mac. I also had a few people give it a run and they also got themekit working on their systems.

The installer script is [here](https://github.com/Shopify/themekit/blob/installers/install) and I've also updated [the website](http://themekit.cat) with this new installation method.

**Comment by csaunders** [comment]
We'll open another issue for Windows users. It might require learning how to build an MSI or something.
