### ISSUE TITLE
Can't create a new theme, never-ending list of errors

### ISSUE THREAD

**Issue by gubisio** [Shopify/themekit#731]
I have just installed Chocolatey and ThemeKit willing to try and create my own theme. Went through all the steps, but there's one thing stopping me. After running the command "theme new --password=mypassword --store=store.myshopify.com --name=theme'" I get this: 
[teapsytea.myshopify.com] theme created
[teapsytea.myshopify.com] config created
Exists locales.
        Exists locales\en.default.json.
Exists templates.
        Exists templates\index.liquid.
        Exists templates\page.liquid.
        Exists templates\product.liquid.
        Exists templates\search.liquid.
        Exists templates\article.liquid.
        Exists templates\cart.liquid.
        Exists templates\collection.list.liquid.
        Exists templates\gift_card.liquid.
        Exists templates\list-collections.liquid.
        Exists templates\page.contact.liquid.
        Exists templates\404.liquid.
        Exists templates\blog.liquid.
        Exists templates\collection.liquid.
Exists templates\customers.
        Exists templates\customers\activate_account.liquid.
        Exists templates\customers\addresses.liquid.
        Exists templates\customers\login.liquid.
        Exists templates\customers\order.liquid.
        Exists templates\customers\register.liquid.
        Exists templates\customers\reset_password.liquid.
        Exists templates\customers\account.liquid.
Exists assets.
        Exists assets\application.js.
        Exists assets\application.scss.
Exists config.
        Exists config\settings_data.json.
        Exists config\settings_schema.json.
Exists layout.
        Exists layout\theme.liquid.
[teapsytea.myshopify.com] uploading new files to shopify
open C:\WINDOWS\system32\LogFiles\WMI\RtBackup: Access Denied.

I'm on Windows 10, hope someone could help me resolve the issue.

Also, I do have the theme on my shopify store. Peculiar. When I download the file, it's empty.

**Comment by gubisio** [comment]
Okay, so I'm trying to resolve this issue myself and wow, what a ride. I found the folders , granted myself access to this by opening and thought "huh, guess it's done". Ran the theme new command, and to my surprise I have witnessed an endless error messages something about illegal characters and such. Can't even copy it.. I'll try to capture it and post it here.

**Comment by tanema** [comment]
What version of themekit are you using. 

Also you do not need to keep running `theme new` if you have already generated the files and config (and thus the actual theme on shopify) you can try and run `theme deploy` from then on while debugging this issue. The reason that the theme exists on your store is because themekit was able to create it with the API but it was not able to upload the files. That is the reason it is empty.

As for your other errors, I am not sure what is happening. Where and how are you running the theme command? it looks like it is trying to upload filenames like `config/systemprofile/AppData/Local/DataSharing/Storage/DSS.log` which should not be possible if you just generated the theme in an empty directory.

**Comment by gubisio** [comment]
My current version of ThemeKit is: ThemeKit 1.0.3 windows/amd64 
 I have never used ThemeKit or Choco before. This would be the very first time. Tried reinstalling everything, step by step, updating Windows and such - still getting the same result. 
 Sadly, no new files generate on my computer. Nothing comes up anywhere, so how would the `theme deploy` work? 

I am running the theme command in admin-ran PowerShell (tried cmd aswell). Both give the same results, and error never seems to stop. Sometimes it actually does, but upon pressing any thing It goes on again.

**Comment by tanema** [comment]
Your output of `theme new` displays that not only are files generated but they are already there. Please look in your System32 folder and see what you see because that is where `config\systemprofile` exists (`C:\Windows\System32\config\systemprofile`) I don't know why files would be generated there but something seems to be linking there. Where are you generating your theme?

**Comment by gubisio** [comment]
First of all thank you for helping me out, I very much appreciate your presence. 

I found something: There's literally every .liquid file in my `System32` folder. Stored in subfolders such as `\templates\customers\` etc. 
I have no idea why it's being generated in the `System32` folder and it seems incredibly odd.

Also, I have no idea what you mean by "Where are you generating your theme". Do I have any options? haha

What should I do now? Is there a way to somehow redirect it?

**Comment by gubisio** [comment]
OKAY WE DID IT.

So, I'm completely new to command line. PowerShell was basically putting me in the System32 folder as default, thus `theme new` created every single file in the System32 folder. The whole errorlist was just an outcome of Windows security working, so files from my System32 don't get uploaded somewhere. 

I sent this thread to my IT friend, who just asked which folder is my PowerShell putting me in. And everything clicked. 
With a little bit of help I "moved" myself to another, newly created folder in the Users folder. This is how I did it: 
![shopify](https://user-images.githubusercontent.com/67743608/87566241-a274c600-c6ba-11ea-9f10-7b45b2efa488.png)

It took me literally 10 hours of constant search to resolve this issue. 
Thank you so much, Tanema, for helping me out. Wouldn't be possible without you.

Files got simply uploaded now and I'm ready to work. Every file is on it's place in the newly created folder. 

Case closed.

**Comment by tanema** [comment]
Congrats for figuring it out!
