### ISSUE TITLE
Consider including your users into feedback loop/roadmap?

### ISSUE THREAD

**Issue by vfonic** [Shopify/themekit#734]
I see there's (finally) some activity in this repo and that's great! I'm really happy to see that. :)

I believe theme and app development/developers is very important part of Shopify ecosystem.

Too bad Slate has been shut down...

That all being said, I think getting theme developers involved in the process could benefit everyone:
1) You won't build something people don't need/want
2) You _would_ build something people need/want

Here are couple of my "favorites":
1. Make it possible/faster to upload multiple files at once. I'm not sure of go's multi-threading capabilities, but uploading/downloading 200 files is a pain in the a$$. But who uploads/downloads 200 files? Glad you asked. :) My client is a bit tech-savy so he sometimes likes to make changes to theme files. I don't want to override his changes so I do `theme download` before kicking off my work. Just one example.
1. [Update python installation script to use Python 3.x](https://github.com/Shopify/themekit/issues/725) - the installation process should be: `<most_mainstream_package_manager_for_platform> install shopify-theme-kit`
2. `theme watch` is slow to acknowledge it's uploading files, then suddenly "processing + Updated" shows (speaking of UX, "processing" is lowercase, "Updated" is uppercase
2. Do retries on timeout. Also:
  > [development] (assets/application.scss.liquid) request timed out. if you are receive this error consistently, try increasing the timeout in your config
   There's no explanation how to do this. I don't have any timeout setting in my `config.yml` and it would be great if I didn't have to go to repo/documentation to figure out how to achieve this
5. "Invalid JSON" could probably point to the line where the error is. There are online tools that can do this for free. Perhaps something could be embedded in the tool?
6. Please don't deprecate this tool after 6 months or so.

**Comment by tanema** [comment]
> Make it possible/faster to upload multiple files at once. I'm not sure of go's multi-threading capabilities, but uploading/downloading 200 files is a pain in the a$$. But who uploads/downloads 200 files? Glad you asked. :) My client is a bit tech-savy so he sometimes likes to make changes to theme files. I don't want to override his changes so I do theme download before kicking off my work. Just one example.

Themekit already does every file operation concurrently, to the limit of restrictions in networks and throttles. It is the main reason it was written in Go. The WIP you are currently seeing is us actually changing the foundations of shopify assets APIs so that we can optimize these.

> Update python installation script to use Python 3.x - the installation process should be:

This is WIP already from the work we have done on improving the distribution of the shopify CLI

> theme watch is slow to acknowledge it's uploading files, then suddenly "processing + Updated" shows (speaking of UX, "processing" is lowercase, "Updated" is uppercase

This is part of the current work in progress along with deliberate debouncing of file operation events.

> Do retries on timeout.

We are trying to eliminate timeouts but may do this in the future.

> "Invalid JSON" could probably point to the line where the error is. There are online tools that can do this for free. Perhaps something could be embedded in the tool?

This error does not come from themekit it is coming from shopify. We may be able to to find lint your json but as you say there are other tools, especially those that are built into editors to help you with this.

> Please don't deprecate this tool after 6 months or so.

I have personally been working on themekit for 4 years and have actively advocating for change, going so far as to get involved with leadership so as to push changes through. 

> Consider including your users into feedback loop/roadmap?

We constantly interview partners about our tools and I have personally sat on many phone calls with partners voicing their frustrations with the tool. Because you have not been involved does not mean it does not happen. 

If there are changes you think might be easy to implement, I suggest opening a PR.

**Comment by vfonic** [comment]
> Themekit already does every file operation concurrently, to the limit of restrictions in networks and throttles. It is the main reason it was written in Go. The WIP you are currently seeing is us actually changing the foundations of shopify assets APIs so that we can optimize these.

This is great! But in practice, I'm seeing themekit being vastly slower than other tools I've used and uploading files one by one. What I need to do to achieve this concurrency?

>>Update python installation script to use Python 3.x - the installation process should be:

>This is WIP already from the work we have done on improving the distribution of the shopify CLI

Would be nice if someone would reply to Mr. @larsschellhas' 22 days old issue.

> This is part of the current work in progress along with deliberate debouncing of file operation events.

Sounds amazing! Thank you, sir! :)

> We are trying to eliminate timeouts

Good luck! :)

>> "Invalid JSON" could probably point to the line where the error is. There are online tools that can do this for free. Perhaps something could be embedded in the tool?

> This error does not come from themekit it is coming from shopify. We may be able to to find lint your json but as you say there are other tools, especially those that are built into editors to help you with this.

I've noticed a lot of issues here talking about UX. Using other tools is killing the UX. User has to copy the entire schema JSON and paste it into some online service. Or have editor plugin that can validate JSON in liquid files. Or copy-paste just the JSON to a new file and use JSON linter.
I don't know of any plugin for liquid offering JSON linting for any of the text editors. Do you know any? I'd love to give it a try.
Even then, with JSON linter enabled in editor, we still don't have things like: "heading" is not a valid key (it should be "header" for example). So this fix has to be done on Shopify's end. Or we're left with recreating Shopify's backend JSON validation locally and then hope the API/validation rules doesn't change (which is just about to happen)

>>Please don't deprecate this tool after 6 months or so.

> I have personally been working on themekit for 4 years and have actively advocating for change, going so far as to get involved with leadership so as to push changes through.

Thank you so much! I really appreciate it! <3 In the past couple of years (about 5+) that I've been working with Shopify platform, I've seen many tools getting deprecated, forums with so many threads old and unanswered and documentation missing. Even now we're in this limbo state of waiting for new sections, while still needing to dig up the "old" (actually "current") documentation for sections, which has been buried somewhere.
All in all, I do see a lot of change in the right direction for well over a year now! Shopify stuff replying on forums, new features being released and tons of documentation added. People see this and appreciate it!

>>Consider including your users into feedback loop/roadmap?

>We constantly interview partners about our tools and I have personally sat on many phone calls with partners voicing their frustrations with the tool. Because you have not been involved does not mean it does not happen.

Oh, I wasn't aware of that! Thanks for doing that. I guess I was wrong with my perception of how you were rolling out new changes.

Glad to see this going in the right direction.

PS Just a tiny plea, if you could have a second look at reviving slate. I think that tool had a great potential of being a much more comprehensive solution for local theme development.

And if I didn't say enough: Thank you for your work!
