### ISSUE TITLE
When I run the themekit setup it creates a new theme in the same directory. Can this be routed into a subdirectory?

### ISSUE THREAD

**Issue by echorashmi** [Shopify/themekit#753]
I followed the instructions as posted here:

https://shopify.github.io/themekit/

specifically these steps to Create a New Theme:

```
Create a new theme.
If you are starting from scratch and want to get a quick start, run the following:

theme new --password=[your-password] --store=[your-store.myshopify.com] --name=[theme name]
```

When I did this, it created the theme in the parent folder (I was expecting a sub-folder to be created). 

Now I'm not sure if I can copy-paste and move the specific files to a subfolder or what to do with the orphaned files, it's really inconvenient and sort of a barrier to a newbie getting started on this. 

I'd recommend either updating the documentation to include this step, or auto-creating a subfolder given the theme name.

**Comment by tanema** [comment]
This can be pointed at a directory by using the `--directory` flag however that will still create the config file in the current directory that you are in. 

We will update the docs to reflect this, thank you for your feedback.

**Comment by Andrewngabriel** [comment]
I just tried to use `--directory` flag in the following context
```bash
theme new --directory="custom-shopify-theme" --password="123" --store="themekit.myshopify.com" --name="Custom Theme"
```
however I got the following error `unknown flag: --directory`. Is there something I'm doing wrong?

I'm happy to update the documentation to include this flag once I confirm how to properly use it locally. Thanks!

**Comment by tanema** [comment]
Sorry, yes the flag is `--dir` not `--directory`. You can see all of the available flags for each command using the `--help` flag. In this case `theme new --help`
