### ISSUE TITLE
Change blue output text to light blue

### ISSUE THREAD

**Issue by cshold** [Shopify/themekit#76]
To improve readability in terminal, can we use a lighter blue for the text?

![screen shot 2015-09-04 at 1 53 29 pm](https://cloud.githubusercontent.com/assets/1730309/9690757/56402f44-530c-11e5-97b4-0f0b5bc66a7a.png)

**Comment by csaunders** [comment]
That's a configuration change you need to make in your terminal. ANSI blue always sucks.

**Comment by cshold** [comment]
:+1:
