### ISSUE TITLE
Issue setting up new theme

### ISSUE THREAD

**Issue by nathansnelgrove** [Shopify/themekit#766]
Hey there,

New to Themekit and new to Shopify (but very familiar with Liquid).

I'm trying to set up a new theme for an existing client and am running this command exactly:

`
theme new --password=[your-password] --store=[your-store.myshopify.com] --name=[theme name]
`

Of course, I'm not including the square brackets. I've put double quotes around the theme name, and I've tried using both my login password and the API password. No matter what I do, I'm getting an error message back that I don't understand:

`
invalid environment [development]: (missing theme_id)
`

There isn't a theme ID; this is a new theme for a new store. Or am I missing something?

Thanks in advance for whatever help you can provide.

**Comment by tanema** [comment]
Hi it looks like you have discovered a bug in our new release. I will patch it ASAP

**Comment by nathansnelgrove** [comment]
@tanema I managed to fix this by adding a theme ID to the list of theme new:

`
theme new --password=[your-password] --store=[your-store.myshopify.com] --name=[theme name] -t=1
`

Hopefully that doesn't add any complexities to development further down the line. Thanks for getting back to me so quickly and I'm looking forward to a patch!

**Comment by tanema** [comment]
Yeah I was just going to mention that a work around would be to provide a bogus theme id. It doesn't change anything, the bug is only in our validations.
