### ISSUE TITLE
Cannot upload customer templates

### ISSUE THREAD

**Issue by cshold** [Shopify/themekit#77]
I get the same error on every customer template:

![screen shot 2015-09-08 at 9 50 19 am](https://cloud.githubusercontent.com/assets/1730309/9736421/16895000-560f-11e5-8620-3d75a92ebc8e.png)

Uploading via admin or theme gem work as expected.

@csaunders 

cc @mpiotrowicz @stevebosworth

**Comment by cshold** [comment]
`theme upload templates/*` does upload them as expected. Steve, could this be a gulp issue then?

**Comment by thisislawatts** [comment]
Which version of themekit are you running? I believe this was fixed just last week. https://github.com/Shopify/themekit/issues/60

**Comment by cshold** [comment]
Ah, just updated to 0.2.7 and seems to work well, although no more colors in terminal. Thanks.

**Comment by csaunders** [comment]
The missing colours appear to be an issue with the console thing you are
using with Gulp. If you run themekit outside of your tooling the colours
should be working correctly. If that is not the case, let me know.

On Tue, Sep 8, 2015 at 10:11 AM, Carson Shold <notifications@github.com>
wrote:

> Closed #77 <https://github.com/Shopify/themekit/issues/77>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shopify/themekit/issues/77#event-403669295>.
>



-- 
Chris Saunders // Developer @ Shopify
