### ISSUE TITLE
Theme watch is not working after updating themekit

### ISSUE THREAD

**Issue by faisalfaisi91** [Shopify/themekit#770]
I run the theme update command this morning, and after that theme watch command is not working anymore. I'm getting the following error on my Dev instance.

"[development] This is the live theme on xxxxxx. If you wish to make changes to it, then you will have to pass the --allow-live flag cannot make changes to a live theme without an override".

Anyone can help me on this? how to solve the problem?

Thanks
Regards
Faisal

**Comment by Kehza** [comment]
The solution is in your message? Pass in '--allow-live flag' during your call when working with a Live Theme.
