### ISSUE TITLE
theme download stopped working without a theme_id

### ISSUE THREAD

**Issue by sonmic** [Shopify/themekit#780]
**Describe the bug**
`theme download` used to download the live theme without the `--themeid` option, but in recent versions it fails with:
```
invalid environment [development]: (missing theme_id)
```

**To Reproduce**
1. run command 'theme download --password=mypassword --store=store.myshopify.com --dir=mydir' 

**Expected behavior**
It should download the live theme.

**Environment (please complete the following information):**
- OS: Mac, Linux
- Themekit version: 1.1.0, 1.1.1

**Comment by tanema** [comment]
Yes, this is not a bug. We have made the theme_id required so that people will no longer accidentally edit their live themes.
