### ISSUE TITLE
invalid environment [development]: (invalid project directory lstat build: no such file or directory)

### ISSUE THREAD

**Issue by brantward** [Shopify/themekit#787]
**Describe the bug**
Getting the following error after running 'theme deploy'
```invalid environment [development]: (invalid project directory lstat build: no such file or directory)```

**To Reproduce**
1. in a new directory, run command `theme new --p=[password] --s=[store.myshopify.com]`
2. check to make sure new theme has been uploaded by running command `theme get --list --p=[password] --s=[store.myshopify.com]`
3. if theme upload is successful, run command `theme deploy`
4. I then see the response; `invalid environment [development]: (invalid project directory lstat build: no such file or directory)`

**Expected behavior**
Deploy command should be successful.

**Environment (please complete the following information):**
 - OS [e.g. iOS]: macOS Catalina 10.15.6 
 - Themekit version [e.g. v0.7.5]: versions 1.0.0 - 1.1.1
 - Editor [e.g. atom, sublime]: none
 - Ignore: none

**Additional context**
For me, `theme deploy` / `theme upload` works for any version below v1.0.0

**Comment by tanema** [comment]
It seems like you are using a `directory` config somewhere, in your `config.yml`, flags, env var or global config that points to a directory called `build` that does not exist in your current project.

**Comment by brantward** [comment]
@tanema Legend. It was a global variables file. Thanks so much!
