### ISSUE TITLE
Checksum checking feature has very verbose logging

### ISSUE THREAD

**Issue by romainmenke** [Shopify/themekit#789]
```
processing ....
Skipped ... (Checksum: ...)
```

Can these logs be behind the `verbose` flag?

**Comment by romainmenke** [comment]
Thank you for the follow up.

This indeed happens when first running the `watch` command.
I understand wanting to give feedback during this process but for example the `download` already logs differently.

A less verbose option would be to follow the already existing functionality of showing a progress bar :

```
104|104 [==============================================================]  100 %
```

**Comment by tanema** [comment]
How would a progress bar work for watch, a command the has nothing to do unless you do something. And then when you do something it uploads a single file. A progress bar is meaningless in this context. 

The output of the watch command is consistent with other tools that have similar behaviour

**Comment by romainmenke** [comment]
Looked through the source code it seems to be the result of how the file watcher polling works.
The watcher (`github.com/radovskyb/watcher`) keeps an in memory state of when a file was last modified.
On the first run this state is missing and emits a first series of events ,causing the `theme watch` command to log once for each file.

Looking at it more closely I do not think a distinction can be made between these initial events and actual file change events.

Just to clarify :

I have absolutely no issue with logging actual events during the watching process.
It are the initial logs when starting the command that bug me.

This seemed an obvious issue to me and I did not take the time to fully explain my case.

**Comment by romainmenke** [comment]
Closing this.

Thank you your feedback :)
