### ISSUE TITLE
theme upload errors out on layout/theme.liquid

### ISSUE THREAD

**Issue by cshold** [Shopify/themekit#79]
Similar to https://github.com/Shopify/themekit/issues/78, `theme upload layout/*` works, but `theme watch` errors out when editing `layout/theme.liquid`. If I remove the offending lines causing syntax errors, a different error pops up. Uploading via admin also works as expected.

```
>> theme upload layout/*
Successfully performed Update operation for file layout/theme.liquid to carson-blank.myshopify.com
~/Documents/Projects/shopify-themes/Venture

>> theme watch
Spawning 2 workers for carson-blank.myshopify.com
carson-blank.myshopify.com Worker #0 ready to upload local changes
carson-blank.myshopify.com Worker #1 ready to upload local changes
Received Update event on layout/theme.liquid
Could not upload layout/theme.liquid:
	Liquid syntax error (line 477): 'if' tag was never closed
```
@csaunders

**Comment by csaunders** [comment]
Is this causing the application to crash? It seems like getting the
feedback you are getting back from the attempted upload is correct.

When you make the appropriate fix, are you still getting errors?

Could you include replication steps similar to these guidelines?
<https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines#str>
?

On Wed, Sep 9, 2015 at 10:07 AM, Carson Shold <notifications@github.com>
wrote:

> Similar to #78 <https://github.com/Shopify/themekit/issues/78>, theme
> upload layout/* works, but theme watch errors out when editing
> layout/theme.liquid. If I remove the offending lines causing syntax
> errors, a different error pops up. Uploading via admin also works as
> expected.
>
> >> theme upload layout/*
> Successfully performed Update operation for file layout/theme.liquid to carson-blank.myshopify.com
> ~/Documents/Projects/shopify-themes/Venture
>
> >> theme watch
> Spawning 2 workers for carson-blank.myshopify.comcarson-blank.myshopify.com Worker #0 ready to upload local changescarson-blank.myshopify.com Worker #1 ready to upload local changes
> Received Update event on layout/theme.liquid
> Could not upload layout/theme.liquid:
>     Liquid syntax error (line 477): 'if' tag was never closed
>
> @csaunders <https://github.com/csaunders>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shopify/themekit/issues/79>.
>



-- 
Chris Saunders // Developer @ Shopify

**Comment by cshold** [comment]
App does not crash, just shows the error. The error listed isn't actually an error, so there's nothing to fix. Strangest part, randomly removing a line and re-saving sometimes uploads it properly during `theme watch`, and other times says there's an error. Gif might help explain a bit:

![themekit](https://cloud.githubusercontent.com/assets/1730309/9765580/f681b3ae-56e2-11e5-895e-4ea88d09171e.gif)

I can reproduce by following these steps:
1. Run `theme watch`
2. Remove a line of code and save. Seems to be any line, liquid or not

Expected result:
Upload file (assuming there are no liquid errors)

Actual result:
Sometimes uploads the file, sometimes says there is a liquid error

**Comment by stevebosworth** [comment]
++ I also run into this issue.  Haven't managed to catch it with mitmproxy though :-(

**Comment by matharoo** [comment]
I just started developing theme for shopify based on Timber and I encountered this issue as well . For me its happening only if I use themekit on Ubuntu. It works fine without any issues on Windows machine. 

So themekit for linux needs to be fixed.

**Comment by jazty** [comment]
I'm constantly having this issue as well. It seems to be that the files are only being partially uploaded to Shopify. When I see an error in SCSS files it's most commonly because the uploaded file is missing a significant chunk. I can confirm this by opening the online file editor and viewing the SCSS file. The same seems to be happening with liquid template files. The errors are thrown because the server only got a piece of the liquid file. Would sure like to get a fix on this one! It happens all the time to me.

Here's a fine example that just now occurred. With 'theme watch' running I saved a theme.scss.liquid file and got the "Successfully performed upload" response. The file locally  is 4499 lines long. If I view that file with the online editor it is only 593 lines and ends with:

```
/*================ Responsive Text Alignment Helper ================*/
@mixin responsive-text-align-helper($grid-breakpoint-type:"") {
  .#{$grid-breakpoint-type}text-left {
    text-align:
```

That'll break it..
