### ISSUE TITLE
Remove mentions of Timber theme from docs

### ISSUE THREAD

**Issue by andyw8** [Shopify/themekit#795]
**Describe the bug**

The docs currently say "New will create theme using Shopify Timber" but this is no longer true.

(and [Timber](https://github.com/Shopify/Timber) is deprecated).

**Comment by Andrewngabriel** [comment]
I have an open [PR](https://github.com/Shopify/themekit/pull/788) for updating documentation and I just removed Timber from it. Feel free to take a look and let me know if I missed it anywhere else.
