### ISSUE TITLE
No output when using the fish shell

### ISSUE THREAD

**Issue by Vincent-Carrier** [Shopify/themekit#805]
**Describe the bug**
When using any `theme` command in the fish shell, nothing is printed to stdout / stderr. Status code is always 0.

**Expected behavior**
It should behave the same way as it does in bash.

**Environment (please complete the following information):**
 - OS [e.g. iOS]: MacOS 11.0 Beta
- Themekit version [e.g. v0.7.5]: 1.1.1 AMD/64
- Fish version 3.0.2

**Comment by andyw8** [comment]
Hi @Vincent-Carrier 

I installed fish through Homebrew but wasn't able to produce this problem.

```
> fish -v
fish, version 3.1.2
> theme -v
Theme Kit is a tool kit for manipulating shopify themes

Theme Kit is a fast and cross platform tool that enables you to build shopify themes with ease.

Complete documentation is available at https://shopify.github.io/themekit/
...
```

I notice you're running an older version of Themekit, could you try update to the latest?

If it still fails, then I wonder if this could be an issue due to the beta version of MacOS? Do you have any other machine you could test on?

**Comment by carlosreyes** [comment]
I've been using 

MacOS 10.14.4
ThemeKit 1.1.1 darwin/amd64 (and previous versions)
fish, version 3.0.2

on the daily, and so far no issues with it.

**Comment by tanema** [comment]
Also, can you test if it does actually work in Bash on your Beta MacOS so we know if we are in for a larger headache soon? :D

**Comment by andyw8** [comment]
@Vincent-Carrier please also share the output of running `which theme`.

**Comment by Vincent-Carrier** [comment]
Yes it works in bash just fine. 

```
$ which theme
/usr/local/bin/theme
```

I updated fish to 3.1 to no avail.
Probably the macOS beta.

**Comment by Vincent-Carrier** [comment]
Works on my new MacBook Pro. Closing :)
