### ISSUE TITLE
Minify JS/CSS prior to uploading to remote server

### ISSUE THREAD

**Issue by theo1985** [Shopify/themekit#807]
**Is your feature request related to a problem? Please describe.**
Speed performance is coming center stage in Shopify and search engines

**Describe the solution you'd like**
Source files should have the option to have a minified version uploaded to the remote server, keeping local source file un-minified and easy to read/edit.

**Describe alternatives you've considered**
Keeping two copies of my own and manually minifying resources in use and upload.

**Additional context**
N/A

**Comment by andyw8** [comment]
Hi @theo1985 

This isn't something that Theme Kit itself would support, but you can configure a build system to automatically minify the files when you save them. You can learn more here: https://www.shopify.ca/partners/blog/minification

**Comment by tanema** [comment]
Themekit is meant to be used in coordination with other tools. Since I don't pretend that we can do these things as good as those tools then I will leave it to them.
