### ISSUE TITLE
Slightly extremely elevated CPU usage

### ISSUE THREAD

**Issue by stevebosworth** [Shopify/themekit#81]
High CPU usage:
<img width="802" alt="screenshot 2015-09-10 16 09 10" src="https://cloud.githubusercontent.com/assets/1938373/9800692/738e4728-57dc-11e5-9b14-4ba3db6ef837.png">

After quitting then restarting: 
<img width="803" alt="screenshot 2015-09-10 16 18 16" src="https://cloud.githubusercontent.com/assets/1938373/9800800/25da981e-57dd-11e5-9f10-704f45b71e4f.png">

After manually killing each process in activity monitor and restarting themekit:
<img width="804" alt="screenshot 2015-09-10 16 40 36" src="https://cloud.githubusercontent.com/assets/1938373/9800739/c1d09620-57dc-11e5-877f-342c675fe651.png">

**Comment by csaunders** [comment]
Hmmm... I wonder if we have some rogue process problems going on here. I don't think that would be the case, but maybe something is causing us to Orphan processes or something? I don't know enough about the go runtime to be sure that's even possible.

We are using a super old version of fsnotify, so upgrading to another version that has better OS notification adapter integrations might be the more appropriate place to look for this.

https://github.com/go-fsnotify/fsnotify

**Comment by csaunders** [comment]
I'm going to remove this from the milestone for now. There's a few other bugs I want to close off before tackling this one.

With the possible API changes in fsnotify, it could end up being a time consuming yak shave.

**Comment by stevebosworth** [comment]
sounds good.  Shall I'll keep an eye on activity monitor to see if I can provide any more info?

**Comment by csaunders** [comment]
Turns out we are indeed using the most recent version of fsnotify. :/

**Comment by stevebosworth** [comment]
Closing this issue.  Turns out it was the result of using themekit with gulp using a node `child_process` with `exec` as opposed to `spawn`.
