### ISSUE TITLE
Cannot make changes to the live theme

### ISSUE THREAD

**Issue by dylandavis13** [Shopify/themekit#811]
I used to be able to make changes to my theme when it was live now that I have updated my themekit I get "if i wish to make changes then I will have to pass the --allow-live flag. cannot make changes to a live theme without an override.

**To Reproduce**
1. set your theme to the live theme on your shopify site
2. rune theme watch
3. 

**Expected behavior**
I run theme watch and I am then able to freely make edits on my live site

**Environment (please complete the following information):**
 - OS [e.g. iOS]: windows 10 pro 
- Themekit version (run theme version to check): 1.1.1
 - Editor [e.g. atom, sublime]: sublime
 - Ignore:

**Additional context**

**Comment by andyw8** [comment]
Hi @dylandavis13 

As the message indicate, you'll need to run `theme watch --allow-live` if you're making changes to a live theme.
