### ISSUE TITLE
[999]Could not perform Update to assets/shop.scss.liquid at Host Unknown

### ISSUE THREAD

**Issue by stevebosworth** [Shopify/themekit#82]
Got the following error from themekit after running our concat css task.  It doesn't look like anything was picked up by mitmproxy either.

![screenshot 2015-09-10 19 15 28](https://cloud.githubusercontent.com/assets/1938373/9803430/84eb617c-57f0-11e5-8506-fc2e97c15c1d.png)

**Comment by stevebosworth** [comment]
Saving the `config.yml` AND restarting `theme watch` seems to resolve the issue.

**Comment by csaunders** [comment]
I'm having a hard time replicating this issue.

**Comment by tanema** [comment]
Closing because this is stale. Please reopen if this is still an issue.

**Comment by pkavanaghjr** [comment]
Hey, im having a similar error showing up.

I have been developing the past couple weeks and all day today using themekit with no issues and have been loving it, until today when this error appeared seemingly out of nowhere.

`[999]Could not perform Update to templates/page.help.liquid at Host Unknown
	Put https://_mystore_.myshopify.com/admin/themes/156958152/assets.json: dial tcp: lookup _mystore_.myshopify.com: no such host`

I didnt do anything different to cause the error to appear, it seemed to just start happening. The only thing that changed was I added another scss import to my main scss file. But ive dont this multiple times today with no issues until now.

**Comment by tanema** [comment]
@pkavanaghjr Is this every request? Is it only on one asset update? What version of themekit are you using?

**Comment by pkavanaghjr** [comment]
on Theme Kit v0.4.6 and yes it is for every request. I havent been able to upload anything for about the past hour.

**Comment by tanema** [comment]
@pkavanaghjr can you please send me your config.yml to tim.anema@shopify.com I will look into it more closely

**Comment by pkavanaghjr** [comment]
Just sent you an email, thank you so much for the quick responses!
