### ISSUE TITLE
"theme open" parameter to hide the preview bar

### ISSUE THREAD

**Issue by designbuedchen** [Shopify/themekit#820]
**Is your feature request related to a problem? Please describe.**
It disturbs me that I always have to manually append ?pb=0 when I use the "theme open" command.

**Describe the solution you'd like**
I want to enter "theme open --without-pb" and then it magically opens https://foo.myshopify.com?preview_theme_id=123456&pb=0 without the theme preview bar.

**Describe alternatives you've considered**
I think there is no alternative to such a good solution... ;-)

**Additional context**
Not needed.

**Comment by tanema** [comment]
Since we will not be merging anything around Black Friday/Cyber Monday, I have created a prerelease with the fixes for this issue included in it. You can install the prerelease by running `theme update --version=v1.1.3-pre`, please share any feedback that you have on this.
