### ISSUE TITLE
`theme download` errors out "silently"

### ISSUE THREAD

**Issue by vfonic** [Shopify/themekit#822]
I had ignored `config/settings_data.json` in my `config.yml`.

```yaml
  ignore_files:
    - config/settings_data.json
```

I forgot I had it ignored and wanted to download latest settings data from the theme to make some simple change within the HTML data and upload it back up.

I ran:
```sh
theme download config/settings_data.json
```

Here's the full output:
```
> theme download config/settings_data.json
[development] Warning, this is the live theme on store-name.
No file paths matched the inputted arguments
```

`development` and `store-name` are in yellow, the rest of the text is in white (default color).

I missed this message unfortunately and thought everything went well.
I made the changes to (old) `settings_data.json` and pushed it to live site.
Only later did I realize that I never downloaded the latest `settings_data.json` from the live site.

I think this warning/error message should be more prominent. Something similar to how `[development]` is in yellow:

```
[development] WARNING: No file paths matched the inputted arguments!
```

**Comment by tanema** [comment]
Since we will not be merging anything around Black Friday/Cyber Monday, I have created a prerelease with the fixes for this issue included in it. You can install the prerelease by running theme update --version=v1.1.3-pre, please share any feedback that you have on this.
