### ISSUE TITLE
`theme deploy` errors silently

### ISSUE THREAD

**Issue by vfonic** [Shopify/themekit#823]
// related: [`theme download` errors out "silently"](https://github.com/Shopify/themekit/issues/822)

If any file fails to upload (deploy), for example, a section file fails to upload because it has invalid schema, then deployment continues. Eventually, having deployment continue and finish, breaks the website, as the section file wasn't deployed along with all the other files.

Failing to upload any file should immediately fail the whole deployment.

**To Reproduce**
1. Open any section file in the theme.
2. Change `"name"` property inside of `{% schema %}` block to: `"Collections Page Filter Header"` (anything longer than 25 characters would do
3. Run `theme deploy`

Or 

3.b Run `theme deploy sections/<your-section-name>.liquid`

Run `echo $?` immediately after.

<details><summary>Here's the sample output from `theme deploy`</summary>

```
...
[production] Updated assets/currencies.jquery.min.js
[production] Updated assets/icon-strong.png
[production] Updated assets/styles-min.css
[production] Updated assets/linkedin.png
[production] Updated assets/whatsapp.png
[production] Updated assets/twitter.png
[production] Updated assets/ico-select-menu.svg.liquid
[production] Updated assets/icon-moderate.png
[production] Updated assets/facebook.png
[production] Updated assets/theme.js.liquid
[production] (sections/collections-page-filter-header.liquid) Invalid schema: name is too long (max 25 characters)
[production] Updated assets/mail_old.png
[production] Updated assets/logo.png
[production] Updated assets/password.js.liquid
[production] Updated assets/script.js
[production] Updated layout/theme.liquid
[production] Updated assets/gift-card.scss.liquid
[production] Updated assets/pointing.png
[production] Updated assets/mail.png
[production] Updated assets/simulator.js
[production] Updated assets/password-page-background.jpg
[production] Updated assets/vendor-scripts.js
...
```

</details>

**Expected behavior**

The command should fail.

`echo $?` - prints last command's exit code. It's 0 for success and different from 0 for failure.
It should print a non-zero code.

**Environment (please complete the following information):**
 - OS [e.g. iOS]: macOS 10.15.7
- Themekit version (run theme version to check): 1.1.2 darwin/amd64
 - Editor [e.g. atom, sublime]: sublime
 - Ignore: /

**Comment by tanema** [comment]
Since we will not be merging anything around Black Friday/Cyber Monday, I have created a prerelease with the fixes for this issue included in it. You can install the prerelease by running `theme update --version=v1.1.3-pre`, please share any feedback that you have on this.
