### ISSUE TITLE
DNS problem while connecting to Shopify, this indicates a problem with your internet connection - but my internet connection is fine

### ISSUE THREAD

**Issue by connor-btown** [Shopify/themekit#824]
**Describe the bug**
My internet connection works, but I get the error "DNS problem while connecting to Shopify, this indicates a problem with your internet connection"

**To Reproduce**
1. run command 'theme watch'

**Expected behavior**
Theme watch to run

**Environment (please complete the following information):**
 - OS [e.g. iOS]: macOS Catalina 10.15.6
- Themekit version (run theme version to check): 1.1.2
 - Editor [e.g. atom, sublime]:
Visual Studio Code
Version: 1.50.0
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:00:00.397Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
 - Ignore:

**Additional context**
N/A

**Comment by andyw8** [comment]
Hi @connor-btown 

Could you please verify that you're able to ping your store, e.g. `ping mystore.shopify.com`

And please also share the output from `nslookup` e.g. (`nslookup mystore.shopify.com`)

You can remove your store name from the output if you wish to keep that private.

**Comment by connor-btown** [comment]
Hey @andyw8 really appreciate the quick comment. I'm going to be removing my store name I'm working on and replacing it with "mystore"

So `ping mystore.myshopify.com` gives me:

`ping: cannot resolve mystore.myshopify.com: Unknown host`

`ping https://mystore.myshopify.com` gets a successful ping response:

```
PING 23.227.38.64.addr.shopifyedge.com (23.227.38.64): 56 data bytes
64 bytes from 23.227.38.64: icmp_seq=0 ttl=57 time=13.232 ms
64 bytes from 23.227.38.64: icmp_seq=1 ttl=57 time=12.729 ms
64 bytes from 23.227.38.64: icmp_seq=2 ttl=57 time=16.408 ms
64 bytes from 23.227.38.64: icmp_seq=3 ttl=57 time=14.526 ms
64 bytes from 23.227.38.64: icmp_seq=4 ttl=57 time=13.135 ms
64 bytes from 23.227.38.64: icmp_seq=5 ttl=57 time=13.438 ms
64 bytes from 23.227.38.64: icmp_seq=6 ttl=57 time=13.037 ms
64 bytes from 23.227.38.64: icmp_seq=7 ttl=57 time=13.180 ms
64 bytes from 23.227.38.64: icmp_seq=8 ttl=57 time=13.301 ms
64 bytes from 23.227.38.64: icmp_seq=9 ttl=57 time=15.349 ms
64 bytes from 23.227.38.64: icmp_seq=10 ttl=57 time=14.199 ms
64 bytes from 23.227.38.64: icmp_seq=11 ttl=57 time=13.845 ms
64 bytes from 23.227.38.64: icmp_seq=12 ttl=57 time=13.243 ms
64 bytes from 23.227.38.64: icmp_seq=13 ttl=57 time=13.008 ms
64 bytes from 23.227.38.64: icmp_seq=14 ttl=57 time=14.887 ms
64 bytes from 23.227.38.64: icmp_seq=15 ttl=57 time=13.194 ms
^C
--- 23.227.38.64.addr.shopifyedge.com ping statistics ---
16 packets transmitted, 16 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 12.729/13.794/16.408/0.988 ms
```

the result of `nslookup https://mystore.myshopify.com` and `nslookup mystore.myshopify.com` are essentially the same:

**https:**

```
Server:         192.168.1.1
Address:        192.168.1.1#53

Non-authoritative answer:
https://mystore.myshopify.com canonical name = shops.myshopify.com.
shops.myshopify.com     canonical name = core-shops.tm.shopifysvc.com.
core-shops.tm.shopifysvc.com    canonical name = 23.227.38.64.addr.shopifyedge.com.
Name:   23.227.38.64.addr.shopifyedge.com
Address: 23.227.38.64
```
**no https:**

```
Server:         192.168.1.1
Address:        192.168.1.1#53

Non-authoritative answer:
mystore.myshopify.com canonical name = shops.myshopify.com.
shops.myshopify.com     canonical name = core-shops.tm.shopifysvc.com.
core-shops.tm.shopifysvc.com    canonical name = 23.227.38.64.addr.shopifyedge.com.
Name:   23.227.38.64.addr.shopifyedge.com
Address: 23.227.38.64
```

Hopefully this is helpful.

**Comment by andyw8** [comment]
> ping: cannot resolve mystore.myshopify.com: Unknown host

This indicates something is wrong... are you behind a proxy or corporate network by chance?

If you can email me with your real store name then I can try dig further (andy.waite at shopify.com).

**Comment by andyw8** [comment]
Also, it's odd that it's resolving to `192.168.1.1` (usually your router) – have you made any edits to your `hosts`  file for testing?

**Comment by cpsoinos** [comment]
I'm also seeing the same issue for my store today 🤔 . Following along for any updates!

**Comment by cpsoinos** [comment]
Update: I'm able to successfully connect using Cloudflare WARP (https://1.1.1.1/), but if I turn that off I'm back to `DNS problem while connecting to Shopify, this indicates a problem with your internet connection`.

**Comment by connor-btown** [comment]
@cpsoinos how do you turn that on?

FYI the issue just resolved itself out of nowhere, it seems fine now...

**Comment by cpsoinos** [comment]
@connor-btown it's an app by Cloudflare you can download from that URL and install on your machine. It's not specific to Shopify or themekit

**Comment by andyw8** [comment]
@cpsoinos you may want to try flushing the DNS cache:

https://help.dreamhost.com/hc/en-us/articles/214981288-Flushing-your-DNS-cache-in-Mac-OS-X-and-Linux

**Comment by cpsoinos** [comment]
> @cpsoinos you may want to try flushing the DNS cache:
> 
> https://help.dreamhost.com/hc/en-us/articles/214981288-Flushing-your-DNS-cache-in-Mac-OS-X-and-Linux

I was hoping this would make a difference, but no luck :\ at least I have a workaround with Cloudflare Warp

**Comment by hecpalomares** [comment]
Having the same issues, trying to deploy to my Live theme

Describe the bug
My internet connection works, but I get the error "DNS problem while connecting to Shopify, this indicates a problem with your internet connection"

To Reproduce
Steps to reproduce the behavior:

run command 'theme watch'
Expected behavior
Theme watch to run

Environment (please complete the following information):

OS [e.g. iOS]: macOS Mojave 10.14.5
Themekit version (run theme version to check): 1.1.2

Editor [e.g. atom, sublime]:
Visual Studio Code

Ignore:
Additional context
N/A

**Comment by andyw8** [comment]
If anyone is still running into this issue today please 👍 this post, otherwise 👎 .

**Comment by connor-btown** [comment]
Hey @andyw8 this seems to have just fixed itself...? the problem went away. can't speak for other folks though. feel free to close the issue.

**Comment by hecpalomares** [comment]
Hey @andyw8, the problem went away on my end too.

**Comment by cpsoinos** [comment]
@andyw8 it seems to have resolved for me, as well!

**Comment by andyw8** [comment]
Closing as this appears to have been a temporary connectivity issue.
