### ISSUE TITLE
pagina de carrinho tira o pop pu 

### ISSUE THREAD

**Issue by eduardoadsmkt** [Shopify/themekit#825]
** Is your feature request related to a problem? Please describe. **
then friend i would like to see that pop pu of the theme when you add the product to the cart and pop the po on the right screen i would like to remove it from the botap checkout boot check cart .. and why i don't use the shopify checkout I use a weaver and my checkout only works on the cart page, you understand, then it would be better for me to remove the right pu pop and poppu when you press the cart, you can endete me if you can help me noix can even negotiate because I need it the most quick as possible please ..

** Describe the solution you'd like **
take the two pop pu, I want my cart as a page understood when customer clicks add the cart go straight to the cart page understood you can help me please i pay for the service

** Describe alternatives you've considered **
it has the best bro but it would be good for me to get this pop pu out of the carirnho, can you help me ?? and why i use checkerboard please help me

my contot 2796419620

** Additional context **
![mai](https://user-images.githubusercontent.com/72841353/95932842-439b1780-0da3-11eb-80f8-ec76ba9deffa.png)
![ima](https://user-images.githubusercontent.com/72841353/95932851-4990f880-0da3-11eb-9345-114795a68cf0.png)

**Comment by paulomarg** [comment]
Hi @eduardoadsmkt, issues in this repository should only be used for bugs and questions about the themekit tool, so unfortunately we won't be able to help you with your question. You can try asking your question in the [Shopify Community Forums](https://community.shopify.com/), and you'll be able to get some help on your problem.
