### ISSUE TITLE
Error on product page, product price bug

### ISSUE THREAD

**Issue by Requ17** [Shopify/themekit#830]
**Describe the bug**
The error is on the product page of my shopify store, when you select the color of the product several times, every click you make comes out a new price of the product repeatedly, this scares the customers and I would like to fix it.

<a href="https://gyazo.com/2c88c3e97d69e4e14f8acb3a2a113a84"><img src="https://i.gyazo.com/2c88c3e97d69e4e14f8acb3a2a113a84.png" alt="Image from Gyazo" width="1054"/></a>

**To Reproduce**
1. run command 'theme new --password=mypassword --store=store.myshopify.com --name=theme'
2. 
3. 

**Expected behavior**
The normal thing would be to be able to select several colors of the product and that the price appears correctly to the client.

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Windows 10
- Themekit version (run theme version to check):
 - Editor [e.g. atom, sublime]: Shopify
 - Ignore:

**Additional context**
I hope this post is useful, I am a Spanish speaking person and it has cost me a lot to get here, I need to solve this as soon as possible, hopefully you can help me, thank you.

**Comment by andyw8** [comment]
Hi @Requ17 

This doesn't appear to be anything related to themekit. I'd suggest you ask in the Community Forums:

https://community.shopify.com/c/Technical-Q-A/bd-p/technical-qa
