### ISSUE TITLE
Can't install Theme Kit using Brew on Fedora 32

### ISSUE THREAD

**Issue by ttlewis** [Shopify/themekit#831]
Hi all,
I am using Fedora 32 and wanted to install Theme Kit, but can't get it to work, here's what I tried:

**Used URL for Linux installation:**
`curl -s https://shopify.github.io/themekit/scripts/install.py | sudo python`

`Error: Python 2 is required for this script.` currently have `3.8.6` installed.

Then  tried to roll back the version of Python to version 2 using: 
`curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python2`

But get `python2: command not found`

**Since I alreadt have homebrew installed, I used the command:**
```
brew tap shopify/shopify
brew install themekit
```
After creating my API key and config.yml, after running `theme watch` in the theme folder, I get: 
`Permission denied`

I am not a Linux pro, but I never had issues with brew before regarding permissions but if someone can help.
Thank you!

**Comment by andyw8** [comment]
Hi @ttlewis 

It looks like you're running `watch theme` but the command should be `theme watch`. Could you see if that works?

**Comment by ttlewis** [comment]
hi @andyw8 thanks for the quick reply, that was a typo on my site, I have now fixed it, however I still get `.linuxbrew/bin/theme: Permission denied` when I run `theme watch` thanks

**Comment by andyw8** [comment]
Could you share the output of running ` ls -l $(which theme)`

**Comment by ttlewis** [comment]
```
/usr/bin/which: no theme in (/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/development/.local/bin:/home/development/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin)
total 8
-rw-r--r--. 1 development development  138 Oct 22 13:57 config.yml
drwxrwxr-x. 7 development development 4096 Oct 15 20:38 theme-template
[development@localhost Shopify-Theme]$ 
```

Again sorry if I missed something blatant.

**Comment by andyw8** [comment]
@ttlewis can you run `brew doctor` and share, in case this a problem with the homebrew installation.

**Comment by ttlewis** [comment]
@andyw8 this is what I get:
```
Warning: python is symlinked to python3
This will confuse build scripts and in general lead to subtle breakage.
```
Can't I get Theme Kit to work with Phython v3?

**Comment by andyw8** [comment]
Theme Kit doesn't depend on Python, it's only used for the installation script. So if you're installing through Homebrew then it shouldn't impact it.

I'm going to do some testing then can provide an update.

**Comment by ttlewis** [comment]
@andyw8 I see, really appreciate the help!

**Comment by andyw8** [comment]
Have you been able to install other programs through Homebrew?

**Comment by ttlewis** [comment]
yeah I have Hugo installed and have it updated to the latest version with no problems.

**Comment by andyw8** [comment]
@ttlewis It appears Homebrew isn't an option because the formula only provide a Darwin (Mac binary):
https://github.com/Shopify/homebrew-shopify/blob/master/themekit.rb

Instead, you could try the Manual Installation steps listed on https://shopify.github.io/themekit/

**Comment by ttlewis** [comment]
@andyw8 oh I see, I just wanted to see if it also worked I should have checked that before. I downloaded the manual install and got permission denied when I did `theme version`: `bash: /usr/local/bin/theme: Permission denied`
Today is not my day...

**Comment by andyw8** [comment]
@ttlewis you mean need to run `chmod +x theme`

**Comment by ttlewis** [comment]
Bingo! Thank you so so much @andyw8! Now able to connect and all works perfectly thanks to you! Off to develop my new theme!

**Comment by andyw8** [comment]
Good to hear it's working now. It seems our docs may be missing that step so I'll update.

**Comment by ttlewis** [comment]
Great, I had to add `sudo chmod +x theme` to get the last bit to work, but that was it. Thanks again

**Comment by andyw8** [comment]
https://github.com/Shopify/themekit/pull/832
https://github.com/Shopify/themekit/pull/833
