### ISSUE TITLE
Dynamic sections not working/showing up

### ISSUE THREAD

**Issue by Roaldkamman** [Shopify/themekit#837]
**Describe the bug**
Dynamic sections don't show up in the admin theme editor

**To Reproduce**
1. GitHub code: https://github.com/Roaldkamman/rjktheme
2. Can only reproduce the problem on my end with access to the admin editor. 

**Expected behavior**
The ability to add a section in the admin editor is available.

**Environment (please complete the following information):**
 - OS: Windows 10
- Themekit version: I replicated the problem with both the newest version and version 1.0.3 the current version of the code is 1.0.3
 - Editor: VSCode
 - Ignore: none

**Additional context**
Link to thread on Shopify forums: https://community.shopify.com/c/Shopify-Design/Dynamic-section-not-showing-up-in-admin-editor/m-p/950736#M239145

https://www.loom.com/share/b8a4cca483b64aee83426b8088d6170f

One thing I didn't mention in the Loom is that I tried using both: "theme watch", and "theme deploy" commands.

**Comment by Roaldkamman** [comment]
Fixed by settings_data.json configuration to the correct properties.

**Comment by droplab** [comment]
I'm having the same issue. What settings did you update to resolve?

**Comment by droplab** [comment]
Just sorted it out. For people who find this issue in the future, you have make sure your preset values match the format in the schema for things to work correctly. Cheers

**Comment by soheimam** [comment]
> Just sorted it out. For people who find this issue in the future, you have make sure your preset values match the format in the schema for things to work correctly. Cheers

Droplab, I am currently having a similar issue would you be able to provide an example of your fix please?

**Comment by yjcyun** [comment]
> Fixed by setting settings_data.json configuration to the correct properties.

@Roaldkamman, I am having a same problem here. Would you be able to share what you have configured in settings_data.json?
