### ISSUE TITLE
Apple M1 Support

### ISSUE THREAD

**Issue by ingueferroque** [Shopify/themekit#838]
Is Apple M1 Support planned, and what is a realistic ETA of expecting that?

Has anyone been able to get themekit to run on the new M1 Mac models? I was hoping we could run Terminal via Rosetta 2 for the time being, but that solution does not work currently. So it looks like things will need to be updated with ARM support.

Thanks for any insight!

**Comment by andyw8** [comment]
Hi @ingueferroque 

What happens when you try run Themekit on the M1?

We do plan to add support native for the M1 in future, but I would have expected it would run in the 'emulated' mode currently.

**Comment by andyw8** [comment]
For native support, we will likely need to wait until this is supported by Go:

> In February, the Go 1.16 release will include the new file system interfaces and build-time file embedding. It will complete the linker rewrite, bringing additional performance improvements. And it will include support for the new Apple Silicon (GOARCH=arm64) Macs.

https://blog.golang.org/

**Comment by ingueferroque** [comment]
I have set Terminal app to 'Open using Rosetta' and done the following steps: 
- brew tap shopify/shopify
- brew install themekit

When doing the last step, it shows the below: 


`Last login: Wed Nov 18 17:16:43 on ttys000
macbookpro@Mac-mini ~ % brew tap shopify/shopify
macbookpro@Mac-mini ~ % brew install themekit
Warning: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
released but not yet supported version.

==> Installing themekit from shopify/shopify
==> Downloading https://shopify-themekit.s3.amazonaws.com/v1.1.2/darwin-amd64/th
Already downloaded: /Users/macbookpro/Library/Caches/Homebrew/downloads/4496e00e976a68ff5284d739994da6e4350d1cc4001e6b95c75b401780edcd3e--theme
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Error: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
macbookpro@Mac-mini ~ % `

Is the above related to macOS 11.0? I have no issues running themekit on my Intel macOS 11.0 machine. Thanks for looking into this!

**Comment by JimmyRittenborg** [comment]
Have you actually installed `Command Line Tools for Xcode 12.2` from https://developer.apple.com/download/more/ ? 🤔

I think I had this issue on Big Sur as well, it wasn't related to themekit though - think I installed the CLTs or reinstalled homebrew.

> I have set Terminal app to 'Open using Rosetta' and done the following steps: 
> 
> - brew tap shopify/shopify
> 
> - brew install themekit
> 
> 
> 
> When doing the last step, it shows the below: 
> 
> 
> 
> 
> 
> `Last login: Wed Nov 18 17:16:43 on ttys000
> 
> macbookpro@Mac-mini ~ % brew tap shopify/shopify
> 
> macbookpro@Mac-mini ~ % brew install themekit
> 
> Warning: You are using macOS 11.0.
> 
> We do not provide support for this released but not yet supported version.
> 
> You will encounter build failures with some formulae.
> 
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> 
> Twitter or any other official channels. You are responsible for resolving
> 
> any issues you experience while you are running this
> 
> released but not yet supported version.
> 
> 
> 
> ==> Installing themekit from shopify/shopify
> 
> ==> Downloading https://shopify-themekit.s3.amazonaws.com/v1.1.2/darwin-amd64/th
> 
> Already downloaded: /Users/macbookpro/Library/Caches/Homebrew/downloads/4496e00e976a68ff5284d739994da6e4350d1cc4001e6b95c75b401780edcd3e--theme
> 
> Error: Your Command Line Tools are too outdated.
> 
> Update them from Software Update in System Preferences or run:
> 
>   softwareupdate --all --install --force
> 
> 
> 
> If that doesn't show you an update run:
> 
>   sudo rm -rf /Library/Developer/CommandLineTools
> 
>   sudo xcode-select --install
> 
> 
> 
> Alternatively, manually download them from:
> 
>   https://developer.apple.com/download/more/.
> 
> 
> 
> Error: Your CLT does not support macOS 11.0.
> 
> It is either outdated or was modified.
> 
> Please update your CLT or delete it if no updates are available.
> 
> macbookpro@Mac-mini ~ % `
> 
> 
> 
> Is the above related to macOS 11.0? I have no issues running themekit on my Intel macOS 11.0 machine. Thanks for looking into this!
> 
> 
> 
>

**Comment by ingueferroque** [comment]
> Have you actually installed `Command Line Tools for Xcode 12.2` from https://developer.apple.com/download/more/ ? 🤔
> 
> I think I had this issue on Big Sur as well, it wasn't related to themekit though - think I installed the CLTs or reinstalled homebrew.

Thank you! Reinstalling the CLTs fixed it! It is working now.

**Comment by tanema** [comment]
Excellent. For future reference for anyone who finds this issue from google, please open a new issue if you receive an error like a segfault. I am pretty sure that apple will emulate our binaries until Go releases a compiler with M1 support and when that happens, we will release it as soon as possible.

**Comment by DaviMarra** [comment]
So, it's that fixed? Can we run themekit on m1 macs? Can someone here explain me how to do it? I've never used Rosetta or any of these softwares. Can someone here give me a tutorial, or a link to one?
