### ISSUE TITLE
Clarification on extent of -n, --nodelete flag during deploy

### ISSUE THREAD

**Issue by Guthrie-S** [Shopify/themekit#841]
Wanted to make absolutely sure I wasn't mis-reading or making an incorrect assumption while running theme deploy - 

Currently docs state that -n, or --nodelete "will run deploy without removing files from Shopify."

In this case, the flag only interacts with files as is related to the "assets" folder within the theme structure itself. 

This is completely separate from  "settings -> files" in the general site, and running or not running -n/--nodelete would have no effect on the files under "settings -> files" correct?

I understand I may be coming off as obtuse, but do appreciate the clarification, and effort given to Themekit. 

Thanks!

**Comment by tanema** [comment]
When running deploy without this flag, themekit will check which files are on the server and which files are local. It will the update the files that are both on the server and on local, and then remove any files from the server that are not on local. If you use `--nodelete`, this second step will not be done and may leave any unused files left over on the server.

**Comment by Guthrie-S** [comment]
Sorry - I'm still not understanding,

Let's say I have 1000 files uploaded under "Settings -> Files" in the admin panel. 

I have a theme A, with 10 files in the /assets folder

Locally on theme A, I remove 2 files, and run "theme deploy" without using -n/--nodelete

I would then have:
1000 files uploaded under "Settings -> Files" in the admin panel.
Theme A on server would have 8 files
Theme A on local would have 8 files

Correct?

**Comment by tanema** [comment]
Server
```
/assets
  app.js
  style.scss
  other.css
```

Local
```
/assets
  app.js
  style.scss
```

Server after `theme deploy -n`
```
/assets
  app.js [updated]
  style.scss [updated]
  other.css [not touched]
```

Server after `theme deploy`
```
/assets
  app.js [updated]
  style.scss [updated]
```

**Comment by Guthrie-S** [comment]
Thank you!
