### ISSUE TITLE
Dynamic sections not showing

### ISSUE THREAD

**Issue by Turqueso** [Shopify/themekit#842]
**Describe the bug**
When trying to customize a new theme you get "This page doesn't have any sections."

**To Reproduce**
1. Create a new theme
2. Create a section
3. Go to Customize
4. Get the message "This page doesn't have any sections."

**Expected behavior**
Should be able to add dynamic sections

**Environment:**
- Themekit version: 1.1.2

**Additional context**
- index.liquid does have {{ content_for_index }}
- Sections does have presets
- No errors on terminal
- I tried multiple sections, coded by hand or copying from other themes with nothing changing.

![image](https://user-images.githubusercontent.com/4932347/99703693-a479d780-2a54-11eb-9754-272c572fde40.png)

**Comment by tanema** [comment]
Are your new sections in your admin when you navigate to the `edit code` section?

**Comment by Turqueso** [comment]
Here, right?
![image](https://user-images.githubusercontent.com/4932347/99731574-56c49580-2a7b-11eb-8b91-3d8133404bd9.png)

**Comment by JonahWeinstein** [comment]
tanema means the shopify admin (what you get when you click "customize themes"). I am having the same problem with a section not showing up in the shopify admin. JSON is valid with presets and {{content_for_index}} in index.liquid, if anyone has any potential solutions please respond!

**Comment by JonahWeinstein** [comment]
here's the schema I'm using 

{% schema %}
{
  "name": "Freeflow Section",
  "class": "shopify-section--freeflow",
  "settings": [
    {
      "id": "background-color",
      "type": "color",
      "label": "Background Color",
      "default": "#b0c089"
    },
    {
      "id": "id",
      "type": "text",
      "label": "ID",
      "info": "Add an ID to link to menu items"
    },
    {
      "type": "select",
      "id": "hide",
      "label": "Hide this on desktop or mobile?",
      "info": "Select whether to hide this section on desktop or mobile devices",
      "options": [
        { "value": "0", "label": "Nah"},
        { "value": "1", "label": "Mobile Only"},
        { "value": "2", "label": "Desktop Only"}
      ],
      "default": "0"
    }
  ],
  "blocks": [
    {
      "type": "image",
      "name": "Image",
      "settings": [
        {
          "id": "image",
          "type": "image_picker",
          "label": "Image"
        },
        {
          "id": "caption",
          "type": "text",
          "label": "Add a caption",
          "info": "This will hug the image more than regular text"
        },
        {
          "id": "class",
          "type": "text",
          "label": "Custom CSS class",
          "info": "Add a class for custom styling"
        }
      ]
    },
    {
      "type": "richtext",
      "name": "Richtext",
      "settings": [
        {
          "id": "richtext",
          "type": "richtext",
          "label": "Text"
        },
        {
          "id": "class",
          "type": "text",
          "label": "Custom CSS class",
          "info": "Add a class for custom styling"
        }
      ]
    },
    {
      "type": "html",
      "name": "HTML",
      "settings": [
        {
          "id": "html",
          "type": "html",
          "label": "HTML"
        }
      ]
    }
  ],
  "presets": [
    {
      "name": "Freeflow Section",
      "category": "Freeflow"
    }
  ]
}
{% endschema %}

**Comment by Turqueso** [comment]
So, I got it working. I need to add at least one static section and the "add section" button appears under the static section. I didn't find any docs about it 😕

**Comment by EmadZedanPrivate** [comment]
this is the solution 👍 
https://www.youtube.com/watch?v=TmRwdP7TQBw
