### ISSUE TITLE
How do I uninstall shopify theme kit from command line?

### ISSUE THREAD

**Issue by white-hat-vaibhs** [Shopify/themekit#846]
**curl -s https://shopify.github.io/themekit/scripts/install.py | sudo python**

Mentioned above is the command that I used to install the theme kit for local development but I need to uninstall this as I realized that Shopify theme development is not a TRUE local Development environment. 
I would really appreciate it if you add that feature but for now please provide with uninstalling command.

**Comment by tanema** [comment]
`rm $(which theme)`

**Comment by white-hat-vaibhs** [comment]
I hope this removed the source file from my local machine too

**Comment by tanema** [comment]
there is no source code on your machine. its a binary

**Comment by white-hat-vaibhs** [comment]
Thankyou
