### ISSUE TITLE
Update event not being passed correct filename/path

### ISSUE THREAD

**Issue by thisislawatts** [Shopify/themekit#85]
I have a file `snippets/page-layout-image-pair.liquid` which when saved with `theme update` running I see the following:
```
Received Update event on layout-image-pair.liquid
[404]Could not complete operation because layout-image-pair.liquid does not exist
```

Having played about a bit with filenames it seems to happen where a snippet name contains 'layout', so perhaps there's some greedy regex flagging it as something else?

```
Received Update event on snippets/something.liquid
Successfully performed Update operation for file snippets/something.liquid to development.myshopify.com
Received Update event on layout-image-pair.liquid
[404]Could not complete operation because layout-image-pair.liquid does not exist
```

**Comment by csaunders** [comment]
So your file is `snippets/layout-image-pair.liquid` and the path is getting all goofed up?

**Comment by thisislawatts** [comment]
The filename is `snippets/page-layout-image-pair.liquid` but it receives an update event for `layout-image-pair.liquid`

**Comment by csaunders** [comment]
Fixed in https://github.com/Shopify/themekit/commit/4fbc0935f631be5bc24fa5228f6dd10b7699c325

Are you building from source or would you need a new build to be released?

**Comment by thisislawatts** [comment]
That's great, thanks @csaunders
👌
