### ISSUE TITLE
Packer DSC Provisioninh

### ISSUE THREAD

**Issue by babu-hub** [Shopify/themekit#853]
{
   "builders": [{
        "type": "azure-arm",
        "client_id": "1f6cc3a2-5c18-4b38-8348-f92c16185cc8",
        "client_secret": "Mf22bNcbBmvN0Pce2v2_~m~lADWA.~m1JU",
        "tenant_id": "85c997b9-f494-46b3-a11d-772983cf6f11",
        "subscription_id": "f018963d-335b-43e0-947a-ed8531680900",
        "managed_image_resource_group_name": "RSG4GoldenImage",
        "managed_image_name": "MTWINHARDIMG19",
        "os_type": "Windows",
        "image_publisher": "MicrosoftWindowsServer",
        "image_offer": "WindowsServer",
        "image_sku": "2019-Datacenter",
        "communicator": "winrm",
        "winrm_use_ssl": true,
        "winrm_insecure": true,
        "winrm_timeout": "5m",
        "winrm_username": "packer",
        "azure_tags": {
            "dept": "Cloud_Security",
            "task": "Image deployment"  
      },
        "location": "East US",
        "vm_size": "Standard_D2_v2"
    }
  ],
    "provisioners": [
      {
          "type": "powershell",
          "inline": [
              "WINRM QuickConfig -q" 
			  
      ]  
    },
	  
      {
        "type": "dsc",
        "manifest_file": "CIS_DSCConfiguration.ps1",
		"configuration_name": "WindowsServer",
        "install_package_management": true,
        "install_modules": {
            "PSDesiredStateConfiguration": "1.1",
			"AuditPolicyDsc" : "1.4.0.0",
			"SecurityPolicyDsc" : "2.10.0.0",
			"NetworkingDsc" : "8.2.0"
			} 
    },
      {
          "type": "powershell",
          "inline": [
              "if( Test-Path $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml ){ rm $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml -Force}",
              "& $Env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /shutdown /quiet"    
      ]  
    }
  ]
}

**Expected behavior**

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
- Themekit version (run theme version to check):
 - Editor [e.g. atom, sublime]:
 - Ignore:

**Additional context**

**Comment by babu-hub** [comment]
while builing the packer script i am getting error as could not find the module dsc resource. Please help me to resolve the issue

**Comment by andyw8** [comment]
This is not a Theme Kit issue.
