### ISSUE TITLE
Cannot cancel `watch` when transfer/theme update is running

### ISSUE THREAD

**Issue by SimJoSt** [Shopify/themekit#855]
**Describe the bug**
When a `watch` command is running and transferring a lot of changes, there is no way to cancel it with `CTRL + C`. You'll have to wait until the transfer of all changes has been completed.  
Leaving you with no way to cancel a possible destructive operation, when you've made a mistake.

**To Reproduce**
1. run command 'theme watch' (config implied)
2. change a lot of files, to keep the `watch` command busy for a few moments
3. try canceling it by using `CTRL + C`

**Expected behavior**
The `watch` command should abort at the next possible moment. Preferably immediately.

**Environment (please complete the following information):**
 - macOS Catalina 10.15.7 (19H15)
- Themekit version: 1.1.2 darwin/amd64
 - Editor [e.g. atom, sublime]: PHPStorm, Sublime
 - Ignore: none

**Additional context**
The larger amount of file changes was made by switching to a branch with a vast amount of changes.   This happened by mistake. These changes should not have been uploaded to the Shopify remote.

**Comment by tanema** [comment]
Youre absolutely right! We capture the signal during watch to be able to clean up and complete requests but with a changeset of that size, the signal will get drowned out and the command will not be stopped. I think I have a fix for this.
