### ISSUE TITLE
six.moves.urllib.request added to install.py but no requirements.txt

### ISSUE THREAD

**Issue by bestrada** [Shopify/themekit#856]
Some of my deployment automation failed because `six.moves.urllib.request` was added in [this commit](https://github.com/Shopify/themekit/commit/b5acb8d3ae63758574652f719757a23307907509). Before you could run `install.py` with just the base Python and no dependencies. Could you publish a `requirements.txt` in case more dependencies are added?

(this is not urgent for me anyways right now because I am able to see the error and add the library manually myself).

**Comment by tanema** [comment]
Ah, I am pretty green with python and thought that was a basic library. I will go back to my ugly fix without that library
