### ISSUE TITLE
Open editor

### ISSUE THREAD

**Issue by Benecke** [Shopify/themekit#870]
Just recently discovered the `open` command, which could come in handy. Wouldn't it be nice to have an `edit` command as well, which would then open the theme editor (customize/storefront editor) of the theme?

**Comment by tanema** [comment]
`theme open --edit` or `theme open -E`

**Comment by Benecke** [comment]
Oh, thanks tanema!
Now I checked the online docs where this is in fact documented. It's not output by `theme` or `theme --help`

**Comment by tanema** [comment]
@Benecke you can get help on individual commands by running `theme open --help`

**Comment by Benecke** [comment]
Ah yes, thanks for enlightening not so terminal-savvy me. Yep, I guess it could make sense to add a hint to that description text. Thanks again for your time.
