### ISSUE TITLE
Why does  `theme new` create an scss file?

### ISSUE THREAD

**Issue by o-t-w** [Shopify/themekit#872]
I have read that [scss is being deprecated by Shopify](https://en.shopify.hk/partners/blog/deprecating-sass), yet the `theme new` command automatically generates a `.scss` file. How do I change it to just use CSS instead?

**Comment by tanema** [comment]
We are in the process of removing it https://github.com/Shopify/themekit/pull/871

Just rename assets/application.scss.css to application.css and change the asset_url in layout/themel.liquid
