### ISSUE TITLE
Hide password on config.yml

### ISSUE THREAD

**Issue by luiscoms** [Shopify/themekit#879]
I want to use environment variable `THEMEKIT_PASSWORD` in order to do not commit the config.yml with password after run `theme` commands.

When I run `theme get` for example, the file `config.yml` is replaced with passoword set on `THEMEKIT_PASSWORD`

```
$ theme version
ThemeKit 1.1.4 darwin/amd64
```

**Comment by tanema** [comment]
duplicate of https://github.com/Shopify/themekit/issues/639
