### ISSUE TITLE
Update completes, but doesn't actually upgrade

### ISSUE THREAD

**Issue by jacobgraf** [Shopify/themekit#884]
Trying to update from v1.1.4 to v1.1.5. When running theme update, it shows that it was updated, but it's no. Any ideas?

![CleanShot 2021-01-21 at 13 06 03@2x](https://user-images.githubusercontent.com/146333/105399749-a9d8d700-5be9-11eb-8e91-4e789fc61106.jpg)

**Comment by smjeffries-snap** [comment]
Happens to me as well. Tried multiple times

**Comment by tanema** [comment]
Should be fixed now, It seems like the deploy only partially finished

**Comment by smjeffries-snap** [comment]
> Should be fixed now, It seems like the deploy only partially finished

Can confirm it works for me now. Thanks!
