### ISSUE TITLE
"Infected web resource detected" from bitdefender when running themekit

### ISSUE THREAD

**Issue by tommypepsi** [Shopify/themekit#890]
**Describe the bug**
Since a week or two whenever I run themekit my antivirus bitdefender detects the url "https://shopify-themekit.s3.amazonaws.com" as an infected web resource and blocks it. Themekit still runs fine but it is now impossible to run npm install on a project using slate because of this same error (which is not that much of an issue for us as we are moving away from slate, just something I noticed).

![image](https://user-images.githubusercontent.com/926715/105762963-212ca480-5f23-11eb-8d49-7ffcd2397136.png)

**To Reproduce**
1. Have bitdefender running.
2. run theme kit. 

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Windows 10
- Themekit version (run theme version to check): ThemeKit 1.1.4 windows/amd64

**Comment by andyw8** [comment]
It seems that Bitdefender is being overzealous in its blocking of executable downloads from AWS. This is outside of our control, but you could perhaps report it to Bitdefender as a false positive.

**Comment by tommypepsi** [comment]
Sure I'll do that! Just wanted to be sure it was known this issue was happening.

If anyone else gets this same issue, it's also possible to just whitelist the url.
