### ISSUE TITLE
Constant ReadAsset errors since upgrade ThemeKit today

### ISSUE THREAD

**Issue by ckizer** [Shopify/themekit#892]
Anytime I'm running themekit today after updating to the latest version on a non-M1 MacBook Pro Intel:

I now get this error when everything has been working fine for months.
[development] error loading /Users/ck/Documents/repos/OruKayak/snippets: readAsset: open /Users/ck/Documents/repos/OruKayak/Users/ck/Documents/repos/OruKayak/snippets: no such file or directory
1

If I save 5x times the error goes away and the theme is updated, but it comes back with each new file I modify.
Yes all the files exist.

**Comment by AntonShevel** [comment]
I experience the same issue after the update. 
macOS V11.1
It randomly happens after I run `theme watch`

`13:29:35 [development] processing /Users/zerg/Work/fr/bajio-theme/theme/assets
[development] error loading /Users/zerg/Work/fr/bajio-theme/theme/assets: readAsset: open /Users/zerg/Work/fr/bajio-theme/theme/Users/zerg/Work/fr/bajio-theme/theme/assets: no such file or directory`

**Comment by tanema** [comment]
dup of https://github.com/Shopify/themekit/issues/885
