### ISSUE TITLE
Themekit install script is returning 404

### ISSUE THREAD

**Issue by particle6** [Shopify/themekit#896]
**Describe the bug**
The shopify pages that previously hosted the install script for themekit https://shopify.github.io/themekit/ is now returning a 404. This has broken my CI pipelines. 

**To Reproduce**
1. curl -s https://shopify.github.io/themekit/scripts/install.py | sudo python

**Expected behavior**
Install script should download and install themekit

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Every environment

**Additional context**
None

**Comment by tanema** [comment]
Ah yes sorry a little hiccup in our docs switch over to https://shopify.dev/tools/theme-kit. The direct path to the scrupt is https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install.py

**Comment by tanema** [comment]
@mcvinci Could I bother you for a second to update shopify.dev for this?

**Comment by itsanolive** [comment]
This took down our whole build system and there are no redirects set up for the docs site... Even the new docs reference the wrong path for the install.py. Please fix asap so other people don't have to deal with this :)

**Comment by sebbean** [comment]
this is really wreaking havoc with a lot of our plumbing

this hasn't been fixed yet?

**Comment by andyw8** [comment]
We're working on a fix, but in the meantime you can work around this with:

`curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install.py | sudo python`

**Comment by kressaty** [comment]
This is a major issue due to several GitHub actions that rely on that URL which are not updated - anything that can be done to update it so it's not broken would be super helpful!

**Comment by andyw8** [comment]
This has been resolved. Please re-open the ticket if you're still having any problem.

**Comment by tanema** [comment]
I suggest that everyone stop building their CI environment on our installation script. I have moved that script 4 times in the lifetime of this project and I have put no guarantees on its continued existence. If you need to install this every time for your CI I suggest pinning it to a single AWS url to download a single version instead.

**Comment by kressaty** [comment]
@andyw8 thank you!

@tanema you're totally right, and it's clear there are no guarantees. unfortunately, sometimes customers do things in sub-optimal ways, and the service provider has to get creative or be somewhat inconvenienced to solve the problems of those potentially less sophisticated customers. this is something shopify as a company is extremely good at, and a big reason why it's been so successful! 

maintaining oss is super tough and the themekit has saved my team and many others a huge amount of time. the work you do is much appreciated, and dealing with issues like these sucks but ends up being super helpful, and we thank you for it!
