### ISSUE TITLE
Redirect GitHub docs site to https://shopify.dev/tools/theme-kit

### ISSUE THREAD

**Issue by andyw8** [Shopify/themekit#899]
https://shopify.github.io/themekit/ is returning a 404, we need to add a redirect for https://shopify.dev/tools/theme-kit

Ideally we'd also redirect deep links and map them to the new site, but doing it at the top level is a helpful first step.

cc @mcvinci

**Comment by itsanolive** [comment]
Seconded!

**Comment by wiledal** [comment]
The install script that was found at https://shopify.github.io/themekit/scripts/install.py was part of our continuous deployment workflow. This threw a wrench in our operations.

**Comment by andyw8** [comment]
We've redirect the homepage in #900 but we're not yet handling deep links.

**Comment by andyw8** [comment]
All the redirects are now in place.
