### ISSUE TITLE
`theme get` overwrites variables with hard-coded values in `config.yml`

### ISSUE THREAD

**Issue by SimJoSt** [Shopify/themekit#906]
**Describe the bug**
Since https://github.com/Shopify/themekit/releases/tag/v1.1.6 by way of https://github.com/Shopify/themekit/pull/891 the `theme --env=stage get` command will overwrite variables for variable interpolation from all environments from the `config.yml`. This has been reported by @luiscoms in https://github.com/Shopify/themekit/pull/891#issuecomment-772733423 and a similar issue is https://github.com/Shopify/themekit/issues/881.

**To Reproduce**
1. Configure variable interpolation and add variables to `config.yml`
2. Run command `theme --env=stage get`
3. All variables from all environments in `config.yml` are overwritten with hard-coded values

**Expected behavior**
- No existing values should be overwritten
- Preferably it wouldn't overwrite any existing values at all.
- Or even better, there would be an option to automatically write the values to the variables file and add the necessary variables for interpolation in the `config.yml` file.  
  Could be controlled via a flag.

**Environment:**
- OS: macOS 11.2 Big Sur
- Themekit version: https://github.com/Shopify/themekit/releases/tag/v1.1.6

**Additional context**
It feels like themekit doesn't want you to use variable substitution. Especially because it doesn't only overwrite the values from the chosen `stage` environment. But from all environments, even though they were not used by the current command.  
Also the content of the `config.yml` is restructured/reordered. The environments are sorted alphabetically and empty lines are removed.

**Comment by tanema** [comment]
dup of https://github.com/Shopify/themekit/issues/881 
it will happen in `new` `get` and `config`
