### ISSUE TITLE
Deploying for multiple specified envs

### ISSUE THREAD

**Issue by paulhuisman** [Shopify/themekit#911]
I saw something in documentation about the possibility to supply a "string array" into `--env` but didn't manage to get it to work.

Is it possible to do something like `theme deploy --env=development,stage` ?

We run a site with many different env's and it would be nice to deploy to multiple env's in one line.

**Comment by andyw8** [comment]
That's isn't supported, but you can pass `--allenvs` to run the deploy for each environment in your config file.

https://shopify.dev/tools/theme-kit/command-reference#deploy

**Comment by paulhuisman** [comment]
Thanks for your response.

**Comment by andyw8** [comment]
I've since learned that there is a way to do this, see https://github.com/Shopify/themekit/issues/913
