### ISSUE TITLE
One theme for multiple stores on different URLs (documentation)

### ISSUE THREAD

**Issue by ladislavsulc** [Shopify/themekit#913]
**Is your feature request related to a problem? Please describe.**
Our client is going to have multiple stores on Shopify, currently, they have one, which they plan to clone. They will use only 1 theme for all these clones of the current one (different markets, different companies).

**Describe the solution you'd like**
Is there any way of using Theme Kit and GIT while having one theme that you have to push and deploy to multiple store URLs and their environments? Can you give any advice? Is it possible? Thank you.

**Comment by tanema** [comment]
Use multiple environments, So you can have multiple configs and then run `theme deploy --env=store-1 --env=store-2`

**Comment by ladislavsulc** [comment]
Thank you @tanema. I hoped this would be possible. Brilliant.
