### ISSUE TITLE
theme open command produces a url with to https:// breaking the link.

### ISSUE THREAD

**Issue by mcqua007** [Shopify/themekit#915]
**Describe the bug**
The bug occurs while running command `theme open`, this command should open a preview theme url but produces a broken links due to two https. Example response:
`[development] opening https://https://EXAMPLE.myshopify.com?preview_theme_id=118754574489`

*Note Just removing the extra https makes the link work as it should
**To Reproduce**
1. run command 'theme open`
2. open produce url It's broken
3.  theres two https:// as shown above

**Expected behavior**
 That the link produce not be broken and have on https

**Environment (please complete the following information):**
 - MacOS V11.0.1 Big Sur 
- Themekit version (run theme version to check): ThemeKit 1.1.6 darwin/amd64
 - Editor [e.g. atom, sublime]: VScode
 - Ignore:

**Comment by tanema** [comment]
Do you have https://EXAMPLE.myshopify.com as your store in your config? If so remove the protocol from your config

**Comment by mcqua007** [comment]
@tanema Oh my...I  feel like such a fool. I recently copied this theme from another and setup the config super quick. 
I did have the protocol in the config. Thanks for the help.
