### ISSUE TITLE
Themekit Deploy --files allow expressions

### ISSUE THREAD

**Issue by Kehza** [Shopify/themekit#937]
Within my build process I have a "Sync" Gulp Task which runs the ThemeKit Deploy Command. However, I don't want to sync everything - the clients we work with often switch out assets, e.g. their logo (as Shopify doesn't support SVGs in Sections). 

To get around this, we use the --files option, however it doesn't accept expressions on literal paths. As an example: 
'./assets/*.js' is seen as the literal path, and it doesn't seem to try and evaluate it.

**Comment by tanema** [comment]
Themekit already does this. You can simply use `theme deploy /.assets/\*.js` you can always find more info on commands by running `theme deploy --help`
