### ISSUE TITLE
Online Store 2.0 will it work with ThemeKit?

### ISSUE THREAD

**Issue by tizzle** [Shopify/themekit#945]
**Is your feature request related to a problem? Please describe.**
Currently i cannot use Online Store 2.0 with my existing ThemeKit setup (which works fine for everything before 2.0). Are there plans to make this possible?

**Describe the solution you'd like**
It would be great to make it possible to use ThemeKit to develop an Online Store 2.0 theme. When testing today the migration detailed here: https://shopify.dev/themes/migration i received errors when deploying a theme for dev.

**Describe alternatives you've considered**
I tried to run the commands detailed in https://shopify.dev/themes/migration, which are based on Shopify CLI, but this does not work with my current folder structure.

**Additional context**
Not much more to say here.

**Comment by mkevinosullivan** [comment]
Shopify doesn't intend to update ThemeKit to develop/use an Online Store 2.0 theme.  The [Shopify CLI](https://github.com/Shopify/shopify-cli) has been updated and extended to work on themes.

You've already found the [theme migration guide](https://shopify.dev/themes/migration); there's also a [command migration guide](https://github.com/Shopify/shopify-cli/blob/main/THEMEKIT_MIGRATION.md) for your reference.
