### ISSUE TITLE
Theme kit access app - Invalid API key or access token

### ISSUE THREAD

**Issue by hugos** [Shopify/themekit#954]
**Describe the bug**
When using the new theme kit access app it always gives me this error: `[API] Invalid API key or access token (unrecognized login or wrong password)`

**To Reproduce**
1. run command 'theme get --password=[themeki tapp generated password] --store=store.myshopify.com'

**Environment (please complete the following information):**
 - OS: Mac os big sur
- Themekit version (run theme version to check): 1.3.0

**Additional context**
Of all the times that I've tried using it it has only worked *once*. This is also happening to a lot of my colleagues.

**Comment by denisinla** [comment]
@hugos Your current command does not work since it contains unknown flag `--name`. If you're trying to create a new theme the proper command is `theme new --password=[your-password] --store="[your-store.myshopify.com]" --name=[theme name]`

**Comment by hugos** [comment]
@denisinla My bad that's just a typo on I don't actually write it like that lol. I spoke to Shopify, this is known issue there they are trying to fix it.

**Comment by robertjmcinnis** [comment]
I have what seems to be the similar issue.

Theme Kit was working fine on our development store.  Then, I started getting this error whenever I tried to run any theme commands, for example:

Steps:
- Using Theme Kit 1.3
- OS: Mac os big sur
- Run any themekit commant (eg/ theme watch)
- After about a minute an error would appear:
request failed after 5 retries with error: Get https://theme-kit-access.shopifyapps.com/cli/meta.json: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
- Follow the JSON in the error message,  https://theme-kit-access.shopifyapps.com/cli/meta.json.  The JSON reads like this: {“errors":"[API] Invalid API key or access token (unrecognized login or wrong password)"
- I’ve tried several things to remedy but all unsuccessful - Updating Theme kit, Homebrew, switching between Theme Kit Access App / Private App, Updating OS, different shopify stores.  
- The only thing that fixed it was switching to a different internet connection.  After switching to a different IP theme kit works like normal.

**Comment by hugos** [comment]
It's unbelievable that this is still happening.

**Comment by fibonacid** [comment]
I've found that you can bypass this problem by creating a custom app and configure the Admin API permission to
`read_themes,write_themes`.

**Comment by fibonacid** [comment]
Yeah, alternatively you can include source code in the repo and use the Github integration.
There are a few options for this, but currently the best one i tried is using git subtrees.

1. Create repo for source code
2. Create repo for compiled code
3. Connect a branch of the compiled repo to a Shopify Theme
4. Build code from `src` to `dist` (include dist in version control)
5. Push contents of `dist` on the source repo to the root of the compiled repo with:
```bash
git subtree push --prefix dist compiled-repo-url $(git branch --show-current)
```
6. Pull contents of compiled repo into `dist` with: 
```
git subtree pull --prefix dist compiled-repo-url $(git branch --show-current) --squash
```

You can abstract the process of keeping the dist folder always in sync with the subtree by using git hooks:
```mermaid
flowchart TD
    subgraph pre_commit_hook[pre-commit]
        stash_unchanged[git stash -q --keep-index]-->build_theme
        build_theme[yarn build]-->stage_changed[git add -u]
        stage_changed-->apply_stashed_changes=[git stash pop -q]
    end
    subgraph pre_push_hook[pre-push]
        pull_subtree[yarn subtree:pull]
    end
    subgraph post_push_hook[post-push]
        push_subtree[yarn subtree:push]
    end
    pre_commit_hook-->git_commit[git commit]
    git_commit-->pre_push_hook
    pre_push_hook-->git_push[git push]
    git_push-->post_push_hook
```

**Comment by chippleh1392** [comment]
I had this issue with Theme Kit Access and was able to fix it by updating Theme Kit to the latest version.

**Comment by laimoh** [comment]
I'm on the latest version and still having this error....

**Comment by hugos** [comment]
It's still happening to be to this day as well. I just use the private apps method.
I'll be closing this for now as this as been happening for too long and a solution does not seem to be coming any time soon.

**Comment by leobaixinxin** [comment]
> I have what seems to be the similar issue.
> 
> Theme Kit was working fine on our development store. Then, I started getting this error whenever I tried to run any theme commands, for example:
> 
> Steps:
> 
> * Using Theme Kit 1.3
> * OS: Mac os big sur
> * Run any themekit commant (eg/ theme watch)
> * After about a minute an error would appear:
>   request failed after 5 retries with error: Get https://theme-kit-access.shopifyapps.com/cli/meta.json: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> * Follow the JSON in the error message,  https://theme-kit-access.shopifyapps.com/cli/meta.json.  The JSON reads like this: {“errors":"[API] Invalid API key or access token (unrecognized login or wrong password)"
> * I’ve tried several things to remedy but all unsuccessful - Updating Theme kit, Homebrew, switching between Theme Kit Access App / Private App, Updating OS, different shopify stores.
> * The only thing that fixed it was switching to a different internet connection.  After switching to a different IP theme kit works like normal.

it works, thank a lot
