### ISSUE TITLE
POSIX python installer does not update existing install 

### ISSUE THREAD

**Issue by jtgrenz** [Shopify/themekit#96]
If you already have a copy of theme kit installed, then the current python install script does not overwrite the existing install. My python is getting rusty, but looks like its this check here https://github.com/Shopify/themekit/blob/installers/install#L74

Doesn't seem to do anything else if it sees themekit is installed aside print the path setup instructions 

@csaunders

**Comment by csaunders** [comment]
Yeah... I wasn't sure if I wanted to overwrite it or not. I guess it
doesn't really matter, or maybe I should prompt the user?

On Fri, Sep 18, 2015 at 12:19 PM, Jon Grenning <notifications@github.com>
wrote:

> If you already have a copy of theme kit installed, then the current python
> install script does not overwrite the existing install. My python is
> getting rusty, but looks like its this check here
> https://github.com/Shopify/themekit/blob/installers/install#L74
>
> Doesn't seem to do anything else if it sees themekit is installed aside
> print the path setup instructions
>
> @csaunders <https://github.com/csaunders>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shopify/themekit/issues/96>.
>



-- 
Chris Saunders // Developer @ Shopify

**Comment by csaunders** [comment]
Installer will just always do an overwrite of the file.
