### ISSUE TITLE
Error while executing watch from CLI

### ISSUE THREAD

**Issue by the-x-man** [Shopify/themekit#978]
**Describe the bug**
After installing the dependencies thru npm i, seeing the following error

Error: spawn ...\node_modules\@shopify\themekit\bin\theme.exe ENOENT
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: spawn ...\node_modules\@shopify\themekit\bin\theme.exe ENOENT".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**To Reproduce**
1. npm run watch
2. 
3. 

**Expected behavior**
Watch for themekit to start

**Environment (please complete the following information):**
 - OS [e.g. iOS]: WIN10
- Themekit version (run theme version to check): ThemeKit 1.3.0 windows/amd64
 - Editor [e.g. atom, sublime]: VS Code
 - Ignore:

**Additional context**
No

**Comment by veb** [comment]
I just had this issue on an M1 Mac, running the latest node.

I changed to `v14.10.0` and it worked. Maybe you could give that a try.

**Comment by the-x-man** [comment]
Many thanks @veb . This solved the problem.
